### ISSUE TITLE
[Suggestion] Dragging elements

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#1]
Right now holding left click changes the camera view. I suggest you reassign this keybind to holding the middle mouse button and assign holding left mouse button to dragging an element you clicked on through the space. Right now it feels **very** tedious to move an element so the dragging in space with the keybinds for moving an element (which I suggested in Discord) should make modelling feel a lot more fluid and nice.

**Comment by JannisX11** [comment]
Added in 1.6.
