### ISSUE TITLE
[Issue] WebGL error

### ISSUE THREAD

**Issue by TadEro** [JannisX11/blockbench#100]
hello, my issue is simple
![the program shows me this](https://user-images.githubusercontent.com/20144307/35477599-417419a8-03a5-11e8-9bb2-c26fdfc71d0f.png)
I tried the app on the web, and it works, but I want to use the deskop app

I'm using Windows 8.1

console: 
![1](https://user-images.githubusercontent.com/20144307/35477611-a85b74ae-03a5-11e8-8308-cd75afb29aca.png) ![2](https://user-images.githubusercontent.com/20144307/35477615-bdcbfaac-03a5-11e8-8f87-8c6be49631b1.png)

**Comment by JannisX11** [comment]
This is an Electron issue and there is no solution for it right now. We are waiting for a new Electron version that fixes it.
You have to use the web app for now. Sorry for the inconvenience.

**Comment by TadEro** [comment]
oh well it's fine. thanks for replying

**Comment by JannisX11** [comment]
Since this hasn't been an issue in almost a year, I'm going to assume that it has been fixed in one of the past Electron updates.
