### ISSUE TITLE
[Issue] Auto UV can cause the UV to go out of bounds

### ISSUE THREAD

**Issue by dragonmaster95** [JannisX11/blockbench#1000]
When using the Auto UV tool (depending on the size of the element and the project resolution) the UV can become higher/wider than the maximum amount, causing it to use a neighboring texture in the texture atlas (in Java at least, not sure what it would cause in Bedrock).

How to reproduce:
-Create a project with the default resolution (16x16)
-Create a cube and rescale it to be wider, higher and/or longer than 16 units
-Move the UV to somewhere in the middle of the texture
-Use the auto uv tool

**Comment by JannisX11** [comment]
Congratulations on issue #1000!

**Comment by catgocri** [comment]
I am also having this issue.

**Comment by dragonmaster95** [comment]
Still an issue
