### ISSUE TITLE
[Suggestion] Support UV Faces on 1.8 Format

### ISSUE THREAD

**Issue by MC874** [JannisX11/blockbench#1001]
# **Introduction**
First of all, Blockbench read 1.8 format the same as 1.10 format (I assume). It has mapped UV instead of per UV Faces [North, South, East, West, Up, Down]. This caused issue where the UV's mismatch with the texture and the model became transparent. 1.8 Format actually do support for UV Faces and any 1.12 properties as its used in Persona Cosmetics (Skin Editor).

# **Problematic**
1)> **UV and Position Coordinate controller become blank** with no values when selecting on each bones
![image](https://user-images.githubusercontent.com/62210133/131346606-ce2b8b8d-614b-4b95-9012-0b14e303dc74.png)
2)> **The model** is obviously **become transparen**t because the **UV is projected/mapped based on bones**. I have trying to fix this by changing texture resolution to 64x64 and 256x256 but no luck.
![image](https://user-images.githubusercontent.com/62210133/131347082-35250798-4fcd-4108-822e-623411a18e2e.png)
3)> The UV Editor does show perface UV however but weirdly it just a projected bones and not actual squared perface UV
![Screenshot (48)](https://user-images.githubusercontent.com/62210133/131348407-a55693b7-deec-48ee-8a49-82f311c3d59b.png)
3)> Im trying to convert the 1.8 format into 1.12 format trough blockbench with perface-UV but only to find that the UV box is too small and tucked together up-left. I really couldnt adjust it manually as its going to messed up the UV Coordinate carried by original geometry and the texture is rambled anyway.
![image](https://user-images.githubusercontent.com/62210133/131350509-d080e223-6575-4764-9adc-fa5479e1739a.png)

# In-Game
Geometry : [Geometry](https://pastebin.com/RDfBr5JH)
![image](https://user-images.githubusercontent.com/62210133/131354154-a2003011-266c-4fa5-9b08-22a5e2a64d67.png)

**Comment by JannisX11** [comment]
I won't port newer features back into older format versions, it would get very messy and inconsistent.
You can however pretty easily convert your model into the new 1.12 format. Just take any 1.12 geo file, and copy the "bones" section from your model into this file, using a text editor. Like in this example: [RDfBr5JH.txt](https://github.com/JannisX11/blockbench/files/7079791/RDfBr5JH.txt)
