### ISSUE TITLE
[Issue] Blockbench ignores visibility options on load

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#102]
If a model contains groups which have been saved with visibility disabled, Blockbench will ignore that on model load and the elements in those groups will be visible (even if the group has the "eye" crossed). This is very annoying since I need to turn off elements every time I open the model.
![image](https://user-images.githubusercontent.com/29360565/36356691-ab56780a-14f5-11e8-8175-1b2ca24c28c2.png)

**Comment by JannisX11** [comment]
Fixed in 1.11
