### ISSUE TITLE
[Beta] [Issue] Loopcut creates shading errors

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1021]
Loopcut creates shading errors on textured view, seems to be purely visual
Blockbench 4 beta1
[model0.zip](https://github.com/JannisX11/blockbench/files/7131065/model0.zip)

![ezgif com-gif-maker (25)](https://user-images.githubusercontent.com/44243757/132564732-c425efe6-55b6-419a-8bba-35970c490f80.gif)

**Comment by JannisX11** [comment]
Are you still able to reproduce the issue in beta 2?

**Comment by Wackyblocks** [comment]
No, feel free to close
