### ISSUE TITLE
[Beta] [Issue] Unable to rotate multiple meshes at once

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1031]
Unable to rotate multiple meshes at once

- Select 2 mesh models
- Rotate

Blockbench 4 beta.1

**Comment by JannisX11** [comment]
I cannot reproduce the issue. Could you record a GIF or write detailed reproduction instructions?

**Comment by Wackyblocks** [comment]
Not sure what I was referring to, but I cannot reproduce this problem, tested with different bone structures and such.

One thing I found was object not being move thats on a different bone when you have a bone selected, because its moving the bone, not the cubes, which I would consider normal behaviour.

Tested on blockbench 4.1.1
![KOoP6lyWaL](https://user-images.githubusercontent.com/44243757/147791865-c4e68959-c9ba-4d87-8709-79abd0f7a3e9.gif)
