### ISSUE TITLE
[Issue] Face and line select sometimes does unintentional multi-selections

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1050]
Face and line select sometimes does unintentional multi-selections. happens with both shift & control select
![ezgif com-gif-maker (44)](https://user-images.githubusercontent.com/44243757/133784308-7a496b08-82da-47b9-9b39-2c231cfc767c.gif)

Blockbench 4 beta.2

**Comment by JannisX11** [comment]
That's somewhat intentional, face and line selection are based on vertices, if all vertices surrounding a mesh are selected, the face is also automatically selected.

**Comment by Wackyblocks** [comment]
Sure, but there should definitely be an option to not do it

**Comment by Wackyblocks** [comment]
Having an option to un-select those could be an alternative option
