### ISSUE TITLE
[Beta] [Suggestion] Pixel snapping on UV editor

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1053]
Pixel snapping on UV editor for meshes would be useful

**Comment by Wackyblocks** [comment]
@JannisX11 Added in 4.0?

**Comment by JannisX11** [comment]
@Wackyblocks It depends what you meant. There are currently two ways to snap to pixels, including holding Shift while dragging, and using the action (in the context menu or optionally added to the toolbar).

**Comment by Wackyblocks** [comment]
Yeah the action seems to do what I asked for

**Comment by JannisX11** [comment]
Cool!
