### ISSUE TITLE
[Beta] [Suggestion] Support for multiple projects on a single scene with different project resolutions

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1059]
Support for multiple projects on a single scene with different project resolutions
Even like an option to combine the projects into 1 template would be helpful

![image](https://user-images.githubusercontent.com/44243757/133993541-1565b5d3-b1fc-4602-bdcd-eea8e339c634.png)

**Comment by JannisX11** [comment]
Textures can now have individual UV sizes.
