### ISSUE TITLE
[Beta] [Suggestion] Loop fill support for more than 5 lines

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1062]
Right now filling a cylinder is quite difficult, here's an example how difficult its to fill a cylinder

https://user-images.githubusercontent.com/44243757/133997947-5a7f81d8-fc89-4ae0-9af3-5c42a0610630.mp4

**Comment by JannisX11** [comment]
This would require n-gons, which the whole mesh system is not designed for. Faces can have 2 vertices (line), 3 vertices (tri) or 4 vertices (quad). Definitely won't add this to 4.0, but I'll keep it open for future updates just in case.

**Comment by Wackyblocks** [comment]
Wasn't necessarily thinking about n-gons, something more similar to blenders grid fill

https://docs.blender.org/manual/en/latest/modeling/meshes/editing/face/grid_fill.html
