### ISSUE TITLE
[Beta] [Issue] Loopcuts do not update correctly

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1072]
Loopcuts do not update correctly

Loopcut wont get created, until you press undo once
Blockbench 4 beta3 

![ezgif com-gif-maker (50)](https://user-images.githubusercontent.com/44243757/134777194-6e13cb0c-5aa0-4d53-8cef-f5363e5f7d69.gif)

**Comment by JannisX11** [comment]
"Dissolve Edges" was mistakenly assigned to the same keyboard shortcut :D
