### ISSUE TITLE
[Issue] Plugins don't install when I press the 'Install' button

### ISSUE THREAD

**Issue by binarypixells** [JannisX11/blockbench#1077]
There's no errors or anything, all that happens is that I click it, and it doesn't install. Please fix this as I'm working on an Optifine resourcepack and I need to use Optifine CEM Template Loader (which was installed previously but was deleted during the update, I don't know if that's a bug or intentional).

**Comment by JannisX11** [comment]
Which version of Blockbench are you using? Which operating system are you on? If you go to File > Developer > Open Dev Tools > Console, are there any red error messages?

**Comment by binarypixells** [comment]
Something weird happened... The program crashed randomly, and when I reopened it all the plugins I had been trying to install were now installed. The weird thing is, it seemed to have installed plugins multiple times...
By the way, I'm using the desktop app on Win 10. And no, there were no error messages.
