### ISSUE TITLE
[Issue] Linux plugins can't be installed

### ISSUE THREAD

**Issue by LocaHa12** [JannisX11/blockbench#108]
I can't install plugins in blockbench linux. Newest version.

Bug from console. 
![unknown](https://user-images.githubusercontent.com/37419894/37488475-ff02133a-2894-11e8-8b46-a7ebcd9f9dc8.png)

I guess there should be plugins folder in opt/blockbench but when i install it there is no such folder. (tried reinstalling and redownloading)

**Comment by JannisX11** [comment]
This will be fixed in 1.11
