### ISSUE TITLE
[Suggestion] Texture organization

### ISSUE THREAD

**Issue by megamanzteam** [JannisX11/blockbench#109]
What I would like to see is a way to group textures to a model or group of models. Similar to how you can group models. On a side note would there be a way for the player model plugin to import a player skin?

EDIT: ignore player skin question. I just figured it out. For those curious, must be full size 1.8+ skin.

**Comment by JannisX11** [comment]
Could you elaborate? I don't get from your text why grouping textures would be useful.

**Comment by JannisX11** [comment]
I do not consider this a very useful or important addition for Blockbench at the current time.
