### ISSUE TITLE
[Issue] Undo overjumps multiple steps / Redo is missing

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#11]
When I edited an element, I assigned a new texture to one side. Then I edited the size of the selected element. When I press undo it brings me to the start, where I haven't assigned a new texture. Shouldn't the redo have brought me to the point where I assigned the texture and have not edited the size yet? 

On another note, redo is missing.

**Comment by JannisX11** [comment]
Fixed in the next release (1.4)
