### ISSUE TITLE
[Issue] Keybind for reloading plugins doesn't work

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#110]
While working on a plugin, I found it highly frustrating that I need to open the plugin dialog each time I want to reload it, since the keybinding doesn't work.

How to reproduce:
1. Create a simple plugin which alerts you with "Reloaded!" in the onUninstall event.
2. Load the plugin
3. Reload it using the button
4. The alert function will work fine each time we reload it.
5. Now, close the plugin dialog and press Ctrl + J
6. Nothing will happen, making it clear that the keybinding doesn't work.

(Attaching the plugin I used to test this issue in a zip because GitHub doesn't support js extensions)
[how_to_reproduce.zip](https://github.com/JannisX11/blockbench/files/1845378/how_to_reproduce.zip)

**Comment by JannisX11** [comment]
This will be fixed in 1.11. I straight up forgot to add this.
