### ISSUE TITLE
[Issue]  Persona not working since update

### ISSUE THREAD

**Issue by thingychan** [JannisX11/blockbench#1102]
Since the latest update (Blockbench 4.0.1), I am having issues with Persona. 

If I open old persona files, they display properly, however, If I save the file, close blockbench and re-open the new saved file these are the issues that I find:

-nothing appears in the outliner, as if there were no geometry, yet the geometry is visible within the viewport.
-the persona textures do not display correctly. If I select the uv's of the base persona model, they appear to be scaled down and placed in a different location to where they were before closing the file.
-it's also generating new body and head textures

I tested it:

- i created a new file, made some random drawings.
- -saved the file
- -closed blockbench
- -re opened blockbench

The first image below shows what I saw before saving and closing Bloackbench. The second image shows what I see when I re open blockbench.

UPDATE: manually uninstalling everything and re installing doesn't fix these issues. And installing the portable version also has the same issues.

![persona error1](https://user-images.githubusercontent.com/92596298/137525171-90151250-4b32-43b8-aafe-04c0a5e031c0.png)
![persona error2](https://user-images.githubusercontent.com/92596298/137525174-bd1d94b0-20f6-47c3-9ec7-d05c9fb9d465.png)

Thank you[](url)

**Comment by PaulFinnerty** [comment]
Same problem here, I will add that after opening the "Preview" tab, I couldn't open the "Edit" or "Paint" tab again.

**Comment by PaulFinnerty** [comment]
@thingychan I found that re-installing the plugin in 4.0.1 solved the problem

**Comment by thingychan** [comment]
@PaulFinnerty tyty! that worked! I actually hadn't tried manually uninstalling the plugin since it just automatically uninstalled for me after a while and I had to re-install... But manually uninstalling after that did work! ty!
