### ISSUE TITLE
[Issue] Blockbench crashes wayland session trying to save

### ISSUE THREAD

**Issue by Alib234** [JannisX11/blockbench#1109]
So I'm on Arch linux, I downloaded the [blockbench-git](https://aur.archlinux.org/packages/blockbench-git/) which basically just builds it from this repo. When I try to save blockbench crashes the entire wayland session about 95% of the time. [Journal log from the crashing](https://pastebin.com/ad54Y49N)

**Comment by JannisX11** [comment]
This could be a duplicate of #1091. When downloaded from the website, it should now work out of the box. When building from source, make sure you are using electron 13.
The version you linked is not supported by me. It is uploaded by a third party and not necessarily up to date.
