### ISSUE TITLE
Inverted quads are weird with rescaling

### ISSUE THREAD

**Issue by Drullkus** [JannisX11/blockbench#111]
![invertrescaele](https://user-images.githubusercontent.com/5010174/38283529-525a3c6c-376b-11e8-8a46-9ddf215b781a.gif)

Issue occurs both on client and web

**Comment by JannisX11** [comment]
They behave the same as non-inverted cubes though. And they scale as expected and as rendered ingame.

**Comment by Drullkus** [comment]
Oh, strange. I’ll investigate further then.
