### ISSUE TITLE
[Issue] Having different models of different resolutions opened messes with some of their texture

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1113]
Opening a tab of a model in x16, then a model in x32 can make the model in x16 double its resolution or something. Closing the tab and reopening it fixes the problem.

This bug did not happen consistently.

![resolution bug](https://user-images.githubusercontent.com/81629481/137637416-9f60b4ba-9de8-4514-aebb-bb96053cd359.PNG)

Blockbench 4.01

**Comment by JannisX11** [comment]
Cannot reproduce. Try if the issue also occurrs without any plugins installed. If it doesn't, it's a plugin issue.

**Comment by PaulFinnerty** [comment]
Will do at some point, I did experience this issue while working on Persona items.
