### ISSUE TITLE
[Suggestion] obj export optimization

### ISSUE THREAD

**Issue by zertrax** [JannisX11/blockbench#113]
-Add an option to export Optimized obj model (deleting hidden faces, currently works with a plugin ONLY within Blockbench, not when exporting)

**Comment by JannisX11** [comment]
Could you move the second suggestion to a new issue? It's a bit easier to handle if each point is seperate.

**Comment by zertrax** [comment]
Done, sorry about that!

**Comment by JannisX11** [comment]
Added in Blockbench 1.11.5
