### ISSUE TITLE
[Issue] copied piece of texture does not scale as you zoom in UV tab

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1139]
Zooming in while having a copy of some texture does not scale to match until you click to drag it (causing some displacement too)

Blockbench 4.0.3

https://user-images.githubusercontent.com/81629481/139079438-2812e9b1-5029-4cef-bfcf-bb750fd28bb6.mp4

**Comment by JannisX11** [comment]
Fixed in 4.0.4
