### ISSUE TITLE
[Issue] the animation timeline shows a double of a bone when you have two models open with a bone of the same name

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1141]
Switching from the "Animate" tab to another model's "Animate" tab will show a double of a bone in red (like a bone that has some keyframes but isn't present in the geometry) if they both bear the same name and were open in the timeline.
they do not need to have a keyframe, just select the bone so that it's visible in the timeline.

-Blockbench 4.0.3

https://user-images.githubusercontent.com/81629481/139083144-c952decb-486b-41cc-b1c6-70e2b9542f30.mp4

**Comment by JannisX11** [comment]
Fixed in 4.0.4
