### ISSUE TITLE
moving a block destroys the uv settings

### ISSUE THREAD

**Issue by blinky000** [JannisX11/blockbench#115]
using the latest version on windows , when moving a block , the uv are destroyed and have to be reset,

**Comment by JannisX11** [comment]
This is the auto UV feature of Blockbench. You can disable it in per element in the outliner (see screenshot) or for all new elements in the settings.
![image](https://user-images.githubusercontent.com/29278436/39584869-bff9f5e2-4ef3-11e8-9b8a-ec9006f4a03c.png)

**Comment by blinky000** [comment]
thank you
