### ISSUE TITLE
[Suggestion] Ability for models to specify backface culling mode

### ISSUE THREAD

**Issue by unascribed** [JannisX11/blockbench#1154]
Currently, "Render Sides: Auto" is hardcoded to enable backface culling only for Java block models:

https://github.com/JannisX11/blockbench/blob/8e977958ec0ed1da32de58914236d74b987c77aa/js/preview/canvas.js#L589-L591

It would be useful if this could be specified by models; I'm creating a bbmodel exporter for a skin customization mod that extensively uses backface culling, and there's no way to get it in a Generic model other than asking people to go into the settings and change the Render Sides option, which is not ideal.

If there is interest in this feature I can attempt a PR.

**Comment by JannisX11** [comment]
Would you need to specify it per model format, or per project, or per texture?

**Comment by unascribed** [comment]
I was thinking per-project (sorry, I said "model" since I was thinking of "bbmodel") - model format wouldn't help me, as I'm exporting `format: "free"` bbmodels and not a plugin. I've considered a plugin but I'm starting with just exporting models.

Something like a "Render Sides: Default, Outside, Outside and Inside" option in the "Project..." dialog, UI-wise.

**Comment by JannisX11** [comment]
Implemented as per texture option in https://github.com/JannisX11/blockbench/commit/f1d00ec8b370a884078e65efc95e8f707956aa7b for 4.6.
