### ISSUE TITLE
[Suggestion] Paint mode to paint on each animation frame layer

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1156]
Paint mode toggle on brushes, fill, and shape tools to paint on each animation frame layer.

**Comment by Trioplane** [comment]
YES PLEASE JANNIS PUT THIS

**Comment by Trioplane** [comment]
like Instead of Create Texture theres another option called create animated texture

**Comment by EnderIzzy124** [comment]
This would be a very useful feature. I wouldn't have to go into Aseprite anymore to make animated textures, haha.
