### ISSUE TITLE
After update i cant anymore create working texture to modded entity forge 1.15 -1.16 MCP. 

### ISSUE THREAD

**Issue by tommitesti** [JannisX11/blockbench#1165]
Detailed description of your issue:
After update i cant anymore create texture to modded entity forge 1.15 -1.16 MCP. It requires 64 x 32 texture size to work, but every time i try to create texture template it changes project back to 64x64 texture size. So when i try to export java entity from blockbench and import to Mcreator textures goes broken. Function worked just fine yesterday, but today after the batch to 4.0.5 not anymore

Model format in which the issue occurs: 
Modded Entity

Blockbench variant (Website / PWA / Program):

Program
Windows 10

**Comment by JannisX11** [comment]
Texture templates are and have always been square.
You can find common MCreator model loading issues here: https://mcreator.net/wiki/common-blockbench-issues-mcreator
