### ISSUE TITLE
[Issue/Suggestion] Blockbench exports all cubes, including hidden ones

### ISSUE THREAD

**Issue by Boundarybreaker** [JannisX11/blockbench#117]
Blockbench 1.11.6

With 2D editing apps like Photoshop or Aesprite, a hidden layer isn't exported when you export a file. However, it looks like all cubes, hidden or not, are exported to JSON when you export in Blockbench. Since it's helpful to design things like cables with all their faces in but then export them separately as submodels, would it be possible to have hidden cubes not exported into json? Thank you!

**Comment by realjackasterisk** [comment]
Are you sure you have the export option turned off for hidden cubes? Hiding elements and toggling whether they're saved or not are entirely different options.
![image](https://user-images.githubusercontent.com/31686191/39842546-a8e150ba-539b-11e8-8c90-d87352cce8e4.png)

**Comment by Boundarybreaker** [comment]
ahhh, that makes sense. Thanks!
