### ISSUE TITLE
[Suggestion] Create Texture from Model Button should be a dedicated button

### ISSUE THREAD

**Issue by Speiger** [JannisX11/blockbench#1171]
Lets say I had trouble finding that, because it was so hidden.
On top of that optimization should be a "Should we optimize it" otherwise just let UVs how they are...

Why is that a issue?
You want to make tiny fixes to a model and get a template texture to your artist or for yourself? Yeah this button is really needed...
And when asking about it in discord someone said: Searching for it for 3 months now...

I had to lookup a YT tutorial to find this SERIOUSLY NESSESARY button.. Techne the outdated version had this button dedicated in its menu bar. Why isn't this a dedicated button here?

For everyone who wants to know how to access it:
- Click on Create texture button,
- And select template Texture, it will create a Texture from the model. If you have your UVs already aligned just disable rearranging uvs.
- This only works when you have a shape already present.

**Comment by JannisX11** [comment]
I don't think this needs to be a separate button. Feels quite well placed as an option in the texture generator.

**Comment by Speiger** [comment]
@JannisX11 it is really hidden and it would be nice if this was more accessible... So i dont rely on a YT video...
Or a random GH issue to find this problem

**Comment by JannisX11** [comment]
I really don't know what you are missing. The "Create Texture" button in the Textures panel is quite easy to find.

**Comment by Speiger** [comment]
@JannisX11 only if you watch a youtube tutorial.
It should be explained in the "help" section at least.
"Create a texture from a model"
