### ISSUE TITLE
[Suggestion] Support "variable" or "v" within Blockbench with variable placeholder value

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1173]
Any "query.foo" or "q.foo" works in a keyframe with a query value placeholder, but not "variable.foo" or "v.foo" with a variable placeholder in Blockbench, it will always return 0.

-Blockbench 4.0.5

**Comment by JannisX11** [comment]
This is already possible in the latest version.

**Comment by PaulFinnerty** [comment]
I tried using "variable.foo == n" in a keyframe (with n different than 0), and it only returned 0

**Comment by JannisX11** [comment]
Make sure you are not using shorthands in the variable placeholder list. That's something that's actually not supported yet.

**Comment by PaulFinnerty** [comment]
Just checked again, I must have had a typo in the variable name... It does work, sorry.
