### ISSUE TITLE
[Screenshoot Model Issue] Pressing save in Screenshoot Model doest work

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1176]
Can save Screenshooted Models
My Blockbench version is the Latest Update

https://user-images.githubusercontent.com/81752216/144437702-f8ad5abe-5504-4c56-97d0-130a3e6e8fa6.mp4

**Comment by JannisX11** [comment]
I cannot reproduce the issue. But you can alternatively long-press on the image to copy or download it.

**Comment by MusicScience** [comment]
Long pressing will also not work
