### ISSUE TITLE
[Issue] elements became invisible/non intractable, controls don't show and gizmo doesn't show as well

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#119]
Supply the following information:
- Detailed description of your issue
elements became non intractable, some became invisible, right side controls don't show up, gizmo is unresponsive and throws errors while working

- Blockbench variant (Webapp/Desktop)
Both Webapp and Desktop

- Operating System
Windows 10 64-bit Home
[-1527981159972.log](https://github.com/JannisX11/blockbench/files/2065685/-1527981159972.log)

**Comment by JannisX11** [comment]
Likely fixed in 2.0.
