### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by Shadowplayz1621** [JannisX11/blockbench#1191]
When creating a new project and going to the edit tab, we can only use the tools for 5 seconds, and then, the model freezes, I tried reloading it and I didn't work, and when I went to quad screen mode and came back to single screen, it again only worked for 5 seconds
And this was in Android (web app)
Please Fis This 🙏

**Comment by JannisX11** [comment]
I cannot reproduce this issue. Maybe the device does not have enough memory.
