### ISSUE TITLE
[Suggestion] Auto-Save feature

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#12]
Often times when making a model it would be irreversibly be lost due to forced restarts/power outages/accidental clicking, etc. Thus it would be really nice if there was a setting you could turn on, where you'd also enter how many minutes pass until another autosave is made. There would be an autosave folder, where a model would have a folder and in that folder there will be files called "modelname_DD_HH_MM" which would be filled by the time it was saved.

**Comment by JannisX11** [comment]
Mrjvs added this as a plugin. Going to close this issue for now.

**Comment by Cassumbra** [comment]
where is this plugin? :?
unsure if its still up, as i cannot find it.

**Comment by JannisX11** [comment]
The plugin no longer exists because this is now a built-in feature (Help > Backup Folder).

**Comment by Cassumbra** [comment]
ah, yeah, i did see that
unfortunately, backups are different from saving files automatically upon changes being made
but maybe i should open a different issue for that since that seems to be a different idea than this one
