### ISSUE TITLE
[Issue] Icon and other issues with Linux desktop file

### ISSUE THREAD

**Issue by RyanGar46** [JannisX11/blockbench#1207]
Please make sure to provide the following information:
- This only applies to Linux
- Icon and other information is incorrect on Linux
- This affects the newest version of Blockbench

This can be fix by editing the Linux section of the package.json file.

**Comment by RyanGar46** [comment]
#1208

**Comment by JannisX11** [comment]
Are you sure? I need to get a linux system to test again, but in theory meta data should be automatically taken from package.json and the icon should be generated from the macOS icns file. Can you show me a screenshot of before and after on linux? Also, which packages does this apply to?

**Comment by RyanGar46** [comment]
After one quick edit I got it to work. I am on mint so I used a .deb file, but I don't know if this affected other packages.
Before:
![Screenshot from 2021-12-13 17-02-17](https://user-images.githubusercontent.com/67124977/145896686-0eb1ff44-97f0-4f36-8b85-4086e12ef871.png)
After:
![Screenshot from 2021-12-13 17-05-36](https://user-images.githubusercontent.com/67124977/145896690-5164b48a-f7f0-4d7b-8e10-b01b1771439e.png)

**Comment by JannisX11** [comment]
Fixed in 4.3.
