### ISSUE TITLE
[Issue] Texture error

### ISSUE THREAD

**Issue by ZeuSantos** [JannisX11/blockbench#1213]
I have a problem, I can't create a perfect texture, when I go to create a texture a yellow texture appears,
furthermore, this bug is not on all devices.

**Comment by Wackyblocks** [comment]
Could you provide more information? what devices, include images and versions, thanks

**Comment by ZeuSantos** [comment]
When I go to create a texture model, it creates a yellow texture with a red band on the top and a green band on the left side.

**Comment by ZeuSantos** [comment]
![Screenshot_2021-12-20-16-58-13](https://user-images.githubusercontent.com/96253617/146827140-a13a15ba-3976-484d-a0ca-afe492035422.png)

**Comment by ZeuSantos** [comment]
![Uploading Screenshot_2021-12-20-16-57-57.png…]()

**Comment by ZeuSantos** [comment]
![Screenshot_2021-12-20-16-57-52](https://user-images.githubusercontent.com/96253617/146827237-cb4a13a2-eec9-4846-ab3e-931db8066710.png)

**Comment by ZeuSantos** [comment]
my smartphone is a samsung

**Comment by ZeuSantos** [comment]
Android 6
