### ISSUE TITLE
[Suggestion] Support query.modified_distance_moved and query.ground_speed + simulate entity movement

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1221]
I got this idea from the new togglable ground plane:

- Be able to set a speed value in Blockbench (either in meters/s, or matching the "minecraft:movement" behavior. The other value should change according to the one you set)

- This would simulate the entity moving forward in a straight line, but keeping it in place. If you toggle the ground plane on, you would see the texture of the ground moving at the speed you set. (synced with the playback speed too)

- If you used speed queries somewhere in an animation keyframe, or in anim_time_update (typically q.modified_distance_moved in anim_time_update), the query values would update accordingly.

- ideally, imported particles would react accordingly (for world space velocity)

---

I mocked it up to make it a little bit clearer. The speed values are bogus, I don't know the exact conversion between behavior speed and m/s.

![bb_mockup_speed_queries](https://user-images.githubusercontent.com/81629481/147268987-ae2ef260-7927-422f-9ed2-1339757f13cd.png)

This would be extremely helpful for making all kinds of walking animations.

**Comment by JannisX11** [comment]
Added in 4.3!
