### ISSUE TITLE
[Suggestion] have the translate gizmo accuracy be used by keys as well

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#123]
Supply the following information:
- Detailed description of your suggestion
Pressing the accuracy modifier keys will be used by the keyboard keys as well for translation
- Blockbench variant (Webapp/Desktop)
Webapp and Desktop
- Operating System
Windows 10 64-bit Home

**Comment by JannisX11** [comment]
Added in 2.0.2
