### ISSUE TITLE
[Issue] 4.0.5 Version updated to 4.1.1 After version, the animation mode cannot display the key frame icon normally

### ISSUE THREAD

**Issue by OldShadowXD** [JannisX11/blockbench#1236]
4.0.5 Version updated to 4.1.1 After version, the animation mode cannot display the key frame icon normally (the cube icon will be displayed in the timeline after the key frame is set normally), 4.1.0 Version and 4.1.1 Version can't be displayed normally. I tried to reinstall 4.0 After version 5, it can be displayed normally and updated to 4.1.1 again After version, the problem occurs again.（When the timeline in the picture is normal, there are key frame points displayed）
（I'm very sorry for my poor English, so I used translation software to assist）
![44SA)JHE~6(GEM}U ~ TF`F](https://user-images.githubusercontent.com/96846032/147706219-2231f68f-5a8c-4fd2-94df-6da57e18260d.png)

**Comment by JannisX11** [comment]
It looks like several icons are invisible, including the move tool icon.
