### ISSUE TITLE
[Issue] Floor cuts background image

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1238]
Floor cuts background image, Floor is rendered as an model, which is rendered above background

Image from nygma_
![unknown](https://user-images.githubusercontent.com/44243757/147783262-38930dc0-ff65-4e38-9c96-7007f2aa8f45.png)

Blockbench 4.1.1

**Comment by JannisX11** [comment]
This works as intended, the model is part of the 3D scene, which sits in front of the background. I agree that there are use cases where you would want background images in front of the ground, that's why I reopened the suggestion.
