### ISSUE TITLE
[Issue] gLTF export does not properly export Groups

### ISSUE THREAD

**Issue by leumasme** [JannisX11/blockbench#1239]
Using the Blockbench Webapp, i am currently making a model for import via Three.js

I am exporting the Model to gLTF, but noticed that the gLTF export of the model does not properly respect the groups i created in blockbench.
All my cubes are in groups, but when importing into Three.js, the children structure is completely flat

![image](https://user-images.githubusercontent.com/29953391/147785316-93969a96-0624-4346-a639-1a38f10f8e50.png)
The top 4 elements are Groups in my blockbench project, that all other cubes are located inside of.
Thus, those cubes should be children of the top 4 elements, which they are not

![image](https://user-images.githubusercontent.com/29953391/147785303-10121033-8e27-4fe3-8277-2ad9e2e1cb67.png)
My VsCode gLTF extension throws warnings in the Blockbench-generated gLTF file, as the Groups generated completely empty nodes.
(I think that this should be proof that this is a blockbench issue - not a three.js issue)

**Comment by leumasme** [comment]
It seems that the Blockbench GLTFExporter.js has support for children/groups, but the three.js scene that is passed into it already uses the same flat structure without children.
I was able to find the real structure of nodes and groups in Outliner.root, but i dont know anything about blockbench's codebase so im too lost to solve this myself.

**Comment by leumasme** [comment]
Creating a Group inside a Group will properly create it as a child in the three.js scene as well - for cubes inside groups, it does not.

**Comment by leumasme** [comment]
I was able to manually fix the Three.js Scene structure for a group by calling
`Canvas.updateAllBones(Outliner.root[0].children)`
updateAllBones is also called by blockbench for groups (which work properly due to that), but not for block nodes

**Comment by JannisX11** [comment]
Which model format are you using? You can see the format by going to File > Project.

**Comment by leumasme** [comment]
> Which model format are you using? You can see the format by going to File > Project.
Java Block/Item, but only as the person who originally made this Model started it in this Format, i am not actually using the Model for Minecraft

**Comment by JannisX11** [comment]
Okay, that's the reason. Java Block/Item models have no hierarchy, the groups in the outliner are just used for sorting. If you want to have a physical hierarchy in the 3D model, you need to convert the model into a format that supports hierarchy, such as Generic Model. So this works as intended.
