### ISSUE TITLE
[Issue] Instead of saying 'Edit' it says 'Pose'. I'm trying to retexture the Bee but I cant resize or position. I can only rotate.

### ISSUE THREAD

**Issue by Adrian123023** [JannisX11/blockbench#1241]

**Comment by Wackyblocks** [comment]
Skin mode was simplified to disable custom geometry, because that wasn't ment to be really used anyway, and it makes the interface less complicated.

But I do agree you with the posing, it should allow moving elements to get ideal poses for screenshots, gifs, etc..
