### ISSUE TITLE
[Suggestion] BarItem.face_tint.condition is hardcoded for java block/item

### ISSUE THREAD

**Issue by SnaveSutit** [JannisX11/blockbench#1248]
Currently the only way to give your format the face_tint option is to overwrite the condition here:
![image](https://user-images.githubusercontent.com/28514936/148645220-a73063e0-93f9-48b5-8362-e91f6e71d8fb.png)

Probably could be changed to operate based on the current project's `format.allow_face_tint` or similar.

**Comment by JannisX11** [comment]
This is now conditioned on the `java_face_properties` format feature.
