### ISSUE TITLE
[Suggestion] Context options for touchscreen

### ISSUE THREAD

**Issue by pedestriantactics** [JannisX11/blockbench#1249]
Given pinch to zoom and panning, the web app is actually more effective on my iPad than on my computer. However, I can’t access any of the context options because I can’t right click. Would it be possible to add visible context options or have some other way to access the context menu?

**Comment by variousaccidents** [comment]
Are there any context options available without keyboard shortcuts to support touchscreens?

**Comment by JannisX11** [comment]
There are actually context menus on mobile that you can access via long-press, however long-press in Safari triggers a text selection and prevents the context menu from opening, which is an issue with the browser.

**Comment by pedestriantactics** [comment]
Would it be possible to add user-select: none to everything in the web app? This is addressed in this article https://www.reddit.com/r/webdev/comments/g1wvsb/ios_safari_how_to_disable_longpress_text_selection/
