### ISSUE TITLE
Null Objects dont show the proper selection of child bones

### ISSUE THREAD

**Issue by Wadoo-Gazoono** [JannisX11/blockbench#1253]
I was trying to use IK with a model on the BlockBench Program, but when I went to select the bone to apply it to from a null object, it gave me the wrong list of bones to choose from, specifically, the list was from the last model I used IK on, and I wasn't able to use IK on my current model because of this.
This is the selection the null object gives me
![image](https://user-images.githubusercontent.com/70168235/149253459-fb1b9924-7f0d-4e04-8b3a-526bc4849469.png)
While this is what the actual model tree looks like
![image](https://user-images.githubusercontent.com/70168235/149253495-54930a6e-3e39-4456-ba45-e55c4ecda0e1.png)

I first saw this in the geckolib format version, but this also happens in the generic model format as well. I am currently using Windows.

**Comment by JannisX11** [comment]
I cannot reproduce this issue.
