### ISSUE TITLE
Invisible keyframes

### ISSUE THREAD

**Issue by RicardoLGCS** [JannisX11/blockbench#1258]
Hi, recently i started to use blockbench to animate my entities and items but i noticed that whenever i try to animate anything whether it is a item, or entity, or even another type of project such as bedrock (i am using java edition) the keyframes don't show up for some reason. The animation is still performed but i am unable to change it as i can't access the keyframes, the OS i am using is Arch Linux with the distribution Garuda Linux if that helps. In the previous version i was able to access them through Ctrl + A even though they were invisible but now i can't even do that, also i tried to look in to the dev console for errors but everything seems to be fine. I would appreciate if anyone could help me, thanks in advance.

**Comment by JannisX11** [comment]
Should be fixed in 4.1.4.
