### ISSUE TITLE
[Issue] The UV of the Reference Models are wrong

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#126]
Supply the following information:

- Detailed description of your issue
The reference models UVs for zombie, baby zombie, armor_stand, and small armor_stand are wrong
- Blockbench variant (Webapp/Desktop)
Webapp and Desktop
- Operating System
Windows 10 64-bit Home

**Comment by JannisX11** [comment]
Please explain what exactly is wrong. I noticed that the bottom of the zombie arms is flipped. When everything is fixed, I can close this issue.

**Comment by 3XH6R** [comment]
![image](https://user-images.githubusercontent.com/32020441/44613291-6c788100-a7c6-11e8-8fb2-dd805bb43c4f.png)
![image](https://user-images.githubusercontent.com/32020441/44613311-a21d6a00-a7c6-11e8-90e3-f8d05d7f7e89.png)
The back/bottom of the head, bottom/top/outer sides/inner sides of arms and legs for every new preview entity there is
