### ISSUE TITLE
[Issue] No way to ungroup/resolve on mobile

### ISSUE THREAD

**Issue by pedestriantactics** [JannisX11/blockbench#1265]
For touchscreens that can’t right click, none of the context menu options are available. Most of these can be found in the toolbar, however I can’t find any option for ungrouping. 

The current workaround is to move everything out of the group and then delete the group from the toolbar.

**Comment by JannisX11** [comment]
You can long-press a group in the outliner to bring up the context menu and resolve it.
There is a suggestion to enable shortcuts for resolving groups here: #1252.

**Comment by pedestriantactics** [comment]
> You can long-press a group in the outliner to bring up the context menu and resolve it.
> There is a suggestion to enable shortcuts for resolving groups here: #1252.

I tried doing this on iOS devices and it immediately goes to selecting the HTML text of the group title. Might be different on Android but it doesn't seem doable at all on iOS.
