### ISSUE TITLE
[Issue] Meshes cannot be selected with box select

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1268]
Cannot box select meshes

Blockbench 4.1.3

![Blockbench_7BE8rAdZPL](https://user-images.githubusercontent.com/44243757/151564929-caa549d9-3fd1-4afd-8972-faf9c591ac8a.gif)

**Comment by JannisX11** [comment]
Double check that your selection mode is Object.

**Comment by Wackyblocks** [comment]
I was not on object mode. Makes sense

I was thinking it would make sense to select it, if it wasnt active, but Blockbench doesnt have a toggle for edit mode, so it wouldnt really work either.
