### ISSUE TITLE
[Suggestion] Preview for Bedrock Edition entity models

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#127]
Supply the following information:
- Detailed description of your suggestion
Possible preview of how an entity model would look in game and a top right Preview tab in entity mode with a drop down list of entities on the side.
- Blockbench variant (Webapp/Desktop)
Webapp and Desktop
- Operating System
The ones Blockbench supports
![preview_off](https://user-images.githubusercontent.com/32020441/42420608-5f53a072-827d-11e8-9a02-8ba757864a46.jpg)
![preview_on](https://user-images.githubusercontent.com/32020441/42420607-5f36ee5a-827d-11e8-9a8a-bcac4bde939a.jpg)

**Comment by JannisX11** [comment]
I'm gonna close this for now since I am working on different ways to basically achieve the same goals.
