### ISSUE TITLE
[Suggestion] Assign cubes to be toggled by the skin layer

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1287]
It would be very helpful if you could assign cubes to be toggled by the skin layer button/keybind. I'd imagine it'd act the same as cubes that are already set to be toggled on/off by default (like the hat layer on the player model in the "Minecraft Skin" preset.)

**Comment by JannisX11** [comment]
You can do this by adding "layer" to the cube's name.

**Comment by Estecka** [comment]
> You can do this by adding "layer" to the cube's name.

This only seems to work on "Minecraft Skin" models. I'm editing an OptiFine model (imported from a json), and renaming the cubes doesn't seem to do anything; the option to toggle the skin layer remains hidden.
