### ISSUE TITLE
[Issue] Can't open "File -> Project..." window

### ISSUE THREAD

**Issue by NguyenDuck** [JannisX11/blockbench#1288]
Click on File -> Project... don't take any effect, window
Screenshot
![Screenshot from 2022-02-14 00-30-07](https://user-images.githubusercontent.com/83252725/153782816-3c34624f-3834-4952-a4b4-da1581fd35b4.png)

- Blockbench variant: Website
- OS: Linux

**Comment by JannisX11** [comment]
I cannot reproduce the issue. According to a quick Google search, it might be caused by a browser extension.
