### ISSUE TITLE
[Suggestion] Be able to parent groups

### ISSUE THREAD

**Issue by Nezara** [JannisX11/blockbench#129]
Hi There

im finding that when creating models with multiple joints I need to rotate and reposition each individual joint (say like a tail). It would be absolutely wonderful to be able to parent groups so that rotating one joint will rotate all subsequent connecting joints in that group. 

If I try and put groups within groups rotating one will reset the second group.

Keep up the amazing work.

**Comment by JannisX11** [comment]
Completely added in Blockbench 2.0.2
