### ISSUE TITLE
[Help] I need help about Script in Particle effect

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1294]
I know this isn't a bug but i have issues about what is this Script in Particle tab
![Screenshot_20220221-192702](https://user-images.githubusercontent.com/81752216/154947357-35936eb0-8bcb-41e2-9896-632edc43e2b8.png)

**Comment by JannisX11** [comment]
Please use the Discord server for help, as explained by Github when creating an issue.
