### ISSUE TITLE
[Issue] Text selection should be disabled for web app to access context menus

### ISSUE THREAD

**Issue by pedestriantactics** [JannisX11/blockbench#1298]
It is possible to select text by long pressing on iOS touchscreen devices, which makes it difficult to access context menus in the web app. I believe this can be disabled in the body of the web app by adding `user-select: none `. 

Visual example
![979DF5A5-620E-4FF8-B9F7-2601AAC51D3F](https://user-images.githubusercontent.com/29744444/155393074-1e1c8757-4088-49c4-9e10-ec17c8c43f7f.jpeg)

This is a more specific request derived from issue #1249.

**Comment by JannisX11** [comment]
This is already the case. Unfortunately Safari ignores it. It works fine in all other major browsers.

**Comment by gerroon** [comment]
I can confirm that Safari on IOS ignores the long click and makes it a text selection, which is sad, because that menu is so useful otherwise.

**Comment by JannisX11** [comment]
Seems to be fixed now in 4.7.1. The usage of `-webkit-user-select` might have helped.
