### ISSUE TITLE
[Issue] Adjusting Mesh UV breaks position and scale

### ISSUE THREAD

**Issue by gravyarts** [JannisX11/blockbench#1300]
Blockbench Version: 4.1.5
![image](https://user-images.githubusercontent.com/43098489/155818807-6a4a6092-7c6a-4b81-8b06-f5db8510d2a4.png)
![image](https://user-images.githubusercontent.com/43098489/155818896-7fb9c135-165e-4db8-8b50-a5cb495e6439.png)

Please make sure to provide the following information:
- Creating a mesh and trying to adjust the UV vertex breaks the position and scaling.
![image](https://user-images.githubusercontent.com/43098489/155818681-e77c4dd6-105e-4a1a-a53d-e1cb96623530.png)
![image](https://user-images.githubusercontent.com/43098489/155818716-e9894e0f-61eb-4a90-adaa-af4fb8f89643.png)
- Generic
- Blockbench Program
- Win10

**Comment by JannisX11** [comment]
I cannot reproduce the issue. Please add detailed steps to reproduce.
