### ISSUE TITLE
[Suggestion] 2 Improvements Suggestion

### ISSUE THREAD

**Issue by Malik12tree** [JannisX11/blockbench#1301]
# Normalizing Vectors
You as developer, you know that Square Roots are heavy operations, specifically when normalizing so many vectors at the same time.
So that there is a faster algorithim called **Quake III** ( _or Fast Inverse Square Root_) for calculating 1/sqrt(x), it makes the operation 3 times faster. when implementing it in JS, u need to use BufferArrays for bit manipulation which decreases the speed to 2 times (still good).
Here is an implementation i found, and made it work with Threejs vectors;

`// original: https://en.wikipedia.org/wiki/Fast_inverse_square_root`
`// JS version: https://gist.github.com/starfys/aaaee80838d0e013c27d?permalink_comment_id=1691253#gistcomment-1691253`
`// have an error of a very small amount, e.g: 1/qr(1) == 1.0016957210172461; but as long its fast, its okay.`
`var buf = new ArrayBuffer(4),`
`    f32=new Float32Array(buf),`
`    u32=new Uint32Array(buf);`
`function q2(x) {`
`    var x2 = 0.5 * (f32[0] = x);  // evil floating point bit level hacking`
`    u32[0] = (0x5f3759df - (u32[0] >> 1)); // what the fuck?`
`    var y = f32[0];`
`    y  = y * ( 1.5 - ( x2 * y * y ) );   // 1st iteration`
`    return y;`
`}`
`THREE.Vector3.prototype.normalize = function() {`
`	const inverseLength = q2((this.x**2) + (this.y**2) + (this.z**2)); // 1/sqrt(...)`
`	this.x *= inverseLength;`
`	this.y *= inverseLength;`
`	this.z *= inverseLength;`
`	return this;`
`}`

# Resolution Screenshots
This is just a concept. Cant we increase the canvas size to a chosen resolution and updating the stretching thingy, then capturing the canvas url? i think this might work🤷‍♂️

**Comment by JannisX11** [comment]
Can you specify which task in Blockbench you mean when you're talking about square root algorithms?

**Comment by Malik12tree** [comment]
> Can you specify which task in Blockbench you mean when you're talking about square root algorithms?

Many places where using the `Vector3.normalize` method _(`MeshFace.getNormal(true)` for example)_; `Math.sqrt()`, its used in `Vector3().length`, for getting the length. In `Vector3().normalize`, it uses the length method which again uses square roots.
