### ISSUE TITLE
[I can’t edit my mobs!!] Hi! My name is Gamer105. I use the mobile blockbench and I have a problem! I was going through the entity wizard and when I tried to go to the area “Next Steps” it instead took me to the export spot even when I already exported it! So can you please help me? I really want to edit my mob!

### ISSUE THREAD

**Issue by Gamer105** [JannisX11/blockbench#1302]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by JannisX11** [comment]
Editing add-ons is a bit more complex on mobile devices. Learn more here: https://www.youtube.com/watch?v=c8nIyjAwl9U
