### ISSUE TITLE
[Scalable Animation Window] Scale Animation tab window so we can customise the tab like we want cause it's so small

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1303]
Scale Animation tab window so we can customise the tab like we want cause it's so small in I can't press buttons
![Screenshot_20220227_114839](https://user-images.githubusercontent.com/81752216/155867511-33c1bff0-7555-4f2c-a9cd-d5834ccf8910.jpg)

**Comment by GlamrockFedy** [comment]
same thing to me but opposite, the animation tab is too big that i cant select anything in the model

**Comment by JannisX11** [comment]
Added in 4.2.
