### ISSUE TITLE
[Issue] Animations on save floats that are written as ".1" should output as "0.1"

### ISSUE THREAD

**Issue by Blairgendary** [JannisX11/blockbench#1308]
**Description**: Minecraft animations won't read ".1" correctly. Therefore it would be great to have any floats that are missing a 0 in front of the decimal output as "0.1" rather than ".1". 
**How to test**: Write a math.sin() animation. Such as X: _math.sin(query.anim_timex360)x.5_. Notice that it will appear nice in blockbench and jittery in bedrock. ( You'll need to replace some x with * ) If you'd like the animation to work in Bedrock you'll need to write the equation as _math.sin(query.anim_timex360)x0.5_.
**Model Format**: Bedrock
**Blockbench Variant**: Program
**Operating Systems**: Windows 10

**Comment by JannisX11** [comment]
Blockbench doesn't process Molang expressions when exporting, you'll have to write valid Molang from the start.
