### ISSUE TITLE
[Issue] Auto UV is atrocious

### ISSUE THREAD

**Issue by JapanYoshi** [JannisX11/blockbench#1313]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.
![image](https://user-images.githubusercontent.com/8707990/156132525-cb0e2227-1339-45a0-852f-a2e726c9a55a.png)

Please make sure to provide the following information:
- Detailed description of your issue
My simple coplanar shape does not get texture mapped correctly. Connected edges jump around willy nilly.
![image](https://user-images.githubusercontent.com/8707990/156132334-fb0f343d-9039-4ad6-aaf4-b2c7126b2b85.png)

- Model format in which the issue occurs
Generic model

- Blockbench variant (Website / PWA / Program)
Website (on Firefox)

- Operating System
Windows 10

**Comment by JannisX11** [comment]
Could you attach the model?

**Comment by JapanYoshi** [comment]
It’s just a rounded square made of one square, four rectangles, and four circles cut into quarters.

**Comment by JannisX11** [comment]
Connected coplanar faces now get UV mapped together with 4.2+.
