### ISSUE TITLE
[Issue] When exporting as gltf the texture and uv get flipped and resized

### ISSUE THREAD

**Issue by asphyxxious** [JannisX11/blockbench#1318]
When I want export models as gltf and then import them into blender I get the issue that the texture UV is flipped upside down and gets resized. But I want them to look the same as in Blockbench.

UV and texture in Blockbench

![image](https://user-images.githubusercontent.com/69436960/156881079-49d5ad6b-222c-416c-88f2-b98301053796.png)

UV and texture in blender:

![image](https://user-images.githubusercontent.com/69436960/156881075-a18eab46-762a-4aaa-9f9f-11b344042649.png)

**Comment by JannisX11** [comment]
The model looks the same to me. The texture gets flipped, but that is intentional due to a different UV coordinate system.
