### ISSUE TITLE
[Issue] I have installed the plugin "Player Article Generator". But this plugin doesn't show up in my filters.

### ISSUE THREAD

**Issue by StasikWlas123** [JannisX11/blockbench#1319]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- I have installed the plugin "Player Article Generator". But this plugin doesn't show up in my filters. What should I do???
- Model format in which the issue occurs
- I was making an AK-47 model
- Blockbench variant (Website / PWA / Program)
- Operating System
- Windows 10

**Comment by JannisX11** [comment]
I assume you are talking about the Player Statue Generator, in that case it only works in the Minecraft Java Block/Item format.
