### ISSUE TITLE
[Entities animation bug inside the minecraft pe game] animation only works from blockbench and not within the game at the time of minecraft pe game

### ISSUE THREAD

**Issue by joelson2023** [JannisX11/blockbench#1320]
I'm having problems with my entity's animation. on the blockbench platform through the browser, everything is correct in the formation of my animation, however when it is opened in my map of the minecraft pe game on my smarphone, the animation does not appear or does not appear. it's like frozen my mob without any movement.

template format is json(animation only bug)
Blockbech variant on the website
Entity animation operating system

![entity animation bug only within minecraft pe game](https://user-images.githubusercontent.com/101033976/156911795-4c36a82b-7f50-44ef-9355-fdc1b3d4c14a.png)
![Entity animation bug within the game](https://user-images.githubusercontent.com/101033976/156911798-cb095086-22b1-40e9-86be-950eec8b6b2f.jpeg)

**Comment by PaulFinnerty** [comment]
That's not an issue with Blockbench, but with your implementation. I suggest you read up on the [Bedrock documentation](https://bedrock.dev/docs/stable/Entities#Client%20Entity%20Documentation) to fix that, or ask in the [Bedrock Add-ons Discord]( https://discord.gg/nkb7Rk7Y) if you have any question
