### ISSUE TITLE
[Beta] [Issue] Color window minimum vertical size limit too small on float mode

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#1327]
- Open paint mode
- Set color tab as float
- Window can be rezised on "Picker" or "Both" modes beyond visual box size

![image](https://user-images.githubusercontent.com/44243757/157879886-705a0d32-bf1a-4096-8967-c3e3c56d29d3.png)

Blockbench 4.2 beta.1

**Comment by Wackyblocks** [comment]
Also an issue on top/bottom panels fills entire window, fills entire middle portion on most screens.
A different layout desing for top/bottom tabs would fit better and take less space

<img width="871" alt="image" src="https://user-images.githubusercontent.com/44243757/157882323-9c0fa458-c111-42e6-ad9f-d00040f1d63d.png">

**Comment by JannisX11** [comment]
Fixed in 4.2 release.
