### ISSUE TITLE
[Issue] Negative scale in display settings not possible

### ISSUE THREAD

**Issue by dragonmaster95** [JannisX11/blockbench#133]
- Detailed description of your issue
When one tries to set the scale of any display setting to a negative number it will be replaced by 0.001
It is however possible to use negative values in scale in vanilla models (basically flips the model).

- Blockbench variant (Webapp/Desktop)
Desktop - Version 1.11.6
- Operating System
Windows 7

PS: Opening a model with negative scale values works fine, but the number gets reset as soon as you edit that number in some way.

**Comment by leoste** [comment]
I might remember wrong but isn't there an option in the settings that enables negative scale?

**Comment by JannisX11** [comment]
Added in the next version:
![image](https://user-images.githubusercontent.com/29278436/48664709-1b191e80-eaa3-11e8-9a9d-30e9e10ed45b.png)
