### ISSUE TITLE
[Issue] Help! Yes it’s me again I don’t know witch app to use! I use a apple ipad. Can you help me please?

### ISSUE THREAD

**Issue by Gamer105** [JannisX11/blockbench#1347]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by JannisX11** [comment]
Please follow the instructions and use the Discord server for help. Github issues are intended for bug reports.
https.//discord.gg/blockbench
