### ISSUE TITLE
[Issue] Keybindings menu cannot be closed

### ISSUE THREAD

**Issue by MidNite00** [JannisX11/blockbench#1350]
The keybinding menu cannot be closed via the "X" or "ESC", the only way out is to switch to settings in the bottom right drop down and close that menu to exit out. I'm not sure of the cause but it seems to reproduce the bug 100% of the time.

- Windows 10
- Blockbench 4.1.5
- Bedrock Model Type

**Comment by JannisX11** [comment]
I cannot reproduce the issue. Could you attach a screenshot of your console after trying to close the dialog? (Help > Developer > Open Dev Tool > Console Tab)
