### ISSUE TITLE
Horizontal images displaying properly in UV window

### ISSUE THREAD

**Issue by ReiaTheGeia** [JannisX11/blockbench#1351]
It displays the textures as if it's vertical, even if the dimensions indicate that it's horizontal. I swap the dimensions and it looks the same but the window wants me to work with it vertically rather than horizontally. With both the actual code works fine, but it displays in such a way to make it unworkable

**Comment by JannisX11** [comment]
You can change the project resolution in the project settings, this affects the aspect ratio.
