### ISSUE TITLE
[Suggestion] Make Blockbench offline again

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1355]
It would be nice if Blockbench would be offline again like in the previous versions

When I open Blockbench when online and then I closed it cause I'm done modelling. a few minutes later i opened blockbench again but offline and its said "To use blockbench for the first time please connect to the Internet" even though it's not my first time

![Screenshot_20220330_161710_com android chrome](https://user-images.githubusercontent.com/81752216/160809543-0b8be3e3-41be-4a8d-85fb-dbe5664da563.jpg)

**Comment by JannisX11** [comment]
I cannot reproduce the issue on my device

**Comment by MusicScience** [comment]
Ok thanks but
can you fix it anyway??
