### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by HmmTYIN** [JannisX11/blockbench#1356]
Blockbench failed to load with this error message:
Uncaught TypeError: cannot read property of null {reading,'inside_vue'}

![image](https://user-images.githubusercontent.com/86844197/160847857-6d79b45d-9e23-4cdb-9d01-928fda01d403.png)

**Comment by JannisX11** [comment]
Fixed in 4.2.1

**Comment by HmmTYIN** [comment]
Alr Thanks!
