### ISSUE TITLE
Were ads really a great idea?

### ISSUE THREAD

**Issue by HmmTYIN** [JannisX11/blockbench#1361]
ads while modeling, why? That's my one question

**Comment by Dakotero** [comment]
You can opt out of ads with the Pro plan, is just 19.99usd a month, and it comes with themes, a [ceate NFT] buttom, and light/dark mode

**Comment by 3XH6R** [comment]
But don't delay, get the Pro plan today! The first three months are 10% off during April 1st to April 8th.
It also includes a free pin badge and a mug as a thanks for your support!

**Comment by ListerWorks** [comment]
Is there a fix for this? It's coming up with inappropriate stuff in the ads. I've had to stop my 11-year-old son from using the program. 20 a month? Your joking right?

**Comment by JannisX11** [comment]
Happy April Fools day!
The ads are now gone, they were all references to something in the Blockbench community, no real ads. Sorry for any inconvenience!
