### ISSUE TITLE
[Issue] confirmEnabled and cancelEnabled dont disable the confirm and cancel buttons on the Dialog object

### ISSUE THREAD

**Issue by tmudway** [JannisX11/blockbench#1369]
Attempting to set either of these properties to false in a Dialog object has no impact on the appearance of the window. Searching for either of those terms in the repository gives zero hits

Code used
```javascript
exportWindow = new Dialog('C&CExportWindow', {
    title: 'BAMO Exporter',
    component: vueComponent,
    confirmEnabled: false,
    cancelEnabled: false,
})
```
Output
![image](https://user-images.githubusercontent.com/3653340/161668220-fe8064e1-587f-4c40-a900-4d8fed2aa70c.png)

**Comment by JannisX11** [comment]
These fields haven't been supported for quite a while. I know they are still on the wiki, I'll remove them next time I update the page.

**Comment by JannisX11** [comment]
Also, if you want to disable either button, you can `return false` in the onConfirm or onCancel event.
