### ISSUE TITLE
[Issue] Unable to use brush on some faces

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#138]
- The brush tool sometimes does not paint faces when you click on the model. It appears to be caused by the face's dimensions not being a multiple of 1.0. Possibly a UV issue? 
- Blockbench 1.11.6 Desktop
- Windows

I am unable to paint the white spots in the model shown below by clicking on it.

Model file & texture:
[halo_ar.zip](https://github.com/JannisX11/blockbench/files/2445058/halo_ar.zip)

![image](https://user-images.githubusercontent.com/7155747/46455368-c3d02080-c778-11e8-8962-15461a3922c6.png)

**Comment by JannisX11** [comment]
Fixed in 2.2.
