### ISSUE TITLE
[Suggestion] Add an option to play animations on looped in the viewer

### ISSUE THREAD

**Issue by MidNite00** [JannisX11/blockbench#1380]
Explanation: In Snowstorm you're able to have "instant" particles play looped in the viewer while working on it, however, Blockbench doesn't have an option for this. As far as I can tell you have to fully change the animation type (how it would export) from "Play Once" to "Loop" while working on it, this isn't ideal. 

My Suggestion: A drop-down menu on the Timeline where you can select "loop in viewer" and then set a value for the delay between the loops would be so helpful

**Comment by JannisX11** [comment]
Added in 4.6.
