### ISSUE TITLE
[Issue] Splash art and Minecraft Entity Wizard prompts always show on startup 

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1382]
Whenever I open Blockbench the Minecraft Entity Wizard and splash art show up, and keep doing so even when I've x-ed out of them before. While I'm not sure whether this is intentional behavior, I recall not having this issue happen before. (before, when you x out of them once they'll never show up on startup, atleast for the splash art, I'm not sure for the entity wizard.)

I'm using the desktop app on Windows 11

**Comment by JannisX11** [comment]
Yup, this is new with 4.2, I decided that the splash arts usually are to beautiful to only show once, so now it always shows up on the start screen. Blender does this too for example.
