### ISSUE TITLE
Can't equip my blockbench skin

### ISSUE THREAD

**Issue by Firestrike3401** [JannisX11/blockbench#1387]
I can't equip my 64× blockbench skin after exported to the gallery 
![Screenshot_20220423-122638_Chrome](https://user-images.githubusercontent.com/104255382/164891218-50f762c0-172f-4323-96b5-b8bccc057ab5.jpg)

![ryXNyBaUMQANxDhB7jJwI8BACsJR3gd252plGCjIYtoNH+NQB8AQL253704F+VAAAAAElFTkSuQmCC (1)](https://user-images.githubusercontent.com/104255382/164891331-52513157-22ef-4373-aa4f-bb2c88c2b044.png)

![Screenshot_20220423-122956_Minecraft](https://user-images.githubusercontent.com/104255382/164891337-8efcbe45-e73b-46b0-9d0e-92e8f4f32109.jpg)

 
What should i do? 
Thanks for the help.

**Comment by JannisX11** [comment]
Minecraft doesn't support high res skins, it only supports 16x resolution skins by default.
In the future, please use the Blockbench Discord server for questions.
