### ISSUE TITLE
[Issue] Preview for dropped item too high

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#139]
- The preview for dropped item models are rendered too high. See the video below. You can see that the model in-game clips through the ground while the model in blockbench does not. Ignore the low FPS, my computer is just crap when having minecraft and blockbench open while recording. 
- Blockbench 1.11.6 Desktop
- Windows

https://www.youtube.com/watch?v=MDYXimc6H20

**Comment by JannisX11** [comment]
Well, it is not that easy unfortunately.

**Comment by Gamebuster19901** [comment]
Wow, what a blast from the past haha.
