### ISSUE TITLE
Error code in blockbench

### ISSUE THREAD

**Issue by OGRobbyJohnson** [JannisX11/blockbench#1398]
I literally had blockbench open yesterday now I am getting this error. I copied the error to clipboard let me know if there is anything else you need.

<html>
<body>
<div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="button" id="copy-to-clipboard" value="Copy Report to Clipboard" style="box-sizing: border-box; user-select: none; appearance: none; background-image: -webkit-linear-gradient(top, rgb(240, 240, 240), rgb(240, 240, 240) 38%, rgb(224, 224, 224)); border: 1px solid rgb(77, 144, 254); border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 0px, rgba(255, 255, 255, 0.95) 0px 1px 2px inset; color: black; font: inherit; margin: 0px 1px 0px 0px; outline: none; text-shadow: rgb(240, 240, 240) 0px 1px 0px; min-height: 2em; min-width: 4em; padding-bottom: 2px; padding-top: 1px; padding-inline: 10px; transition: border-color 200ms ease 0s;"></div><div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Graphics Feature Status</h3><ul class="feature-status-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas out-of-process rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Direct Rendering Display Compositor:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Compositing:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Multiple Raster Threads:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Out-of-process Rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">OpenGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Rasterization:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Raw Draw:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Skia Renderer:<span> </span></span><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">Enabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Decode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Encode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Vulkan:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL2:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li></ul></div><div class="problems-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Problems Detected</h3><ul class="problems-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">gpu_compositing</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">GPU process was unable to boot: GPU process crashed too many times with SwiftShader.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">all</span></i></li></ul></div><div class="dawn-info-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">DAWN Info</h3><ul class="dawn-info-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><br style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">&lt;Discrete GPU&gt; D3D12 backend - NVIDIA GeForce RTX 2070</b><br style="box-sizing: border-box; user-select: text;"><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Default Toggle Names]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">lazy_clear_resource_on_first_use:<span> </span></b><a href="https://crbug.com/dawn/145" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/145</a><i style="box-sizing: border-box; user-select: text;">: Clears resource to zero on first usage. This initializes the resource so that no dirty bits from recycled memory is present in the new resource.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_resource_heap_tier2:<span> </span></b><a href="https://crbug.com/dawn/27" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/27</a><i style="box-sizing: border-box; user-select: text;">: Enable support for resource heap tier 2. Resource heap tier 2 allows mixing of texture and buffers in the same heap. This allows better heap re-use and reduces fragmentation.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_render_pass:<span> </span></b><a href="https://crbug.com/dawn/36" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/36</a><i style="box-sizing: border-box; user-select: text;">: Use the D3D12 render pass API introduced in Windows build 1809 by default. On versions of Windows prior to build 1809, or when this toggle is turned off, Dawn will emulate a render pass.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_residency_management:<span> </span></b><a href="https://crbug.com/dawn/193" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/193</a><i style="box-sizing: border-box; user-select: text;">: Enable residency management. This allows page-in and page-out of resource heaps in GPU memory. This component improves overcommitted performance by keeping the most recently used resources local to the GPU. Turning this component off can cause allocation failures when application memory exceeds physical device memory.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_unsafe_apis:<span> </span></b><a href="http://crbug.com/1138528" style="box-sizing: border-box; user-select: text;">http://crbug.com/1138528</a><i style="box-sizing: border-box; user-select: text;">: Produces validation errors on API entry points or parameter combinations that aren't considered secure yet.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[WebGPU Forced Toggles - enabled]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_spirv:<span> </span></b><a href="https://crbug.com/1214923" style="box-sizing: border-box; user-select: text;">https://crbug.com/1214923</a><i style="box-sizing: border-box; user-select: text;">: Disallow usage of SPIR-V completely so that only WGSL is used for shader modules.This is useful to prevent a Chromium renderer process from successfully sendingSPIR-V code to be compiled in the GPU process.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Supported Features]</span><li style="box-sizing: border-box; user-select: text;">texture-compression-bc</li><li style="box-sizing: border-box; user-select: text;">pipeline-statistics-query</li><li style="box-sizing: border-box; user-select: text;">timestamp-query</li><li style="box-sizing: border-box; user-select: text;">dawn-internal-usages</li><li style="box-sizing: border-box; user-select: text;">multiplanar-formats</li><br style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">&lt;CPU&gt; D3D12 backend - Microsoft Basic Render Driver</b><br style="box-sizing: border-box; user-select: text;"><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Default Toggle Names]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">lazy_clear_resource_on_first_use:<span> </span></b><a href="https://crbug.com/dawn/145" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/145</a><i style="box-sizing: border-box; user-select: text;">: Clears resource to zero on first usage. This initializes the resource so that no dirty bits from recycled memory is present in the new resource.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_resource_heap_tier2:<span> </span></b><a href="https://crbug.com/dawn/27" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/27</a><i style="box-sizing: border-box; user-select: text;">: Enable support for resource heap tier 2. Resource heap tier 2 allows mixing of texture and buffers in the same heap. This allows better heap re-use and reduces fragmentation.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_render_pass:<span> </span></b><a href="https://crbug.com/dawn/36" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/36</a><i style="box-sizing: border-box; user-select: text;">: Use the D3D12 render pass API introduced in Windows build 1809 by default. On versions of Windows prior to build 1809, or when this toggle is turned off, Dawn will emulate a render pass.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_d3d12_residency_management:<span> </span></b><a href="https://crbug.com/dawn/193" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/193</a><i style="box-sizing: border-box; user-select: text;">: Enable residency management. This allows page-in and page-out of resource heaps in GPU memory. This component improves overcommitted performance by keeping the most recently used resources local to the GPU. Turning this component off can cause allocation failures when application memory exceeds physical device memory.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_unsafe_apis:<span> </span></b><a href="http://crbug.com/1138528" style="box-sizing: border-box; user-select: text;">http://crbug.com/1138528</a><i style="box-sizing: border-box; user-select: text;">: Produces validation errors on API entry points or parameter combinations that aren't considered secure yet.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[WebGPU Forced Toggles - enabled]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_spirv:<span> </span></b><a href="https://crbug.com/1214923" style="box-sizing: border-box; user-select: text;">https://crbug.com/1214923</a><i style="box-sizing: border-box; user-select: text;">: Disallow usage of SPIR-V completely so that only WGSL is used for shader modules.This is useful to prevent a Chromium renderer process from successfully sendingSPIR-V code to be compiled in the GPU process.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Supported Features]</span><li style="box-sizing: border-box; user-select: text;">texture-compression-bc</li><li style="box-sizing: border-box; user-select: text;">pipeline-statistics-query</li><li style="box-sizing: border-box; user-select: text;">timestamp-query</li><li style="box-sizing: border-box; user-select: text;">dawn-internal-usages</li><li style="box-sizing: border-box; user-select: text;">multiplanar-formats</li><br style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">&lt;Discrete GPU&gt; Vulkan backend - NVIDIA GeForce RTX 2070</b><br style="box-sizing: border-box; user-select: text;"><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Default Toggle Names]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">lazy_clear_resource_on_first_use:<span> </span></b><a href="https://crbug.com/dawn/145" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/145</a><i style="box-sizing: border-box; user-select: text;">: Clears resource to zero on first usage. This initializes the resource so that no dirty bits from recycled memory is present in the new resource.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">use_temporary_buffer_in_texture_to_texture_copy:<span> </span></b><a href="https://crbug.com/dawn/42" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/42</a><i style="box-sizing: border-box; user-select: text;">: Split texture-to-texture copy into two copies: copy from source texture into a temporary buffer, and copy from the temporary buffer into the destination texture when copying between compressed textures that don't have block-aligned sizes. This workaround is enabled by default on all Vulkan drivers to solve an issue in the Vulkan SPEC about the texture-to-texture copies with compressed formats. See #1005 (https://github.com/KhronosGroup/Vulkan-Docs/issues/1005) for more details.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">vulkan_use_d32s8:<span> </span></b><a href="https://crbug.com/dawn/286" style="box-sizing: border-box; user-select: text;">https://crbug.com/dawn/286</a><i style="box-sizing: border-box; user-select: text;">: Vulkan mandates support of either D32_FLOAT_S8 or D24_UNORM_S8. When available the backend will use D32S8 (toggle to on) but setting the toggle to off will make ituse the D24S8 format when possible.</i></li><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_unsafe_apis:<span> </span></b><a href="http://crbug.com/1138528" style="box-sizing: border-box; user-select: text;">http://crbug.com/1138528</a><i style="box-sizing: border-box; user-select: text;">: Produces validation errors on API entry points or parameter combinations that aren't considered secure yet.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[WebGPU Forced Toggles - enabled]</span><li style="box-sizing: border-box; user-select: text;"><b style="box-sizing: border-box; user-select: text;">disallow_spirv:<span> </span></b><a href="https://crbug.com/1214923" style="box-sizing: border-box; user-select: text;">https://crbug.com/1214923</a><i style="box-sizing: border-box; user-select: text;">: Disallow usage of SPIR-V completely so that only WGSL is used for shader modules.This is useful to prevent a Chromium renderer process from successfully sendingSPIR-V code to be compiled in the GPU process.</i></li><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">[Supported Features]</span><li style="box-sizing: border-box; user-select: text;">texture-compression-bc</li><li style="box-sizing: border-box; user-select: text;">pipeline-statistics-query</li><li style="box-sizing: border-box; user-select: text;">timestamp-query</li><li style="box-sizing: border-box; user-select: text;">depth-clamping</li><li style="box-sizing: border-box; user-select: text;">dawn-internal-usages</li></ul></div><div style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Version Information</h3><div id="client-info" style="box-sizing: border-box; user-select: text;"><div jstcache="0" style="box-sizing: border-box; user-select: text;">

Data exported | 2022-05-01T21:16:24.631Z
-- | --
Chrome version | Chrome/98.0.4758.141
Operating system | Windows NT 10.0.19044
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/33a12dd010d119bcacce1b7054ae0922483b082f/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/33a12dd010d119bcacce1b7054ae0922483b082f/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | aa07ecef98d7
2D graphics backend | Skia/98 615322e97b5d9cac54aae62a0f4f73475ce7bef6
Command Line | "C:\Users\robby\AppData\Local\Programs\Blockbench\Blockbench.exe" --allow-file-access-from-files --ignore-gpu-blacklist --enable-accelerated-video

</div></div></div><div class="feature-status-for-hardware-gpu-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Graphics Feature Status for Hardware GPU</h3><ul class="feature-status-for-hardware-gpu-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Canvas out-of-process rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Direct Rendering Display Compositor:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Compositing:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Multiple Raster Threads:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Out-of-process Rasterization:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">OpenGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Rasterization:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Raw Draw:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Skia Renderer:<span> </span></span><span class="feature-green" style="box-sizing: border-box; user-select: text; color: rgb(0, 128, 0);">Enabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Decode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Video Encode:<span> </span></span><span class="feature-yellow" style="box-sizing: border-box; user-select: text; color: rgb(128, 128, 0);">Software only. Hardware acceleration disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Vulkan:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li><li style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">WebGL2:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">Disabled</span></li></ul></div><div class="problems-for-hardware-gpu-div" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Problems Detected for Hardware GPU</h3><ul class="problems-for-hardware-gpu-list" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">gpu_compositing</span></i></li><li style="box-sizing: border-box; user-select: text;"><a style="box-sizing: border-box; user-select: text;">GPU process was unable to boot: GPU process crashed too many times with SwiftShader.</a><br style="box-sizing: border-box; user-select: text;"><i style="box-sizing: border-box; user-select: text;"><span style="box-sizing: border-box; user-select: text;">Disabled Features:<span> </span></span><span class="feature-red" style="box-sizing: border-box; user-select: text; color: rgb(255, 0, 0);">all</span></i></li></ul></div><div id="log-messages" jsdisplay="values.length" jstcache="1" style="box-sizing: border-box; user-select: text; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 jstcache="0" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;">Log Messages</h3><ul jstcache="0" style="box-sizing: border-box; user-select: text; margin-bottom: 0px; margin-top: 0px;"><li jsselect="values" jstcache="2" jsinstance="0" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[4332:0501/171445.518:ERROR:viz_main_impl.cc(188)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Exiting GPU process due to errors during initialization</span></li><li jsselect="values" jstcache="2" jsinstance="1" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="2" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[5764:0501/171445.604:ERROR:viz_main_impl.cc(188)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Exiting GPU process due to errors during initialization</span></li><li jsselect="values" jstcache="2" jsinstance="3" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The GPU process exited normally. Everything is okay.</span></li><li jsselect="values" jstcache="2" jsinstance="4" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">[8672:0501/171445.680:ERROR:gpu_init.cc(454)]<span> </span></span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">Passthrough is not supported, GL is disabled, ANGLE is</span></li><li jsselect="values" jstcache="2" jsinstance="*5" style="box-sizing: border-box; user-select: text;"><span jscontent="header" jstcache="3" style="box-sizing: border-box; user-select: text;">GpuProcessHost</span>:<span> </span><span jscontent="message" jstcache="4" style="box-sizing: border-box; user-select: text;">The info collection GPU process exited normally. Everything is okay.</span></li></ul></div>
</body>
</html>

**Comment by JannisX11** [comment]
I don't have a concrete solution for this issue unfortunately. What might help is restarting your comptuter, updating your graphics drivers, or using Blockbench without Hardware Acceleration.
See also #593.
