### ISSUE TITLE
[Issue] Texture sync doesn't work

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#14]
![image](https://user-images.githubusercontent.com/8559428/27012686-0a4a2f92-4ed5-11e7-93f2-ebcb0345d476.png)
The left block with the green stripes is selected in the UV but the old texture, where the right block was before is shown in the editor.

**Comment by JannisX11** [comment]
Can't reproduce.

**Comment by AlexMCool** [comment]
Did you have any clear sides to the element? (I can't think of any other difference why it wouldn't work)

**Comment by Yulife** [comment]
@JannisX11 I'll try to reproduce it with 1.4.2 and see if it's still there :)

**Comment by Yulife** [comment]
Seems like it's fixed @AlexMCool could you also try it again with 1.4.2?
