### ISSUE TITLE
[Issue] Blockbench glitches out on 1024px Texture

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1402]
Blockbench Glitches when zooming on 1024x1024 or higher texture resolution
Sometimes the model disappear

Blockbench version:4.2.4

https://user-images.githubusercontent.com/81752216/166867126-aff2b6dc-d400-4e8c-9121-37e3b1848786.mp4

**Comment by JannisX11** [comment]
I cannot reproduce the issue.
