### ISSUE TITLE
Textures glitch when I press ctrl+z

### ISSUE THREAD

**Issue by BBmodeler** [JannisX11/blockbench#1404]
**There is this glitch in block bench where if I press ctrl+z when having two or three TEXTURED cubes in box UV mode, it suddenly textures it weirdly**
![image](https://user-images.githubusercontent.com/105065305/167160614-17140ba1-003e-49c3-a9bb-1e6aecd825be.png)
It has been happening for EACH AND EVERY project I create in Box UV mode for the project. I want to use box UV since I want the model to be exported to a software called "Mine-Imator."

I am using the portable version btw. Like if I remake it, the glitch still happens!!!!!! Is it because I sometimes put textures of sizes 64 and 32??? PLZ HELP!

### Details:

-Project settings: Generic model and Java model (.json file); Box UV mode; 16x16 project texture size......
-Blockbench PWA
-OS: Windows 10

**Comment by JannisX11** [comment]
I cannot reproduce the issue currently. It could help if you could describe the detailed steps to reproduce the issue from start to finish, or record a video of it happening.
