### ISSUE TITLE
[Issue] hi i finished a generic model to make an animation to it when i finsih i want to export it as a java entity but i didn't find this option i watched a lot of videos and they are all find export as jave entity so how can i export my generic model as a java entity

### ISSUE THREAD

**Issue by hussain584** [JannisX11/blockbench#1405]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by JannisX11** [comment]
If you have questions, you can ask on the Blockbench Discord server. Please don't create an issue.
