### ISSUE TITLE
[Issue] Auto UV causes UV map to go out of bounds.

### ISSUE THREAD

**Issue by catgocri** [JannisX11/blockbench#1411]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them. No red messages.
Screenshot: [Imgur](https://imgur.com/a/RYzfWo6)

Please make sure to provide the following information:
- Detailed description of your issue
Whenever you create/convert to a modded entity project the auto UV messes up the UV map and causes it to go out of bounds. To reproduce the issue, try making a texture for a block model in the generic model format, then upload the JSON model to a modded entity project, the UV gets misplaced.
- Model format in which the issue occurs
Modded Entity/Java Entity.
- Blockbench variant (Website / PWA / Program)
Program.
- Operating System
Windows 10.

**Comment by JannisX11** [comment]
Works as intended. Modded entity uses "Box UV", a UV mapping system where the UV faces of a cube are connected. If you want to convert a project to Box UV, first convert the UV map to box UV by creating a texture template for all elements with "Box UV" enabled in the template generator.
