### ISSUE TITLE
[Issue] Animation setting back to Base Pose when clicking bones / timeline

### ISSUE THREAD

**Issue by Endesman** [JannisX11/blockbench#1412]
Issue:

Discovered this a few days ago, apparently after i converted a minecraft skin into generic model. Now every time I'm animating, whenever i randomly click timeline or any bone of the model, it resets the animation to base pose, which DOES mess with animations, because sometimes i select a keyframe, and its rotation, considered to be as if it was on base pose, starts rotating from there, destroying any previous keyframes that were elsewhere. Makes animation painful and adds so many extra clicks to re-set where the keyframe should actually be, and started happening on other models that were working just fine. I'm about to try a clean installation, but steps to reproduce the bug are apparently trying to convert from minecraft skin.

Model format - Generic model (And apparently other formats since discovering the issue a few days ago)
Blockbench PC latest
Windows 10

Trying to upload videos. 

https://user-images.githubusercontent.com/105240117/167476937-510088bd-3638-4092-ae8e-5d784e9ee5d5.mp4

https://user-images.githubusercontent.com/105240117/167477047-a0bf9487-0166-428e-8c48-55c83516886c.mp4

**Comment by JannisX11** [comment]
This was an issue with the CEM Template Loader plugin, fixed in https://github.com/JannisX11/blockbench-plugins/pull/233

**Comment by Endesman** [comment]
LOL i was running a whole debug thing and was just about to come here happily discovering that :C
