### ISSUE TITLE
[Issue] Error when creating a template without Rearrange UV when meshes and cubes selected at the same time

### ISSUE THREAD

**Issue by mchorse** [JannisX11/blockbench#1415]
I couldn't find something similar by search, but basically as title says. When Box UV mode is being used, only cubes are getting textured on the new texture. While when using per-face UV mode, following error is get thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at texture_generator.js:1296:15
    at Object.scanCanvas (painter.js:933:12)
    at drawTemplatePolygons (texture_generator.js:1293:12)
    at texture_generator.js:1501:6
    at Array.forEach (<anonymous>)
    at Object.generateFaceTemplate (texture_generator.js:1477:13)
    at Object.addBitmap (texture_generator.js:160:22)
    at Dialog.onConfirm (texture_generator.js:71:22)
    at Dialog.close (dialog.js:566:22)
    at HTMLButtonElement.<anonymous> (dialog.js:649:11)
```

Steps to reproduce:

1. Add a cube
2. Create some mesh
3. Select both cube and mesh
4. Create new texture
5. Select **Texture Template** type
6. Uncheck **Rearrange UV**
7. Click **Confirm**

I don't know if this is supposed to be supported, but if it doesn't I think it's worth adding a warning popup.

I'm using latest version (`4.2.4`) on Windows. I didn't try in another model modes, but I think Generic is the only mode that supports it, but I'm not 100% sure (correct me if I'm wrong). Thank you for attention!

**Comment by JannisX11** [comment]
Meshes and Box UV are not intended to be used together, but should be fixed anyways.
