### ISSUE TITLE
[Suggestion] Ability to rotate on the other two axes simultaneously

### ISSUE THREAD

**Issue by qsef1256** [JannisX11/blockbench#142]
This writing has been translated into Google Translate and misleading content may be present.

Problems occur when rotating a rotated object on another axis.

![image](https://user-images.githubusercontent.com/44014066/47017340-f02e6880-d18c-11e8-9e9b-eb9da63e7069.png)
In short, I want fill this corner, but can't.

There are similar inconveniences not only with this, but also with other things. I am modeling cars and I need to build a streamlined body.

![image](https://user-images.githubusercontent.com/44014066/47017791-2f10ee00-d18e-11e8-9a8e-5c13927bbd71.png)

I want to build a car along that red line, but I can't.

So, so far, I have solved it this way.

![image](https://user-images.githubusercontent.com/44014066/47017948-84e59600-d18e-11e8-8c34-4074ce88dc18.png)

But it's hard to make cars this way anymore, and I needed new feature.

So, I wish I had the ability to rotate a cube about two or more axes at the same time.

And I would like to have the feature to determine the polygon shape according to the point. For example, in the first picture, I wanted to have the feature to choose three points and make corner.

I know that similar functionality already exists in the SMP ToolBox, Cubic Studio. So I think you can implement this feature. I like this tool because it is easier to manipulate cubes than the SMP ToolBox, but I hope you can improve it.

Thank you for reading my suggestion!

**Comment by GitWither** [comment]
Sadly, this is a Minecraft limitation. An element can't be rotated on 2 axis.

**Comment by JannisX11** [comment]
Rotation on multiple axes will be possible in the next version, but keep in mind that if you plan to add those models to Minecraft, it will not be possible without specific mods.
