### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by manppy** [JannisX11/blockbench#1423]
I created a 32x minecraft skin "Steve" type, and when I finished it I saved and tried to put it in game. The problem is that the game says the picture is not 64x64 or 64x32, how can I fix it? I tried to convert the picture but the skin messes up. I spent a long time working on it and I'd really love to try it in game.

**Comment by JannisX11** [comment]
It's too big, the maximum resolution is 64 pixels for Minecraft, so you have to use the 16x option. For questions, please use the Discord server in the future.
