### ISSUE TITLE
[Issue] If the last keyframe is catmulrom, it is not considered to extend or reduce the animation length

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1428]
https://user-images.githubusercontent.com/81629481/169068462-a7ca336d-8a82-43ab-8750-76a639e596e9.mp4

- Blockbench 4.2.4, Bedrock format

**Comment by JannisX11** [comment]
The last keyframe can be used as a control point to change the angle of the curve, it does not necessarily need to be part of the animation.
