### ISSUE TITLE
Buttons missing, as well as keyframe icons

### ISSUE THREAD

**Issue by zehuifang** [JannisX11/blockbench#1431]
![image](https://user-images.githubusercontent.com/90441953/169691046-eb26cbd6-41ae-403f-98c5-0daf8fc20108.png)
![image](https://user-images.githubusercontent.com/90441953/169691074-9492c737-d8e3-4852-8e23-aa5a2175b960.png)

**Comment by JannisX11** [comment]
Please state version and operating system.

**Comment by zehuifang** [comment]
> Please state version and operating system.

tried 4.2.4, 4.2.3, and another older version. Found same problem in all of them.

os: Windows 10
