### ISSUE TITLE
[Suggestion] Add ability to use background images in gif

### ISSUE THREAD

**Issue by l3rosiah** [JannisX11/blockbench#1432]
Would it be possible to allow you to you use a background image in a gif from within blockbench? I was just trying to do it today and realized you couldn't.

**Comment by PaulFinnerty** [comment]
it would be cool to be able to make the gif sync with an animation, to use them as reference to animate walk cycles and the likes

**Comment by l3rosiah** [comment]
That would be neat for design, but not entirely necessary- from an export standpoint when trying to deliver a really nice-looking but fast gif showing an animation it would really add a lot to be able to include the background image

**Comment by PaulFinnerty** [comment]
Nevermind, I misunderstood the suggestion you made, I thought you were asking to be able to import animated gifs as a background image.

**Comment by l3rosiah** [comment]
No but that would still be nice for creating animations!
