### ISSUE TITLE
Mobile Side Panels are broken

### ISSUE THREAD

**Issue by bushytestaccount** [JannisX11/blockbench#1434]
- The "Tools" on the side/edge don't show anything when using them. This makes Blockbench unusable.
![Screenshot_20220530-120626](https://user-images.githubusercontent.com/106546968/171029116-d43229c0-f049-42c8-8efd-00ccba4d22de.png)

- Format: Any
- Version: Mobile App
- OS: Android 11

**Comment by JannisX11** [comment]
You might have to resize the sidebar and make it larger to see anything. Also, how about the other panels like Outliner?

**Comment by BushyAnim** [comment]
They are all like that, 97% of them.
