### ISSUE TITLE
[Issue] Local rotation sometimes does not update the model nor saves animation data in the keyframe

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1438]
This mostly happens when you drag the rotation gizmo from a keyframe with [0,0,0], I assume it has to do with the math to make local rotations work.

https://user-images.githubusercontent.com/81629481/171163128-d53369d8-f649-49bd-8eb9-d85698599e71.mp4

- Blockbench 4.2.4 Desktop app, W10

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench/commit/2df6e73dc5ab6b288d521776812b09fed2b4b19f. For now, enable Motion Trails to fix.

**Comment by JannisX11** [comment]
Cherry-picked and fixed in 4.2.5.
