### ISSUE TITLE
[Issue] Can't export as OptiFine JPM while in Block Mode

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#144]
Uncaught TypeError: Cannot read property 'value' of undefined    io.js:1177
    at buildJPMModel (io.js:1177)
    at HTMLLIElement.click (actions.js:1431)

- Detailed description of your issue
When you go to export as OptiFine JPM nothing happens and it throws and error.

- Blockbench variant (Webapp/Desktop)
Webapp and Desktop

- Operating System
Windows 10 Home Version 1809

**Comment by JannisX11** [comment]
Fixed in 2.0.2
