### ISSUE TITLE
[Suggestion] Attachable support (Bedrock Edition)

### ISSUE THREAD

**Issue by Chikorita-Lover** [JannisX11/blockbench#1440]
Add a tab for Bedrock geometries (similar to Java Edition's item/block models) that can be used to position and rotate a geometry (in an animation) for use as an attachable. The tab would include first-person and third-person views, and would help Bedrock creators out a lot for attachables, especially those held in the hand.

**Comment by JannisX11** [comment]
Added in 4.7.
