### ISSUE TITLE
[Issue] Animated Texture Limit Java

### ISSUE THREAD

**Issue by Wertologist** [JannisX11/blockbench#1441]
There seems to be a limit on how big a texture size limit for animated textures in Java. I'm trying to work with a 128x8192 animated texture, but when I try to load it in and apply it to a cube, it looks as if the entire texture is smushed together and doesn't register that it's animated

I am not sure why it does this. I was instructed to report the issue here

**Comment by JannisX11** [comment]
Cannot reproduce. Maybe you can share a screenshot of the entire interface, or a project file.

**Comment by Wertologist** [comment]
Sorry, I never saw this email. I'm doing java blocks

For some reason, textures like this don't seem to work
