### ISSUE TITLE
Blockbench.net Download page is broken/missing

### ISSUE THREAD

**Issue by boinkitsbroken** [JannisX11/blockbench#1442]
Felt someone should say something about it, but didn't want to just leave a message in a Discord forum that may or may not be found.
https://www.blockbench.net/downloads responds with an Error 500 page and nothing else at the moment.

Feel free to delete/close this issue if someone is currently working on the page, or whenever the problem is fixed.

**Comment by JannisX11** [comment]
Is this still an issue?
