### ISSUE TITLE
Model View does not load

### ISSUE THREAD

**Issue by Cns22F** [JannisX11/blockbench#1443]
- Imported a CEM model from optifine and the preview of model does not loading now
- Optifine CEM
- Program
- Windows 8.1
Issue:
![image](https://user-images.githubusercontent.com/107172768/172783631-7db8cea4-5a51-4d2c-9fc7-77dd916a5ddb.png)
Console: 
![image](https://user-images.githubusercontent.com/107172768/172783734-e14b1c46-b7ae-4e76-b690-b42af40eea3c.png)

**Comment by JannisX11** [comment]
I don't have a concrete solution for this issue unfortunately. What might help is restarting your comptuter, updating your graphics drivers, or using Blockbench without Hardware Acceleration.
See also https://github.com/JannisX11/blockbench/issues/593.
