### ISSUE TITLE
[Suggestion] Entity Animations for Minecraft Java Edition

### ISSUE THREAD

**Issue by BurnutsGaming** [JannisX11/blockbench#1445]
Since there is configurable animations added in Minecraft Java Edition 1.19 that is used for the Warden and the frogs animations, you might need to add this feature to help assist in creating animations instead of using GeckoLib for it. This feature you will add should only be available in `mojmap-1.19.x`.

**Comment by JannisX11** [comment]
Currently available as a plugin: https://www.blockbench.net/plugins/animation_to_java

**Comment by JannisX11** [comment]
Added to Blockbench in 4.9.
