### ISSUE TITLE
[Issue] Resizing background image while using rectangle selection shortcut locks the cursor in rectangle selection mode until restart 

### ISSUE THREAD

**Issue by Ycarx** [JannisX11/blockbench#1446]
+ The selection rectangle is not displayed 
+ cannot be reverted, requires restart to fix

https://user-images.githubusercontent.com/37698893/172852853-838dad44-cc7f-41ca-8083-0c4d7cd4a00d.mp4

**Comment by JannisX11** [comment]
Cannot reproduce. What is your rectangle selection shortcut? Are there any console errors?
