### ISSUE TITLE
[Floor stuck to model]

### ISSUE THREAD

**Issue by No-NameYT** [JannisX11/blockbench#1456]
This happens when I try to display the model on the program (windows version), I also tried to uninstall and reinstall block bench and it still did not fix. This doesn't happen on the website though. (Sorry if this issue has been reported) 
Here are some images of what is happening.
![Screenshot 2022-06-21 162722](https://user-images.githubusercontent.com/107910241/174731185-a4d5b3e8-a2f5-47f8-976d-0288b87a1502.png)
![Screenshot 2022-06-21 162648](https://user-images.githubusercontent.com/107910241/174731222-ddb7b2ca-4dad-4a16-aec2-40ab54c024db.png)

**Comment by JannisX11** [comment]
Fixed in 4.3
