### ISSUE TITLE
[Suggestion] Deleting Recent Creations

### ISSUE THREAD

**Issue by ErythroCraft** [JannisX11/blockbench#1458]
Hello

Can you give an update to delete recent creations in start section.

That would be good if you haven't saved your creations or don't want to see them in the star view.
However, files should not be deleted.

![Screenshot 2022-06-24 170204](https://user-images.githubusercontent.com/76217862/175564317-a59a9bb5-d296-49ed-9b09-4c61a73f307e.png)

**Comment by JannisX11** [comment]
Added in 4.3 via right click.
