### ISSUE TITLE
[Bug] Import Palette doesn't Import all colours within a GPL file.

### ISSUE THREAD

**Issue by xVanquishx** [JannisX11/blockbench#1460]
Windows 10
Program v4.2.5

I imported a GPL file of 6 colours, only 3 of them were correctly imported into BB.

Content of .GPL file:
GIMP Palette
Name: Blue Fire
Columns: 0
(Hash Symbol(github formatting issue))
183 232 235	Blue Fire
102 190 249	Untitled
 48 154 241	Untitled
 17 101 193	Untitled
  4  63 152	Untitled
156 222 235	Untitled

**Comment by xVanquishx** [comment]
![image](https://user-images.githubusercontent.com/29439049/176517839-3a883639-5fd2-4e82-9623-45e057c093aa.png)
<img width="157" alt="image" src="https://user-images.githubusercontent.com/29439049/176517941-3ac9ff8a-6ca8-4526-9983-4a72f9aefa25.png">

Additional Context, but unsure how it occurs.

**Comment by JannisX11** [comment]
Ah, I see. It's because of the white spaces in front of the numbers, which Github deleted in your post.
