### ISSUE TITLE
[Issue] Overlay Texture in Minecraft Skin Format doesn't work

### ISSUE THREAD

**Issue by RoCris12** [JannisX11/blockbench#1462]
I am using the latest version of blockbench in mobile.

So I made a new Minecraft Skin project, selected Pig with Layer Texture on. Then I wanted to edit the overlay texture, so I activated Skin Layer, started painting and it painted the pig texture not the overlay. All blocks are unhidden and I have made any changes.

Format: Minecraft Skin Pig

Mobile Installed by browser so Website version

I have a Samsung A51 Phone (Android)

**Comment by JannisX11** [comment]
Blockbench's skin mode depicts entity models the way they are in Minecraft. Any some only specific entities use layers for specific things. The pig does not have any layers.

**Comment by RoCris12** [comment]
Ohh, Im so sorry. I thought all mobs have layer texture. Do u know any ways
to make overlay texture on a pig? If not dw. Thanks
