### ISSUE TITLE
[bug] Model animation Override

### ISSUE THREAD

**Issue by SkyaniSoup** [JannisX11/blockbench#1470]
When creating a player animation and applying the animation override setting to that animation, it never works.
I am using a Windows 11 Acer Laptop, and using the bedrock model.

**Comment by JannisX11** [comment]
What doesn't work?

**Comment by SkyaniSoup** [comment]
When i make a player animation for the player model, theres a setting on that animation to override previous animations, when i select that as true, it doesnt do it, and the previous player animations still continue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JannisX11** [comment]
In Blockbench or in Minecraft Bedrock Edition?
