### ISSUE TITLE
[Issue] Issue summary Black screen bug after I start for a few minutes ends up dropping fps and the black screen bug 

### ISSUE THREAD

**Issue by valterineCraft** [JannisX11/blockbench#1476]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by JannisX11** [comment]
Hello, you forgot to fill in the template and provide context information around your issue.
