### ISSUE TITLE
[Suggestion] Close tab menus when you move away

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#148]
- Detailed description of your issue
The menu doesn't close unless you click elsewhere and clicking it again closes the menu but if you're still hovering over it it will open again.

![image](https://user-images.githubusercontent.com/32020441/47131711-2505f280-d255-11e8-9dd1-83a1b59457a1.png)

**Comment by JannisX11** [comment]
The menu is not supposed to close after you leave the menu with the cursor.
In the next version, clicking the option in the menu bar will close the menu.
