### ISSUE TITLE
[Issue] Keyframe Particles no Texture

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#1481]
Texture doesn't load when importing particles in keyframe particle

![Screenshot_20220714_154803](https://user-images.githubusercontent.com/81752216/178930119-d3dc643f-c869-4734-bd33-e4d91a98ae87.jpg)
![Screenshot_20220714_154744](https://user-images.githubusercontent.com/81752216/178930138-4fa135c7-c13f-4ea4-a845-49fae1854dc3.jpg)

**Comment by JannisX11** [comment]
Works as intended. Particles preview without texture on the web app because the web app does not have access to the texture file on your hard drive. The exception are particles that use default Minecraft particle textures.

**Comment by JannisX11** [comment]
#993 could be a solution for this.
