### ISSUE TITLE
Setting pivot point for cube

### ISSUE THREAD

**Issue by inlanoche** [JannisX11/blockbench#1493]
It seems I can only set a pivot point if I select the whole group.  I was hoping to set a pivot point for a single cube in a group.  I see it being done in this video:
https://youtu.be/k1g2KWK59no?t=210
But when I try to recreate this action, I have no ability to move the pivot point unless the whole group is selected...

**Comment by JannisX11** [comment]
There are formats where cubes cannot be rotated. Therefore, they cannot have a pivot point.

**Comment by inlanoche** [comment]
ok, I guess it was an option that was taken out...  thanks.
