### ISSUE TITLE
[Issue] jem models missing

### ISSUE THREAD

**Issue by Kri0k** [JannisX11/blockbench#1496]
After saving my optifine model as jem the only thing that the saved file has is

![image](https://user-images.githubusercontent.com/68000966/180781166-263ab31c-877e-4e8d-ad3d-18d08d3369a1.png)

json files saves as usual, but not the jem

programm, windows 11

**Comment by JannisX11** [comment]
You must use bones to put your cubes in. Most likely that's why your model appears empty. Please refer to the tutorial that's linked on the Start Screen when selecting the OptiFine entity format.

**Comment by Kri0k** [comment]
But i am making minecart model
