### ISSUE TITLE
[Suggestion] Better automated bone names when duplicating and flipping

### ISSUE THREAD

**Issue by AngeloVH** [JannisX11/blockbench#1497]
Make the automatic numbering of duplicate bones reset when the bones are flipped and have "right" or "left" in the name.

example:

duplicating nested bones like leftarm0>leftarm1 results in leftarm2>leftarm3
flipping the arm will then result in in rightarm2>rightarm3

it would be much nicer if they were then renamed to rightarm0>rightarm1

**Comment by JannisX11** [comment]
Added in 4.4.
