### ISSUE TITLE
[Suggestion] Make center view on selection not change angle of model in viewport

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1498]
Would help a ton for screenshots so that when you center view on selection it would keep the angle of the model the same, rather than changing it like it does currently.

**Examples:**
(without centering view on selection)
![image](https://user-images.githubusercontent.com/68472867/180906616-ef59111f-0f01-48f3-a377-57774cf14bf8.png)

(with centering view on selection)
![image](https://user-images.githubusercontent.com/68472867/180906708-a69eafc1-8610-4587-9d90-ebbc609f15e7.png)

**Comment by JannisX11** [comment]
Would it make sense to you to only implement this for orthographic camera mode?

**Comment by pixelstoriez** [comment]
I feel like it'd be more helpful if it wasn't exclusive to orthographic mode
