### ISSUE TITLE
[Issue] Missing convert model translation

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#150]
- Detailed description of your issue
![image](https://user-images.githubusercontent.com/32020441/47155545-d9296c80-d299-11e8-8f29-22e3d6d997ea.png)

- Blockbench variant (Webapp/Desktop)
Webapp and Desktop

- Operating System
Windows 10 Home Version 1809

**Comment by JannisX11** [comment]
Fixed in upcoming version.
