### ISSUE TITLE
[Suggestion] Save the selected slot and model in Display Mode

### ISSUE THREAD

**Issue by JuliGame** [JannisX11/blockbench#1500]
Saving the selected slot and model in Display window.
Right now if you are creating a hat you have to select head, and then select the model every time you change the window.
It would be a lot faster and dynamic to change from display to editing mode if the latest state was saved.
![image](https://user-images.githubusercontent.com/60196802/181736957-4dab7d8a-e610-40e4-8c30-9d620ad8a4b4.png)
(Save that.)

**Comment by JannisX11** [comment]
Added in 4.11.
