### ISSUE TITLE
Commands in animation instructions are appended semicolons on save

### ISSUE THREAD

**Issue by Energyxxer** [JannisX11/blockbench#1505]
### Description
Commands in an animation timeline (Instructions) are appended a semicolon at the end on save.
This breaks most commands.
While commands, events and bone animations usually don't go together in the same animation, it is part of the Bedrock animation format and should probably be supported. 

I suggest checking if the line starts with a `/` (for commands) or `@` (for events) and not appending the semicolon if that's the case.

### Model Format
Bedrock Geometry (animation)

### Blockbench Variant
Program

### Operating System
Windows 10

**Comment by JannisX11** [comment]
Explain why you are using commands in Blockbench animations :O

**Comment by Energyxxer** [comment]
Can't really say much, but we have our own tools that generate server animations from Blockbench animations.
