### ISSUE TITLE
Textures not saving in the model

### ISSUE THREAD

**Issue by BaconJunior** [JannisX11/blockbench#1508]
Since Tuesday, block textures are not saving in the model, i even did a simple block with one texture in all the sides and it is not working

Every single model as a block is failing, i installed the program in another computer and in a tablet, also i tried in the web, and it is same issue. With entities it is not any problem, only with blocks.
(and i know how to use the program, so it must some kind of bug because with every single block i tried to create this week, it is happening this on and on)

Thanks!

![podcraftfoto](https://user-images.githubusercontent.com/99895067/183031151-97d67e13-0412-44bb-bf24-86a2530c3561.png)

**Comment by JannisX11** [comment]
Please attach the model file.

**Comment by BaconJunior** [comment]
It is 3 different models, i attach every one of them, i did like 20 models just for see why it was happening and since Tuesday not even a single block it is working, sadly!
Thanks for the reply

[modelblockbench.zip](https://github.com/JannisX11/blockbench/files/9275225/modelblockbench.zip)

**Comment by JannisX11** [comment]
All models have texture files. They open fine for me. Are there any console errors (Help > Developer > Open Dev Tools)?

**Comment by BaconJunior** [comment]
I still having same issue, as a model it has textures etc, but when i save the model as a json file, it lose the textures and when i take it to mcreator....it does not work, sadly!

![image](https://user-images.githubusercontent.com/99895067/183593860-d88b9c6f-5ee8-470b-88ef-6c19f3925eaf.png)

**Comment by BaconJunior** [comment]
![image](https://user-images.githubusercontent.com/99895067/183594683-bc26f773-399c-4353-bff4-4ece624e15eb.png)
 This is what it says

**Comment by BaconJunior** [comment]
![image](https://user-images.githubusercontent.com/99895067/183595096-6ab7db6f-0f2c-4354-b067-e5c816b5bce4.png)

all models saying same thing

**Comment by BaconJunior** [comment]
I gave as much information as i can......unless wanna know what´s the issue or if i need to download a new program, because this is still not working and getting same error in every model

**Comment by JannisX11** [comment]
Once you export your model to a JSON file, you need a valid Minecraft resource pack structure in order to load the texture automatically. It will also give you a warning about this when loading the texture.
More info in this tutorial: https://www.youtube.com/watch?v=aaJ8XgMAOno

**Comment by BaconJunior** [comment]
oh it is something new i guess, because in 6 months i was always doing this same way, okey, i will look at the video so, thanks!
