### ISSUE TITLE
[Issue] Entity Mode's UV Full View's inside is not centered // vertical/horizontal sliders are stacked

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#151]
- Detailed description of your issue
![image](https://user-images.githubusercontent.com/32020441/47157159-99648400-d29d-11e8-98b3-d2e92e9f1225.png)
![image](https://user-images.githubusercontent.com/32020441/47157236-bf8a2400-d29d-11e8-888c-2d08c18236fc.png)

- Blockbench variant (Webapp/Desktop)
Webapp and Desktop

- Operating System
Windows 10 Home Version 1809

**Comment by JannisX11** [comment]
Fixed in 2.0.2
