### ISSUE TITLE
Blockbench Not Allowing Me To Paint On Outer Layer

### ISSUE THREAD

**Issue by LunarJaguar8837** [JannisX11/blockbench#1512]
On the desktop version of Blockbench in the skin editor, an issue occurs where the app doesn't allow me to paint on the outer layer, eg. Hat, Jacket. When I try to paint on said layers, it automatically switches to the underlayer (head, body, limbs). Please fix.

**Comment by JannisX11** [comment]
Make sure the outer layer is visible and not locked. You can toggle visibility and lock in the Outliner.

**Comment by LunarJaguar8837** [comment]
Thanks for the response! The problem has gone now. It wasn't to do with visibility or anything, it was just my stupid brain positioning the head separately from the hat so I couldn't paint the hat. Thanks anyway!
