### ISSUE TITLE
[Issue] Emissive Render Mode does not make the model shaderless

### ISSUE THREAD

**Issue by KloxEdgeX** [JannisX11/blockbench#1514]
Setting a texture's Render Mode to Emissive does not change the model in the viewport.
It also does not use emissiveness when you render a model via the Screenshot function.
The Render Mode name implies that the model with the texture applied should turn shaderless in the viewport, which does not happen.
What actually happens (nothing):
![image](https://user-images.githubusercontent.com/79337750/184023116-eed6130b-f114-43c2-9ef0-9f95d2ca8a17.png)
What is expected to happen (shaderless model to whatever the texture is applied to):
![image](https://user-images.githubusercontent.com/79337750/184023320-aa13843c-62a7-4918-bdc0-300843b4e769.png)

**Comment by JannisX11** [comment]
Emissiveness on textures is controlled by the alpha channel. The lower the alpha value, the more emissive the pixel. You can use an eraser with a specific opacity to make specific elements, like the eyes, emissive.
