### ISSUE TITLE
[Suggestion] Be able to edit position of symmetry line

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1518]
Already said in the title but being able the move/rotate the symmetry line on the X and Z axes would help a lot when modelling

**Comment by JannisX11** [comment]
For mirror painting?

**Comment by pixelstoriez** [comment]
Forgot that there wasn't already a mirror tool in edit mode but I had originally meant the suggestion to be for edit mode😅

**Comment by JannisX11** [comment]
Ah okay. By the way, for the mirror painting tool there will be an option to select a different axis in the next version.
