### ISSUE TITLE
[Issue] Creating a New Project While Animating in a Different Project Messes with Blockbench

### ISSUE THREAD

**Issue by ItsToastCraft** [JannisX11/blockbench#1520]
When creating a new project using the + button or the home button while in the animation tab in a different project causes Blockbench to soft-lock and stops you from closing Blockbench. It also renders other buttons useless. If you manage to switch to a different model, you are able to use buttons normally, but you still can't close Blockbench (note that it sometimes fixes itself if you are able to create another new tab).
- Generic Model format
- Program
- Windows 10

https://user-images.githubusercontent.com/56282814/184683811-a852b591-39e2-4264-9456-832b1bd426bd.mp4

**Comment by JannisX11** [comment]
Which version of Blockbench are you in? (Help > About)

**Comment by ItsToastCraft** [comment]
Oh mb I installed 4.3.1 before doing this but apparently it didn't update my Blockbench properly after a couple of restarts.

**Comment by JannisX11** [comment]
If you're having trouble with it auto updating to the wrong version, disable Update to Pre-Releases in the settings.

**Comment by ItsToastCraft** [comment]
Thanks!
