### ISSUE TITLE
this is a question about variable place holders

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#1525]
(Didn't really know how to label it and couldn't find any info on the subject so I came here.)

what does the variable placeholder do and how does it work? I know it can do scripting like x = 7 + 3 or math.random() but idk how it's properly used. 
Can I use it to enhance animations?(ie. can I use math.random(1,2) for an animation to have an object move up either 1 or 2 pixels every loop?

also I guess while I'm at it asking questions, where can I find the moving ground pane for animations?(can't find it from the new update lol)

**Comment by JannisX11** [comment]
For questions, you can use the help channels in the DIscord server. You can find an invite link when selecting New Issue on Github.
