### ISSUE TITLE
Theres a bug when i edit, The edit and resize and everything on the side is buggy

### ISSUE THREAD

**Issue by Bbddong** [JannisX11/blockbench#1526]
The controls when i resize or whatever the arrows dissappear 
![Screenshot_2022-08-18-12-59-23-28](https://user-images.githubusercontent.com/110160944/185298284-9a3d467a-5f51-491a-9c9d-ca6e63c9be7c.jpg)

**Comment by JannisX11** [comment]
Are there any issues in Help > Developer > Error Log?
