### ISSUE TITLE
Blockbench auto save fail

### ISSUE THREAD

**Issue by meltroll888** [JannisX11/blockbench#1535]
I was creating an Indoraptor model for a mod I was working on, when the tab close. When I reopened the tab, the website didn't give me the option to recover the model, I had worked on it for around a month and cried when it failed.

**Comment by meltroll888** [comment]
Is there any way to get it back.

**Comment by JannisX11** [comment]
There should be an option on the start screen to recover all models. If there isn't, you cannot get it back.

**Comment by meltroll888** [comment]
There isn't a recover button, thanks the help anyway.
________________________________
