### ISSUE TITLE
[Issue] Cannot select multiple groups.

### ISSUE THREAD

**Issue by r4isen1920** [JannisX11/blockbench#1539]
Whenever I hold `CTRL`, and select with my `left mouse` button, it should select multiple groups. But what happens is that the *contents of those groups* are selected instead when clicking another group. The last group you clicked will be the only one selected, the rest are ignored.

![image](https://user-images.githubusercontent.com/43404913/186348752-56397b20-f4e4-428b-827b-1697f6e4f15e.png)

**Comment by JannisX11** [comment]
Works as intended, only one group can be selected at a time.
