### ISSUE TITLE
[Suggestion] UV Overlay in Edit mode

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1545]

**Comment by JannisX11** [comment]
This is essentially a suggestion for a button in the toolbar, or a different UI implementation to handle this. Since it is already possible to show all UVs by opening the UV menu and setting **Display UV** to **All Faces on All Elements**.

**Comment by pixelstoriez** [comment]
Ah okay, didn't know that. It feels like a really obscure feature since there's not much reason to right click on the UV editor.
