### ISSUE TITLE
[Issue] Particle texture make model don't render

### ISSUE THREAD

**Issue by Francy-Chan** [JannisX11/blockbench#155]
If I have a blockmodel with particle texture AND I use it in the model, the model doesn't render proprely.

Console:
> ![noname](https://user-images.githubusercontent.com/40085587/47166107-cdf23300-d2d1-11e8-9764-70c949254b5b.png)
Example file:
[example.zip](https://github.com/JannisX11/blockbench/files/2492555/example.zip)

- Blockbench 2.0.1 Desktop
- Windows 10

**Comment by JannisX11** [comment]
Fixed in the next version.
