### ISSUE TITLE
Blockbench not properly starting; White screen then crash

### ISSUE THREAD

**Issue by Dillpickle2169** [JannisX11/blockbench#1553]
When I attempt to open Blockbench, the program doesn't properly start up. When I install Blockbench from the Windows installer, it automatically boots up to a white screen with a light blue bar going across the top of the window. I try to boot up the application, normally and running as admin, and the results are the same. The white screen pops up for a second then crashes. Is there a solution to this?

![image](https://user-images.githubusercontent.com/112786222/188292286-e1f94851-484b-461e-9dd7-5687bbfe21e9.png)

Downloaded the current version, 4.3.1, Windows installer

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by JannisX11** [comment]
Could you try to run Blockbench from the console and see if it logs any errors? The executable should be under `C:\Users\USER\AppData\Local\Programs\Blockbench\Blockbench.exe`
