### ISSUE TITLE
[Issue] Installer Thinks App is Constantly Running

### ISSUE THREAD

**Issue by SaltSouls** [JannisX11/blockbench#1554]
So I'm trying to install the latest version of Blockbench(4.2.5 -> 4.3.1) but every time it gets about halfway done it says to close Blockbench and retry. I have shutdown all associated apps using task manager, and even restarted my computer, yet this message persists. It happens when trying to update via the program as well as when trying to install it using a newly downloaded installer.

Windows: Windows 11 Home - 21H2 - 22000.856
Processor: AMD Ryzen 7 3800X @ 4.20GHz
Installed RAM: 64 GB (54.9 GB usable)
System type 64-bit operating system, x64-based processor

**Comment by JannisX11** [comment]
Try to right-click the installer and Run as Administrator.
