### ISSUE TITLE
[Suggestion] [Beta] Simple Right-Click Options In Brush Presets Dialog

### ISSUE THREAD

**Issue by SirJain0** [JannisX11/blockbench#1559]
For BB 4.4 Beta 2

I think the ability to be able to right-click the area marked in the screenshot and have some default options, like "Delete" would be cool. The delete feature also stays consistent with the "right-click to delete" idea that happens throughout Blockbench (right-clicking textures or cubes, for example, and finding the delete option). The Delete key as a word is alright but a right-click option also feels like it should be there.

![image](https://user-images.githubusercontent.com/94301223/189465358-a96bd121-64f2-47a6-8620-ae454c37bcb4.png)

**Comment by Mysterious-Dev** [comment]
This issue can be closed with the recent commit.
