### ISSUE TITLE
[Issue] Webapp cant export Bedrock Entities or OBJ

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#156]
Bedrock Entity Export:
actions.js:1421 Uncaught ReferenceError: writeFileEntity is not defined
    at HTMLLIElement.click (actions.js:1421)
click @ actions.js:1421

OBJ Export:
actions.js:1467 Uncaught ReferenceError: writeFileObj is not defined
    at HTMLLIElement.click (actions.js:1467)
click @ actions.js:1467

- Detailed description of your issue
Cant export as bedrock entity or obj in the webapp

- Blockbench variant (Webapp/Desktop)
Webapp

- Operating System
Windows 10 Home Version 1809

**Comment by JannisX11** [comment]
Resolved.
