### ISSUE TITLE
I can't edit entity wizard

### ISSUE THREAD

**Issue by theemeraldsword** [JannisX11/blockbench#1563]
When I open entity wizard it asks for an entity name, the ID, the look and the behavior and the spawn egg. Then it asks about the pack and where I want to save it to. Then it exports it and doesn't ever give me the option to edit the model.

**Comment by theemeraldsword** [comment]
![2022-09-11](https://user-images.githubusercontent.com/113296133/189531955-cd08cb9b-613a-4882-bf52-d0c9f1934a6c.png)

**Comment by JannisX11** [comment]
This works as intended. If you need help editing your pack, please ask on the Discord server.
