### ISSUE TITLE
[Suggestion] Permission to submit to Snapcraft

### ISSUE THREAD

**Issue by anrouxel** [JannisX11/blockbench#1570]
Hello,
I'd like to submit Blockbench for inclusion in [Snapcraft](https://snapcraft.io/), to make it more easily available on Linux distributions. Though the AppImage is helpful, they're generally not discoverable through desktop environment's built-in app stores like [Ubuntu Software](https://snapcraft.io/snap-store) or [Snap Store](https://snapcraft.io/snap-store).

Packaging Blockbench into a snapcraft for distribution is done by building off the source and requires no modifications in how Blockbench is currently shipped. There will be no additional burden on the Blockbench maintainers and updates are picked up automatically when new commit in main are made.

Since I'm not a blockbench contributor myself, I was wondering if I could continue to publish Blockbench on Snapcraft.

Here is the link to the publication on Snapcraft : https://snapcraft.io/blockbench-snapcraft

I'd need confirmation of one thing:

* Blockbench maintainers agree to let me submit this to Snapcraft

A few notes on : https://github.com/anrouxel/blockbench-snapcraft

Best Regards

**Comment by JannisX11** [comment]
Permission is hereby granted to continue publishing Blockbench on Snapcraft.
Hope that helps!
