### ISSUE TITLE
[Suggestion] Better adjustable color picker display size

### ISSUE THREAD

**Issue by xZinjoo** [JannisX11/blockbench#1577]
Color picker display size should be more adjustable in size like in the old versions.
Size limitation of the color picker display should be removed

**Comment by JannisX11** [comment]
Could you clarify which color picker you are talking about, and which size limitations and old version?

**Comment by xZinjoo** [comment]
![image](https://user-images.githubusercontent.com/97406135/192270787-3b462ce8-3912-4be7-9410-c3328ace59af.png)

**Comment by JannisX11** [comment]
Ah, I see. But this is pretty big already, right? Any specific reason why you need it to go even bigger?

**Comment by xZinjoo** [comment]
I just find it unnecessary to put a limitation on it because there wasnt any in the older blockbench versions. Besides you can pick color way more faster & precisely than by typing in the values.

**Comment by TaisenSchettler** [comment]
I agree with Zinjoo on this, would be cool to get the ability back. It makes precise color picking and small adjustments much easier.
