### ISSUE TITLE
[Issue] Preview Player skin doesn't show second layer

### ISSUE THREAD

**Issue by Francy-Chan** [JannisX11/blockbench#158]
The second layer of the skin (hat, jacket, sleeves, pants) doesn't render
Slim model also have some issues as if #157 
> Example:
> ![the thing goes kraaa](https://user-images.githubusercontent.com/40085587/47198371-2f51ea80-d342-11e8-82ac-0d1b5dcc8033.png)
- Blockbench 2.0.1 Desktop
- Windows 10

**Comment by JannisX11** [comment]
This is intentional and to prevent transparency rendering issues caused by WebGL.
Support for slim models is planned.

**Comment by spidertwine** [comment]
im still having this issue on regular steve skin.
