### ISSUE TITLE
Fix the freeze bug on Blockbench Android 

### ISSUE THREAD

**Issue by SquisSloim** [JannisX11/blockbench#1586]
Hi! I'm Squish, and I'm a beginner 3d artist. And ever since I discovered Blockbench it really gave me a lot of opportunities to play around and spark my creativity even though I'm using an Android Phone (Android 6/Octa Core) to be specific. So my issue here is that my Blockbench freezes whenever I add just one cube, ONE. Everytime I change tools, it freezes, crashes and everytime it does that it annoys me. After many trials and errors, it still doesn't fix until a log said "Can't extract WebGL context, Should change graphics driver" correct me if I'm wrong. And I'M ON AN ANDROID I CAN'T CHANGE MY GPU... So please I just want y'all to fix the crash. That's all and Thank you

**Comment by JannisX11** [comment]
Make sure your Chrome browser is up-to-date. If that doesn't help, I'm afraid your phone does not meet the minimum hardware requirements.
