### ISSUE TITLE
[Suggestion] Make Line Breaks work in toolbars

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1588]

**Comment by JannisX11** [comment]
There are already line breaks in toolbars. Or do you mean specifically in the toolbar above the viewport? That's the only one with a fixed height so multiple lines don't show at once.

**Comment by PaulFinnerty** [comment]
Ah yeah, I didn't try it with the other toolbars, the top one is indeed the one I would have liked them to work in.

**Comment by JannisX11** [comment]
Yeah, I don't want to make the main toolbar have variable height, since it would affect too much of the rest of the interface. For now it's possible to use line breaks or over-fill toolbars, and the new line can be accessed by scrolling.
