### ISSUE TITLE
Custom-sizing UV scale causes the scale to bug out

### ISSUE THREAD

**Issue by Tslat** [JannisX11/blockbench#159]
When manually typing a size for a UV Scale-X or Scale-Y, about 75% of the time the sizing will bug out and flip, stretching itself to the far left of the texture and becoming unusable

For example, if I have a 128x128 texture to map, I drop the Scale-X to 0.25, then manually type 0.125 to get a single pixel width mapping. Instead of making the Scale 0.125 like it did previously, the UV preview box will extend all the way to the left of the texture, and will become something like -8.875.
This makes custom-sizing UV mappings near impossible, and I had to downgrade back to 1.1.6 to continue modelling.

Steps:

1. Create a handful of new cubes, size doesn't matter
2. Apply a texture to it, open the enlarged UV mapping screen
3. Move the UV box somewhere to the right of the screen
4. Attempt to set the size to something custom (I usually use 0.125)
5. Watch it flip out

If those steps don't work, try it on a few other of the cubes, and then try again on the original one. I can't seem to figure out what causes it exactly, seems to be random, but extremely common.

**Comment by JannisX11** [comment]
Fixed in the next version.
