### ISSUE TITLE
[Suggestion] Soft selection for vertices / Proportional editing

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1594]
Explained in detail here: https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/3DSMax-Modeling/files/GUID-BEF2CC1E-40BE-45DD-A8E9-228EE4A1EE98-htm.html

There are a lot of ways to make soft selection more precise, but I imagine this gets complicated on the back-end. 

---

Imo a good first version for Blockbench could focus on just specifying the number of vertices away from your selection you want to affect (with a linear fall-off).

This could be a number tool (like the brush size or opacity) with 0 by default (= 0 vertices away from your selection are affected).
If you raised this number to say, 2, that means vertices directly adjacent to the ones you selected will be moved/rotated/scaled by 66% of what you did to your selected vertices, and the next ones over by 33%.

**Comment by JannisX11** [comment]
Added in 4.7.
