### ISSUE TITLE
[Issue] The model in Blockbench is different from the model in Minecraft.

### ISSUE THREAD

**Issue by HYB1022** [JannisX11/blockbench#1596]
Please make sure to provide the following information:
- Detailed description of your issue : I modeled it on Blockbench and applied it in Minecraft, but it looks different from what I modeled.
- Model format in which the issue occurs : BedrockEdition Model
- Blockbench variant (Website / PWA / Program) : Program
- Operating System : Windows 10
Blockbench 
![image](https://user-images.githubusercontent.com/115002543/193812558-e051fc5a-2caf-4d02-894e-1221b3e41159.png)
Minecraft
![image](https://user-images.githubusercontent.com/115002543/193812653-17bb27c9-4db0-466b-9af4-53566c691055.png)

Blockbench
![image](https://user-images.githubusercontent.com/115002543/193812692-865a3c58-5160-49d0-9760-5c83fb3e2134.png)
Minecraft
![image](https://user-images.githubusercontent.com/115002543/193812735-5b2b8fb3-10f3-404a-9b0a-1f53a11f0fe3.png)

Blockbench
![image](https://user-images.githubusercontent.com/115002543/193812785-59dd18b6-fb44-41c0-9c65-24eb76e738bb.png)
Minecraft
![image](https://user-images.githubusercontent.com/115002543/193812823-830d60e4-15a0-4d0c-b81f-aa6c4483046b.png)

This problem occurs when the cube is rotated.

**Comment by JannisX11** [comment]
I am stumped. Could you attach the model? You can also remove the elements that do not show the problem.

**Comment by HYB1022** [comment]
I can't attach a file because I've already solved it and saved it. I solved the problem by selecting all the cubes and setting the pivot point.
