### ISSUE TITLE
[Issue] BlockBench Session error

### ISSUE THREAD

**Issue by FrogNiche** [JannisX11/blockbench#1597]
Hello! I was creating a GeckoLib animated entity, and I wanted to create a session for my friend to join me and animated the model, and when I created the session, it won't give me the code to pass out to my friend. Then when I went to File ->Session, it gives me this message that I am connected to a session when I'm supposed to create one? Please help! Thank you!

Here's the link to the image of BlockBench: https://cdn.discordapp.com/attachments/1027324815729762404/1027327076711288872/wrong.png

**Comment by JannisX11** [comment]
Sorry, should work again now!
