### ISSUE TITLE
[Suggestion] Keybinds to move cubes relative to the camera direction

### ISSUE THREAD

**Issue by Tslat** [JannisX11/blockbench#160]
As of update 2.0.0, the ability to manually move cuboids over 1 grid space by pressing the arrow keys has stopped working.

I've checked through all the keybindings settings and all other settings, and I can't even seem to see another issue request here.

Last worked in 1.1.6 - I had to downgrade back to this to get the functionality back

**Comment by JannisX11** [comment]
This has been removed because of low priority. It might be re-added later on.

**Comment by Tslat** [comment]
That's a shame, it's a bit of a killer for me, not having it

**Comment by LordGiacomoS** [comment]
Agreed, if it comes back I will probably be so happy, I will donate if I have funds in order

**Comment by LordGiacomoS** [comment]
It would be cool as a [Plugin Idea] because it can be a bit confusing to some
