### ISSUE TITLE
[Issue] Can't select external image editor in Linux.

### ISSUE THREAD

**Issue by vvvbbbcz** [JannisX11/blockbench#1606]
I'm using Linux (Kubuntu 22.04). When I was trying to jump to an external image editor in Blockbench program, it reported "Can't find external editor", then I tried to select GIMP as the editor, but found the file filter only shows .exe file.

**Comment by JannisX11** [comment]
What are the typical file extensions for apps on linux?

**Comment by vvvbbbcz** [comment]
> What are the typical file extensions for apps on linux?

Applications on Linux usually do not have extensions, but the file extensions of their shortcuts is ".desktop".
