### ISSUE TITLE
[Suggestion] Option to disable name tag in json printout

### ISSUE THREAD

**Issue by Tslat** [JannisX11/blockbench#161]
Prior to 2.0.0, if you left the cubes at their default names, when exporting the model it would leave out the "name" tag entirely in the JSON printout.
This was great for keeping clean JSON files where the names of the cuboids weren't important.

Since 2.0.0, it just prints out "name": "cube"

**Comment by JannisX11** [comment]
This got lost in the update. I have no idea why.
It will be re-added in the next version.
