### ISSUE TITLE
[Issue] Blockbench web image shrink

### ISSUE THREAD

**Issue by Psychodeus** [JannisX11/blockbench#1612]
So when I go to from the minecraft skin tab, to the image tab it turns to be like this
![image](https://user-images.githubusercontent.com/93028949/196274471-96665f1c-97cd-40ce-9088-3dd1b99d5b5e.png)

And I need to manually control + scroll wheel to zoom out the page to make the page correct.
![image](https://user-images.githubusercontent.com/93028949/196274416-f53b1470-a6a0-4c92-8b97-101a3b03c5fd.png)

If I go back to minecraft skin tab and goes back to image tab, the bug repeat.

**Comment by JannisX11** [comment]
Cannot reproduce. If you open the dev tools (Ctrl + Shift + i) and switch to Console, are there any error messages (red)?

**Comment by Psychodeus** [comment]
Hmmm strangely it doesn't occur when I try it again today, but yesterday it really did happened.
And as I attempt to recreate my first problem, the second problem occured:
![image](https://user-images.githubusercontent.com/93028949/196515809-35ad8e57-5450-42f9-a2ac-cf9f9dd8fe0b.png)
![image](https://user-images.githubusercontent.com/93028949/196515494-bbd795f1-f46f-48e0-88aa-bf624928b354.png)

My 16x skin won't be in it's place. It becomes scrambled egg. I'm confused.

**Comment by JannisX11** [comment]
64 x 32 px skins are generally not supported by Blockbench. Maybe you wanted to select the Armor preset instead of Steve?
