### ISSUE TITLE
[Issue] Using 'Import Open Project' on Java model only exports 1 texture to .json

### ISSUE THREAD

**Issue by ElsewhereHere** [JannisX11/blockbench#1613]
Please make sure to provide the following information:
**- Detailed description of your issue**
When combining two Java models with the 'File>Import>Import Open Project' option, only the imported texture is output to the json. The model and UVs appear correctly in BB with multiple textures, but when exported as a Block/Item Model only a single texture is used in game. (It will output it if it is defined as the 'particle' texture, but still will not assign it to the proper cubes)
Can only be fixed by 'Deleting' the texture in BB, re-'Importing' it and using 'Apply to Elements'.

![BB_Issue1](https://user-images.githubusercontent.com/58707237/196313928-8a800325-ff2b-4622-8a6c-8ddd2b600a76.png)
![BB_Issue2](https://user-images.githubusercontent.com/58707237/196313930-47b90b07-3367-4e08-964c-deaad373600c.png)
<img width="297" alt="BB_Issue3" src="https://user-images.githubusercontent.com/58707237/196313932-cad78cb2-8fb1-4248-8aef-12cf60b55ae9.PNG">

**- Model format in which the issue occurs**
Java Block/Item

**- Blockbench variant (Website / PWA / Program)**
Program

**- Operating System**
Windows 10

**Comment by JannisX11** [comment]
I assume it doesn't change the texture ID when importing the project. You can also change this ID when double clicking the texture. By default it's 0.
