### ISSUE TITLE
[Issue] I cant able to download plugin. "IT IS SHOWING NO PLUGIN Avalible"

### ISSUE THREAD

**Issue by Dexxxxxxxxxx** [JannisX11/blockbench#1618]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by JannisX11** [comment]
What type of device, browser, version are you using, and which country are you trying to access plugins form?

**Comment by Dexxxxxxxxxx** [comment]
I m from India
I m using Google Chrome
1 have latest version of blockbench available on Google Chrome.

**Comment by JannisX11** [comment]
Are you generally able to access jsdelivr?
https://cdn.jsdelivr.net/gh/JannisX11/blockbench-plugins/plugins.json
