### ISSUE TITLE
[Suggestion] Add tabbing order for scale/position fields at top of window

### ISSUE THREAD

**Issue by Tslat** [JannisX11/blockbench#162]
At the top of the screen are the fields for "Move", and "Scale".
At the moment, creating cubes based on known existing values means having to click between each field.

Can a tabbing order be added so that you could, for example:
1. Click on _Move X_
2. Enter value
3. Press Tab to focus on _Move Y_
4. Enter value

**Comment by JannisX11** [comment]
Added in 3.2.
