### ISSUE TITLE
[Issue][4.5 Beta 1] Dragging textures into open models no longer opens a menu, and always opens the texture editor

### ISSUE THREAD

**Issue by Cart3r1234** [JannisX11/blockbench#1621]
In 4.4.3 (running the application on Windows 11), dragging a texture into the workspace would open a menu with options for what you wanted to do with the texture, such as importing it or replacing existing textures when dragging onto them.  4.5 Beta 1 removes this menu, instead always opening the inbuilt texture editor when dragging a texture into the workspace.

I've attached clips of me trying to drag a texture into a model in the Java Block/Item format in both 4.4.3 and 4.5 beta 1.  The recordings just show Blockbench, but I drag the texture in from file explorer twice during the 4.5 recording and once in the 4.4.3, and drop it right on top of the existing texture reference in the texture window in both recordings.

4.5:

https://user-images.githubusercontent.com/69820300/198814487-f727dfbc-ae0d-4115-8e5e-b2b6ab4a39f5.mp4

4.4.3:

https://user-images.githubusercontent.com/69820300/198814713-39d45e1b-658f-446b-9648-cae05380d38a.mp4

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench/commit/aaac6a22dbce2437b7fbf1f1e1a53be7a35ad7f7
