### ISSUE TITLE
[Issue] Block Wizard

### ISSUE THREAD

**Issue by Suffix30** [JannisX11/blockbench#1627]
- haven't seen current issues posted
- latest version of Blockbench 4.4.3
- no (red) error messages

Please make sure to provide the following information:
- Detailed description of your issue 

- **Hitbox** 
  Gives a size option for entity collision; set to (2 blocks high) 
  when exported and in game it loads as (one block high)
  Collision doesn't seem to holdup/work at 2
  When another block is being placed on top, interrupts the block models texture/geo. 
 (note)~picture displays the difference of block height limiting it to 30 vs the collision at 32 or 2 blocks high 
 I would imagine adding a "3rd" block onto a collision of 2 should be flush & seamless and not gapped.
  
- **Block Wizard**
  work space is just shy of 32 and seems to cap out at 30 ( BLUE box displayed )
  yellow and purple show the difference of 2
  suggestion: raise the height from 30 to 32
 
- Model format in which the issue occurs
  **_Block Wizard_**

- Blockbench variant (Website / PWA / Program)
  **Program**
  
- Operating System
  **Micro$uck Windows 10**

![goodies](https://user-images.githubusercontent.com/49195535/199259949-062ef72c-d2d2-4209-9a5c-2c48275f1966.png)

- Love the app btw.

**Comment by JannisX11** [comment]
* This should go into the plugin repository as explained on the issue menu.
* Collision is not officially supported by Minecraft yet. Once it's supported it will become available in Blockbench
* Size is restricted by the format, not by Blockbench. The limits are intentionally set in place by Mojang.
