### ISSUE TITLE
[Issue] Clicking between move and scale fields too fast causes the value to reset

### ISSUE THREAD

**Issue by Tslat** [JannisX11/blockbench#163]
When entering values quickly in the move and scale fields, if you enter a value and then click on the next field too quickly, the original field will reset to its previous value.

Reproduction:
1. Click on _Scale X_
2. Enter a value, then immediately click on _Scale Y_
3. Immediately set _Scale Y_ to something
4. Watch _Scale X_ reset to 0.5 (or whatever it was before)

Might be easier to see if you quickly try and set all 3 values to a single number or something

**Comment by JannisX11** [comment]
You need to release the key you pressed to change the value. This is necessary for the slider to correctly recognize the input. If you let go any buttons you used to change the value before clicking on the next field, it will register the change.
