### ISSUE TITLE
[Issue][BETA] textures saved from the image editor get corrupted

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1632]
![image](https://user-images.githubusercontent.com/81629481/199637439-4fd9863b-12eb-4d9c-bd4f-c659a3b49ccd.png)

Saving a texture in the image editor shows this error in the textures tab +makes the texture 0 octets and unopenable.

Blockbench 4.5.0 beta 2, Windows 10 Desktop app

**Comment by JannisX11** [comment]
Cannot reproduce. Any console errors?

**Comment by PaulFinnerty** [comment]
Not that I can see
![image](https://user-images.githubusercontent.com/81629481/199827136-f665f64c-49c4-4db6-b9bf-0efdd0a4ade0.png)

**Comment by PaulFinnerty** [comment]
Trying to paint on the texture after saving gets me this error
![image](https://user-images.githubusercontent.com/81629481/199828226-4d843b37-3608-49ea-8e53-b087c3f7dcf9.png)

**Comment by PaulFinnerty** [comment]
I also had this issue in 4.5.0 beta 1.

if that can clue you in, on the web app (chrome, 4.5.0 beta 2), saving an image prompts me with saving "model.png" first, then the actual texture.

model.png, or whatever name I pick is 0 octets, but then the actual texture works

**Comment by JannisX11** [comment]
I cannot reproduce that either.
I have heard of people having this issue before (pre 4.4) so I don't think it's directly related to the 2D editor.

**Comment by PaulFinnerty** [comment]
I just noticed this issue does not occur if I use the save icon in the Textures tab, instead of using the Save Model keybind.
