### ISSUE TITLE
[Issue] Animated textures don't work on meshes?

### ISSUE THREAD

**Issue by yaetuz** [JannisX11/blockbench#1634]
Hi. Basically what the video says. I have a cube with animated textures, the moment I convert it to a mesh - textures break. Is it intentional? Is is a bug? Are there any plans to make animated textures work on meshes? 

Blockbench 4.4.3 Desktop. Nothing in the Dev Tools.

(Also, thanks for Blockbench - amazing tool)

https://user-images.githubusercontent.com/108496496/199956773-017eb5fa-0428-41c4-880b-d5de2c607276.mp4

**Comment by JannisX11** [comment]
Yeah, meshes do not have support for animated textures at the moment.

**Comment by Xyndra** [comment]
this is not a suggestion, this is a core required feature! bumping this
