### ISSUE TITLE
[Issue][BETA] bugged Animations

### ISSUE THREAD

**Issue by Cub0use** [JannisX11/blockbench#1638]
Observed in Bedrock entity and generic model formats:

Adding animations does not expose them to saving.

It is also not possible to rename animations, change their loop mode, delete or unload them (individually, or per Animation file).

Got errors with that:
![image](https://user-images.githubusercontent.com/81629481/200578524-cffbcb43-de3e-4f0e-a9c8-4e590eb54816.png)

- Blockbench 4.5.0 beta 3, Windows 10 Desktop app

**Comment by JannisX11** [comment]
Fixed in 4.5.
