### ISSUE TITLE
Não conseguir mudar de cor

### ISSUE THREAD

**Issue by ThrowRed** [JannisX11/blockbench#1639]
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

**Comment by ThrowRed** [comment]
Alguém sabe como resolver?

**Comment by PaulFinnerty** [comment]
This is not the place to ask questions on how to use the software, please redirect to the [Blockbench Discord](https://discord.com/channels/314078526104141834/314078902949511169) to do that.

You'll have to use English, and be more detailed with your question too.
