### ISSUE TITLE
[Issue]Disabling visibility in wireframe mode, then activating visibility in normal mode causes problems.

### ISSUE THREAD

**Issue by qsef1256** [JannisX11/blockbench#164]
- Detailed description of your issue
![1](https://user-images.githubusercontent.com/44014066/47255435-22510a80-d4ac-11e8-8fe3-90980bb78fba.png)
![2](https://user-images.githubusercontent.com/44014066/47255436-22510a80-d4ac-11e8-89f5-09395c0a26b3.png)
![3](https://user-images.githubusercontent.com/44014066/47255437-22510a80-d4ac-11e8-8e66-da5d2a24e02e.png)
![4](https://user-images.githubusercontent.com/44014066/47255438-22e9a100-d4ac-11e8-813b-8642dcc729fb.png)
![5](https://user-images.githubusercontent.com/44014066/47255439-22e9a100-d4ac-11e8-8918-4e638a73486c.png)
![image](https://user-images.githubusercontent.com/44014066/47255450-59272080-d4ac-11e8-9539-5069915a5e38.png)

:(

- Blockbench variant (Webapp/Desktop)
Desktop
- Operating System
Windows 10 64 bit

**Comment by JannisX11** [comment]
Fixed in 2.0.2
