### ISSUE TITLE
[Suggestion] Show Notification When Update

### ISSUE THREAD

**Issue by Malik12tree** [JannisX11/blockbench#1643]
Blockbench should show a device notification when it finishes/fails updating when app is not focused.

**Comment by JannisX11** [comment]
The current goal is to make auto-updating relatively quiet, and not explicitly tell users to restart. After closing, updating takes a few seconds, and when trying to start while it's still updating users will get an error message saying that Blockbench is not installed. That's how the auto-updater that Blockbench uses works unfortunately, so the best workflow is to update while the user is not actively using Blockbench, e. G. after closing the program to do something else.
