### ISSUE TITLE
[Suggestion] Also range-select keyframes horizontally with shift+click

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1645]

**Comment by JannisX11** [comment]
This is already possible.

**Comment by PaulFinnerty** [comment]
https://user-images.githubusercontent.com/81629481/201478689-cc26f856-4ba3-4b61-a8b3-fafa1221ee90.mp4

Not for me; I'm pressing shift the entire time in this video. It works vertically on the same timestamp, but not horizontally, within a group's channels or across groups.
