### ISSUE TITLE
[Issue] Updating Image Creates Image Error

### ISSUE THREAD

**Issue by zoombaz** [JannisX11/blockbench#165]
I am using BlockBench 2.0.1 When I export an image from my illustration software I get an image error. I am usually able to do this once or twice before it no longer works. This was not an issue on the previous version I used. I demonstrate the issue in this video:
https://www.youtube.com/watch?v=svXp8nlEsuo&feature=youtu.be

![345gadf](https://user-images.githubusercontent.com/34973440/47261672-3f281680-d489-11e8-83e2-f88c724afbe0.PNG)
Blockbench Variant
- Desktop

OS
- Windows 7 Professional 64-bit

**Comment by JannisX11** [comment]
Fixed in 2.0.2.
