### ISSUE TITLE
[Issue] Flipping cubes does not flip UV anymore

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1653]
![bb_bug_flip_uv](https://user-images.githubusercontent.com/81629481/201418068-023a633f-d10e-46bd-8ec8-64a9672ae622.gif)

Observed in Bedrock entity format

- Blockbench 4.5.0, Windows 10 Desktop app

**Comment by paiwoohyung** [comment]
I'm having the same problem as you. I hope it will be fixed soon.
