### ISSUE TITLE
[Suggestion] Restrict brush to pixel grid in paint tab with smoothness on

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1658]
Not sure if it is intended, but when the brush has some smoothness, it becomes free of the pixel grid alignment. (in 4.5.1)

I'd like it to stay restricted to the pixel grid to be more precise , but I guess this could be an option in preferences, plus a keybinding to toggle it.

**Comment by JannisX11** [comment]
While working on the brush update I noticed that restricting smooth brushes to the pixel grid creates unwanted artifacts and banding. It creates a much smoother brush stroke if the position is free. So with the exception of painting individual dots or straight lines, I do not see an advantage in restricting it to the grid.
