### ISSUE TITLE
[Issue] I can't tap the cubes folders on android  (webapp)

### ISSUE THREAD

**Issue by MrMinechest** [JannisX11/blockbench#166]
Hello I'm Mike , This Morning I was going to start a new model but sadly I can't touch any cube folder , I tap so many times and I doesn't work 
Please Fix this issue as soon as possible 
Thanks 
Mike

**Comment by MrMinechest** [comment]
![screenshot_2018-10-21-09-26-09-1](https://user-images.githubusercontent.com/44335586/47264826-d76bdd00-d515-11e8-80ed-3f6b4aea14a0.png)

**Comment by JannisX11** [comment]
Fixed in 2.1
