### ISSUE TITLE
[Issue] Paint eraser with animated texture selecting wrong area

### ISSUE THREAD

**Issue by Daniel-Mendes** [JannisX11/blockbench#1663]
When I use the paint eraser tool with an animated texture and select the 2/3/4 frame the erase area is not where the cursor is.

![image](https://user-images.githubusercontent.com/28825568/202905298-28f2bc97-cee0-4c63-9c5f-a82428fa6ec6.png)

See in the image, my cursor is at top but the erase area is in bottom.

Blockbench 4.5.1

**Comment by JannisX11** [comment]
Fixed in 4.5.2
