### ISSUE TITLE
[Suggestion] Binary FBX Export

### ISSUE THREAD

**Issue by MrScautHD** [JannisX11/blockbench#1668]
Hello!
I tried to add my model to MonoGame and Blender and i saw it is not Compatible with Blockbench Models

This Screenshot shows that the Blender FBX Model work and the Blockbench FBX Model not! (MonoGame)
![grafik](https://user-images.githubusercontent.com/65916181/204125651-ed05aa81-2650-4a25-abbe-3244e24d2e45.png)

Blender Error:
![grafik](https://user-images.githubusercontent.com/65916181/204125797-69b95e1f-25af-4101-8d78-7fba65249756.png)

Blockbench version: 4.5.2
Windows: 11
MonoGame: https://www.monogame.net/

**Comment by JannisX11** [comment]
Yeah, Blockbench exports FBX as ASCII files, which some applications may not support.

**Comment by MrScautHD** [comment]
i dont need it anymore... xD
