### ISSUE TITLE
Why won't it let me export as Minecraft entity wizard?

### ISSUE THREAD

**Issue by 1000nicemice** [JannisX11/blockbench#1669]
I don't have Bedrock or Java, but I know that i can export it to Minecraft Edu, which I have. I have already exported another mob, but when I try to export this new one, it only allows me the default export options. I have already checked the box for my target to Minecraft Edu, but it won't allow me to export as a Minecraft Entity Wizard file. If anyone could help me that would be great. Thanks, -Mouse

**Comment by JannisX11** [comment]
For support ask on https://discord.gg/blockbench
