### ISSUE TITLE
[Question] How do you export multiple models into the same addon?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [JannisX11/blockbench#1674]
I am working on a stranger things mod for me and my little brother in Blockbench, but every entity and block gets its own addon. So is there a way to export multiple entities and blocks into the same addon?
![image](https://user-images.githubusercontent.com/112659665/205141937-4c44f868-db77-458d-ad7f-6839da1d1fbb.png)
![image](https://user-images.githubusercontent.com/112659665/205141944-3d0368d2-4471-4516-8d4d-352bc4c44867.png)

**Comment by JannisX11** [comment]
This is the Blockbench github page. For questions and modeling support, please ask on the Discord server: https://discord.gg/blockbench

**Comment by TheRealDigitalMaster** [comment]
Discord is blocked for me. I can only ask questions here because my parents do not allow discord. There should be a discussions page on this repo.
