### ISSUE TITLE
Rotations of the Z axis when animating blocks, rotates on the X axis

### ISSUE THREAD

**Issue by NoobZea** [JannisX11/blockbench#1681]
when I was moving to animate my walking cycle, I wanted to rotate the torso of my model but, when I went to rotate the block on its Z axis. The model then proceeded to rotate as if it were being rotated on its X axis. I went through the console that the developer tool directed me to, but it didn't bear any fruit, for there was no error shown. Despite this, I have posted a video that you can see by clicking on the link provided in the bug report.

Blockbench Version 4.5.2 Windows 10
[https://youtu.be/7SmH5yAzThY](url)

**Comment by PoolloverNathan** [comment]
Did you modify the rotation numbers in the editor? Euler angles make it really easy to shoot yourself in the foot.

**Comment by KJEntytek303** [comment]
BB version 5.0.5 Archlinux, same issue.
