### ISSUE TITLE
custom geometery skins. 

### ISSUE THREAD

**Issue by SugmaNUTSbiatch** [JannisX11/blockbench#1687]
it would be nice to have custom geometry skins built into the app or web app! it would give me something more to do inside the app. i feel my problem as the same of multiple people and it would be nice to have the option of creating custom geometry skins.

thank you if you are reading this from me a former blockbench user.

**Comment by JannisX11** [comment]
Minecraft does not support custom geometry skins by default. However there are solutions like the Figura mod for Minecraft Java Edition (https://www.curseforge.com/minecraft/mc-mods/figura) that make 3D skins possible, and they are compatible with Blockbench.
