### ISSUE TITLE
I cannot delete or duplicate any animation geometry.

### ISSUE THREAD

**Issue by CesarZorak** [JannisX11/blockbench#1689]
### Detailed description of your issue

Try right click
With the added button
And with the 2 options on the taskbar:
menu - edit - delete
menu - frames - delete

No option and obtained results.

![Captura de pantalla 2022-12-11 000902](https://user-images.githubusercontent.com/107509756/206889135-4d9813b6-27d9-4578-a466-6f224623da32.png)

### Model format in which the issue occurs

model free

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Could you attach a screenshot or your error log? Help > Developer > Open Dev Tools > Console tab.
