### ISSUE TITLE
[Issue] Some tools are hidden

### ISSUE THREAD

**Issue by GoofyMonkeyMan** [JannisX11/blockbench#1690]
### Detailed description of your issue

I want to use loop cut but couldn't find it at the top. So I went to customize the toolbar and couldn't find loop cut until I looked at the top. It showed a bunch of gray tools and said "Some tools are hidden because they are not available in the current mode, format, or situation." I was just making a generic model, no loaders and no Minecraft. Thanks in advance.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Website

### Operating System

Laptop

**Comment by JannisX11** [comment]
Mesh tools like loop cut only work on meshes in face/edge/vertex mode: https://www.youtube.com/watch?v=WbyCbA1c8BM

**Comment by GoofyMonkeyMan** [comment]
Thanks so much
