### ISSUE TITLE
[Issue] Leftclick is completely ignored / throws errors

### ISSUE THREAD

**Issue by Plagiatus** [JannisX11/blockbench#1691]
### The issue
Leftclick inside the canvas area of blockbench is being completely ignored for me, making it impossible to rotate the view.

rightclick works fine, so moving the view around is no problem, but rotating the view seems impossible.

A screenshot of the errors I'm getting in the console:
![grafik](https://user-images.githubusercontent.com/7681159/207626309-f82093bf-1fdd-424b-95ba-14f35cb02a36.png)
The single issues are me clicking the LMB, the repeated issues is my mouse moving (with or without holding the LMB)

### Steps attempted  
- ran installer again without uninstalling
- uninstalled and reinstalled (see further info)
- reset keybinds to mouse + trackpad 
- delete BB folder / use uninstaller in there and reinstall

### Further info
I just installed the latest version of blockbench (4.5.2) manually over an existing one (3.6.6). when I search for the program in windows program list, they both show up. If I uninstall either one of them, i'm stuck with this: 
![grafik](https://user-images.githubusercontent.com/7681159/207626865-3cdd9f98-11fb-4b4d-8282-4035fa1c4847.png)

### Model format in which the issue occurs

Tested with Bedrock Entity

### Blockbench variant

Program

### Operating System

Win 10

**Comment by JannisX11** [comment]
This is an error message from a plugin. Do you have any plugins installed?

**Comment by Plagiatus** [comment]
I do indeed have multiple plugins installed. I tried removing them one by one, but it never fixed itself. Only after a restart it now works as expected. So I cannot tell which one of my 3 plugins caused the issue after all (because I don't need any of them anymore anyways). But it was some rogue plugin indeed.

**Comment by JannisX11** [comment]
Judging from the error message it was one with at least 3487 lines, which should narrow it down.

**Comment by Plagiatus** [comment]
Well, I've had two very old ones (snowstorm back when it was a plugin, the deprecated model converter) and one proprietary one. So like I said - won't need any of those anymore anyways, as they are old. But yes, if I didn't just yeet them thorough uninstalling, i could probably narrow it down that way.
