### ISSUE TITLE
[Issue] Color picking from a Blockbench window does not transfer opacity to other windows

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1693]
### Detailed description of your issue

With the option "Pick Color Opacity" turned on, color picking a translucent/transparent pixel works in the window it was picked from, but not for other Blockbench windows. The RGB values are correctly transferred though.

### Model format in which the issue occurs

Bedrock Entity + Image

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
The syncing option was removed in 4.9, so this is no longer an issue.
