### ISSUE TITLE
[Suggestion] NEW color markers and being able to change them ! 

### ISSUE THREAD

**Issue by Art-bor** [JannisX11/blockbench#1703]
### Detailed description of your suggestion

So when you select a cube, mesh and right click the cube, mesh there is an option called Color Markers 
there are colors you can mark the object with currently there is colors but being able to change the marker colors would be awesome i use it a lot as it helps you visualize your model before putting textures and is good distinguisher 

![image](https://user-images.githubusercontent.com/121435109/209545173-b5d48820-d131-499d-a537-b77173140dac.png)

as you can see there is Marker colors being able to add more colors would be AMAZINGGG
easy to do and would be awesome THANKS

**Comment by JannisX11** [comment]
You can do this with https://www.blockbench.net/plugins/custom_marker_colors
I think a plugin is a good place for that feature.
