### ISSUE TITLE
[Issue] Locator and Null object icon position in viewport not updated upon flipping their position

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1709]
### Detailed description of your issue

Using Flip X, y or Z does not update the position of the locator/Null object in the viewport. The gizmo does go to the correct position. Changing the position of the locator/null object with the gizmo or from the Element tab snaps it back to the right position.

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Fixed in 4.6.
