### ISSUE TITLE
[Issue] Quad view top right pane resets

### ISSUE THREAD

**Issue by dhiawesome** [JannisX11/blockbench#171]
Whenever I switch between move, display, and back to move, the top right pane of the Quad view resets to the 360/normal view. I prefer to have this in the bottom right, and having two normals show up simultaneously when unwanted is slightly odd. (As a note, I set the view in top right to West)
This is on the desktop app, specifically using Windows 10 Education.
Console does contain some errors, however this might be from loading while on restricted internet connections:
![image](https://user-images.githubusercontent.com/31384994/47562259-48b9ee80-d961-11e8-96b9-9cfdc603695a.png)

**Comment by JannisX11** [comment]
Yes, the error messages are from a missing internet connection and from outdated plugins that you still have installed.
