### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by kwrst76** [JannisX11/blockbench#1714]
### Detailed description of your issue

I launched BlockBench and it gave me a GPU description. It told me all the things that were disabled but i ignored it. When i went to make a skin it was stuck at 2 fps. I tried the Non Hardware acceleration mode but it didnt fix anything.

### Model format in which the issue occurs

Minecraft Skin

### Blockbench variant

Program

### Operating System

Windows

**Comment by JannisX11** [comment]
Does the web app work better?
