### ISSUE TITLE
[Issue] "Properties" is misspelled with an F in the UV section of the UI

### ISSUE THREAD

**Issue by DB20-official** [JannisX11/blockbench#1717]
### Detailed description of your issue

When using per-face UV for a model, beside all the directional UV selections, the button "Face Properties" has a typo where "Properties" is spelled with an F instead of a P. Ensure you have a cube in per-face UV mode, and hover over the button with what looks like a checklist beside all the buttons containing each UV directions. From my testing, this happens with any model type with per-face UV.

### Model format in which the issue occurs

Any with Per-Face UV

### Blockbench variant

Program

### Operating System

Windows 11 22H2

**Comment by JannisX11** [comment]
Fixed in 4.6.
