### ISSUE TITLE
[Can't see anything in worckspace macOS] when we mac users open blockbench the work space is empty as void

### ISSUE THREAD

**Issue by binugamez** [JannisX11/blockbench#1723]
### Detailed description of your issue

**Issue screen shot**
![Empty Blockbench Issu](https://user-images.githubusercontent.com/116512066/212457467-77fbe796-f18b-4d83-8686-91872bc594fd.png)

**macOs**
10.13.6

**graphics card**
NVIDIA GeForce 320M 256 MB

**Information**
I was happy it was fixed yesterday , but it came back
PLS fix it

### Model format in which the issue occurs

blank in workspace for mac

### Blockbench variant

Program

### Operating System

macOS 10.13.6

**Comment by JannisX11** [comment]
I already explained in #1617 that your device does not meet the minimum hardware requirements. I'm gonna have to ask you to stop opening duplicate issues.
