### ISSUE TITLE
[Issue] Scrolling using scrub bar in input boxes causes freeze

### ISSUE THREAD

**Issue by MerpisMe** [JannisX11/blockbench#1729]
### Detailed description of your issue

Input boxes that use the new system introduced in 4.6.0 (variable placeholders, keyframe, etc) cause the entire program to freeze when the scrub bar is used to scroll through them. Scrolling works fine otherwise.

### Model format in which the issue occurs

Generic, Bedrock Legacy, Bedrock Entity

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by MerpisMe** [comment]
update: this is temporarily fixed by using the scroll wheel on another scrollable input field

**Comment by JannisX11** [comment]
I am unable to reproduce this issue.

**Comment by MerpisMe** [comment]
I'll send a video as soon as I can. Could it maybe be related to hardware acceleration?

**Comment by JannisX11** [comment]
This works for me with or without hardware acceleration. Do you have a 100% reproduction rate?

**Comment by MerpisMe** [comment]
I do, yes. I've only tested it on my home PC, though, but I've yet to test it on the web app
