### ISSUE TITLE
[Suggestion] Pressing "Escape" with Copy-paste tool in Move mode should return the texture to its original spot

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1731]
### Detailed description of your suggestion

Pressing the escape key on keyboard with a selection of the Copy-Paste tool in "Move" mode will erase the piece of texture that was moved.

I think it should return the moved piece of texture back to its orginal spot, and not delete it (this is also happening without moving the piece of texture).

**Comment by JannisX11** [comment]
Tracking this as bug since it is not intended behavior and also does not handle undo integration correctly.
