### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by BangXDty** [JannisX11/blockbench#1734]
### Detailed description of your issue

The screen freezes when I scroll for a while but everything else works fine.

### Model format in which the issue occurs

OPPO A5s CPH1909

### Blockbench variant

Website, Program

### Operating System

Android

**Comment by JannisX11** [comment]
What part of the interface exactly are you scrolling?

**Comment by BangXDty** [comment]
part used to scroll through the model It freezes when I move it.

ในวันที่ ส. 21 ม.ค. 2023 01:28 น. JannisX11 ***@***.***>
เขียนว่า:

**Comment by JannisX11** [comment]
Duplicate of #1729
