### ISSUE TITLE
[Issue] BlockBench doesn't focus the new window when a popup window occurs on Linux Mint 21.1

### ISSUE THREAD

**Issue by jordan4ibanez** [JannisX11/blockbench#1736]
### Detailed description of your issue

In LInux Mint 21.1 when you have a popup window, save, load, export, etc, the window is shown behind the primary window and you need to globulate yourself through the windows to get to it. A minor issue, but annoying enough for me to make an issue report.

### Model format in which the issue occurs

N/A

### Blockbench variant

Program

### Operating System

Linux Mint 21.1

**Comment by JannisX11** [comment]
Upstream issue on Electron https://github.com/electron/electron/issues/32857

**Comment by JannisX11** [comment]
Fixed in Blockbench 4.10.2.
