### ISSUE TITLE
[Animation tooltip] Inconvenience in the new version

### ISSUE THREAD

**Issue by npoctoMAXIK** [JannisX11/blockbench#1737]
### Detailed description of your issue

In the new version of the application, an animation hint popup has been added (for OptifineEntity). This window obscures the line in which I am currently writing, and by pressing ENTER the first line of the options offered in the window is selected (although I kind of just want to go to a new line of code).
That being said, I can't find a way to disable this popup. So far, this only greatly complicates the work with animation. I hope you understand everything, although I wrote through a translator) Thank you.

![nameless123481](https://user-images.githubusercontent.com/123228186/213845916-71258139-c405-492e-8d30-64ee3f4637dc.png)
![nameless123482](https://user-images.githubusercontent.com/123228186/213845963-afa139b7-751d-466a-aed9-d2c095af8da2.png)

### Model format in which the issue occurs

OptifineEntity

### Blockbench variant

Program

### Operating System

Windows

**Comment by JannisX11** [comment]
The incorrect offset was fixed in 4.6.1.
