### ISSUE TITLE
[Bug] Display problems

### ISSUE THREAD

**Issue by Q2114** [JannisX11/blockbench#1744]
### Detailed description of your issue

• I encountered an error while running the application. 
• Problem video below
https://youtu.be/Q1_1jiSfNxs

### Model format in which the issue occurs

All

### Blockbench variant

Website

### Operating System

Android 10 ( Chrome OS)

**Comment by JannisX11** [comment]
I have no idea honestly. How often does this happen?

**Comment by Q2114** [comment]
To be honest, not very often, after changing the chrome it seemed to stop appearing. I think it's all through my smartphone.
