### ISSUE TITLE
[Suggestion] [Image editor format] When using copy/paste tool, move the toolbar/relevant widgets to below the selection

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1748]
### Detailed description of your suggestion

Currently when in image editor, the copy/paste tools are placed at the bottom of the screen and can be hard to see. Whilst this behaviour is the same as in any other format, it can be harder to find and takes longer to use.

My suggestion is to move the widgets to below the selection (shown in lil mockup i made)
![image](https://user-images.githubusercontent.com/38400400/216827622-493190b8-9a93-454a-acd3-28626acd9f27.png)

**Comment by Magicmaan** [comment]
alternatively, move the tick/cross to the other side to be next to the other widgets. I imagine this would become more annoying on larger displays

**Comment by JannisX11** [comment]
Will close this as the copy-paste tool has been replaced by selections + layers that are more similar to classic image editors.
