### ISSUE TITLE
cant add blocks in edit mode

### ISSUE THREAD

**Issue by mjvdgaming** [JannisX11/blockbench#1749]
### Detailed description of your issue

if i am in edit mode the whole thing on the right is empty

### Model format in which the issue occurs

java

### Blockbench variant

Program

### Operating System

i dont get it

**Comment by JannisX11** [comment]
Please attach a screenshot.

(PS: The Operating System is the software system that your computer uses. Most computers use Windows, Apple computers use Mac, etc...)
