### ISSUE TITLE
[Issue] Wireframe mode is disabled when Vertex Snapping is turned on in Wireframe mode.

### ISSUE THREAD

**Issue by qsef1256** [JannisX11/blockbench#175]
- Detailed description of your issue
![image](https://user-images.githubusercontent.com/44014066/47613933-03213100-dadb-11e8-8910-ec2344d4acef.png)

![image](https://user-images.githubusercontent.com/44014066/47613935-07e5e500-dadb-11e8-9cff-ed3a1373d242.png)

![image](https://user-images.githubusercontent.com/44014066/47613939-12a07a00-dadb-11e8-9d39-2182ff0a4ea8.png)

![image](https://user-images.githubusercontent.com/44014066/47613947-2815a400-dadb-11e8-8ca5-ec930dd99666.png)
The wireframe mode does not work with the Z key.

- Blockbench variant (Webapp/Desktop)
Desktop
- Operating System
Windows 10, 64 bit

**Comment by JannisX11** [comment]
Vertex snap and wireframe view cannot be used at the same time. Works as intended.
