### ISSUE TITLE
[Issue] Javascript Error when finished downloading updater

### ISSUE THREAD

**Issue by StickyChannel92** [JannisX11/blockbench#1755]
### Detailed description of your issue

![image](https://user-images.githubusercontent.com/48563620/218963936-289d0bc9-1abd-435e-896b-fc7d6256970f.png)
**Issue:** When Blockbench finishes installing its updater, a JavaScript error prevents it from running a PowerShell command to run Blockbench updater executable.

**Steps to reproduce:**
1. Download and install Blockbench 4.6,3
2. Open BlockBench
3. Wait until the update is complete.
4. Error appears.

**Expected Result:** Blockbench should automatically update.
**Actual Result:** JavaScript error prevents the PowerShell command from running, thus not updating Blockbench.

### Model format in which the issue occurs

Pop-up error

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
Waiting for it to get fixed here: https://github.com/electron-userland/electron-builder/issues/7127
Manually updating Blockbench from the website should work though.
