### ISSUE TITLE
[Suggestion] [Image editor format] When using mirror tool, add option to select area/axis to mirror by

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1761]
### Detailed description of your suggestion

Current behaviour has the mirror tool working on the entire texuture sheet, a useful tool would be if you could set the axis to mirror by, or a selection area to mirror in.
This could also be merged into a more general "selection" tool, that could then also be used for a fill bucket

**Comment by JannisX11** [comment]
Added in 4.7.
