### ISSUE TITLE
[Issue] Save warning does not have proper fallback

### ISSUE THREAD

**Issue by CherryLax** [JannisX11/blockbench#1763]
The pop up window asking "Do you want to save your model?" has three options: Save, Discard, and Cancel. When you choose Discard, the changes are discarded and you are brought back to the home page. Unfortunately, this is what also happens when you choose Cancel. I expect that the intended function of the Cancel button is to bring you back to the model without saving or discarding any changes.

To recreate this, open a saved JSON model, make any change, then close the tab to get the window.

Thank you for the great program. I hope you are able to patch up this small oversight to make it even better.

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
I cannot reproduce this issue. Can you check if you have any related console errors? (Help > Developer > Open Dev Tools > Console)

**Comment by CherryLax** [comment]
Oh you're right, I gave you the wrong instructions 😅

Try this:
Open a saved JSON model, make any change, then close the tab to get the window. After that press save and THEN press cancel.

This happens when I forget to save before closing, then when I try to save the only option is to save as a Blockbench project when I really want to continue using the JSON format. So naturally, I cancel so I can save as it in the correct format. This is when all the changes are discarded.

I hope that helps clear things up!
