### ISSUE TITLE
Cam Rotation Broken

### ISSUE THREAD

**Issue by StudzPlayz** [JannisX11/blockbench#1768]
### Detailed description of your issue

Can't Rotate Cam After Clicking A Cam Rotation Preset.

### Model format in which the issue occurs

Any

### Blockbench variant

Website

### Operating System

ChromeBook

**Comment by PaulFinnerty** [comment]
you were probably in one of the orthographic view presets. Pressing 5 or 1 on your keypad will return you to the initial angle, where you can rotate the camera freely.

**Comment by StudzPlayz** [comment]
thx
