### ISSUE TITLE
Block textures not loading on specific faces of custom blocks

### ISSUE THREAD

**Issue by guysimtheprinter** [JannisX11/blockbench#1779]
### Detailed description of your issue

Hi, i am currently working on a texture pack for a private server i will be playing with my friends. I have made the texture for the cartography table into a printer, and i used Blockbench to fix the orientation and allow for unique textures on the sides (normally, the cartography table re-uses the north facing texture for the west facing texture and uses dark oak planks for the bottom texture)

When i go in game and place it, it looks fine. It looks fine in the inventory, the mining particles work, all that.
![2023-03-11_14 53 09](https://user-images.githubusercontent.com/38056324/224509317-547040e7-0abc-4538-bea2-6e9f2e26f673.png)

But then when i place a block next to it, it does this weird tunnel effect where it just deletes some of the textures for the faces and makes them transparent.
![2023-03-11_14 53 19](https://user-images.githubusercontent.com/38056324/224509324-f014b0b6-a12b-4e5b-87a6-c01735880506.png)

I'm not sure where to even begin with this. I tried making the inside textures the same as the outside textures to see if that worked, but it did not. Here is another instance of the glitch but in mid air.
![2023-03-11_14 53 40](https://user-images.githubusercontent.com/38056324/224509327-7d859f57-c4e1-4fac-9767-8ebd00d0b37f.png)

How do i fix this? Or even better, what is causing this problem?
I would also like to note that this version of the game that I am running is modded, using Forge 1.19.3-44.1.23 with a few client side mods and Optifine preview version 1.19.3 HD U I2 pre5. 

### Model format in which the issue occurs

Minecraft Java Block/Item

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
You probably have an accidental cullface set. Make sure all these cullface selectors are either set to None, or to the same direction as each face.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/29278436/224537842-a61e3b92-bb62-4910-af01-bca1f330ff37.png">

**Comment by guysimtheprinter** [comment]
> You probably have an accidental cullface set. Make sure all these cullface selectors are either set to None, or to the same direction as each face. <img alt="image" width="272" src="https://user-images.githubusercontent.com/29278436/224537842-a61e3b92-bb62-4910-af01-bca1f330ff37.png">

Okay, where is that menu? I don't have anything that says cullface anywhere.
