### ISSUE TITLE
[Issue] 3D widget blocking selection in wireframe mode

### ISSUE THREAD

**Issue by pixelplayer14** [JannisX11/blockbench#178]
When a cube is behind the 3d widget it is not possible or only possible on the edges to select it by clicking on it. 
Blockbench variant: Desktop
operating system: Windows
Example:
![afbeelding](https://user-images.githubusercontent.com/44682324/47877358-fe7eb480-de1b-11e8-9fc9-2f91aa5f44c0.png)

**Comment by JannisX11** [comment]
It is not possible to click through the widget to select the cube because it has it's own click event to move/resize the cube.
Wireframe is a special case when it comes to click detection and it will be redone in the next update.
