### ISSUE TITLE
[Issue] Plugins not installing

### ISSUE THREAD

**Issue by Cec-Krem** [JannisX11/blockbench#1784]
### Detailed description of your issue

Whenever I want to download a plugin, it just doesn't, even if it underlines the "+ Install".
I DO NOT KNOW if it's because of the network I'm on, even if I think it's the issue. I will be able to try with another one this week-end.
I do have exceptions generating, somehow that's ETimedOuts
-I think the network I use just blocks the download of plugins.
Console :

![timedout_issue_plugins](https://user-images.githubusercontent.com/127088905/225627332-4535a920-32ed-4c1a-9ac8-3238b20fdaf8.png)

### Model format in which the issue occurs

(?) Network exception

### Blockbench variant

Program

### Operating System

Windows 10, 64 bits

**Comment by JannisX11** [comment]
It does seem to be network related. Are you using a VPN or similar?

**Comment by pacmanfever** [comment]
mine aren't installing ether
