### ISSUE TITLE
Import Issue BlockBench

### ISSUE THREAD

**Issue by DavinProjct** [JannisX11/blockbench#1785]
### Detailed description of your issue

Uh i want to make models and i open .json and This text Cant Completed actions your memory was full i check and i have 1gb but wtf cant open models :-( help bro

BlockBench

### Model format in which the issue occurs

Bug

### Blockbench variant

Website

### Operating System

Android

**Comment by DavinProjct** [comment]
Bug

**Comment by JannisX11** [comment]
Looks like you need more RAM. I'll update the minumum hardware requirements on the website.
