### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by zaitaz** [JannisX11/blockbench#1789]
### Detailed description of your suggestion

Hello blockbench there is an that is I can't open outliner so please fix it🙏

**Comment by tastetest** [comment]
Hi,

I suggest giving more detail about what problems you are encountering, as well as providing a more detailed title. 
What platform are you running block bench on? Also, did you encounter any errors while trying to open the "outliner"?

Thank you!

**Comment by JannisX11** [comment]
Please attach a screenshot.
