### ISSUE TITLE
[Bug] Cone prevents me saving files

### ISSUE THREAD

**Issue by huangmeme** [JannisX11/blockbench#1793]
### Detailed description of your issue

In the process of my production, a variant appeared and I couldn't edit it or see it. I can edit other models but when I save and exit Blockbench my changes are lost, unless I delete that cone.
Here is the link to the file :
https://drive.google.com/file/d/1Rwn82DppzTkw5YpDQaKRCoEeiixUEtkP/view?usp=sharing

### Model format in which the issue occurs

bbmodel

### Blockbench variant

Program

### Operating System

Windows11

**Comment by JannisX11** [comment]
The model definitely has an issue. One of the faces is using vertices that do not exist on the mesh.
The interesting part would be which tools you used to edit this mesh. Do you know what you did specifically to create and edit it? Are you just using Blockbench's default tools, or additional tools from plugins like MTools to edit the mesh?

**Comment by huangmeme** [comment]
Yes, I just use the default editor. and also without using any plugins.
Here is my version number and list of plugins :
![image](https://user-images.githubusercontent.com/13671341/227069310-fc2ecd7d-1578-4689-a4f7-0dd98e6a7876.png)
I just remember I was duplicating the model，Other than that I don't remember。
Model :
![image](https://user-images.githubusercontent.com/13671341/227071462-4df20c0e-d207-4e82-8ba7-2168840afdc5.png)
