### ISSUE TITLE
[Suggestion] Arbitrary IK target

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [JannisX11/blockbench#1800]
### Detailed description of your suggestion

In blender, the IK target could be anywhere in the hierarchy and the chain was handled with a separate modifier. Not being able to put the IK target anywhere restricts what can be animated. I'm trying to make a quadruped's front legs snap to the ground, but because they are children of the torso the target moves with the torso, essentially making IK useless.

**Comment by EnderIzzy124** [comment]
The same issue has been a problem for me for ages.

**Comment by TheDrawingCoder-Gamer** [comment]
good news, #1818 will fix this if it's PR'd

**Comment by TheDrawingCoder-Gamer** [comment]
closed as #1825 is merged
