### ISSUE TITLE
[Issue] Can't delete groups

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#181]
Blockbench throws an error when trying to delete a group/bone.
![image](https://user-images.githubusercontent.com/29360565/48318664-3b109400-e604-11e8-9d9d-21395ad7ff9c.png)

**Comment by Gamebuster19901** [comment]
Temporary workaround: After you have clicked delete on the group, right click the group folder on the sidebar and press [Resolve], the group folder will now disappear.

**Comment by JannisX11** [comment]
Fixed in 2.2.
