### ISSUE TITLE
[Group keyframe editing] The ability to select multiple keyframes of the same type to edit them simultaneously

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#1810]
### Detailed description of your suggestion

There are multiple cases while animating where I'll have for example a set of rotations for a head to simulate bobbing. 
(example)
![image](https://user-images.githubusercontent.com/82787823/230675341-e59ac4b2-b5d5-4072-9221-cda43dcef602.png)

If I wanted to shift the rotation of the object in a certain direction, I would have to manually change each keyframe. 
With this suggestion, it would be possible to select multiple keyframes of the same type(ie rotation, position, scale) and move them in the animation window, and the change would be applied to all keyframes selected.

So if I were to select all the rotations as shown above for example, and shift the head +22.5 degrees on the x axis, all selected keyframes would gain +22.5 degrees of rotation on the x axis.(so 10 deg would go to 32.5, 15 deg would go to 37.5, etc.)

**Comment by JannisX11** [comment]
This is already possible. You can use the graph editor to move multiple keyframes at the same time. In addition, the labels next to the values in the Keyframe panel also act as sliders.
