### ISSUE TITLE
[Issue] not letting me animate (im on mobile)

### ISSUE THREAD

**Issue by Bruhman99** [JannisX11/blockbench#1813]
### Detailed description of your issue

It let's me paint and edit but not animate! This is REALLY annoying

### Model format in which the issue occurs

BlockBench

### Blockbench variant

Program

### Operating System

Mod maker for minecraft

**Comment by PaulFinnerty** [comment]
This Github repository is meant to report bugs, and suggest features.

If you need help with how Blockbench works, go make a post in the Discord https://discord.gg/blockbench, people can guide you (see the #how-to-get-help channel)
