### ISSUE TITLE
[Issue] Color Picking from second monitor always turns black

### ISSUE THREAD

**Issue by TMAAM** [JannisX11/blockbench#1815]
### Detailed description of your issue

So while trying to color pick using "Pick screen Color" it functions normally on my main monitor (a laptop), but when I use it to try and get a color from my second monitor, where I usually have my references, It just shows black no matter where on the screen I am with the cursor
I think it might be an issue with my laptop but dont know how I could fix it

### Model format in which the issue occurs

all

### Blockbench variant

Program

### Operating System

windows 11

**Comment by JannisX11** [comment]
Duplicate of #930
