### ISSUE TITLE
Extruding texture makes blockbench grey screened

### ISSUE THREAD

**Issue by Allfather492** [JannisX11/blockbench#1821]
### Detailed description of your issue

When i try to extrude a texture it makes my screen go grey. I try to extrude it in pixels to do some of the details but then it crashes and I have to exit the app,any fixes?

![Screenshot 2023-04-12 141728](https://user-images.githubusercontent.com/128399815/231575932-e5d8c4e8-0615-4f75-8ec4-6de87ae0642a.png)
![Screenshot 2023-04-12 142108](https://user-images.githubusercontent.com/128399815/231575961-48bc450b-4282-46a8-8ef2-e0ac4387099a.png)

### Model format in which the issue occurs

Java block/ item

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
Try with a smaller and lower-resolution image. It's possible that Blockbench ran out of memory by converting these probably thousands of pixels into cubes.
