### ISSUE TITLE
Screen turning wite

### ISSUE THREAD

**Issue by OlderCrafter** [JannisX11/blockbench#1826]
### Detailed description of your issue

the inner part of the screen thurns randomly wite
<img width="1920" alt="2023-04-16 (1)" src="https://user-images.githubusercontent.com/130909976/232313444-dca336e2-9f3d-4258-a314-d1c19c1d1a76.png">

### Model format in which the issue occurs

Moddet Entity

### Blockbench variant

Program

### Operating System

Windos 11

**Comment by JannisX11** [comment]
When or how often does this happen?

**Comment by OlderCrafter** [comment]
mostly when I switch from construction to drawing mode. but also occasionally when using the resize tool
