### ISSUE TITLE
[Issue] Deleting vertex doesn't appear to update model until moving it

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1827]
### Detailed description of your issue

4.7.0 beta 3

1) delete vertex
2) move model

https://user-images.githubusercontent.com/38400400/232323700-7a2cee34-b9ce-4521-b8b5-c1d2b910626c.mp4

### Model format in which the issue occurs

Generic model MESH

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
I cannot reproduce this issue. Are there any console errors?

**Comment by Magicmaan** [comment]
how would I check?

**Comment by JannisX11** [comment]
You'll see errors in Help > Developer > Error Log if there are any.

**Comment by Magicmaan** [comment]
https://pastebin.com/WHbZGMFy
2 errors and 2 warnings
