### ISSUE TITLE
[Issue] creating new face with shift+F then selecting other vertex causes it to offset

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1828]
### Detailed description of your issue

4.7.0 beta 3
select 3 or more vertexes and create new face with shift+F
select different vertex

https://user-images.githubusercontent.com/38400400/232323839-865714e7-ddcd-4231-b150-39a2bda22230.mp4

### Model format in which the issue occurs

Generic model MESH

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Is this still an issue?

**Comment by Magicmaan** [comment]
yes
