### ISSUE TITLE
[Issue] background image opacity resets to nearest whole number in context menu

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1829]
### Detailed description of your issue

4.7.0 beta 3

set opacity with bar to anything
double click to enter context menu
the opacity bar widget snaps to either end, without updating the value
upon exiting, the opacity changes but not the bar

https://user-images.githubusercontent.com/38400400/232323949-2df0be7a-60c1-44ba-aa55-e04a9f1541b1.mp4

### Model format in which the issue occurs

All / general model

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Fixed in 4.7.0
