### ISSUE TITLE
[Issue] spelling mistake in keybindings > edit

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1830]
### Detailed description of your issue

![image](https://user-images.githubusercontent.com/38400400/232323987-c12010e6-82ea-4cfe-952c-a65acb2c6933.png)

### Model format in which the issue occurs

All / general model

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Fixed in 4.7.0
