### ISSUE TITLE
Improve Privacy Policy for Use in Education

### ISSUE THREAD

**Issue by jeremybullock** [JannisX11/blockbench#1834]
### Detailed description of your suggestion

Hi there,

Thank you so much for making Blockbench.

I am trying to get Blockbench approved by my district for use in my school, but the privacy policy indicates that parental consent is needed for children under 13 to use the site because of data it collects.  It seems that Blockbench is fully capable of being used without any data being collected at all.  Is it possible to update the privacy policy with a more accurate description of whether or not data is collected and used?

Thank you,
Jeremy

**Comment by jeremybullock** [comment]
I've looked through the code a bit and don't quickly see any place where user data is being collected.  If this is accurate, it seems the current privacy policy is overly broad and could easily prevent users from being able to use it in organizations, especially schools.  

Could you verify that no personally identifiable data is being collected and perhaps discuss the option of updating the privacy policy? 

Thanks again.

**Comment by JannisX11** [comment]
Yeah, neither Blockbench nor the website collect any personal information. The privacy policy is just a precaution. I'll look into updating it.

**Comment by jeremybullock** [comment]
Thank you so much.  My district is really cautious with student data with security breaches at an all time high lately.  I really appreciate you taking a look.

**Comment by JannisX11** [comment]
I hope this helps
https://www.blockbench.net/privacy-policy

**Comment by jeremybullock** [comment]
Thank you so much!

**Comment by jeremybullock** [comment]
Hi again,

Thank you so much for your work on this.  My school district is still stuck on the language around children's data and consent.  The specific section is "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."

Since Blockbench doesn't collect student data, does that still need to stay in there?  I certainly understand the need to be careful and make sure the privacy policy is keeping you protected, but I wanted to ask if there is a chance to take a look at that section.

Thanks again.

**Comment by JannisX11** [comment]
You are right, that section is now redundant.
