### ISSUE TITLE
[Issue] I can't zoom in or out when i tap the hand in the paint tab online.

### ISSUE THREAD

**Issue by Parachute2004** [JannisX11/blockbench#1835]
### Detailed description of your issue

When I am editing an image when I press the little hand icon I can't do anything. Then when I try to edit a entity texture when I press the hand it just makes selection boxes when I try to zoom in. I'm using the mobile website.

### Model format in which the issue occurs

I don't know

### Blockbench variant

Website

### Operating System

I don't know

**Comment by JannisX11** [comment]
Fixed in web-only hotfix.
