### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by Cholin178** [JannisX11/blockbench#1837]
### Detailed description of your issue

HELP, I cannot save my work, both ctrl+s and doing it manually by clicking file>save model does not work, I cannot find any tutorial to fix this ;-;. I try to restart, but when I do ctrl+s it seems to be only capable of saving the png/texture, what should I do? It seems to be incapable os saving json file, nothing happened when I try to save. Specifically when it comes to json specifically, you know how Crt+s will automatically save your work as json, doing it manually is the same right? well nothing happened this time, I legit cannot save it as json for minecraft but can in any other kind of save file format. I am on Google Chrome browser.

Edit: I just tested it, this is the same case for the Blockbench app, it will only save the png.

### Model format in which the issue occurs

json

### Blockbench variant

Website

### Operating System

Windows 10

**Comment by Q2114** [comment]
Try going to your browser settings if you are using Chrome.
In the site settings there is a "Download automatically" or something like that. And just remove the blockbench from there. It usually helped me, I use an Android device.
![IMG_20230419_155309](https://user-images.githubusercontent.com/102694456/233081057-cf6a305e-0198-41ba-b576-05ea78fd9043.jpg)
![IMG_20230419_155254](https://user-images.githubusercontent.com/102694456/233081068-737b0d17-a6ea-45a0-8404-ce75df817d2e.jpg)
Or, try to download the ARCHIVE model.

**Comment by Cholin178** [comment]
I try it, and nope, this does not pixes it, I still cannot download/save json file.

**Comment by Cholin178** [comment]
Update, I figure out how to fixes it, fist open "privacy and security" setting> click "View permissions and data stored across sites"> look for Blockbench> click the trash icon to delete blockbench from permission record> reset> open blockbench> do some modeling ro load your project> press Ctrl+S> it will then download the png first but don't worry, a pop up will appear asking if it is allowed to download json model > click "Allow" and you shall haved your json file downloaded. Case SOLVED.
