### ISSUE TITLE
[Suggestion] Tooltips dynamic selection

### ISSUE THREAD

**Issue by teuszoio** [JannisX11/blockbench#184]
the selection mode needs an upgrade. the dynamic selection used in photoshop can also be applied.

**Comment by teuszoio** [comment]
maybe using shift + something

**Comment by JannisX11** [comment]
What exactly is the suggestion here? Is this a duplicate of https://github.com/JannisX11/blockbench/issues/180 ?

**Comment by teuszoio** [comment]
I had not read this other topic until I sent mine. but it's the same thing

**Comment by JannisX11** [comment]
Duplicate of #180
