### ISSUE TITLE
[Issue] Blockbench Gray Screening/Crashing when using scroll wheel

### ISSUE THREAD

**Issue by MidNite00** [JannisX11/blockbench#1840]
**Bug:** Blockbench turning entirely gray within seconds with no way to interact, the only option is to force-quit. 
**How to Reproduce Bug:** Open Blockbench, scroll in any menu or use scroll wheel in any way, instantaneous gray-screen.
**Platform:** Windows 10 (Most Recent Version)
**Version:** Blockbench 4.7.0
**Severity:** Makes Blockbench Unusable
**Errors:** None in Console

I made 2 GIFs, one shows me using the menu scroll bar with the scroll wheel and the other shows me attempting to zoom in on a new project file.

gyazo.com/b9ae4d1198a00777d904203d20f54179
gyazo.com/7dea3bcdfccc8258beb22f003e70b7f4

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by MidNite00** [comment]
Update: Restarting my PC, and Reloading all Pluggins/Blockbench has fixed it for the time being. I'm keeping this up as it's still a bug that can happen again, I assume.

**Comment by JannisX11** [comment]
This seems to be related to #1729.
It's most likely an electron issue, though I can't find other reports about it. And with no way to reliably reproduce it it's hard to debug.
