### ISSUE TITLE
[Issue] changing model format

### ISSUE THREAD

**Issue by K1NGANG0RR0T** [JannisX11/blockbench#1843]
### Detailed description of your issue

Modding Minecraft java 1.18.2 and I Changed the Model Format from Block to Modded Entity, It Messed up the Model, and the 
'selectin blocks' that the Users Use to Select Pixels weren't stacked, I know that Users Aren't able to stack them but it helped with the Models.

### Model format in which the issue occurs

4.5.0+

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
From what you have described this is probably an effect of the different restrictions that the formats have, and something that I can't fix.
