### ISSUE TITLE
[Issue] Using custom variables in anim-time-update blocks animation preview

### ISSUE THREAD

**Issue by AngeloVH** [JannisX11/blockbench#1845]
### Detailed description of your issue

I am using a custom variable in the anim-time-update, however after doing so animation won't preview anymore. Once you click on play the timeline glitches for a second and then sets back to 0. Allow anim-time-update to use variable placeholders?

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by PaulFinnerty** [comment]
what variable placeholder are you using specifically? I can use them just fine.
