### ISSUE TITLE
My blockbench the scaling does not working

### ISSUE THREAD

**Issue by CKFA** [JannisX11/blockbench#1846]
### Detailed description of your issue

As title mentioned, my blockbench unexpected not working by using cube scaling. How to solve it? Any Hotkey can fix it? Or is that bug? Many Thanks. 

![image](https://user-images.githubusercontent.com/59402813/234257807-b8f6ff45-64ad-44f8-ab10-3f7d466793b4.png)

### Model format in which the issue occurs

.bbmodel

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by CKFA** [comment]
It only appear in 4.7.0+ version. It works well in 4.6.4

**Comment by JannisX11** [comment]
Could you describe in more detail what you are trying to do and what happens instead? And attach a video?
