### ISSUE TITLE
[Issue] Cannot paint in viewport

### ISSUE THREAD

**Issue by KelianRD** [JannisX11/blockbench#1848]
### Detailed description of your issue

As the title says I cannot use the paint tool directly in the viewport as I have seen in tutorials, it only works in the left window.
I already asked for help on the discord server but they did not understand either.
There are no errors in the console

https://discord.com/channels/314078526104141834/1100545481291071611

https://user-images.githubusercontent.com/63228746/234536252-cb7218dc-72f2-4fae-9bb3-8e613f8fd8d9.mp4
![image](https://user-images.githubusercontent.com/63228746/234538008-ea660d91-ec22-4684-89ed-6d9ddeac759a.png)

### Model format in which the issue occurs

bbModel / Modded Entity

### Blockbench variant

Program

### Operating System

Windows

**Comment by JannisX11** [comment]
Did you try again after restarting your computer? Does the same issue occur in the web app as well, or only in the desktop app?

**Comment by KelianRD** [comment]
> Did you try again after restarting your computer? Does the same issue occur in the web app as well, or only in the desktop app?

Yes i tried restarting the computer and uninstalling - reinstall but its stays the same
Tho it works fine in the web app
