### ISSUE TITLE
[Issue] keyframe he's broken

### ISSUE THREAD

**Issue by teuszoio** [JannisX11/blockbench#185]
![image](https://user-images.githubusercontent.com/28912725/48517598-fc6e1a00-e84d-11e8-8543-2c9ac235cbf3.png)
![image](https://user-images.githubusercontent.com/28912725/48517607-0263fb00-e84e-11e8-91e7-c1c114e201a6.png)

**Comment by teuszoio** [comment]
it's jumping 30 seconds

**Comment by JannisX11** [comment]
What you got there is one second.

**Comment by teuszoio** [comment]
ops. realy. but the counter skips 30 milliseconds

**Comment by JannisX11** [comment]
Miliseconds are 1/1000th of a second. The unit I used in Blockbench is 1/30th of a second which is based the NTSC video standard that many video editors and 3D rendering programs use.
