### ISSUE TITLE
[Issue] FBX export incorrectly exports animations that alter positions

### ISSUE THREAD

**Issue by miyo6032** [JannisX11/blockbench#1853]
### Detailed description of your issue

When exporting to FBX (ascii), any animations that alter the position of a group will offset that group by too much. This was observed when importing the model into unity and verifying that animations. I fixed it for my purposes by removing the '* 100' from this line of code in js\io\formats\fbx.js. Not sure if that is the actual fix but maybe it is a starting point.
```
if (track.channel == 'position') {
	values.forEach((v, i) => values[i] = v * 100);
}
```

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Operating System

Windows

**Comment by JannisX11** [comment]
Fixed in 4.7.2 via https://github.com/JannisX11/blockbench/commit/ea402f5a7673edac51eee74462432955b14cd1db
