### ISSUE TITLE
[Issue] 'Minecraft Skin -> Model:Block' 3D model doesn't work

### ISSUE THREAD

**Issue by slightlyrandom** [JannisX11/blockbench#1854]
### Detailed description of your issue

When selecting New -> Minecraft Skin -> Model:Block the central 3D model starts up empty, and doesn't respond to painting being done in the top left Paint window, nor can painting be done on the 3D model.
Can get 3D model to obtain and change color by using the Paint Bucket in Paint window, but this doesn't fix the issue.

All other tested Models (Steve, Alex, Bat, etc.) seem to work fine.

Happens both on standalone version and website, both 4.7.1

### Model format in which the issue occurs

Minecraft Skin

### Blockbench variant

Website

### Operating System

Linux

**Comment by slightlyrandom** [comment]
Converting it to a Java Block/Item or Generic Model project seems to be a workaround

**Comment by JannisX11** [comment]
"Model:Block" is not a standard format in Blockbench. Are you using a plugin to add this?

**Comment by slightlyrandom** [comment]
![image](https://user-images.githubusercontent.com/3150475/235296130-0d45574d-8c88-4b2c-92b7-6344f2d0aae9.png)

**Comment by JannisX11** [comment]
Okay I see what you mean.
