### ISSUE TITLE
[Problem] Wrong download

### ISSUE THREAD

**Issue by LittleMissSunshineZ** [JannisX11/blockbench#1855]
### Detailed description of your issue

When I download Blockbench, it gives me an application and when I click on it, it downloads, but it's not a separate app. I have no way to access it or open it.
Attached is a photo when I actually downloaded it

![Screenshot 29 04 2023 23_22_55](https://user-images.githubusercontent.com/132169675/235324825-b331d7d6-db4e-4792-9f6f-fc1a1b5c03df.png)

### Model format in which the issue occurs

Blockbench 4.7.1

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
Did you download the installer, or the portable version? When you open the file you downloaded, does that open Blockbench? Are you using any third party antivirus software by any change? Some antivirus programs tend to quarantine downloaded executable files for no valid reason.

**Comment by LittleMissSunshineZ** [comment]
I have downloaded the installation program.
When I open the downloaded file, it opens Blockbench. But before that a window appears saying that Blockbench is being installed.
And yes I use an antivirus program, I will test if it works when I delete it.
I will let you know then

**Comment by LittleMissSunshineZ** [comment]
It does not work even with the antivirus program disabled.

**Comment by JannisX11** [comment]
Check if the program exists in `C:/Users/NAME/AppData/Local/Programs/Blockbench/Blockbench.exe` and the shortcut exists in `C:/Users/NAME/AppData/Roamnig/Microsoft/Windows/Start Menu/Programs/`. If it does, I have no idea why Windows would fail to list it in the start menu.

**Comment by LittleMissSunshineZ** [comment]
Ich habe Blockbench durch die Anwendung "Blockbench deinstallieren" deinstalliert und neu installiert und jetzt funktioniert es
