### ISSUE TITLE
[Problem] Texture missing

### ISSUE THREAD

**Issue by LittleMissSunshineZ** [JannisX11/blockbench#1856]
### Detailed description of your issue

If I want to make a block transparent, I can't because the corresponding field is missing.

Here is a photo of it
![blockbench issue](https://user-images.githubusercontent.com/132169675/235325191-ab8bd467-f8f8-42f2-8a69-742fe6e3e609.png)

### Model format in which the issue occurs

Blockbench 4.7.1

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
You can make it invisible by clicking the eye icon in the outliner.

**Comment by LittleMissSunshineZ** [comment]
But I want to have the block visible, just transparent

**Comment by JannisX11** [comment]
I suppose you can go into the UV editor, switch to Face Properties, and disable all faces.

**Comment by LittleMissSunshineZ** [comment]
I have found a way, now it works

**Comment by LittleMissSunshineZ** [comment]
Thank you
