### ISSUE TITLE
Recommended Build with Inno Setup to Install the package

### ISSUE THREAD

**Issue by NebulaTechs** [JannisX11/blockbench#1858]
### Detailed description of your suggestion

Recommended Build with Inno Setup · Install the package ,Because this allows you to switch the installation path

**Comment by JannisX11** [comment]
Your suggestion is to be able to specify the installation path when installing Blockbench, and you would recommend Inno to create the installer. Is that correct?

**Comment by JannisX11** [comment]
Duplicate of #1884
