### ISSUE TITLE
Iphone not loading blockbench

### ISSUE THREAD

**Issue by Furballllllll** [JannisX11/blockbench#1859]
### Detailed description of your issue

I was trying to figure out how to make a homescreen bookmark for my iphone 12 and I loaded the online version a couple of times and it worked fine. But one time I loaded it and it was just blank. I kept trying to reload it and I already tried turning my phone off and on again and disconnecting from my wifi but it won't load. Every other site will load. Does anyone know how to fix this? Thx

### Model format in which the issue occurs

None

### Blockbench variant

Website

### Operating System

Iphone 12

**Comment by JannisX11** [comment]
Try and clear your browser cache.
