### ISSUE TITLE
Preview skin overlay is too big

### ISSUE THREAD

**Issue by Francy-Chan** [JannisX11/blockbench#186]
The skin overlay in preview is bigger than In-game.
It's happening for both arms and legs.
I'm not sure if it's occur with head or body.

![TheBug](https://user-images.githubusercontent.com/40085587/48585899-3f46f500-e915-11e8-95a7-9f053ad72fa0.png)

- Blockbench 2.1.0 Desktop
- Windows 10

**Comment by JannisX11** [comment]
Fixed in 2.2.
