### ISSUE TITLE
[Issue] Blockbench does not work on version 4.7.2 on Windows 7

### ISSUE THREAD

**Issue by ItzDfyz** [JannisX11/blockbench#1867]
### Detailed description of your issue

After updating Blockbench to version 4.7.1, it stopped running on Windows 7 giving the following error:
"Access point in DiscardVirtualMemory procedure not found in DLL KERNEL32.dll"
And older versions work flawlessly

### Model format in which the issue occurs

4.7.2

### Blockbench variant

Program

### Operating System

Windows 7 64bit

**Comment by JannisX11** [comment]
On the download page under system requirements Windows 10 is listed as a minimum requirement. There is also a special section on how to get Blockbench working on Windows 8 and 7.
https://www.blockbench.net/downloads
