### ISSUE TITLE
Mobel site does not let the user add a textureI

### ISSUE THREAD

**Issue by E34222** [JannisX11/blockbench#1871]
### Detailed description of your issue

In The mobile site for Android   the textures tab stays to far over and the user cannot drag the textures tab more overol to add or select textures 

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Website

### Operating System

Andriod

**Comment by JannisX11** [comment]
I do not understand this description. Please describe the issue in more detail. Screenshots can also help.
