### ISSUE TITLE
Help fix to bug

### ISSUE THREAD

**Issue by enot12345** [JannisX11/blockbench#1874]
### Detailed description of your issue

Help!!!
I was just drawing in Blockbench and at one point I seem to have pressed either a button or a combination of keys and now I can't narmally use tools such as:
-Create a bone
-Create a cube
and more.
![2023-05-10_19-08-12 (2)](https://github.com/JannisX11/blockbench/assets/133141291/3ccf3922-b25c-4c29-a336-09c265fb3dd1)

I will explain in more detail:
When creating a bone, it is not visible in the panel
The cube can only be created by adding a key
Maybe there's just a way to reset the app to the initial settings?
Tell me what to do.

### Model format in which the issue occurs

?

### Blockbench variant

Program

### Operating System

Windows

**Comment by JannisX11** [comment]
You have folded some of your sideebar panels like Outliner. And currently your UV Editor and Outliner are folded, and the outliner is in the bottom left, while it's usually in the bottom left.

You can unfold them by pressing the upwards arrow button next to them. And you can reset the layout by going Tools > Action Control (F) > Reset Layout.
