### ISSUE TITLE
cant adding groups or blocks

### ISSUE THREAD

**Issue by Lazarusk15** [JannisX11/blockbench#1875]
### Detailed description of your issue

hello i want to report and issue when i try adding group or blocks it doesnt let me 

### Model format in which the issue occurs

enderman

### Blockbench variant

Program

### Operating System

windows 11

**Comment by JannisX11** [comment]
"enderman" is not a valid format. You can find the format in File > Project > Format.

**Comment by antoine-hnkx** [comment]
@Lazarusk15 I'm guessing you are using the CEM Template Loader plugin.

You cannot add new root groups or root elements/cubes, this is a limitation with Minecraft/Optifine Custom Entity Models (CEM), so the plugin/Blockbench prevents you from doing so. If you want to add something to the model you have to first select an existing group and put you new group or element/cube inside of it.

You can find all CEM limitations here: https://optifine.readthedocs.io/cem_limitations.html
And here is also a good introduction to Optifine's CEM by the creator of the CEM Template Loader plugin (Ewan Howell): https://www.youtube.com/watch?v=arj2eim42KI (The limitation is mentioned at [5:39](https://youtu.be/arj2eim42KI?t=339))
