### ISSUE TITLE
Mirror Painting paints double the brush size on the other side in Java Entity models

### ISSUE THREAD

**Issue by shinycosmic** [JannisX11/blockbench#1876]
### Detailed description of your issue

When I turn on mirror painting, and paint with a 1 pixel size brush, it paints a 2x2 spot on the other side. This only seems to happen in the Java Entity Format

### Model format in which the issue occurs

Java Entity Format

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
Fixed in 4.8.
