### ISSUE TITLE
Cant add or remove groups or blocks

### ISSUE THREAD

**Issue by Shadow7800** [JannisX11/blockbench#1877]
### Detailed description of your issue

Hello, I wanted to report an issue with adding groups or blocks on new or old models. I have been working on one of my own models and the problem occurred I tried creating another mob model but the same problem appeared.

### Model format in which the issue occurs

Optifine entity

### Blockbench variant

Program

### Operating System

Windows 10 Home

**Comment by JannisX11** [comment]
What are you trying to do, and what happens instead? Can you access the buttons to add groups and cubes? Does it give you an error message?
Also, do you have the CEM Template Loader plugin installed?

**Comment by Shadow7800** [comment]
I am trying to add a new or remove an old group and add a block in it, but a message appears which says: ,, You cannot remove root cubes/groups". I just tried to add a group from the top tools Edit and it added the group. So I kinda I guess solve it. But the right side button for adding groups or blocks doesn't allow to add and the same message appears as I mentioned previously.

**Comment by JannisX11** [comment]
This restriction is added by the CEM Template Loader plugin. And it is intentional, since Optifine models only work with the predefined set of root groups and do not support root cubes at all.
