### ISSUE TITLE
Textures missing/garbled

### ISSUE THREAD

**Issue by IkuraG** [JannisX11/blockbench#1879]
### What are you trying to do, and what do you expect to happen?

I created a model in blockbench and saved it. I expected the model to look the same when I reopened it later.

### What happens instead?

When I re-opened that file my model has a messed up texture. I am including an image of that.
Also, I can no longer import my packages into minecraft.

![image](https://github.com/JannisX11/blockbench/assets/133543316/13dcec4c-64a4-496f-85e3-c09c797fe816)

### Model format in which the issue occurs

4.7.2

### Blockbench variant

Program

### Operating System

Windows 11

### Installed Blockbench plugins

Minecraft Entity Wizard. Minecraft Block Wizard

**Comment by JannisX11** [comment]
Is this the correct texture, or a different texture?
Which format did this happen in? 4.7.2 is a version number, not a format.
Could you attach your resource and behavior pack so that I can see what happened?
