### ISSUE TITLE
[Suggestion]moving the bones is different from moving a cube

### ISSUE THREAD

**Issue by teuszoio** [JannisX11/blockbench#188]
![image](https://user-images.githubusercontent.com/28912725/48676322-4277f600-eb4c-11e8-9d0d-3ca08137e4ff.png)
![image](https://user-images.githubusercontent.com/28912725/48676336-8965eb80-eb4c-11e8-8ce6-314c1998511a.png)
![image](https://user-images.githubusercontent.com/28912725/48676367-ee214600-eb4c-11e8-833b-b05964d9df71.png)
enter the position of the bone, distorts the position of the cubes

**Comment by JannisX11** [comment]
Entering a number into the text field changes the position of the lower north west corner of the cube. Since it is a fix number, it will set the Y coordinate of all selected cubes to the same value resulting in both cubes ending up on the same height.
