### ISSUE TITLE
FPS Limit Setting

### ISSUE THREAD

**Issue by tavurth** [JannisX11/blockbench#1880]
### What are you trying to do, and what do you expect to happen?

While using on mac I would expect the Blockbench app to use little CPU especially if I'm not currently looking at the window.

### What happens instead?

A very high CPU usage:

<img width="735" alt="Screenshot 2023-05-15 at 18 00 59" src="https://github.com/JannisX11/blockbench/assets/100964/ce9f0691-de9d-40b6-bc1c-330de96f37af">

Perhaps adding some way to limit the FPS in preferences?

Then this could be then used when the window loses focus (lower FPS to 5 or some low number)

### Model format in which the issue occurs

Render

### Blockbench variant

Program

### Operating System

OSX

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
There is actually a setting called "Background Rendering" that can be disabled to prevent rendering when the window is not in focus.
How many elements do you have in your project while the CPU performance is at 26%?

**Comment by tavurth** [comment]
> How many elements do you have in your project while the CPU performance is at 26%?

Just a single untextured cube

**Comment by tavurth** [comment]
> There is actually a setting called "Background Rendering" that can be disabled to prevent rendering when the window is not in focus.

Thank you this setting seems to help in general!

**Foreground:**
<img width="1440" alt="Screenshot 2023-05-16 at 10 18 07" src="https://github.com/JannisX11/blockbench/assets/100964/341bbe6c-6667-4c40-bb3f-5af87774dbd5">

**Background:**
<img width="1440" alt="Screenshot 2023-05-16 at 10 18 29" src="https://github.com/JannisX11/blockbench/assets/100964/28ca111b-d46a-4a07-966c-6d9feba8204f">

Would be cool to see a `limited FPS` option, I would much rather run at 40 fps and have my mac run cooler and save battery.

**Comment by goshki** [comment]
I'm experiencing a similar issue on a 2017 MBP with an Intel Iris 640 GPU but in my case Blockbench is heavily taxing GPU (even up to 80%) and sometimes can't keep up rendering at 60 FPS. My model has 1400 vertices and 700 triangles – I'm not sure if that's a high polygon count for Blockbench standards.

But the point is, I'd also love to see some kind of an FPS limiter because I'm mostly working with geometry/textures.

**Comment by hablethedev** [comment]
This would be very cool to see - no need for Blockbench to run at 144 fps and make my fan go brrrr...
