### ISSUE TITLE
i found 2 bugs in blockbench

### ISSUE THREAD

**Issue by SteelTigerV2** [JannisX11/blockbench#1887]
### What are you trying to do, and what do you expect to happen?

1: if i rename a model in file explore it shows old name in blockbench

2: renamed in file explore models have problems with saving uv mapping

### What happens instead?

1. shows first name given

2. i have to redo mapping

### Model format in which the issue occurs

bbmodel

### Blockbench variant

Program

### Operating System

windows 10

### Installed Blockbench plugins

none

**Comment by JannisX11** [comment]
Yeah that's normal and something I won't fix. If you move or rename the file that you are editing while it's open in Blockbench, then it won't know where to save changes to.
