### ISSUE TITLE
Brushes and Eraser in UV View Non-Functional as of 4.7.3

### ISSUE THREAD

**Issue by beanrollup** [JannisX11/blockbench#1890]
### What are you trying to do, and what do you expect to happen?

**Action:** Using the paint brush and eraser on the UV view
**Expected Result:** The paint brush behaves the same way it does on the model

### What happens instead?

**Actual Result:** Painting and erasing works on the model as expected, but not on the UV view. The Clone Brush also doesn't work.

(Also worth noting - the fill, gradient, color picker, draw shape, and selection tools work as expected on the UV and there isn't an issue with those).

Confirmed to be non-functional on all model formats - only tested in the program and the website, not sure about PWA.

Video: https://github.com/JannisX11/blockbench/assets/69904813/3521713f-a337-41da-8161-3b6fc437a11c

Screenshot *(Provided by dragonmaster95)*:
![4 7 3 Console Issues](https://github.com/JannisX11/blockbench/assets/69904813/1a944867-ae83-4496-889f-c0c480991096)

### Model format in which the issue occurs

All formats

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

Entity Wizard, Block Wizard, Colour Gradient Generator, Animation Sliders, Code View

**Comment by JannisX11** [comment]
Fixed in 4.7.4
