### ISSUE TITLE
Cannot add reference images when viewport is orthographic 

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1891]
### What are you trying to do, and what do you expect to happen?

When I try add a reference image to a model, whether through my clipboard or by uploading it directly, it usually works fine. But I've noticed after 4.7.3 that I cannot add reference images to models when I have orthographic mode enabled

### What happens instead?

Reference image is not added at all, only works if I leave orthographic mode first and then add the reference image.

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Operating System

Windows 11

**Comment by JannisX11** [comment]
I cannot reproduce this issue. Are there any console errors? Does it list the image when you press the List button in the toolbar at the top?

**Comment by pixelstoriez** [comment]
Here's a video showing what happens when I try to add reference images in orthographic mode. There is no console errors from what it looks like but the image does show up when I press the List button
https://github.com/JannisX11/blockbench/assets/68472867/8c933ae8-8676-40b9-afbb-f8882b73ea39

**Comment by JannisX11** [comment]
Thats helpful, thanks!
