### ISSUE TITLE
[Suggestion] Improvement when exporting java modded entity

### ISSUE THREAD

**Issue by HungTeen** [JannisX11/blockbench#1892]
### Detailed description of your suggestion

When export modded entity with Forge 1.17+ (Mojmaps) format, the blockbench template will only automatically generate the root 'ModelPart', but at most of time modders need manually add a lot of child 'ModelPart' which is waste time.
So **I wish blockbench can automatically generate all 'ModelPart' fields**, and get their value from constructor param named 'root' by 'getChild' method.
The related code is at [https://github.com/JannisX11/blockbench/blob/master/js/io/formats/modded_entity.js#L248](url).
Like this:
![image](https://github.com/JannisX11/blockbench/assets/46000045/57c35656-3870-42a8-a812-44e369fe36d1)

**Comment by JannisX11** [comment]
@SizableShrimp what is the reason that these are no longer generated? Should we add this as an export option?

**Comment by SizableShrimp** [comment]
@JannisX11 It's been a while since I wrote this, but it probably just came down to complexity, so I didn't bother. Adding this back as the default would probably be good.
