### ISSUE TITLE
[Suggestion] A new keybind and option in the "View" tab to quickly toggle visibility of the grids

### ISSUE THREAD

**Issue by TheLaddd** [JannisX11/blockbench#1896]
### Detailed description of your suggestion

There should be a new keybind and a option in the "View" tab to quickly toggle the flat grids that appear below the model (Small Grid, Block Grid, and Precise Block Grid). Quick options and keybinds already exist for toggling the ground plane and painting grid, but none exist for the standard grids below the model.

Rather than adding individual options and keybinds for all three grids, there can be a singular option/keybind that toggles the visibility of all three at once rather than outright toggling them in the settings. This would preserve the specific grids that are enabled in "Settings" while introducing the option to quickly toggle their visibility in the viewport.

Alternatively, there could be individual options and keybinds for each of the three grids, but that would be rather tedious.

Concept as an example:
![image](https://github.com/JannisX11/blockbench/assets/97115421/7a5cd2b3-6e61-4ea0-8ddd-50303676feb5)

**Comment by JannisX11** [comment]
Added in 4.8.
