### ISSUE TITLE
In Display Mode, switching tab causes camera to stay locked if in GUI slot

### ISSUE THREAD

**Issue by antoine-hnkx** [JannisX11/blockbench#1901]
## Context:
- In a Java Block/Item Model > Display, there are Display Slots for each view of the item (thirdperson left/right, firstperson, gui, etc.)
- On the Display Slot "GUI" the Z axis is locked for convenience since Minecraft's GUI is in 2D.
- If you have 2 models open, changing back and forth will reset the currently selected Display Slot to the first slot (Thirdperson Right)

## Expected behaviour:
- When switching back to a model where you last were on the GUI slot, it should reset the slot to 'Thirdperson Right' and the camera should be unlocked on the Z axis since we are not on the GUI slot anymore

OR

- When switching back to a model where you last were on the GUI slot, it should not reset to the 'Thirdperson Right' slot and remember the slot you were on.

### What happens instead?

- When switching back to a model where you last were on the GUI slot, it resets to the first slot (Thirdperson Right) BUT the camera is still locked on the Z axis as if it was still on the GUI slot.

### Model format in which the issue occurs

Java Block/Item but potentially occurs with other formats

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

CEM Template Loader, Texture Stitcher

**Comment by andriantorian880** [comment]
button disappears

**Comment by JannisX11** [comment]
Fixed in 4.9.
