### ISSUE TITLE
Extremely High CPU Usage and Low FPS

### ISSUE THREAD

**Issue by Rise0956** [JannisX11/blockbench#1904]
### What are you trying to do, and what do you expect to happen?

I am basically modeling, as what everyone does.

### What happens instead?

 after updating Blockbench aboutaround Late May to Early June 2023, I reopened a project after moving all of them to my SD Card, and even though the Model Project I am working on was running smoothly before the update, It seems after the update, or after I moved my BBModel File and the other assets to My SD Card, CPU Usage Jumped to 100% and Memory Usage was over 50% on my computer. it's not a bad Computer either, sure it isn't top of the line, but that's not important. Even when I hide everything in the model, the FPS May still be below 10, at most at 25fps, rarely. 30 fps is ok, but it rarely gets that high. 

My idea is that something with the update, or more likely, the fact that the assets are on my  MicroSD Card, Is causing Blockbench to use more of my computers Resources, even when model is hidden. also no Preview scene, shading, or Ground Plane is active. after a LONG While it will go up, but only to about 35-42 before going back to ~24 or lower.

### Model format in which the issue occurs

Bedrock Model Format (Non legacy).

### Blockbench variant

Program

### Operating System

Windows 11

### Installed Blockbench plugins

"Animation Sliders" by JannisX11, "Optimize" by Krodi, "Preview Scene Customizer" and "Plugin Loader 2.0" by Ewan Howell,

**Comment by JannisX11** [comment]
Try and install the Performance Audit plugin and use it via the Help menu. It should give you some details on what is limiting your performance.
