### ISSUE TITLE
Problem with texture coloring when using the pixel brush

### ISSUE THREAD

**Issue by Lil020** [JannisX11/blockbench#1907]
### What are you trying to do, and what do you expect to happen?

Texturing with the basic pixel brush on an entity. I was expecting a fully solid color in the area I was painting.

### What happens instead?

Some sort of color dithering messes up my uniform color. There are spots of color that are close but not the same color as I was using. It makes it really hard to use the paint bucket tool when not all the colors are perfectly matching. I reloaded blockbench multiple times, and factory reset a few times. Didn't seem to fix it. Especially visible on grey color. I attached some images of my models having this problem.

![Screenshot_20230613-174848_Samsung Internet](https://github.com/JannisX11/blockbench/assets/136511850/10ab738e-1586-4141-8444-254cdb723ce6)
![Screenshot_20230613-175104_Samsung Internet](https://github.com/JannisX11/blockbench/assets/136511850/69f178d7-0570-4d70-ba1d-4ca1be0b78f5)

### Model format in which the issue occurs

Bbmodel. Bedrock entity

### Blockbench variant

Website, Program

### Operating System

Android 12, Chrome OS, Chrome web browser, Microsoft edge mobile browser(mostly mobile)

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Where does the dithering occur? On areas that you painted with a brush? On areas that you painted with a fill tool? Or does it appear on some areas while you are editing other areas of the texture?

**Comment by Lil020** [comment]
Only where I have painted on mobile. I wasn't too sure about the the paint bucket. It may have been just fine previously. Because it seems normal today. This only occurs in paint mode. Nothing to do with editing or animating. At this point I just use it on my computer when I'm at home. It's just fine on my pc. This problem may be my phones issue with the screen. I have it on vivid lighting.

**Comment by Tyxaar** [comment]
![Image](https://github.com/user-attachments/assets/39a5dd5c-9833-474d-92d6-0312ca016f2f)
I've also had this issue. I'm using Blockbench on firefox browser, on windows 11. There seems to be no option that can fix this.

**Comment by Tyxaar** [comment]
Posting here to reiterate that this is still an issue. When attempting to make a skin today, I encountered this problem blocking out an area. Again, I'm on firefox with windows 11 on the latest browser version of blockbench.

<img width="837" height="548" alt="Image" src="https://github.com/user-attachments/assets/d6d26835-512e-4296-a25b-b1c2f7a18037" />

**Comment by JannisX11** [comment]
It's an upstream issue in the respective web browser, not an issue in Blockbench itself. So you can fix it by using a different web browser, at least on computers.
