### ISSUE TITLE
Plugin not showing and not working

### ISSUE THREAD

**Issue by FuntimeRedbear** [JannisX11/blockbench#1912]
### What are you trying to do, and what do you expect to happen?

i was trying to make a model as I usually do 

### What happens instead?

some reason my plugin's that i have installed were not in the app nor in the available section and installed the new version of blockbench and I don't know what to do

### Model format in which the issue occurs

nothing 

### Blockbench variant

Program

### Operating System

 Processor	AMD Ryzen 5 4500U with Radeon Graphics            2.38 GHz Installed RAM	8.00 GB (7.37 GB usable) Device ID	00288BB8-A86A-43CF-8CF3-A87ECF3D29F5 Product ID	00325-82103-12428-AAOEM System type	64-bit operating system, x64-based processor Pen and touch	Pen and touch support with 10 touch points and Edition	Windows 11 Home Version	22H2 Installed on	‎10/‎7/‎2022 OS build	22621.1848 Serial number	INVALID Experience	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by JannisX11** [comment]
Are you in Egypt? Egypt recently broke Blockbench plugins.
https://twitter.com/blockbench/status/1667898475218911233
