### ISSUE TITLE
OBJ Model not Being Opened or Loaded (Imported)

### ISSUE THREAD

**Issue by Xinvon207** [JannisX11/blockbench#1913]
### What are you trying to do, and what do you expect to happen?

Im expecting it to show the OBJ model and Be the corrent size.

### What happens instead?

When I want to import a OBJ Model it does not either Show the Mesh or does not Import it or loads as a mesh. or even shows it at all. If you can fix this bug please.

### Model format in which the issue occurs

It does Not show the Model

### Blockbench variant

Website

### Operating System

Windows 11

### Installed Blockbench plugins

none

**Comment by JannisX11** [comment]
You need to attach the model.
