### ISSUE TITLE
cut off protruding edges from blocks

### ISSUE THREAD

**Issue by AlexDerProGamer** [JannisX11/blockbench#1914]
Tool to cut the edges so there is no residue

![image](https://github.com/JannisX11/blockbench/assets/111710468/6ee90edb-72d0-4f00-801d-2c3175fac823)

Sorry for my bad english

**Comment by JannisX11** [comment]
I assume you are using cubes. In that case, there is nothing you can do, except delete the pixels on the texture. Cubes can only be resized, not deformed.
For dynamically shaped elements, use meshes.
