### ISSUE TITLE
[Suggestion] Layouts

### ISSUE THREAD

**Issue by GronyRalph** [JannisX11/blockbench#1918]
### Detailed description of your suggestion

Hi Jannis, I think this could be pretty useful for more efficient workflow, for example in Adobe Premiere Pro, there's buttons at the top of the screen known as "workspace tabs" or "panels." These tabs allow you to quickly access different panels or windows within the software for specific tasks.
Just saving and loading the window sizes and position would be awesome, have a nice day :)

At least a reset layout button, please

**Comment by JannisX11** [comment]
You can find Reset Layout under Help > Developer, or in Tools > Action Control.

Blockbench already has separate Interface Modes for different tasks, such as Edit, Paint, Animate. Which other functionality are you currently missing with this system?
