### ISSUE TITLE
[Issue] Skin preview is broken when the skin has only one layer

### ISSUE THREAD

**Issue by jimchen5209** [JannisX11/blockbench#192]
Using blockbench desktop app version 2.1.0 on Windows 10 Home version 1803

I was changing the display skin in preview setting, when I change in to some player's skin which only has one layer, the preview is broken.
If I use the skin which has two layers, it previews normally.

Skin which has only one layer:

> Used skin player: MHF_Herobrine
> It suppose to be: Herobrine
> Screenshots:
> ![default](https://user-images.githubusercontent.com/10269287/49232482-f9b71b80-f42e-11e8-9596-79b9a11a61a8.png)
> ![default](https://user-images.githubusercontent.com/10269287/49232500-050a4700-f42f-11e8-82e1-da1a906fdd39.png)

Skin which has two layers:
> Used skin player: jimchen5209
> Screenshot:
> ![default](https://user-images.githubusercontent.com/10269287/49233068-21f34a00-f430-11e8-92c7-9c392e5ff416.png)

**Comment by JannisX11** [comment]
The skin you tested uses the old skin mapping system. Generally, skins without layers are supported but they have to be in the new post 1.7 format. There are no plans to support the old format.

**Comment by Luke18033** [comment]
Can the old skin layout please be supported? I use it sometimes for compatibility with older versions of the game, but that means Blockbench won't render my skin properly. I doubt it would be very difficult to add support for this - just check the image dimensions, if it's the old size then disable the secondary layers, and mirror the right arm/leg for the left ones.

**Comment by JannisX11** [comment]
> Can the old skin layout please be supported? I use it sometimes for compatibility with older versions of the game, but that means Blockbench won't render my skin properly. I doubt it would be very difficult to add support for this - just check the image dimensions, if it's the old size then disable the secondary layers, and mirror the right arm/leg for the left ones.

Just to make sure, are you talking about skins in display mode or about the skin editor?

**Comment by Luke18033** [comment]
The display preview. I didn't even know there was a "skin editor", I'm assuming that's for Bedrock entities or something?

**Comment by JannisX11** [comment]
There is a skin editor that works for both Minecraft editions and for both skins and most entities.
I definitely won't be adding support for the old skin format in display mode.

**Comment by Luke18033** [comment]
Why not, is it really that difficult?
