### ISSUE TITLE
[Suggestion] Curves

### ISSUE THREAD

**Issue by GronyRalph** [JannisX11/blockbench#1921]
### Detailed description of your suggestion

It'd be helpful, we have something similar with smooth proportional editing but unironically as its name suggest doesn't keep proportions on what it modifies, for now I figured out this is already possible by making a vertical plane, drawing the line, then extruding it and removing the unnecessary but it's not efficient, anyway hope you consider it :D 
I'll attach a video showing it in-depth and pictures of the idea, thanks, have a nice day!
https://github.com/JannisX11/blockbench/assets/56495047/fdfae846-be67-4e46-80f9-f4449fdb7d2b
![image](https://github.com/JannisX11/blockbench/assets/56495047/14726ec6-5ada-420a-affc-fe682fad43ff)

**Comment by GronyRalph** [comment]
I noticed they're called splines

**Comment by JannisX11** [comment]
This is probably out of scope for Blockbench.

**Comment by GronyRalph** [comment]
> This is probably out of scope for Blockbench.

How about making extrusions keep the angle they had if a vertex was modified, I mean instead of this:
![Sin título](https://github.com/JannisX11/blockbench/assets/56495047/1a588385-d612-4b27-9b62-c984672ed783)
I can't get it right but something like:
![Sin título(1)](https://github.com/JannisX11/blockbench/assets/56495047/323ac065-24b4-4769-9ce9-b49bdfeda8f7)
Just extruding in the angle it had I think'd get the job done, or is there already a way to do this?

**Comment by Azagwen** [comment]
I kind of agree that this would be useful, but mostly for tubular meshes.
I once modeled pipes in Blockbench, but without curves you need to carefully extrude each segment or spawn a lot of "construction" meshes to have perfectly shaped turns.

But it would be one of the only use for curves, so unsure if it's worth it

**Comment by JannisX11** [comment]
Closing this as #2313 suggests an approach that fits into Blockbench better.
