### ISSUE TITLE
quick color picker feature

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#1922]
### "Quick Color Pick" Keybind

a simple keybind option for a "quick color pick" where on click, blockbench will select the color that is currently under the cursor(weather in the texture editor or the 3d editor) like the normal color picker, but without switching to the color picker tool. (A similar feature exists in the program Aesprite for reference)

Example scenario:
A user will be texturing a surface with a handful of colors, they can hover their mouse over a previously used color and press the quick color pick button, for example "Q", and quickly switch to that color and continue using the brush tool uninterrupted.

This would be a nice qol feature, as I find myself many times switching to color picker to pick a color, and then switching immediately back to continue brushing, and a feature like this would eliminate a commonly unnecessary step.

**Comment by PaulFinnerty** [comment]
If you assign the color picker key to a modifier key (like shift, alt or control) + Left Click, you can already do that.

**Comment by JannisX11** [comment]
Already exists via Alt key.
