### ISSUE TITLE
When I undo the UV skin, it completely breaks

### ISSUE THREAD

**Issue by IshuCute** [JannisX11/blockbench#1925]
### What are you trying to do, and what do you expect to happen?

i just press ctrl+z to undo action

### What happens instead?

UV of model completely breaks.

### Model format in which the issue occurs

customizable player models

### Blockbench variant

Program

### Operating System

windows 10

### Installed Blockbench plugins

customizable player models

**Comment by IshuCute** [comment]
this what happens 
![image](https://github.com/JannisX11/blockbench/assets/119164425/9df906a7-548a-42f1-897c-83bdbd2e9ddf)

**Comment by JannisX11** [comment]
That might be an issue with the plugin you listed. Where did you download the plugin from?

**Comment by IshuCute** [comment]
from authors link (https://tom5454.com/cpm/cpm_plugin.js)

**Comment by JannisX11** [comment]
Yeah I cannot reproduce the issue. It might be an issue with the plugin, or something that only happens with your specific model or something specific that you did.
