### ISSUE TITLE
blockbench plugins not available offline

### ISSUE THREAD

**Issue by princessaylana** [JannisX11/blockbench#1928]
### What are you trying to do, and what do you expect to happen?

it seems I have to be online to use my plugins, else they dont show. 
can we make it so the app downloads the plugins to disc?

using linux kde neon

### What happens instead?

my plugins doesnt show when offline from the internet.
cant use any plugins when not on the internet.

### Model format in which the issue occurs

not sure

### Blockbench variant

Program

### Operating System

KDE Neon 5.27

### Installed Blockbench plugins

geckolib, fabric modded entity, etc

**Comment by JannisX11** [comment]
Fixed in 4.8.
