### ISSUE TITLE
'Texture' menu shows a small white box which has no options

### ISSUE THREAD

**Issue by orliesaurus** [JannisX11/blockbench#1929]
### What are you trying to do, and what do you expect to happen?

When users click on the ‘Texture’ option, they might observe a small white box appearing, which indicates a display issue. It seems that the options related to “Texture” are not being displayed correctly.

### What happens instead?

White texture are showing up. Check the evidence [![Dashcam - Dashcam](https://community.bugbashes.com/uploads/default/original/1X/c7fe9dda9ec3e7bca6c3f386db6825f5ce419a8e.gif)](https://app.dashcam.io/replay/645b7032d003090064cbfe3f?share=mnr8NSr1iWSE6jBt7MuJw) 
  
Watch [the full clip here](https://app.dashcam.io/replay/645b7032d003090064cbfe3f?share=mnr8NSr1iWSE6jBt7MuJw) on Dashcam

### Model format in which the issue occurs

na

### Blockbench variant

Program

### Operating System

platform darwin distro macOS release 13.3.1 codename macOS Ventura

**Comment by JannisX11** [comment]
This is entirely normal. An empty box indicates an empty menu, which is to be expected since no texture exists.
