### ISSUE TITLE
Block bench does not layout uv's evenly when model is semetric

### ISSUE THREAD

**Issue by Shadowblitz16** [JannisX11/blockbench#1930]
### What are you trying to do, and what do you expect to happen?

I was trying to follow the snake tutorial for block bench on youtube and I released the block bench does not layout the left and right side of the model the same way even if the vertices are the exact signed opposite

### What happens instead?

It seems to generate the left side different then the right side
![image](https://github.com/JannisX11/blockbench/assets/2453707/0f381ce7-efc9-4367-a355-96ba03c4152a)

### Model format in which the issue occurs

generic model

### Blockbench variant

Program

### Operating System

kubuntu 22.04

### Installed Blockbench plugins

Default

**Comment by JannisX11** [comment]
Could you attach the model where this happens?

**Comment by Shadowblitz16** [comment]
I don't have the model with me now but I have this one where it happens
[models.zip](https://github.com/JannisX11/blockbench/files/11952816/models.zip)

Just take the green uv's and flip them and try to align them with the red uv's they don't match up.
And it's not just a position problem each individual uv are in different offsets to eachother

**Comment by JannisX11** [comment]
I used mirror modeling to make sure the model is symmetric, and tested this again in 4.9. Looks like the issue is resolved.
