### ISSUE TITLE
Add pixel perfect option

### ISSUE THREAD

**Issue by Shadowblitz16** [JannisX11/blockbench#1932]
### Detailed description of your suggestion

Please add a option in the either the block bench settings or the project settings which forces all operations to snap to the nearest pixel.

This means all tools such as translate, rotate, scale and offset snap vertices to the nearest pixel
This also applies for uv's  and uv generation, and context options like extrude, inset, loop cut and merge vertices

**Comment by JannisX11** [comment]
This is already the default behavior of all tools in Blockbench. Of course, on more complex models there are some exceptions to ensure that tools work as expected.
Can you name a more specific problem that you are trying to solve?
