### ISSUE TITLE
Animation tab not working in edit session, and model randomly going away also in edit session.

### ISSUE THREAD

**Issue by OrtheSnowJames** [JannisX11/blockbench#1934]
### What are you trying to do, and what do you expect to happen?

I've been waiting for a year and I still didn't know this page existed! Anyway here is my issue report. When I am making a bedrock entity with my friends, I thought it would act like normal blockbench.

### What happens instead?

The animation tab doesn't display the keyframe window. Also, when I am working, the model randomly deletes somehow. Can you patch this? 

### Model format in which the issue occurs

Bedrock Entity, Modded Entity, and those are the only place I recorded it in. (Modded entity didn't have anything bad with animation since it doesn't have an animation tab, but it still deletes the model in there.)

### Blockbench variant

Program, Website

### Operating System

Windows, Mac

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Does this happen when you are using Edit Sessions?

To access the Keyframe window, did you make sure to select an animation, a bone, and a keyframe?
