### ISSUE TITLE
[Issue] 3D brush outline does not adapt to inflated/deflated cuboids

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1938]
### What are you trying to do, and what do you expect to happen?

3D brush outline should conform to inflated/deflated cuboids

### What happens instead?

![image](https://github.com/JannisX11/blockbench/assets/81629481/e0db70f6-fbc8-47f0-b64f-cb7e7c58fc28)

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

Persona Creator, Collapsible Start Screen Categories, Screencast Keys, Explorer, Quick Box-UV Layout, , Scene Recorder, Bakery, Simplify Models, Preview Scene Customiser, Plaster, MTools, Animation Sliders, Texture Stitcher, Seat Position + Hitbox, Shape Generator

**Comment by JannisX11** [comment]
Fixed in 4.8.
