### ISSUE TITLE
New Plugin Loader is unable to load about.md for local plugins

### ISSUE THREAD

**Issue by Elenterius** [JannisX11/blockbench#1943]
### What are you trying to do, and what do you expect to happen?

I'm side-loading a local plugin with the new plugin format introduced in Blockbench version 2.8 and the about section should be populated with the content from the local about.md file.

### What happens instead?

The plugin loader fails to load the local about.md and tries to load the about.md from a remote source instead.

### Model format in which the issue occurs

n/a

### Blockbench variant

Program

### Operating System

windows 10

**Comment by Elenterius** [comment]
![image](https://github.com/JannisX11/blockbench/assets/6061273/844752b8-0a37-4003-9cfa-5d237f544435)

**Comment by JannisX11** [comment]
Fixed in 4.8.
