### ISSUE TITLE
Почему поверхность не имеет текстур?

### ISSUE THREAD

**Issue by KingDiece** [JannisX11/blockbench#1944]
### What are you trying to do, and what do you expect to happen?

Я хотел раскрасить свою модель и думал, что блоки закрасятся.

### What happens instead?

Выдаёт, что данная поверхность не имеет текстур.

### Model format in which the issue occurs

Блок/Предмет Java

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

Никакие

**Comment by JannisX11** [comment]
This is normal, elements do not have textures by default. To learn how to use Blockbench, please watch tutorials instead of asking here.
