### ISSUE TITLE
[Issue] Loop cut tool sometimes does not cut

### ISSUE THREAD

**Issue by Azagwen** [JannisX11/blockbench#1947]
### What are you trying to do, and what do you expect to happen?

Cut a edge loop across a face loop.

### What happens instead?

Nothing happens at first glance, the edge loop does not appear, and the selection sometimes jumps around. This behavior doesn't happen on every Mesh.

I have not tested this on the current release, the following video is using the 4.8 Beta 1

https://github.com/JannisX11/blockbench/assets/30528331/7e7e5e3a-1915-4cf3-bbb8-f4a14c46fbd0

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

- CEM Template Loader 
- Geckolib Animation Utils 
- Shape Generator 
- Texture Stitcher 
- MTools 
- Optimize 
- Plaster 
- Mod Utils 
- Tint Preview 
- Code View 
- Reference Models 
- Explorer

**Comment by JannisX11** [comment]
I cannot reproduce this, can you send me a mesh where this happens?

**Comment by Azagwen** [comment]
Yeah, I will I need to test this further, I can't seem to reproduce it accurately either, even on the same model that the video was captured with 😅
Will let you know + file if I manage to!

**Comment by Azagwen** [comment]
I have managed to encounter this again, here is the file in which it happened (with all irrelevant content removed except for the bugged element): https://blckbn.ch/tMLsCD

**Comment by Azagwen** [comment]
I encountered this in 4.8 Beta 2, but it remains pretty hard to trace why it ends up happening, it feels like Blockbench doesn't think the faces I want to loop cut are connected/quads
