### ISSUE TITLE
My skin keeps on disappearing 

### ISSUE THREAD

**Issue by Rhino33354** [JannisX11/blockbench#1948]
### What are you trying to do, and what do you expect to happen?

I am trying to make a skin and I am expecting it to not disappear on me

### What happens instead?

It disappears 

### Model format in which the issue occurs

Skin maker

### Blockbench variant

Program

### Operating System

Ipad

### Installed Blockbench plugins

Mobmaker

**Comment by JannisX11** [comment]
Please attach screenshots.
