### ISSUE TITLE
[Issue] Paint tools color selector doesn't open from correct location

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#195]
Paint tools color selector doesn't open from correct location.
https://youtu.be/ZgDQGWmGyE4

How to reproduce:
- Create 2 paint color selector toolbar shortcuts.
- Click paint selector.
- Both paint selector will open from same location.

Blockbench 2.1.0 Windows desktop

**Comment by JannisX11** [comment]
Special widgets like sliders and color pickers are not supposed to be in two toolbars simultaneously.

**Comment by JannisX11** [comment]
In version 2.2, adding a widget to a toolbar will remove it from all other toolbars.
