### ISSUE TITLE
Eu não posso mecher na animação porque eu clico e não vai

### ISSUE THREAD

**Issue by Josegamerback** [JannisX11/blockbench#1954]
### What are you trying to do, and what do you expect to happen?

Isso e um bug né porque eu sou o rei dos bugs

### What happens instead?

Não sei

### Model format in which the issue occurs

Não lenbro

### Blockbench variant

Website

### Blockbench version

Mais recente

### Operating System

Não sei

### Installed Blockbench plugins

Não sei

**Comment by JannisX11** [comment]
Some formats do not support animations. So this is likely not a bug. But I cannot say for sure if you do not remember the format.
