### ISSUE TITLE
Incorrect translation

### ISSUE THREAD

**Issue by RinF-UwU** [JannisX11/blockbench#1956]
### What are you trying to do, and what do you expect to happen?

There is an error with the translation into Ukrainian in the plugin manager. The word "Installed" is translated incorrectly. The correct translation is "Встановленні" or "Інстальовані".

### What happens instead?

null

### Model format in which the issue occurs

null

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

Windows

**Comment by JannisX11** [comment]
Fixed in 4.8.
