### ISSUE TITLE
Rename Java item to "Not Minecraft"

### ISSUE THREAD

**Issue by Dant35tra5t** [JannisX11/blockbench#1958]
### Detailed description of your suggestion

Almost blew out my wall trying to get this into MC for someone to tell me to set this to generic. Yo MC is java based, can we not?

**Comment by PadawanAmy** [comment]
This suggestion will only help the boomers who dont know about the modern age

**Comment by Dant35tra5t** [comment]
If modern agers named things correctly then us Boomers could join up in making content.

**Comment by JannisX11** [comment]
You have it backwards. "Java Block/Item" is a format in the Minecraft category and is intended for Minecraft. "Generic Model" is a generic format and is not for Minecraft.
