### ISSUE TITLE
Impossible to paint cube

### ISSUE THREAD

**Issue by Herbert-RD** [JannisX11/blockbench#1959]
### What are you trying to do, and what do you expect to happen?

Paint a specific cube 

### What happens instead?

Nothing happens, the brush simply don't work

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Blockbench version

4.8 beta 2

### Operating System

Windows 10

### Installed Blockbench plugins

Geckolib Animations Player Statue Generator Shape Generator Resourcepack Packager Plaster Bakery Persona Creator

**Comment by JannisX11** [comment]
A video of the issue would be helpful, showing all of the UI.
