### ISSUE TITLE
I made the model With its complete cubes and groups but when i open the model that i save the base of my model has been gone i don't know why but that happend to me 2nd time

### ISSUE THREAD

**Issue by micoenz** [JannisX11/blockbench#1961]
### What are you trying to do, and what do you expect to happen?

I opened the model that i save then when i open the base Has gone i expect that If i open the model it will be able to get the complete cubes 

### What happens instead?

Nothing.

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Website

### Blockbench version

New

### Operating System

Phone

### Installed Blockbench plugins

Minecraft wizard entity

**Comment by JannisX11** [comment]
Can you show a before and after screenshot?
