### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by Flopperjam123** [JannisX11/blockbench#1962]
### What are you trying to do, and what do you expect to happen?

I am trying to rotate my torus in the animation editior.

### What happens instead?

I cannot select objects, and when i found a way to do, it couldn't be rotated for an odd reason.
![● Mmmmm - Blockbench 25_07_2023 15_26_49](https://github.com/JannisX11/blockbench/assets/140525781/7c38d9b2-9e59-47f0-9477-681b943ff023)

### Model format in which the issue occurs

idk

### Blockbench variant

Program

### Blockbench version

4.4

### Operating System

windows 11

### Installed Blockbench plugins

all of them

**Comment by JannisX11** [comment]
Only bones can be animated. not individual elements.
