### ISSUE TITLE
Model Not Opening Correctly

### ISSUE THREAD

**Issue by bruhmomentum12534** [JannisX11/blockbench#1963]
### What are you trying to do, and what do you expect to happen?

I'm trying to make a model for a Minecraft mod, and I've experienced this issue many times already. I'm trying to open a .java file in Blockbench (which was literally a model that was made in and downloaded from Blockbench) so I can fix the model because I noticed something was wrong with it during playtesting.

### What happens instead?

Instead, no new cubes appear, and I've been extremely frustrated about it, especially because of how time consuming it was to make the model.

### Model format in which the issue occurs

.java

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

Windows 10 Home

### Installed Blockbench plugins

Texture Stitcher 1.0.1, GeckoLib Animation Utils 3.0.5, CEM Template Loader 7.0.0

**Comment by JannisX11** [comment]
.java model files cannot be imported into Blockbench in most cases. When exporting a .java file, the program will warn you about this fact. Make sure to keep your project files.
