### ISSUE TITLE
Model or Grid not rendering in view

### ISSUE THREAD

**Issue by titanlock** [JannisX11/blockbench#1964]
### What are you trying to do, and what do you expect to happen?

Went to just go edit a generic model I was working on.

### What happens instead?

For some reason the 3D world was not rendering the model or the default grid, the model was there as I was able to select it and see the texture I made for it but would just not show up in the view port at all. I checked with all of the minecraft options as well and they too could not show anything besides the background checkered board. I did find it would render the model if I enabled face orientation in the view mode but the grid still did not show up. I even tried restarting/reinstalling and nothing worked. 

I did end up fixing my issue by completely deleting my .config/Blockbench folder and then everything worked fine from there. So I think there is a bug somewhere related to this folder. The only thing I had changed on blockbench was changing it to the retrowave theme and had no plugins either.

I didn't take any screenshots at the time to show but thought I would bring this to attention in case some else runs into this issue as well and maybe a fix can be found.

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

Arch Linux

### Installed Blockbench plugins

None

**Comment by SaltSouls** [comment]
Can confirm that I am also getting this issue.
![Screenshot_20230808_021203](https://github.com/JannisX11/blockbench/assets/36361103/37ae2dc6-76a2-4c74-917f-a70b5eaa26f9)

**Comment by Earthcomputer** [comment]
I just had this issue as well. Void linux

**Comment by superpowers04** [comment]
+1 Can confirm I am also getting this issue. I can render everything but the model, grid or ground plane
![image](https://github.com/JannisX11/blockbench/assets/38338700/6418a928-6711-44e1-96b2-21e03728f511)

**Comment by superpowers04** [comment]
Did a bit of messing around. The issue doesn't happen on 4.7.4. It fixes if you disable hardware acceleration on 4.8.2

**Comment by henriquelalves** [comment]
Also happened with me, on a Manjaro Linux (Blockbench v 4.8.3). Didn't test disabling GPU acceleration, but deleting `.config/Blockbench` solved the issue.

**Comment by sebastianulm** [comment]
Only some (most?) Textures don't render. If you switch to "Solid" the object displays. Preview UV's also works and is a texture. Studio and the new Minecraft environments also render. Deleting `.config/Blockbench/GPUCache` seems to be enough, so you can keep your Settings. 
Maybe its a reasonable to automatically clear caches when upgrading from an older version?

**Comment by JannisX11** [comment]
Can anyone confirm if this is still an issue in 4.9?

**Comment by superpowers04** [comment]
Still a bug, deleting all of the cache in .config/blockbench fixes it for a bit though

**Comment by KawaiiBakemono** [comment]
I also use Arch Linux, it's still an issue for me on 4.9.3. Disabling hardware acceleration is the best workaround for now it seems.

**Comment by superpowers04** [comment]
(I haven't actually checked to see if this has fixed anything)
It looks like the patch just does the GPU cache clear every update, however this issue doesn't relate to updates. As I haven't updated blockbench in a bit (bbmodel slightly changed and it has broken Figura so I'm staying on an older version for now until Figura gets updated to support `"texture" = false`) and it usually happens every few days or so

**Comment by JannisX11** [comment]
It happens every few days? So I guess a better strategy would be to clear it every time the program is used?

**Comment by superpowers04** [comment]
> It happens every few days? So I guess a better strategy would be to clear it every time the program is used?

Probably, to be honest

**Comment by CeruleanDerpo** [comment]
Why is this closed? The issue is still occuring to me

**Comment by freeflo** [comment]
Also happening for me now, randomly after using this for weeks.
