### ISSUE TITLE
Smooth interpolation non differentiability in loop

### ISSUE THREAD

**Issue by AlexandreChaussard** [JannisX11/blockbench#1965]
### What are you trying to do, and what do you expect to happen?

Hi ! 👋 

When using **smooth interpolation in looping animations**, it seems that the **last keyframe is not interpolated with the first one** of the loop, leading to a breaking point in the curve - non differentiability. (see picture 1 below)
Practically speaking, this leads to a **weird momentum in the animation that doesn't feel natural**.

![image](https://github.com/JannisX11/blockbench/assets/78101027/e1ec676b-f677-4aee-9ee9-17cca90d150b)

Currently, this is fixable using the baking plugin, by turning everything in linear interpolation. The procedure is the following, so that the interpolation is captured correctly:
- Copy the whole loop
- Paste it twice
- Bake the middle part (correct interpolation being performed)
- Replace the whole animation by the baked section

This gives the following result (see picture 2 below):

![image](https://github.com/JannisX11/blockbench/assets/78101027/29631984-a84e-4eb3-8890-5eb87f9d4a16)

This procedure works, but it makes the editing of the animation impossible after baking sadly.

### What happens instead?

My suggestion is then the following: simply account for a "ghost" animation after the last keyframe that is a copy of the animation, and perform the interpolation accordingly (see picture below)

![image](https://github.com/JannisX11/blockbench/assets/78101027/3470f24d-5cfd-4ef7-9c87-3f0a32342119)

### Model format in which the issue occurs

generic

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

Windows

### Installed Blockbench plugins

Bakery, Animation Sliders

**Comment by cronvel** [comment]
I'm running on the same issue, trying to get a walk animation right.
Everything is set to smooth, and the legs are slowing down around the loop.

It's possible to fix this with the Bezier mode, but Bezier do not works with any surrounding smooth keyframe, so this means turning all keyframes into Bezier : a very long and boring process.

**Comment by Tempest-5ky** [comment]
Getting what I believe is the same issue, resulting in an odd pause in the animation seemingly between loops
