### ISSUE TITLE
Broken armature and bones position when choosing a different export scale

### ISSUE THREAD

**Issue by LavaHoleD** [JannisX11/blockbench#1966]
### What are you trying to do, and what do you expect to happen?

Export my model (with armature) at a different export scale

### What happens instead?

The armature and bones position break
![immagine](https://github.com/JannisX11/blockbench/assets/73123805/c6a12fa6-cd5c-4b85-9331-6732d98a9873)

This doesn't happen if I choose the export scale as the standard 16.

### Model format in which the issue occurs

Generic Forma

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

Windows 11

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
I wasn't able to reproduce the issue. Maybe you can attach your Blockbench model?

**Comment by LavaHoleD** [comment]
> I wasn't able to reproduce the issue. Maybe you can attach your Blockbench model?

Sure thing. The export scale I had this issue was 32.
https://drive.google.com/file/d/1MGgvLNEv_2VuBHlOBsp9qEn5aAKFiPul/view?usp=sharing

**Comment by LavaHoleD** [comment]
> I wasn't able to reproduce the issue. Maybe you can attach your Blockbench model?

Please let me know when you download it. I don't quite like having my models floating around

**Comment by JannisX11** [comment]
I downloaded the model and tested. It looks fine to me when opened in Blender. Using Blockbench 4.8.1 and Blender 3.6.2
[ak47 32.zip](https://github.com/JannisX11/blockbench/files/12387788/ak47.32.zip)
