### ISSUE TITLE
Repeated problems with the web

### ISSUE THREAD

**Issue by ghost** [JannisX11/blockbench#1967]
### What are you trying to do, and what do you expect to happen?

Repeated problems with the web.I waited three days.

### What happens instead?

.

### Model format in which the issue occurs

No.It's blockbench‘s.

### Blockbench variant

Website

### Blockbench version

Web，I don't know

### Operating System

iPadOS16.6，Safari

**Comment by YYLWZDXPGD** [comment]
Because I'm a Chinese student and haven't finished learning English, I use Google Translate.

**Comment by YYLWZDXPGD** [comment]
It is always happen.
To enter it, I can only enter the page by loading it at least 12 times, but only the icon of BlockBench and "home" have nothing else, and it is not a network problem.
It is often like this
![IMG_5392](https://github.com/JannisX11/blockbench/assets/128379352/569a914a-de97-40d7-9456-cad7dd8479d5)
