### ISSUE TITLE
When I'm exporting to fbx the model is disappear 

### ISSUE THREAD

**Issue by LushDash** [JannisX11/blockbench#1971]
### What are you trying to do, and what do you expect to happen?

I'm trying to export extruded texture to fbx

### What happens instead?

When I export The model disappear 

### Model format in which the issue occurs

Fbx

### Blockbench variant

Website

### Blockbench version

Website

### Operating System

Android

### Installed Blockbench plugins

-

**Comment by JannisX11** [comment]
Any errors in Help > Developer > Error Log?
