### ISSUE TITLE
Unable to install plugins on Linux Desktop

### ISSUE THREAD

**Issue by Oreool** [JannisX11/blockbench#1974]
### What are you trying to do, and what do you expect to happen?

When attempting to install any plugin for Linux Desktop Blockbench, expecting plugin to install.

Steps to recreate:
1. Open Blockbench
2. Open File > Plugins...
3. Select any Plugin
4. Press Install

### What happens instead?

Nothing happens except for error in log:
```
desktop.js:114 Electron 25.2.0, Node 18.15.0
boot_loader.js:52 Three.js r129
boot_loader.js:53 Blockbench 4.8.0 Desktop (Linux)
node:events:491 Uncaught Error: connect ECONNREFUSED 2a04:4e42:8f::485:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
__node_internal_captureLargerStackTrace @ node:internal/errors:490
__node_internal_exceptionWithHostPort @ node:internal/errors:668
afterConnect @ node:net:1494
```

### Model format in which the issue occurs

Any or none open.

### Blockbench variant

Program

### Blockbench version

4.8 (happened in 4.7 as well)

### Operating System

Linux Mint Cinnamon Edition

**Comment by JannisX11** [comment]
Cannot reproduce. Are you doing anything special with your network? Any VPNs? Or are you in a country that would potentially block URLs?

**Comment by Oreool** [comment]
My mistake, you're absolutely correct on the VPN. I'm running Mullvad version 2023.3. Disconnecting allowed me to download plugins as expected.
