### ISSUE TITLE
Multi-texture keeping will break previous layer assignments

### ISSUE THREAD

**Issue by ocome85** [JannisX11/blockbench#1977]
We believe it is partially related to the following issues
#1972
If they are identical issues, we will withdraw them.
I apologize in advance.

### What are you trying to do, and what do you expect to happen?

When multi-texture keep is done, it is judged as a separate UV and the image size changes automatically.
(Confirmed to work with 4.7.x)
### What happens instead?

![image](https://github.com/JannisX11/blockbench/assets/50471874/27186acf-e4c0-4290-a71d-cd13b1f16343)
![image](https://github.com/JannisX11/blockbench/assets/50471874/eb784e3f-bfee-4f3b-adf7-a65c67ccfdbd)
I decided to make a duplicated object like this a different color, so I moved it and rebuilt it.

![image](https://github.com/JannisX11/blockbench/assets/50471874/b4812eeb-0093-4089-92b2-bae1fa93e6ea)
Multi-textures are broken and oddly sized

### Model format in which the issue occurs

geckolib animated model  

### Blockbench variant

Program

### Blockbench version

latest(4.8.1)

### Operating System

Windows 10 windows11

### Installed Blockbench plugins

Geckolib Animation Utile

**Comment by CraftsyCraft** [comment]
I hope BlockBench will fix this issue

**Comment by JannisX11** [comment]
@ocome85 could you share the model where this happens?

**Comment by ocome85** [comment]
https://github.com/ocome85/bbupload

**Comment by ocome85** [comment]
The current version(4.8.3) seems to have fixed it
Thank you from the bottom of my heart for your support <3
