### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Ptik01** [JannisX11/blockbench#1979]
### What are you trying to do, and what do you expect to happen?

I'm on version 3.6.6 with the Java Entity plugin, I'm creating a creature, and I need to rotate it literally a couple of degrees. I pick up the tool and nothing is displayed. The toolbar shows that the item is selected, but I can't turn it around. Tell me why this is and what to do?

### What happens instead?

I'm on version 3.6.6 with the Java Entity plugin, I'm creating a creature, and I need to rotate it literally a couple of degrees. I pick up the tool and nothing is displayed. The toolbar shows that the item is selected, but I can't turn it around. Tell me why this is and what to do?

### Model format in which the issue occurs

Java Animetted Entity (plugin)

### Blockbench variant

Program

### Blockbench version

3.6.6

### Operating System

.

### Installed Blockbench plugins

Java Animetted Entity

**Comment by Ptik01** [comment]
Yesterday I made a model of a wild boar, and the turn worked for me. And I had the exact same thing. Plugin, version - all the same. I haven't updated my computer since.

**Comment by JannisX11** [comment]
That version is 3 years old and no longer supported.
