### ISSUE TITLE
Model & texture won't save properly

### ISSUE THREAD

**Issue by Kimiron34** [JannisX11/blockbench#1983]
### What are you trying to do, and what do you expect to happen?

I am doing a small model in Java block/item which contains exactly 40 cubes and one 512 x 512 texture. Today, while editing the texture, I tryed as usual to do Ctrl+S to save the model & the texture, but nothing happened. Ctrl+s, right-click - save and save as, everyting I tried doesn't seem to save the model. Even when closing blockbench and pressing "save", it will just left the app opened and the model unsaved. Note that when I undo the changes, the "Saved as model.json" message appear as always, but as it's already saved it doesn't help.
I am on the latest version of Blockbench.

### What happens instead?

Well as I said previously nothing happens. The app and the model just remain opened and unsaved.

### Model format in which the issue occurs

Java block/iten

### Blockbench variant

Program

### Blockbench version

The latest version, 4.8

### Operating System

Windows 10 with all updates.

### Installed Blockbench plugins

MC Entity wizard, Shape generator, Player statue generator, Resourcepack packager, MTools, Texture stitcher, Color gradient generator, Double sided cubes, Brush color randomizer, Outline generator.

**Comment by JannisX11** [comment]
Any errors in Help > Developer > Error Log?

**Comment by Kimiron34** [comment]
Apparently not.

**Comment by JannisX11** [comment]
I am not able to reproduce the issue.
