### ISSUE TITLE
Different behavior of Mirror Modeling depending on Transform Space

### ISSUE THREAD

**Issue by Hiiamwilliam** [JannisX11/blockbench#1986]
### What are you trying to do, and what do you expect to happen?

Testing the Mirror Modeling option, I noticed a strange behavior related to Move Transform Space and Mirror Modeling. 
I expected the mirrored results to be the same regardless of Transform Space.

### What happens instead?

The following steps produce different results when the Move Transform Space is Global/Bone or Local:

1. Add Mesh
2. Move it a bit away from the origin towards +X
3. Enable Mirror Modeling
4. Move the Mesh towards +Z

If, on step 1, Transform Space is:
- Global/Bone: step 4 results in another Mesh being created at the mirrored position (1 Mesh -> 2 Meshes)
- Local: step 4 results in the geometry being replicated at the mirrored position, but it's the same object (1 Mesh -> 1 Mesh)

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Windows 10 64-bit

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Works as intended. Meshes with a position (origin) at the center get mirrored within the same mesh. Moving in global space changes the mesh position.
