### ISSUE TITLE
everything graying

### ISSUE THREAD

**Issue by realazalas** [JannisX11/blockbench#1989]
### What are you trying to do, and what do you expect to happen?

add color to a texture via bucket/brush

### What happens instead?

everything outside of the current brush gets slightly grayer until its entirely gray

### Model format in which the issue occurs

generic

### Blockbench variant

Website

### Blockbench version

current website version as of august 5th

### Operating System

MacBook

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
Which browser are you using? Would it be possible to record a video of the issue?

**Comment by realazalas** [comment]
I am using safari and I can record it

**Comment by JannisX11** [comment]
Please do that then.
