### ISSUE TITLE
[Issue] No cancel or retry option after recording a gif

### ISSUE THREAD

**Issue by iWackyy** [JannisX11/blockbench#199]
No cancel or retry option after recording a gif
Even when pressing escape, it will open saving window.
https://i.imgur.com/8J0hZvC.png

Using: Blockbench 2.2.0 Win10 Desktop

**Comment by JannisX11** [comment]
Cancel button added in 2.3. I don't consider a retry button necessary at this point because you might aswell use the menu again.
