### ISSUE TITLE
Renaming cube to layer doesn't work on Bedrock Entity

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1990]
### What are you trying to do, and what do you expect to happen?

Usually, I expect that adding layer to a cube's name will allow its visibility to be toggled similar to the Minecraft skin format

### What happens instead?

Nothing happens to the cube(s) when pressing the keybind to toggle layers

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Blockbench version

4.8.6

### Operating System

Windows 11

### Installed Blockbench plugins

CEM Loader, Simplify Models, Reference Models

**Comment by JannisX11** [comment]
Toggling layers as well as exploding is only a feature in the skin editor. It does not translate to custom models.
