### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by sillybillycrazy** [JannisX11/blockbench#1993]
### What are you trying to do, and what do you expect to happen?

i was trying to make skins for a mod im making and i turned off mirror brush for the legs and arms 

### What happens instead?

when i painted the right arm the same detail i painted for the right arm went to the left arm

### Model format in which the issue occurs

zombie

### Blockbench variant

Program

### Blockbench version

idk

### Operating System

laptop

### Installed Blockbench plugins

no

**Comment by JannisX11** [comment]
This appears to be a UV mapping problem, not an issue with the program itself.
