### ISSUE TITLE
Clicking and dragging a box on the UV map to move it also moves the camera

### ISSUE THREAD

**Issue by Geoc1de** [JannisX11/blockbench#1994]
### What are you trying to do, and what do you expect to happen?

In this example I was making a hammer, and it has a center head and two seperate, larger faces. I want those faces to use the same piece of the UV map (and therefore have the same texture) to save space. Intuitively I would expect to be able to drag the box for the first hammer face's texture on top of the second's texture on the UV map. 

### What happens instead?

When I drag the box that defines the hammer face's texture, it also drags the entire UV map with it - essentially it thinks I'm trying to pan around the UV window while also dragging the box. I know that it is trying to drag the box, because the whole map lags behind by a few frames, while the box doesn't. I'm currently using box UV mode, but it also happens with per-face UV mode.

### Model format in which the issue occurs

Modded Entity

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Windows 10

### Installed Blockbench plugins

Animated Java Model Format

**Comment by JannisX11** [comment]
This is probably happening because you set the Drag View keybinding to left click, which is also used for dragging but cannot be changed.
Let me add an exception for that.

**Comment by Geoc1de** [comment]
Ah, I didn't think of that. Thanks c:
