### ISSUE TITLE
Paint brush preview is shown incorrectly on rotated cubes

### ISSUE THREAD

**Issue by Marskind21** [JannisX11/blockbench#1995]
### What are you trying to do, and what do you expect to happen?

Paint brush preview is shown on the rotated cube.

### What happens instead?

Paint brush preview is shown in mid air.

https://github.com/JannisX11/blockbench/assets/142215285/46ced333-13f3-41a7-86d0-d1d30dc890a5

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Fixed in 4.8.2.
