### ISSUE TITLE
Random translucent pixels appearing on models

### ISSUE THREAD

**Issue by JadenBrummett** [JannisX11/blockbench#1996]
### What are you trying to do, and what do you expect to happen?

basically in the past month or so whenever I tried to paint my models (mainly whenever I use the paint-bucket) specific pixels on my model will start becoming more and more translucent each time I use the paint bucket, and no the UV is not overlapping so that isn't the issue + im not even using translucent colors, so i have no idea what's happening, also im not the only one whos having this issue.

![Logopit_1690394482513-1](https://github.com/JannisX11/blockbench/assets/82528841/282848b6-9757-4aa4-9018-076a67685bda)

### What happens instead?

explained above.

### Model format in which the issue occurs

Texture

### Blockbench variant

Website

### Blockbench version

Latest (i think)

### Operating System

Android

**Comment by JannisX11** [comment]
This might be related to #1907, seems to be an issue on a few android devices.
