### ISSUE TITLE
[Suggestion] Create a vertex in the middle of an edge

### ISSUE THREAD

**Issue by Gliese-832-c** [JannisX11/blockbench#2002]
### Detailed description of your suggestion

Create a vertex in the middle of an edge. Kind of like loop cut but only in one spot instead of around the whole thing.

**Comment by JannisX11** [comment]
Can you explain more about your use case for this? Blockbench works with faces that are either quads or tris, so an extra point would not really work, it would either make the model no longer watertight, or it would split quads into 3 tris.

**Comment by Gliese-832-c** [comment]
I think it would be totally fine to split a face into multiple smaller faces.

For example, this:
![image](https://github.com/JannisX11/blockbench/assets/55159077/4de61173-e62a-45a1-8dda-79fd44211314)
could turn into this:
![image](https://github.com/JannisX11/blockbench/assets/55159077/75074693-1b0f-40a3-81c3-2d6a18ec30b9)

Right now, if you try to use loop cut on a triangular shape, this is what it does:
![image](https://github.com/JannisX11/blockbench/assets/55159077/e3185df4-3379-4287-b431-2a56cd7f7ccb)
The face becomes disconnected:
![image](https://github.com/JannisX11/blockbench/assets/55159077/149df1a6-b9a1-415d-ad59-0c400a1c8c1f)

**Comment by Gliese-832-c** [comment]
I suppose I can sort of get what I want by using another loop cut on the top face, then connecting the vertices, but I think it would be better if it was supported natively.

**Comment by JannisX11** [comment]
In this case that seems to be a bug, it should split the top face as well.
