### ISSUE TITLE
Unable to type in input boxes on mobile

### ISSUE THREAD

**Issue by MrRedstoneYT** [JannisX11/blockbench#2005]
### What are you trying to do, and what do you expect to happen?

Type in input boxes on creation of model

### What happens instead?

It acts like I can type in it and even brings up my keyboard, if you start typing it does nothing

### Model format in which the issue occurs

Every

### Blockbench variant

Website

### Blockbench version

4.8.1

### Operating System

IOS

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Can you make a list for which text fields this issue applies, and for which it works?

**Comment by MrRedstoneYT** [comment]
It's every single text box for some reason.

**Comment by MrRedstoneYT** [comment]
Project Create screen. Every text ox within this menu on every model creation option. On IOS
