### ISSUE TITLE
unable to move the camera when using my mouse left/right hold

### ISSUE THREAD

**Issue by Rellisalreadytaken** [JannisX11/blockbench#2006]
### What are you trying to do, and what do you expect to happen?

In my app when I left/right hold my mouse the camera doesn't follow. I don't know if this is only for me or I messed something in the settings or something that made my camera unable to follow when I left/right hold my mouse.

### What happens instead?

The camera seems to doesn't respond when I hold left/right on my mouse.

### Model format in which the issue occurs

the whole thing doesn't work in all of my models

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Blockbench

### Installed Blockbench plugins

outlines, entity wizard, block wizard, title generator

**Comment by JannisX11** [comment]
Navigation does not always use left and right mouse button. You have probably set it to something else. You can see and modify your navigation keys in File > Preferences > Keybindings.
