### ISSUE TITLE
"Show in File Explorer" leaves Finder unresponsive until Blockbench is closed (Mac)

### ISSUE THREAD

**Issue by notfingees** [JannisX11/blockbench#2007]
### What are you trying to do, and what do you expect to happen?

When I right click a file (such as texture.png) in Blockbench and click "show in file explorer", I expect Finder to pop up with texture.png selected. 

### What happens instead?

My Finder becomes unresponsive (spinning circle, can't be clicked or used in any way) until Blockbench is closed, and then Finder is back to normal. Downgrading to Blockbench 4.7.4 (patch 4) solves this issue. 

### Model format in which the issue occurs

All model formats (GeckoLib Entity, Java block/entity, Generic model) 

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

MacOS

### Installed Blockbench plugins

GeckoLib, Optifine Player Models.

**Comment by JannisX11** [comment]
Cannot reproduce on macOS 12.4.

**Comment by notfingees** [comment]
I've updated to the latest version of MacOS (14.5) and have a clean slate of the latest version of Blockbench (4.10.3). Trying to "show in file explorer" any asset (texture, animation) results in Finder being unresponsive (but works for other, non-Blockbench applications). I get this could be hard to debug without being able to replicate the issue, but is there anything I could try to fix it? Blockbench 4.7.4's compatability with GeckoLib suddenly stopped working for me last night so I need to upgrade

**Comment by notfingees** [comment]
A Blockbench factory reset does not solve the issue
