### ISSUE TITLE
I can't Download Pictures

### ISSUE THREAD

**Issue by micoenz** [JannisX11/blockbench#2009]
### What are you trying to do, and what do you expect to happen?

I click the screenshot model tool to download the picture for editing

### What happens instead?

I didn't Appear on my gallery but my notification shows that downloaded the picture

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Website

### Blockbench version

New

### Operating System

Phone

### Installed Blockbench plugins

Minecraft wizard entity

**Comment by micoenz** [comment]
![Screenshot_2023-08-23-18-48-01-877-edit_com miui gallery](https://github.com/JannisX11/blockbench/assets/133521424/db14915a-5f9e-40f5-bcff-f75bdb2922c1)
![Screenshot_2023-08-23-18-46-29-054_com android chrome](https://github.com/JannisX11/blockbench/assets/133521424/7d3aa659-7b40-460d-9661-0a73d11aef81)

**Comment by JannisX11** [comment]
It works for me. This is likely an issue with the browser, and might work again after a restart.

**Comment by micoenz** [comment]
Hello good afternoon can i ask what's happening with blockbench right now?
When you click "reload" nothing happens. Not just me but all of my friends
that using blockbench is experiencing the same problem. Hoping this issue
will be fixed as soon as possible thankyou!
