### ISSUE TITLE
[Plugin request] Texture to 3d

### ISSUE THREAD

**Issue by MCrafterzz** [JannisX11/blockbench#201]
Hello, as you maybe already knew buildin/generated generates a 3d model out of a 2d texture. It would be super cool if you could do something similar. Using buildin/generated does work but as the model can't be offset the model is floating in the middle of the block. I would use the plugin for rails for example. Creating the bent rail 3d model would take a long time so if a plugin could do it for me then it would be great!

How it would work:

- Create a plane and add a texture

- Click Plugin > 3dlize

- The plane would now have been replaced with multiple elements that use the same texture. The texture positions isn't that hard to generate as it's the same as the pixels position.

To make it simpler generate one cube per pixel but if possible (pretty hard) make it so that multiple pixels share the same model which would make it more optimized.

Thanks, I hope you can implement it!

**Comment by JannisX11** [comment]
You can use "File" > "Import" > "Extruded Texture" to achieve the same thing.

**Comment by MCrafterzz** [comment]
Thanks! Had no idea that this existed

**Comment by BlendCreator** [comment]
Where i can find this ,,buildin/generated´´? i´ve already found the extruding texture but not the buildin/generated.
