### ISSUE TITLE
Rotating my blocks forces them to teleport

### ISSUE THREAD

**Issue by Furballllllll** [JannisX11/blockbench#2014]
### What are you trying to do, and what do you expect to happen?

I was creating a model and I wanted to rotate it downwards slightly.

### What happens instead?

On the X and Z axis when I rotate any piece it will break and move into a different position.

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Blockbench version

Most recent release (srry idk how to check)

### Operating System

PC (idk specifics)

### Installed Blockbench plugins

Geckolib, Entity Wizard, Gradients, Structure importer

**Comment by JannisX11** [comment]
This is normal, as the format you specified has very strict limits on how things can be rotated.
