### ISSUE TITLE
Camrea is locked in a top down view

### ISSUE THREAD

**Issue by Hungrybug2** [JannisX11/blockbench#2017]
### What are you trying to do, and what do you expect to happen?

Trying to turn my camera from a top down view to any other angle. 

### What happens instead?

Just stuck in a top down view only lets me move around in a top down view.

### Model format in which the issue occurs

BlockBench program

### Blockbench variant

Program

### Blockbench version

id but just downloaded it today

### Operating System

im on window 10

### Installed Blockbench plugins

idk even know what this can i pls just move the camera

**Comment by PaulFinnerty** [comment]
Press 5 on your numpad to get back to the initial view. Or click on the hamburger icon in the top right corner of the viewport and follow the steps in this screenshots.

![image](https://github.com/JannisX11/blockbench/assets/81629481/1a36a932-7af5-4f88-aaa7-922c4ab1af50)

You must have switched to the top orthographic view by pressing 8 on your numpad, or the same way as what I showed in the screenshot. The presets of orthographic views don't let you rotate the camera.
