### ISSUE TITLE
[Suggestion] Allow the input of a specific time in the animations interface

### ISSUE THREAD

**Issue by destruc7i0n** [JannisX11/blockbench#202]
Above the scrubber, where the current time that the animation is at is listed, it would be nice if we could manually edit that, so we can go to precise moments in the animation.

This would make working with probably longer animations easier (the scrolling bar currently only seems to update/render while playing, so I cannot manually go to the end of an animation that is longer than the current scrubber) to allow for more precise fine tuning of animations etc.

**Comment by JannisX11** [comment]
Added in 2.3.
