### ISSUE TITLE
The model breaks in the game

### ISSUE THREAD

**Issue by funnystump** [JannisX11/blockbench#2020]
### What are you trying to do, and what do you expect to happen?

![IMG_20230904_144609_545](https://github.com/JannisX11/blockbench/assets/144024019/d20ad461-815b-4c5c-bb84-61f7af1b7a58)

### What happens instead?

![IMG_20230904_144613_167](https://github.com/JannisX11/blockbench/assets/144024019/1aa9ae21-2e2b-4387-afa8-123386bdd627)
I don't understand why the model breaks in the game

### Model format in which the issue occurs

.geo.json but I don't think the problem is in the format

### Blockbench variant

Program

### Blockbench version

1

### Operating System

Android

### Installed Blockbench plugins

No plugins installed

**Comment by JannisX11** [comment]
Please ask modeling questions on the Discord server: https://discord.gg/blockbench
