### ISSUE TITLE
Blockbench.addDragHandler is not a function

### ISSUE THREAD

**Issue by Rystars** [JannisX11/blockbench#2022]
### What are you trying to do, and what do you expect to happen?

[Blockbench.addDragHandler](https://lh3.google.com/u/0/d/1n45r7qS1q73_vm1i81syBZ3wwzPSSWvY=w348-h260-p-k-nu-iv1) 

this is why when I run index.html it's always like this

### What happens instead?

Blockbench.addDragHandler is not a function

### Model format in which the issue occurs

Type Error

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Android

### Installed Blockbench plugins

nothing

**Comment by JannisX11** [comment]
Unable to reproduce this issue. Are there any other issues in Help > Developer > Error Log? Maybe directly after starting Blockbench?
