### ISSUE TITLE
Models with fabric plugins does work.

### ISSUE THREAD

**Issue by FavioMc19** [JannisX11/blockbench#2023]
### What are you trying to do, and what do you expect to happen?

I am exporting a model with the fabric plugin and adding the .java file in my mod.

### What happens instead?

when exporting a model with "Java entity model" using the fabric plugin the model in the game looks all deformed.
![image](https://github.com/JannisX11/blockbench/assets/50508766/8f5f99a6-3ae4-4cb8-9031-4dd52da9455e)

### Model format in which the issue occurs

.java

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

windows

### Installed Blockbench plugins

fabric. optifine. gekolib

**Comment by JannisX11** [comment]
Did you try changing the Flip Y Axis option in File > Project?
