### ISSUE TITLE
I cant use my colors to paint it says it does not have texture and when i remove texture it regenerate texture and says it again plz fix this! Issue Summary

### ISSUE THREAD

**Issue by Lionking91** [JannisX11/blockbench#2026]
### What are you trying to do, and what do you expect to happen?

I'm trying to inform you that I can't use color or any paint tool  plz fix this so I can make my models colourful again!

### What happens instead?

Plz fix I appeal you 🙏 

### Model format in which the issue occurs

Bedrock block and entity

### Blockbench variant

Website

### Blockbench version

1.0

### Operating System

Bin

### Installed Blockbench plugins

I don't know

**Comment by JannisX11** [comment]
This sounds more like user error. You can try and ask on the Discord server. Or, if you disagree and you are sure that it is an issue with the program, please record and attacha a video of the issue.
