### ISSUE TITLE
24 X 48 PNGs are treated as an animated image with 2 frames

### ISSUE THREAD

**Issue by LandofHeros2234** [JannisX11/blockbench#2027]
### What are you trying to do, and what do you expect to happen?

Make a 24 X 48 image that is a static image

### What happens instead?

It makes a 24 X 24 image with 2 frames
Note: It is still treated as a 24 X 48 image outside of Blockbench, with frame 1 being the top and frame 2 the bottom

### Model format in which the issue occurs

png

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows 11

**Comment by JannisX11** [comment]
Should be fixed in 4.11
