### ISSUE TITLE
textures not appearing on the 3d model when exporting to .obj

### ISSUE THREAD

**Issue by springbonnie105** [JannisX11/blockbench#2034]
### What are you trying to do, and what do you expect to happen?

i tried exporting into a .obj for a animation.

### What happens instead?

when i opened the model, the textures were just purple and not the textures i added.

### Model format in which the issue occurs

.obj

### Blockbench variant

Website

### Blockbench version

latest

### Operating System

windows 10

### Installed Blockbench plugins

none

**Comment by PaulFinnerty** [comment]
https://blender.stackexchange.com/questions/47915/when-i-save-something-as-an-obj-file-the-texture-does-not-save-with-it-why
