### ISSUE TITLE
Keeps Auto Updating...why?.when I have auto updating turned off..??

### ISSUE THREAD

**Issue by curbs22** [JannisX11/blockbench#2035]
### What are you trying to do, and what do you expect to happen?

4.8.3 doesn't work....so I downloaded 4.8.0....to see if that still works but your software keeps auto updating even when I have it turned off.

### What happens instead?

It updates.

### Model format in which the issue occurs

4.8.3

### Blockbench variant

Program

### Blockbench version

4.8.0

### Operating System

Win11

### Installed Blockbench plugins

Plaster and upload to Minecraft

**Comment by JannisX11** [comment]
This can happen if the update was already downloaded when you disabled the setting. The setting only stops Blockbench from downloading new updates, it does not stop it from launching in the new update if it has already been downloaded.
Works as intended.
