### ISSUE TITLE
After upload new Blockbench block, installed...crazy light flashes all around area where new block installed

### ISSUE THREAD

**Issue by curbs22** [JannisX11/blockbench#2036]
### What are you trying to do, and what do you expect to happen?

Installed new block and exspected to move on to another but these crazy light flashes in the water all around the block i just installed kill the map...it wont load past a certain spot.  

### What happens instead?

Light flashes happen all around the new block installed...in water on my map.  Before I installed it from BB the map is fine....install it from BB and the map is bad.  After installing 4.8 and hitting the not to update button, it updated all by itself to 4.8.3.  

I'm sorry but the other version did NOT have any of this going on.

I'm going to have to stop using your program, shame.

### Model format in which the issue occurs

Bedrock

### Blockbench variant

Program

### Blockbench version

4.8.3 and 4.8.0

### Operating System

Win11

### Installed Blockbench plugins

Loaders and Plaster...

**Comment by JannisX11** [comment]
From the description this sounds like a Minecraft issue. This repository is for Blockbench.
