### ISSUE TITLE
I saved my model in blockbench two months ago and it is gone, there are no backups!

### ISSUE THREAD

**Issue by Nitro8ortiN** [JannisX11/blockbench#2038]
### What are you trying to do, and what do you expect to happen?

I saved my model about two months ago and its not in blockbench anymore. I checked the backups and there are no backups of it too. What should I do?

### What happens instead?

In the saved backups, there are only the backups of my previous model, that I just created.

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Website

### Blockbench version

Latest

### Operating System

Windows 10

### Installed Blockbench plugins

Minecraft entity wizard

**Comment by JannisX11** [comment]
If you save your model somewhere on your computer, you still have that file, unless you deleted it.

The Blockbench web app only saves backups of the models that you had last open and didn't save. If you would like to keep constant backups of your work, you can use the desktop app, which saves backups by default every 10 minutes and for up to 30 days. You can adjust the settings if you would like to keep your backups for even longer.
