### ISSUE TITLE
[ISSUE/BUG] Plugin Page not showing avaliable or installed plugins at all

### ISSUE THREAD

**Issue by ninjaaydan** [JannisX11/blockbench#2041]
Whenever I sign out of my device, somehow when i sign back in all my plugins in Blockbench, both available and installed, are gone. I can't get them back, unless I factory reset each and every time it happens. I know others have this issue, but none of them got a solution. Probably because of the lack of info. So, I'm here to give all the info I can to fix this.

**Blockbench version-**
Latest Version, 4.8.3 (according to BB)

**Device-**
School-Managed HP Chromebook 11 G8 EE, Latest Version, ProdID:1A762UT#ABA

**Wi-fi-**
School-Managed Wi-fi/possibly Xfinity, Or my home's Verizon Wi-fi

**Issue-**
When signed out/back in, BB stops showing ALL plugins on both available and installed, stopping all installed plugins from working/functioning. When Plugins are reloaded, the notification says "0 Plugins Reloaded", even though many plugins were installed. The only current solution is to factory reset, forcing a redo of all settings and key binds, including the plugins I had previously installed. 

If possible, can a patch/bug fix go out, or some kind of applicable code so it protects the plugins from disappearing? Or even an option to download all the installed plugins, so if it happens you can just import it all again? If you need more info, just look at my README.mx file in my profile for contact info. I will check back later to see if you responded.

(P.S. I searched through my settings for any to be a possible cause, and noticed that I turned on CDN mirroring. Is that an option for people who are missing some plugins, because It says it's for people in Egypt. Is that the problem?)

![Screenshot 2023-09-29 9 11 17 AM](https://github.com/JannisX11/blockbench-plugins/assets/146445785/0f7fdebc-fe9d-4d4f-9e35-b12aaf35cbc4)
![Screenshot 2023-09-29 9 11 29 AM](https://github.com/JannisX11/blockbench-plugins/assets/146445785/b0922c8c-3630-4927-b07b-35a8d3cdba56)

**Comment by JannisX11** [comment]
Well, are you in Egypt? And did turning CDN mirror on fix your issue?
Are there any error messages in Help > Developer > Error log?

**Comment by ninjaaydan** [comment]
It just started working when I turned off CDM mirror. So, i guess problem solved.. sorry about this-
