### ISSUE TITLE
Custom Geometry skin textures don't load in Minecraft bedrock

### ISSUE THREAD

**Issue by LordFeathers** [JannisX11/blockbench#2044]
### What are you trying to do, and what do you expect to happen?

I am trying to load Blockbench textures as skins in Minecraft Bedrock, I am not sure if this is a bug or a "help" issue, so sorry if this is in the wrong category. I correctly created the skin, geometry, and manifest files. I  then deleted the default persona file with iobit unlocker and replaced it with mine.

### What happens instead?

 When I load the textures into Minecraft with iobitunlocker, a skin pack appears, but there is never anything in it, even if I correctly created the manifest, skins, and geometry files.

### Model format in which the issue occurs

Geometry.json

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows 11

### Installed Blockbench plugins

none
Here is the persona I tried to import to Minecraft Bedrock:
[persona.zip](https://github.com/JannisX11/blockbench/files/12794319/persona.zip)

**Comment by JannisX11** [comment]
Not a Blockbench issue.
