### ISSUE TITLE
When uploading a bedrock entity to Sketchfab The textures won't load

### ISSUE THREAD

**Issue by Nico976l** [JannisX11/blockbench#2045]
### What are you trying to do, and what do you expect to happen?

I tried to upload my custom bedrock mob to Sketchfab 
[assets (3).zip](https://github.com/JannisX11/blockbench/files/12796085/assets.3.zip)

### What happens instead?

The textures didn't export

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Website

### Blockbench version

4.8.3

### Operating System

Windows

**Comment by JannisX11** [comment]
Unsure if this is a Sketchfab or a Blockbench issue. Either way this is the recommended way to upload models to Sketchfab: https://www.youtube.com/watch?v=vq-m_ZjdeUU

**Comment by Nico976l** [comment]
ok thanks alot
