### ISSUE TITLE
Blockbench plug-in issue

### ISSUE THREAD

**Issue by FreddieMars** [JannisX11/blockbench#2046]
### What are you trying to do, and what do you expect to happen?

So basically when i try to install this plug-in it just says "Only for the desktop app" and I don't know what that means so i guess this isn't really an issue but more like a problem, can any of you resolve this problem so i can install this plug-in?, also i am using Android and not a PC

### What happens instead?

![Screenshot_2023-10-07-00-35-41-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/JannisX11/blockbench/assets/147186400/25fe925b-4604-4a6d-9a1b-af661883d4e9)

So here's the problem, please tell me another way to install this plug-in ON ANDROID BLOCKBENCH, Thankou!

### Model format in which the issue occurs

It's just an plug-in not a model

### Blockbench variant

Website

### Blockbench version

Idk

### Operating System

Idk

### Installed Blockbench plugins

Idk

**Comment by JannisX11** [comment]
Desktop means computer. This plugin can only be used on computers.

**Comment by FreddieMars** [comment]
Thank you for your response, I understand now hehe just a little
misunderstanding it is, my apologies.
