### ISSUE TITLE
animation error

### ISSUE THREAD

**Issue by Samkoboy** [JannisX11/blockbench#2058]
### What are you trying to do, and what do you expect to happen?

Every time I try to animate a project it doesn't want to interact with it.

### What happens instead?

It does nothing.

### Model format in which the issue occurs

on the bedrock entity animation section  

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Windows 11

### Installed Blockbench plugins

Minecraft Entity Wizard
Minecraft Item Wizard
Minecraft Block Wizard
Seat Position + Hitbox

**Comment by JannisX11** [comment]
You need groups to animate, you cannot animate just elements.

**Comment by Samkoboy** [comment]
wait what do you mean ?

**Comment by Samkoboy** [comment]
wait how do i get a group to animate ?
