### ISSUE TITLE
[Issue] Grid smaller than 64 is not possible

### ISSUE THREAD

**Issue by jvanbruegge** [JannisX11/blockbench#206]
I am trying to model a very fine block and thus set the grid size (snapping) first to 64 (everything in 0.25 steps) and later to 80 (0.2 steps). But even with 80 in there, the blocks are still of size and move in steps of 0.25

Using 80 as either control or shift grid size works as expected.

I am using the latest desktop version on Arch Linux, downloaded yesterday.

P.S.: Thanks for this, helps tremendously for writing mods

**Comment by JannisX11** [comment]
This was actually intended in a previous version. But because the limit doesn't make that much sense anymore in the latest versions, I will raise it.

**Comment by JannisX11** [comment]
Fixed in 2.3.
