### ISSUE TITLE
[Issue] I cannot paint any cubes in any format on BlockBench.

### ISSUE THREAD

**Issue by IAMGOLFz** [JannisX11/blockbench#2064]
### What are you trying to do, and what do you expect to happen?

Hello, I have a painting issue.

This is the first issue that I face now, I cannot paint any cube in any format. I choose all types of brushes and colors that I would like to paint and drag the brush on textures but It doesn't work. [I used Minecraft skin and Java Block/Item formats for example in this video]. 

https://drive.google.com/file/d/1spHfG2fJqHOsAGNQcHvW9_pAm3-njiXx/view?usp=sharing

NOTE: the video that I gave, for example, is too big, I had to use Google Drive instead of dragging the video in this form.

### What happens instead?

After I chose the brush and color and dragged the brush on the cube object and Minecraft skin, it didn't work instead it changed color while I dragged the brush.

### Model format in which the issue occurs

All fomats

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Window 10 Home

### Installed Blockbench plugins

I Installed all non-deprecated plugins

**Comment by JannisX11** [comment]
You installed all plugins? Try uninstalling them one by one and see at which point it works again. Might have to restart after uninstalling as well.
It is not recommended to install plugins that you don't need.

**Comment by IAMGOLFz** [comment]
> You installed all plugins? Try uninstalling them one by one and see at which point it works again. Might have to restart after uninstalling as well. It is not recommended to install plugins that you don't need.

Thank you.
