### ISSUE TITLE
Release a .apk on F-Droid and in releases for Android

### ISSUE THREAD

**Issue by RustoMCSpit** [JannisX11/blockbench#2067]
### Detailed description of your suggestion

There's a webapp but a .apk is more ideal

**Comment by JannisX11** [comment]
Duplicate of #1187

**Comment by RustoMCSpit** [comment]
not a duplicate, having a native app ≠ uploading a .apk to f droid

**Comment by RustoMCSpit** [comment]
please re-open

**Comment by RustoMCSpit** [comment]
> while this is technically not a duplicate issue, blockbench does not seem to have an android native release, therfore, this could be seen as asking for a native release.

this is an issue relevent to another issue then, different issues though. re-open please
