### ISSUE TITLE
On My iPhone, a weird bug occurred when I was trying to type. The typing a backwards and trying to create a model was impossible. Could you please fix this!

### ISSUE THREAD

**Issue by Ills320** [JannisX11/blockbench#2069]
### What are you trying to do, and what do you expect to happen?

I was trying to type and I expect it to go forward and I also expect to make a model.

### What happens instead?

It goes backwards and does not let Me save a model.

### Model format in which the issue occurs

When typing and making a model.

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

IPhone

### Installed Blockbench plugins

Minecraft Entity Wizard, Minecraft Item Wizard, Minecraft Block Wizard.

**Comment by JannisX11** [comment]
Are you talking about the text field for model name, etc.? When you type, the letter appears at the start, not at the end of the field?
