### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by neondeex** [JannisX11/blockbench#2075]
### What are you trying to do, and what do you expect to happen?

Im trying to use blockbench and no model appears in the program

### What happens instead?

Models are not showing up
![image](https://github.com/JannisX11/blockbench/assets/30392593/b19328ea-2b44-41fc-8fa7-46ceaf7f911f)
![image](https://github.com/JannisX11/blockbench/assets/30392593/a0634c31-94d7-4683-a020-887ebb9bb5b8)

### Model format in which the issue occurs

bedrock and java not working correctly

### Blockbench variant

Program

### Blockbench version

latest

### Operating System

EndavourOS with wayland/hyprland 

### Installed Blockbench plugins

Entity wizard gecklib shape generator resoucepack packager wasd control code viw pie menu explorer and items adder

**Comment by JannisX11** [comment]
Duplicate of #1964
