### ISSUE TITLE
Black areas in GIF can be rendered as transparent

### ISSUE THREAD

**Issue by 21ChenYe** [JannisX11/blockbench#2076]
### What are you trying to do, and what do you expect to happen?

I am attempting to specify a background image in the Record Gif settings. 

![settings](https://github.com/JannisX11/blockbench/assets/49247040/cf990c62-c390-457f-b07b-3ea346edfaa8)

I expect the final result to simply be my model with a background image specified.

### What happens instead?

When a background image is specified, the model sometimes gains partial transparency:

![transparency](https://github.com/JannisX11/blockbench/assets/49247040/4fe7ea26-a07c-4017-9fb9-b325b87d1ea9)

Here's what the final product looks like when uploaded to a website with a white background:

![whitetreansparency](https://github.com/JannisX11/blockbench/assets/49247040/b2b2c7fe-d4a3-4b06-99f1-179f619d8f45)

As you can see... only parts of the model are transparent. 

This can be replicated consistently with certain background images:

![test2](https://github.com/JannisX11/blockbench/assets/49247040/4b792df1-52e9-4fbe-8a61-e4be95c1a5a2)

However, for some indiscernible reason, certain background images do not trigger this issue:
![test1](https://github.com/JannisX11/blockbench/assets/49247040/5e0eff7d-2289-41c6-aa6c-9bea940d097a)

Steps taken to try to mitigate this issue:

1. I've set the "Background Color" setting to a solid color, and also transparency - no effect
2. Changing the color of the affected areas does have some effect - I've been doing testing and this only appears to affect colors very close to pure black. Here's an example color that also runs into the issue:
![shades](https://github.com/JannisX11/blockbench/assets/49247040/5e841712-a1f6-40e1-8bbf-09e89a660981)
3. I've tried creating a solid background with tiny spots of transparency in the corners. I was unable to reliably re-create the issue through this method.

**Conclusion:**
1. adding a background image forces colors very close to pure black to become transparent on the model
2. something about the background image affects this, but I am unsure and will require additional investigation

I am attaching the backgrounds I used in a zip file. There are three backgrounds:

[backgrounds.zip](https://github.com/JannisX11/blockbench/files/13197185/backgrounds.zip)

### Model format in which the issue occurs

Low Poly - untested in other formats

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows 10

**Comment by lunahhhhhhhhhhhhhhhh** [comment]
I'm very new to the world of gifs, but I *think* I understand what is going on. It looks like Blockbench is setting `transparency: true` in the `writeFrame` command of the Gifencoder library [here](https://github.com/JannisX11/blockbench/blob/f7f7c002059c92b3516e71fb129d0be91352ff34/js/preview/screenshot.js#L566C84-L566C101) which we don't want to do according to the [GIF specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) as this is meant to be used in conjunction with the `transparency index` param.

> Transparency Flag - Indicates whether a transparency index is given in the Transparent Index field.

Setting `transparency: false` seems to fix the bug

**Comment by JannisX11** [comment]
Fixed in 4.10.
