### ISSUE TITLE
[Web] [UI] implement window-controls-overlay API

### ISSUE THREAD

**Issue by glitch128** [JannisX11/blockbench#2079]
### Detailed description of your suggestion

I have a question. why is the display override in tabbed mode? I feel like this doesn't make sense. a better API for this would be window-controls-overlay to make it more like a native app like vscode.

**Comment by JannisX11** [comment]
You're right, that can be updated.

**Comment by glitch128** [comment]
the way to do that would to be to add  
```css
 width: env(titlebar-area-x, 100%);
```
to "header" in the window.css file if that is the only header element as well as changing 
```json 
"display_override": ["tabbed", "minimal-ui"],
```
 to 
```json 
"display_override": ["window-controls-overlay", "minimal-ui"],
```
I see that you have already created app-drag-regions, so this should be all you need to do. I have not tested these suggestions as I can't seem to get the web app to work on replit.

**Comment by glitch128** [comment]
I have created a pull request implementing these changes.
