### ISSUE TITLE
update_selection event runs twice when used in a ValidatorCheck

### ISSUE THREAD

**Issue by KitCat962** [JannisX11/blockbench#2085]
### What are you trying to do, and what do you expect to happen?

I am trying to have a ValidatorCheck execute once every time the selection updates. I expect only 1 warning to appear in the Validator dialog.
This is the plugin used to issolate this issue:
```js
// plugin.js
(function () {
    BBPlugin.register('plugin', {
        title: "Plugin",
        author: "Katt",
        icon: "icon.svg",
        tags: ["Minecraft: Java Edition"],
        version: "0.1.1",
        min_version: "4.8.0",
        variant: "both",
        onload() {
            Validator.checks.push(
                new ValidatorCheck('plugin_rule', {
                    update_triggers: ['update_selection'],
                    condition: {
                        method: (context) => true
                    },
                    run() {
                        this.warn({
                            message: "This should only appear once..."
                        })
                    }
                })
            )
        }
    })
})()
```
[plugin.js.txt](https://github.com/JannisX11/blockbench/files/13326715/plugin.js.txt) (.js files cannot be uploaded)

### What happens instead?

2 warnings appear in the Validator dialog.
![image](https://github.com/JannisX11/blockbench/assets/94943674/8e5ec4be-f299-41c1-9ce4-8bb8555c2232)

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows 10

### Installed Blockbench plugins

plugin.js in "What are you trying to do"

**Comment by JannisX11** [comment]
This happens because you are pushing the validator check into the Validator.checks list. Creating a new check already does that, so you end up adding it twice.

**Comment by KitCat962** [comment]
oops. Thank you!
