### ISSUE TITLE
[Beta] [Issue] Texture template scale is inversely proportionate to texture size pre-texture creation

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#2089]
### What are you trying to do, and what do you expect to happen?

Creating a template texture for a new model.

### What happens instead?

Before creating a texture for the model with the texture template option, when the UV of the model is too big to fit in the UV frame OR when the UV frame is bigger than the smallest power-of-two size needed to fit the model UV, the texture generated (the pixels, not the resolution of the texture) are of the wrong scale.

The ratio seems inversely proportionate (UV too big for the frame -> the template texture is scaled up. UV frame much bigger than needed -> template texture is scaled down).

If the UV is much bigger than the project texture size pre-texture creation, the texture generated might even be blank because the scale of the template was so big (the top-left corner next to the white and green faces is blank). Or if I had to guess, it might have to do with the number of occupied quadrants by the UV of the model (like at the beginning of the video, the UV crosses the origin of the UV frame to the left and the top).

https://github.com/JannisX11/blockbench/assets/81629481/b6ed45f9-4eed-42eb-a0ae-8139ad96916c

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Program

### Blockbench version

4.9.0 Beta 1

### Operating System

W10

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
Fixed in 4.9.
