### ISSUE TITLE
[Releases] [Beta] add link to beta web version

### ISSUE THREAD

**Issue by glitch128** [JannisX11/blockbench#2094]
### Detailed description of your suggestion

I think that you should add a link to the beta version of the web editor in the beta releases so that people can find it easier on GitHub

**Comment by JannisX11** [comment]
You're right, I forgot to include all my boilerplate beta text.

**Comment by glitch128** [comment]
hey, also, if it doesn't cost any more, maybe you could move it to beta.blockbench.net or something like that.
