### ISSUE TITLE
Soft painting Seperate UV opacity bug

### ISSUE THREAD

**Issue by HypixelJacob** [JannisX11/blockbench#2097]
### What are you trying to do, and what do you expect to happen?

I want to soft paint with a wide brush on the model, and have the soft brush blend its opacity with the color of all the geo it reaches. Even neighboring geo that has a vastly different UV space.

### What happens instead?

The neighbouring, non-UV connected blends the soft brush opacity with transparency instead, creating a noticeable hole in the model.
<img width="449" alt="Blockbench - SoftpaintBug settings" src="https://github.com/JannisX11/blockbench/assets/144714137/8f63be97-7f00-4e14-a0b0-67aec3d1ba53">
<img width="639" alt="Blockbench- SoftPaintBug" src="https://github.com/JannisX11/blockbench/assets/144714137/e27b8dd5-42f4-4a19-9598-c9070a3b2e35">
Green line is the brush width, the red is where i painted, and the blue outline is the disconnected geo. (The Eye is a different place in the texture than the eye socket. as shown in this UV
<img width="227" alt="Blockbench - Soft Paint bug UV" src="https://github.com/JannisX11/blockbench/assets/144714137/48c4e88a-54f9-4cdf-ade1-c6a4b687a76a">

### Model format in which the issue occurs

Blockbench.

### Blockbench variant

Website, Program

### Blockbench version

4.83, 4.90 Beta web version

### Operating System

Windows

### Installed Blockbench plugins

None (in beta), occurs with and without plugins.

**Comment by JannisX11** [comment]
As discussed in DM, this is a depth sorting issue that can be resolved by changing the Transparency Render Order of the element.
