### ISSUE TITLE
[Beta] [Issue] Loading bbmodel in 4.9 format does not save textures

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#2101]
### What are you trying to do, and what do you expect to happen?

- Load model in 4.9 b1
- Save
- Open model again

### What happens instead?

-  Model no longer loads textures when opening bbmodel

### Model format in which the issue occurs

BBMODEL

### Blockbench variant

Website, PWA, Program

### Blockbench version

4.9 b1

### Operating System

w11 home

**Comment by JannisX11** [comment]
Is it just not visible on the model, or is the texture list empty?
