### ISSUE TITLE
putting my mobs and blocks into minecraft

### ISSUE THREAD

**Issue by 219wad** [JannisX11/blockbench#2106]
### What are you trying to do, and what do you expect to happen?

im trying to put my skins and blocks and bosses in.

### What happens instead?

nothing happens it loads normal Minecraft.

### Model format in which the issue occurs

it does not do anything

### Blockbench variant

PWA

### Blockbench version

the version that is  used around thanksgiving 2023

### Operating System

windows

### Installed Blockbench plugins

i dont know

**Comment by JannisX11** [comment]
This is the repository for Blockbench, the 3D modeling program.
For support with Minecraft modding, you can ask in Forums or channels about the topic, such as this discord server: https://discord.gg/zpTv3qur3V

**Comment by 219wad** [comment]
the thing is i cant go into discord it bug out also i dont have it
