### ISSUE TITLE
Import/Export from Techne Models 

### ISSUE THREAD

**Issue by Heltrato** [JannisX11/blockbench#212]
I've been using Techne before for modelling purposes (mainly large model projects) before i stop for a while and now returning back to modelling i saw this one and it has most convenient tool to make large models for entities work faster. Hopefully maybe a plugin to be added soon a Import/Export for Techne models so that some of my works from techne can be continue here. I will credit this project also for helping me out. 

[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title if your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any error messages, please attach a screenshot of it to your issue.

Supply the following information:
- Detailed description of your issue
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by GitWither** [comment]
I'll look at Techne's source since what it exports has unsupported encoding

**Comment by GitWither** [comment]
Could you give me some techne models so I can test them?

**Comment by GitWither** [comment]
@Heltrato Just saying, there is now a techne importer plugin available :)

**Comment by SmaIKNT** [comment]
@GitWither Can you please export to techne?

**Comment by JannisX11** [comment]
Added in the plugin "Mod Utils" by JTK222.
