### ISSUE TITLE
Highlight brush line and Undo action don't match

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#2122]
### What are you trying to do, and what do you expect to happen?

Highlighting a brush line by holding shift after undoing the last brush stroke.

### What happens instead?

The highlight line is drawn, but no line is painted, just the single brush stroke.

### Model format in which the issue occurs

All with Paint tab

### Blockbench variant

Program

### Blockbench version

4.9.0

### Operating System

W10

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
Wasn't able to reproduce this issue.

**Comment by PaulFinnerty** [comment]
Just tested again in 4.9.1, the line is not drawn anymore after undoing a brush stroke and holding shift.
Must have been fixed with one of the issues I reported about the highlight brush line.
