### ISSUE TITLE
Add tabula exporter  [Suggestion]

### ISSUE THREAD

**Issue by Abhishek890** [JannisX11/blockbench#213]
Add  model.tbl  support so we can import model from tabula

**Comment by JannisX11** [comment]
Added in the plugin "Mod Utils" by JTK222.

**Comment by BizarreAltispinax** [comment]
I think there should be a Tabula model exporter, so we can export our BlockBench models back to Tabula.

**Comment by NinjagoJay7299** [comment]
i agree we need this desperatly

**Comment by MuddyMudalark** [comment]
I do infact agree with all comments above

**Comment by JannisX11** [comment]
Feel free to create one: https://www.blockbench.net/wiki/docs/plugin
There are no plans to integrate any tabula into Blockbench directly.
