### ISSUE TITLE
UV faces move when creating new textures

### ISSUE THREAD

**Issue by cyanbug01** [JannisX11/blockbench#2133]
### What are you trying to do, and what do you expect to happen?

I was making new textures

### What happens instead?

every other shape that has a texture has the UV shift drastically and i have to change the faces back to how they were

### Model format in which the issue occurs

generic

### Blockbench variant

Program

### Blockbench version

most recent version

### Operating System

windows 11

**Comment by cyanbug01** [comment]
Hello?

**Comment by cyanbug01** [comment]
Can you answer my question?

**Comment by JannisX11** [comment]
This was fixed in 4.9.1 as noted in the [changelog](https://github.com/JannisX11/blockbench/releases/tag/v4.9.1).
If after installing 4.9.1 you are still able to reproduce the issue, please include detailed steps to reproduce, or simply a video of the issue. Thanks!
