### ISSUE TITLE
Breaking textures

### ISSUE THREAD

**Issue by Miiron26** [JannisX11/blockbench#2140]
### What are you trying to do, and what do you expect to happen?

i were trying to add textures

### What happens instead?

https://github.com/JannisX11/blockbench/assets/152911598/e5cab82c-4e5f-4c31-8b1e-efa414cf7584

### Model format in which the issue occurs

Attachment file type: unknown lisa.bbmodel

### Blockbench variant

Program

### Blockbench version

4.9.0.

### Operating System

widows 10

**Comment by JannisX11** [comment]
The update that fixes this is already out.
