### ISSUE TITLE
Paint tab texture editor does not save copy/pasted sections of texture to file upon Ctrl+S

### ISSUE THREAD

**Issue by chef-boyarcheeze** [JannisX11/blockbench#2145]
### What are you trying to do, and what do you expect to happen?

I am trying to save a texture that I made to the file that I am working in, after copying sections of the texture and pasting them elsewhere in the same texture. (Blockbench Paint Tab editor)
![Capture](https://github.com/JannisX11/blockbench/assets/24446092/8ed22995-3131-4906-a93d-d13574198245)

### What happens instead?

The Paint tab editor shows the correctly copied and pasted sections, but the file shows what was there previously before copying and pasting. (Blockbench texture list)
![Capture](https://github.com/JannisX11/blockbench/assets/24446092/da0a2de4-5976-4c5d-89d1-e57996f4358c)

Also, the file outside of Blockbench is similarly not updated. (Paint3D and Gimp)
![Capture](https://github.com/JannisX11/blockbench/assets/24446092/f7e88342-2e69-4f3c-8ead-01ddd77e39f7)

![Capture](https://github.com/JannisX11/blockbench/assets/24446092/e14d0d07-dabd-4e25-bd52-4fe65309c759)

### Model format in which the issue occurs

Geckolib Animated Model

### Blockbench variant

Program

### Blockbench version

4.9.1

### Operating System

Windows 10

### Installed Blockbench plugins

Color Gradient Generator (not used)

**Comment by chef-boyarcheeze** [comment]
Also, hitting refresh brings this window up, where with other textures that are correct, the window does not show up:
![Capture](https://github.com/JannisX11/blockbench/assets/24446092/5aa31bf6-d85b-4a87-a9d2-3594cd652096)

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench/commit/ec49a12a36f00407b210ef94a06b34983eaa4750, to be shipped with 4.9.2.
