### ISSUE TITLE
new box select cannot function on large textures, add back old selector

### ISSUE THREAD

**Issue by Mecanix-Creations** [JannisX11/blockbench#2148]
### What are you trying to do, and what do you expect to happen?

can copy and paste on any texture

### What happens instead?

cannot select and copy parts of the texture to another one, the selector disspears.

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Blockbench version

4.9.1

### Operating System

Windows

### Installed Blockbench plugins

none

**Comment by JannisX11** [comment]
You can with Ctrl+C and Ctrl+V.
