### ISSUE TITLE
Error in Spanish language text 

### ISSUE THREAD

**Issue by Minecraft123siy** [JannisX11/blockbench#2152]
### What are you trying to do, and what do you expect to happen?

I am using the application in English but it is difficult for me, and I hope they fix it in the Spanish language 
![Screenshot_20231218-154441](https://github.com/JannisX11/blockbench/assets/153931893/2d4a7274-d7b1-40db-8c45-9d4c064d1ab7)

### What happens instead?

The problem is that I get bugged texts in the Spanish language 
![Screenshot_20231218-154441](https://github.com/JannisX11/blockbench/assets/153931893/baab8f24-d72f-4002-af05-9e46b7fded85)

### Model format in which the issue occurs

All

### Blockbench variant

Website

### Blockbench version

The most recent 

### Operating System

Android 

### Installed Blockbench plugins

None

**Comment by Minecraft123siy** [comment]
Ami the same 
![Screenshot_20231218-154441](https://github.com/JannisX11/blockbench/assets/153931893/72f8e430-fe36-4581-8fd3-ec6822a8ea16)

**Comment by JannisX11** [comment]
Don't use Google translate to translate the website. Choose your language in File > Preferences > Settings instead.
