### ISSUE TITLE
Connect vertexes is very hard to use on mobile

### ISSUE THREAD

**Issue by DogBat3** [JannisX11/blockbench#2153]
### What are you trying to do, and what do you expect to happen?

Connect vertexes is very hard to use on mobile

I try to use connect for taxes and it doesn’t work unless you pretty much spam click and then it only works sometimes

### What happens instead?

It doesn’t do anything

### Model format in which the issue occurs

BBmodel.txt but I haven’t tried any other models

### Blockbench variant

Website

### Blockbench version

Mobile 

### Operating System

Ipad

**Comment by JannisX11** [comment]
Made the selection area for each vertex larger on touch screens, that should fix this issue.
