### ISSUE TITLE
Unable to donwload or use plugins

### ISSUE THREAD

**Issue by DiddiLeija** [JannisX11/blockbench#2154]
### What are you trying to do, and what do you expect to happen?

I'm currently using some Blockbench plugins, including some from Minecraft (such as the Block Wizard, the Item Wizard, etc.). I would expect to be able to use such plugins and also to download new plugins.

### What happens instead?

Instead, my downloaded plugins (such as the minecraft wizards) does not appear where they used to be in the main menu (below the "Minecraft" model suggestions). When I searched for my downloaded wizards they appeared as installed and active, but their icon images weren't available.

Also, I can't install more plugins. I click the "install" button, but nothing else happens (on a similar way to #2068, but I don't get any error message by now). So, when I deleted my plugins to re-install them (hoping to fix the above issue), I couldn't install them again.

### Model format in which the issue occurs

N/A

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Windows 10

### Installed Blockbench plugins

Minecraft Entity Wizard, Minecraft Item Wizard, Minecraft Block Wizard

**Comment by DiddiLeija** [comment]
I tried to verify on the web version, but it works as expected. I can download and use plugins with no problems. So, there's probably an issue with the app or my installation.

**Comment by JannisX11** [comment]
Check for error messages in Help > Developer > Open Dev Tools > Console tab.
Also try with and without using the CDN Mirror setting in Blockbench.
This could be caused by VPN or network configuration issues or by regionally blocked addresses.

**Comment by DiddiLeija** [comment]
> Also try with and without using the CDN Mirror setting in Blockbench.

Without the CDN mirror, the console tab indeed drops an uncaught error.
However, if I turn on the mirror, everything seems to work as expected! (though a bunch of `Action {some_plugin_related_action} has a duplicated ID`, but the behavior doesn't seem to be affected).

> This could be caused by VPN or network configuration issues or by regionally blocked addresses.

Well, now I also think so. Maybe we can close this issue then, thanks for the support! :)
