### ISSUE TITLE
Broken Session Synchronization

### ISSUE THREAD

**Issue by gravyarts** [JannisX11/blockbench#2163]
### What are you trying to do, and what do you expect to happen?

Creating a session and transforming a model.

### What happens instead?

Model Manipulation does not synchronize between sessions. Encountered this issue while collaborating on a model with my friend. Had to downgrade to ~4.7.0 in order to take advantage of sessions. I'm not sure if this helps, but I'm willing to test versions up to 4.9.2 if it helps!

Here is a [quick video demonstrating](https://youtu.be/aEziOZA-TWU) the bug and the console log from said demonstration.
![image](https://github.com/JannisX11/blockbench/assets/43098489/919fea72-f95d-4bad-a0de-d0441ce723fc)

### Model format in which the issue occurs

Generic* - Have not tested this on other formats.

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Win10

### Installed Blockbench plugins

CEM Template Loader, Animated Java, Animation Sliders, Texture Stitcher, Cameras, Plaster, WASD Controls, Outline Creator, Splash Art Customiser, Discord RPC, Scene Recorder, Pie Menus

**Comment by JannisX11** [comment]
Fixed in 4.9.3.
