### ISSUE TITLE
[Issue] Lefthand display problem

### ISSUE THREAD

**Issue by Cryoroz** [JannisX11/blockbench#217]
Hey,

### **Issues :**

**1)** After loading a model from my computer into Blockbench, I've noticed in the display window that the "First Person Left" slot keeps its default values instead of loading my actual model's values.

**2)** Then if you replace the default values with the values you should have had and save the model, the `"firstperson_lefthand"` preset in the JSON file will be moved at the end of the `"display"` section (which is a not a big problem, but is different from the normal generating order of Blockbench)

### **How to reproduce :** 

**First issue :** 
- Load a model that has rotation, translation or scale values for the `"firstperson_lefthand"` (JSON file) display preset
- Check the "First Person Left" slot in Blockbench to see that your values haven't been loaded

**Second small issue :** 
- Set your values and save your model
- Check the `"display"` section in the JSON file

### **Infos :** 

These issues both occur in the Software and also in the Webapp
_Version : 2.3.1_

(I'm not English by the way so please pardon my English speaking skills ^^")

**Comment by JannisX11** [comment]
Congrats, this is a very well written and structured issue report. The bug will be fixed in the next version/patch.
