### ISSUE TITLE
Cannot customize texture animation for Generic Model

### ISSUE THREAD

**Issue by MelonHell** [JannisX11/blockbench#2170]
### What are you trying to do, and what do you expect to happen?

I want to customize an animated texture for my Generic Model, but the settings are just hidden

Expected result: See full texture settings
![image](https://github.com/JannisX11/blockbench/assets/53826469/0d1801a3-6936-406e-a393-e46df8af630b)

### What happens instead?

See reduced texture settings
![image](https://github.com/JannisX11/blockbench/assets/53826469/acf44857-3214-4347-9cbf-607f54ee4f01)

although the bbmodel file contains the lines I need
![image](https://github.com/JannisX11/blockbench/assets/53826469/298d4ef8-669a-4c44-9b21-877b40e533d3)

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Windows 11

**Comment by JannisX11** [comment]
These options are specific to the Minecraft format "Java Block/Item", they are not available in other formats.
