### ISSUE TITLE
Pivot tool with Local Transform Space is Global, not Local (Misrotated rotate tool in Local Transform space)

### ISSUE THREAD

**Issue by DrageonDB** [JannisX11/blockbench#2174]
### What are you trying to do, and what do you expect to happen?

Step to reproduce:
1. Make a cube
2. Rotate the cube
3. Set the pivot position with Local Transform Space in the cube

Expected Results:
It should be followed with the Local Transform Space

![image](https://github.com/JannisX11/blockbench/assets/110581007/4f19c532-9901-4cf7-ab76-1cf3161279ab)

### What happens instead?

Pivot Local Transform Space is Global Transform Space, look this picture

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Windows 11 22H2

**Comment by JannisX11** [comment]
Duplicate of https://github.com/JannisX11/blockbench/issues/774
