### ISSUE TITLE
Move tool with Local Transform Space is not moving the Pivot position

### ISSUE THREAD

**Issue by DrageonDB** [JannisX11/blockbench#2175]
### What are you trying to do, and what do you expect to happen?

**Step to reproduce:**
1. Add a cube
2. Select the cube
3. Change Transform Space to Local
4. Move the cube

**Expected results:** It should be follow + add a checkbox to prompt user, is it need to move the pivot position or not.

https://github.com/JannisX11/blockbench/assets/110581007/cc479938-526b-4500-a4e7-4441398987f1

### What happens instead?

The cube move with Local Transform Space is not moving the pivot position

### Model format in which the issue occurs

All

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Windows 11 22H2

**Comment by JannisX11** [comment]
Works as intended. The pivot point is the threshold between global/bone and local.
