### ISSUE TITLE
No option to 'paste' saved preset in display mode. (Mac)

### ISSUE THREAD

**Issue by Moderocky** [JannisX11/blockbench#218]
There is a 'new preset' button for saving a set of display rotations and scale values for a model, however, there is no button to load a saved one. This is on Mac.

There also used to be various in-built default presets, such as "block", "tool", "item" and possibly "bow". These are also missing since version 2.0 in the Mac desktop version.

Here is an image of the "new preset" option on Mac. In my version there are no more preset options I can add to the toolbar.
https://i.imgur.com/E7WTss0.png

I have tried reinstalling it. I am on the latest update (currently 2.3.2?)

**Comment by JannisX11** [comment]
Use the menu Display > Apply Preset to apply a default or custom preset in Blockbench 2.0+
