### ISSUE TITLE
Can't open bbmodels/ json files

### ISSUE THREAD

**Issue by Pemarces273** [JannisX11/blockbench#2180]
### What are you trying to do, and what do you expect to happen?

I was trying to open one of my models and I expect the program to load it. ( bbmodels/json )

### What happens instead?

The program instead shows the below:
![Screenshot_13](https://github.com/JannisX11/blockbench/assets/148306311/c9c7b494-bb0b-40e1-8560-55e474ef9b0b)

I could not do anything, changing everything but results are the same as above

### Model format in which the issue occurs

bbmodels, json

### Blockbench variant

Program

### Blockbench version

4.9.2 - 4.9.3

### Operating System

Windows 64 bit

### Installed Blockbench plugins

Animation Sliders

**Comment by JannisX11** [comment]
Are you sure that is the only installed plugin?
Can you send a screenshot of the log? Help > Developer > Open Dev Tools > Console tab.

**Comment by Pemarces273** [comment]
Oh right! I forgot to mention that it somehow fixed itself. I reinstall Blockbench just this morning and it works normally now. Sorry for the report.
