### ISSUE TITLE
Item & Block Wizard do not show up

### ISSUE THREAD

**Issue by EclipseMC-YT** [JannisX11/blockbench#2181]
### What are you trying to do, and what do you expect to happen?

Open Item/Block Wizard
Expected to work fine

### What happens instead?

Item & Block Wizard do not show up in Loaders. Reloading the plugins and restarting the program does not work.

### Model format in which the issue occurs

none

### Blockbench variant

Program

### Blockbench version

4.9.3

### Operating System

Windows 10

### Installed Blockbench plugins

Minecraft Title Generator, Minecraft Item, Block, & Entity Wizard, Animated Java, Player Statue Generator, Shape Generator, Animation Sliders, Seat Position + Hitbox, Resourcepack Packager, Colour Gradient Generator, Preview Scene Customiser, Brush Plus, Skin Mirror, WASD Controls, Cameras, Outline Creator, Ambient Occlusion, Plaster, Minecraft Skin Pack Packager, Structure Importer, Missing Texture Highlighter, Splash Art Customiser, Code View, Voxel Importer, Tint Preview, Bakery, Custom Marker Colors, Bedrock Block Exporter, Clone Brush, Reference Models, Workspaces, Light Tracer Uploader, Activity Tracker, Performance Audit, CraftStudio Model Format, Pie Menus, Startup Tips, Screencast Keys, Explorer, Grayscale Preview, Collapsible Start Screen Categories, Backup Viewer, Bedrock Entity Model Presets, Bedrock Pivot Fix 2, Text Generator

**Comment by EclipseMC-YT** [comment]
am sad

**Comment by JannisX11** [comment]
Since you have more than 40 plugins installed at once, my first recommendation would be to uninstall all plugins except for the Item Wizard and Block Wizard, restart Blockbench and try again.

**Comment by EclipseMC-YT** [comment]
ok

**Comment by EclipseMC-YT** [comment]
> Since you have more than 40 plugins installed at once, my first recommendation would be to uninstall all plugins except for the Item Wizard and Block Wizard, restart Blockbench and try again.

Test failed to work.

**Comment by JannisX11** [comment]
Can you send a screenshot of the log? Help > Developer > Open Dev Tools > Console tab.

**Comment by EclipseMC-YT** [comment]
I fixed it. I just had to uninstall and reinstall the plugins.
