### ISSUE TITLE
Exporting/Import Color palettes in different formats

### ISSUE THREAD

**Issue by MadstonMagic** [JannisX11/blockbench#2183]
### Detailed description of your suggestion

Hi,

I have tried looking around for this but couldn't find anything.. But it would be really helpful if there's a way to import and export color palettes.
I usually go to lospec.com for pixel art palettes but the downloads are in a specific format. They're in a PNG format where all colors are loaded from left to right. It would be cool if there's an option within BlockBench to import such PNG palettes and name the newly added palette the name of the file name. So imagine me downloading `firecolors_v1.png`, add it to BlockBench, it will add a new palette called `firecolors_v1`.

However not just importing would be cool, exporting would be super useful as well! Exporting in the same PNG format for example but also in Paint.NET format, Aseprite or Photoshop. Not sure how reasonable this would be but it would help alot.

Thanks!

**Comment by JannisX11** [comment]
Blockbench supports importing color palettes in a variety of different formats, including .gpl, .hex, .css, .txt, .png, .aco, .act and .ase.
Export is also supposed as .gpl, which is a widely supported format.
