### ISSUE TITLE
Trying to delete a vertex, edge, or face off a mesh deletes the whole mesh

### ISSUE THREAD

**Issue by ThatStrangeDoll** [JannisX11/blockbench#2184]
### What are you trying to do, and what do you expect to happen?

I select an edge, vertex, or face of a mesh, right click and hit Delete. This should delete the selected edge, vertex, or face off the mesh as it has done in the past.

### What happens instead?

Instead, after hitting delete, the whole mesh is deleted as if I had selected all of it.

### Model format in which the issue occurs

.bbmodel

### Blockbench variant

Program

### Blockbench version

4.9.3

### Operating System

Windows 10

**Comment by JannisX11** [comment]
Fixed in 085ecdae63f171e2e3508bfb23fbf06bc1f33101
You can press the Delete key on your keyboard for now.
