### ISSUE TITLE
I use the chrome version of blockbench and I only sometimes i can download animations or models and stuff for my custom Wither Storm addon

### ISSUE THREAD

**Issue by AGoofsterThatIsGoofy** [JannisX11/blockbench#2188]
### What are you trying to do, and what do you expect to happen?

I'm trying to export my animation files and my geo.json, animation files (.json) or .bbmodel files

### What happens instead?

Nothing happens and the files aren't downloaded into my android's download folder.

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Website

### Blockbench version

Latest Version

### Operating System

Android

**Comment by JannisX11** [comment]
This is most likely an issue with Chrome. You can try these steps: https://support.google.com/chrome/thread/240279398/issues-downlaoding-files-in-chrome?hl=en#:~:text=Go%20to%20"Settings%20>%20Privacy%20and,"%20Click%20"Clear%20data."&text=Conflicting%20extensions%20might%20cause%20download,see%20if%20the%20problem%20persists.

**Comment by AGoofsterThatIsGoofy** [comment]
so way before this response I used the opera browser for my model downloads
but thanks for helping with the chrome browser problem.
