### ISSUE TITLE
Image scale does the same as crop/expand

### ISSUE THREAD

**Issue by SuXYIO** [JannisX11/blockbench#2196]
### What are you trying to do, and what do you expect to happen?

Trying to resize a texture by scale, went to Image-ResizeTexture-Scale and imputed the size I want. 
Expect the texture to resize and fill the whole canvas. 

### What happens instead?

Instead, the original image is at the left-top and the rest of the canvas is empty. 

### Model format in which the issue occurs

image, .png

### Blockbench variant

Program

### Blockbench version

4.9.3.428

### Operating System

MacOS

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Fixed in 4.9.4.
