### ISSUE TITLE
[Suggestion] Search bar for actions

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#220]
Search bar for actions. sometimes its hard to find some actions or don't know where they are located, this could be useful for new users.

The search bar could suggest limited amount of options or have a scroll bar so it doesn't fill the whole screen when searching for an action.

![image](https://user-images.githubusercontent.com/44243757/51079090-d5a35700-16c9-11e9-95b7-947b8eba8d62.png)

**Comment by JannisX11** [comment]
May I present: "Action Control"

![image](https://user-images.githubusercontent.com/29278436/51086205-fc05d880-1743-11e9-8eb2-055f7fcf16dd.png)
