### ISSUE TITLE
Can't export animation with using locator and nullobject

### ISSUE THREAD

**Issue by DevLofell** [JannisX11/blockbench#2201]
### What are you trying to do, and what do you expect to happen?

I'm trying to import my modeling in unreal. i checked when i changed objects(not nullobject) values(transform, rotation, etc.) that can export animation(glTF format), but when i using nullobject with locator(i checked ik root and ik target) i can't export with glTF format.
![image](https://github.com/JannisX11/blockbench/assets/45657506/952c1af1-483f-4595-a936-5d9fc72f1530)
![image](https://github.com/JannisX11/blockbench/assets/45657506/44eee058-dd8d-4574-ac36-93a4620b3a65)
![image](https://github.com/JannisX11/blockbench/assets/45657506/9eb9fdda-5092-40dd-ae08-bb0ab4f4ca64)
![image](https://github.com/JannisX11/blockbench/assets/45657506/e428d245-e73b-4f66-a9ae-6c0a30266d5d)

### What happens instead?

.

### Model format in which the issue occurs

glTF

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows

**Comment by DevLofell** [comment]
but if i not use null obj and locator then when i use just change only transform,rotation and scale animation. it works

**Comment by MrJoshBowman** [comment]
Same exact issue. Trying to export animations using target/null will not let me export as GLB. I want to be able to export as armature so that I can play animations with GLB models in PowerPoint.
