### ISSUE TITLE
[BUG] Exported models with GLTF / GLB broke the animations.

### ISSUE THREAD

**Issue by MrScautHD** [JannisX11/blockbench#2204]
### What are you trying to do, and what do you expect to happen?

Loading the model into model viewers, and played the animations. (like this: https://sandbox.babylonjs.com/)

### What happens instead?

But the model starts to brake:

Instead of:
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/9d166264-9a2b-452a-a680-f28b9db85189)

It looks like this:
![image-1](https://github.com/JannisX11/blockbench/assets/65916181/8bbd49ec-5978-4752-b6c7-bf2e4fbcb359)

### Model format in which the issue occurs

GLTF / GLB

### Blockbench variant

Website, Program

### Blockbench version

4.9.4

### Operating System

Windows 11

**Comment by MrScautHD** [comment]
@JannisX11 already fixed?

**Comment by MrScautHD** [comment]
It looks like the animations get mixed

**Comment by JannisX11** [comment]
Could you test if this is still an issue in the 4.10 beta? https://github.com/JannisX11/blockbench/releases/tag/v4.10.0-beta.1

**Comment by MrScautHD** [comment]
> Could you test if this is still an issue in the 4.10 beta? https://github.com/JannisX11/blockbench/releases/tag/v4.10.0-beta.1

Still broken :(

**Comment by MrScautHD** [comment]
@JannisX11 is it still an issue?

**Comment by JannisX11** [comment]
I am not sure, I have tested a few models during beta and haven't run into the issue since. If you can still reproduce it, please share the model and configuration so that I can recreate it on my end.

**Comment by MrScautHD** [comment]
@JannisX11 Here is a model build with the latest Blockbench version:
[Player-Female-new.zip](https://github.com/JannisX11/blockbench/files/15366253/Player-Female-new.zip)
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/bffdd377-7420-4750-a6ab-aa938e53fa14)

**Comment by MrScautHD** [comment]
And here are the arms up
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/4a31b79e-d3ec-4285-8484-b52150726511)

it looks like the animation blending in one.

That is how it should looks like:
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/a6b8daf0-3f8c-4730-ac9b-866114b53cc3)

**Comment by JannisX11** [comment]
Could you share the bbmodel file with the export configuration of an affected model so that I can try and reproduce it?

**Comment by MrScautHD** [comment]
@JannisX11 
[Player-Female.zip](https://github.com/JannisX11/blockbench/files/15368709/Player-Female.zip)

**Comment by MrScautHD** [comment]
@JannisX11 do you found the error?

**Comment by JannisX11** [comment]
Yup, it happens because the arm bones have a 90 degree angle in edit mode. The armature animation doesn't handle that correctly. I'm working on a fix.

**Comment by MrScautHD** [comment]
@JannisX11 And what about the mixing of the Animations i mean in idle the hands move upwards, the feed is rotated wierd... Should that get fixed too?

**Comment by JannisX11** [comment]
Fixed 🎉

**Comment by glitch128** [comment]
has the site been updated yet?

**Comment by MrScautHD** [comment]
@JannisX11 

Amazing work, thx.
But there a still some small issues

If you see one shoe is a bit more rotated down as the other one
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/b23601b8-6d2b-4fd9-825b-9e6913ed3184)

But in blockbench it works fine:
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/26e41c91-0059-4c51-87fe-3b5b22913c00)

Even for the arms:
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/c9244e20-734a-4b94-9575-58d33f42ddfd)

In blcokbench:
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/d4705827-198a-49fb-8c0b-86fed95171b3)


But it looks like this happans when seting a diffrent animation like from walk to idle the hands working fine but by moving from run to idle the hands breaks. (Like the old pos of the animations not reset just get overriden)

**Comment by MrScautHD** [comment]
But i see right now the issue comes from (https://sandbox.babylonjs.com/)

Because with the windows model viewer it works fine.
![grafik](https://github.com/JannisX11/blockbench/assets/65916181/9e8809a3-7794-4cc4-ae88-97631c2fc576)

**Comment by glitch128** [comment]
looks fine on https://glb.ee/ as well. maybe it's just a thing with babylon
