### ISSUE TITLE
Missing geometry when importing .obj from Blender

### ISSUE THREAD

**Issue by sighlessm** [JannisX11/blockbench#2206]
### What are you trying to do, and what do you expect to happen?

I made a simple model in Blender and exported as .obj to texture it in blockbench.
![blendergenerator](https://github.com/JannisX11/blockbench/assets/86335202/27ccc719-f5cc-4353-9720-c86287f69fb4)

### What happens instead?

The imported model is missing geometry and has holes all through it and vertices that are connected which even aren't connected in Blender.
![test](https://github.com/JannisX11/blockbench/assets/86335202/ea0695e1-1691-49b3-8900-63b63152b7a9)

### Model format in which the issue occurs

Generic

### Blockbench variant

Program

### Blockbench version

4.9.3/4.9.4 (also tested 4.8.3)

### Operating System

Windows 11

**Comment by sighlessm** [comment]
A slightly different result after a limited dissolve in Blender
![testwlimiteddissolve](https://github.com/JannisX11/blockbench/assets/86335202/8a063bfd-2f7f-44ac-afc1-d07c6777cc65)

**Comment by sighlessm** [comment]
I solved this on the blender end. In the .obj export options under the Geometry drop-down, there is an option "triangulate faces" that needs to be checked
![image](https://github.com/JannisX11/blockbench/assets/86335202/8bce7a2d-93e1-410b-8d9b-88fe172fbfa6)

**Comment by FatGapingHole** [comment]
Omg Thank you so much for posting your solution you saved my butt!!!
