### ISSUE TITLE
No loop cut

### ISSUE THREAD

**Issue by for-comments** [JannisX11/blockbench#2211]
### What are you trying to do, and what do you expect to happen?

In the web app, when on generic model, the loop cut does not exist. I am trying to follow a tutorial and it requires loop cut. I'm on a chromebook without a mouse if that helps.

### What happens instead?

I just said.

### Model format in which the issue occurs

Generic model

### Blockbench variant

Website

### Blockbench version

I dont know

### Operating System

Chromebook

**Comment by JannisX11** [comment]
It does exist. Make sure to create a mesh and select one of the faces to cut it. If you can't find it in the toolbar, you can use it from the context menu or from Help > Search and Run Action.
