### ISSUE TITLE
4.7.0 Beta 1 - Still no GLB armature export

### ISSUE THREAD

**Issue by MrJoshBowman** [JannisX11/blockbench#2222]
### What are you trying to do, and what do you expect to happen?

I want to download the GLB file with 'convert to armature' option selected.

### What happens instead?

Every time i tick the 'export as armature' option when exporting GLB, it doesn't generate any file to download. Only when i untick it does the app allow me to download the file. I want to download the file with armature animations though.

### Model format in which the issue occurs

GLB

### Blockbench variant

Website

### Blockbench version

4.7.0 Beta 1

### Operating System

Windows

**Comment by JannisX11** [comment]
Why are you using that version? It's long outdated.

**Comment by MrJoshBowman** [comment]
how embarrassing....I swear I'm getting dumber as I age...
