### ISSUE TITLE
Swap tools does not work

### ISSUE THREAD

**Issue by program-beta** [JannisX11/blockbench#2225]
### What are you trying to do, and what do you expect to happen?

swap the tool i hold to another. by pressing space. this does not happen

### What happens instead?

100% of the time it just selects color picker. I so do not care about color picker, i do not like color picker, and that is all it does. If you remove color picker? It just swaps to "nothing". Notably, there is no swapping of any kind, and I assume swapping is what that button that says 'swap' would do. Instead it is just a super annoying color picker hotkey

### Model format in which the issue occurs

image

### Blockbench variant

Program

### Blockbench version

4.9.3

### Operating System

win 10

**Comment by JannisX11** [comment]
Not an issue, the color picker is the alt tool for most paint tools.
For configuring this, you can upvote #1777

**Comment by program-beta** [comment]
but I never used alt? I specifically used swap tools. And it then remains stuck on color picker. So it is just not doing what it says it will do. heck, if it alternated between color picker and brush, then that would be 'swapping', but no matter how many times i press spacebar it remains on color picker, which is not what swapping is. I guess I am confused why color picker has anything to do with 'swap tools' specifically, color picker is just another tool, why is it treated specially for that hotkey?
