### ISSUE TITLE
when you press ctrl or shift, the object is still scaled by 1 pixel

### ISSUE THREAD

**Issue by Aurum68** [JannisX11/blockbench#2228]
### What are you trying to do, and what do you expect to happen?

I'm trying to scale an object by 0.1 pixels. To do this, I press ctrl according to the instructions.

### What happens instead?

However, instead, the object is scaled by 1 pixel. More precisely, the program interface says that there is a change of tenths of a pixel. However, the object is not scaled.

### Model format in which the issue occurs

Modding Entity

### Blockbench variant

Website, Program

### Blockbench version

4.9.4

### Operating System

Windows

**Comment by JannisX11** [comment]
As explained on the format screen of Modded Entity, cube sizes are limited to integers. This is a restriction by the format. It can be disabled in the settings under "Modded Entity Integer Size", but that makes UV hard to work with.
