### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by Jae-Kyaah** [JannisX11/blockbench#2230]
### What are you trying to do, and what do you expect to happen?

When I open the blockbench and when I create new project the (Faces, Vertices and edges) won't show up 

### What happens instead?

I tried to look for it to the point i even resetted the tools and restarting the software and it won't show up.
![image_2024-03-15_024800328](https://github.com/JannisX11/blockbench/assets/89892691/f6521d77-d951-4a0d-9fbc-f2c05ad1dde8)

### Model format in which the issue occurs

N/A

### Blockbench variant

PWA

### Blockbench version

4.9.4

### Operating System

WIndows

**Comment by JannisX11** [comment]
The tools in question are only usable when a mesh is selected.
