### ISSUE TITLE
Display settings not displaying & exporting scale correctly

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#2232]
When opening the following model in blockbench, it displays the X axis scale as `0.4`. rather than `-0.4`
When exporting the model, it still exports it as `-0.4`, despite displaying it as `0.4`

```json
{
	"elements": [],
	"display": {
		"firstperson_righthand": {
			"rotation": [0, 45, 0],
			"translation": [0, 6.5, 0],
			"scale": [-0.4, 0.4, 0.4]
		}
	}
}
```

### Model format in which the issue occurs

Java Block/Item

### Blockbench version

4.9.4

**Comment by JannisX11** [comment]
Not an issue. Display scale has mirror options, however they are hidden by default because they are pretty much useless in recent Minecraft versions due to backface culling. They can be enabled in the settings though.
