### ISSUE TITLE
Exported models with transparent textures are always opaque when imported elsewhere

### ISSUE THREAD

**Issue by ZedDevStuff** [JannisX11/blockbench#2234]
### What are you trying to do, and what do you expect to happen?

Exporting a simple cube with a semi transparent texture as gltf, fbx or obj then importing that in Unity or Blender should have the model render correctly 
![image](https://github.com/JannisX11/blockbench/assets/98429642/fce33a37-5d3a-46bd-97a0-593f6c9ebd40)

### What happens instead?

The model material in the target software is opaque 
![image](https://github.com/JannisX11/blockbench/assets/98429642/f5fba810-dc2e-4429-b301-76d1f00c8054)
![image](https://github.com/JannisX11/blockbench/assets/98429642/3f79d8c3-a548-414f-a58a-c09f571002ee)

### Model format in which the issue occurs

.obj, .fbx, .gltf and .glb, .dae

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 11 

### Installed Blockbench plugins

GeckoLib Animation Utils, Shape Generator, Brush Plus, WASD Controls, Optimize, VoxelShape Generators, Figura Model Format

**Comment by JannisX11** [comment]
This is not an issue with Blockbench. Translucency requires additional setup in most other 3D application. The alpha channel is saved to the texture, but reading transparency values between 0 and 1 directly from the alpha channel is not something that most 3D applications or formats support.
