### ISSUE TITLE
Auto Pack UVs

### ISSUE THREAD

**Issue by mcrimson974** [JannisX11/blockbench#2236]
### Auto Pack UVs

Is there a way to Pack the UVs of an object automatically? Preferably using the empty spaces of an existing texture so it doesn't overlap existing UVs. 

This is useful when adding elements to an existing textured object without altering the texture and still being able to use the same texture.

![image](https://github.com/JannisX11/blockbench/assets/46675520/0e58b561-db6d-4f7e-8c01-165fed62d55b)

**Comment by JannisX11** [comment]
Closing because this already exists as Append Elements to Template

**Comment by mcrimson974** [comment]
Is it possible to add a padding when doing so?

**Comment by mcrimson974** [comment]
Also, when using Append Elements to Template, some faces becore transparent.
