### ISSUE TITLE
Preview Skin Torso is displayed mirrored on front and back

### ISSUE THREAD

**Issue by UnhelpfulRevelations** [JannisX11/blockbench#224]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title if your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any error messages, please attach a screenshot of it to your issue.

Supply the following information:
- Detailed description of your issue
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by JannisX11** [comment]
Fixed in 2.4.
