### ISSUE TITLE
Add an animated texture frame property to animation keyframes(not an april fools joke)

### ISSUE THREAD

**Issue by Coderchris842** [JannisX11/blockbench#2255]
### Detailed description of your suggestion

Let us control what frame an animated texture is on with an animation. This would make it a lot easier to make characters with multiple expressions.

**Comment by Coderchris842** [comment]
this is not an April fools joke I just happened to be working on this today and did not want to wait a day to make a suggestion.

**Comment by JannisX11** [comment]
This is already possible.

You can set the value of a variable using Instruction keyframes in the Effect animator.
![image](https://github.com/JannisX11/blockbench/assets/29278436/e50e41c2-4a97-4eea-9cf9-07b551ccebd3)
Set the texture frame value in the keyframe panel:
![image](https://github.com/JannisX11/blockbench/assets/29278436/a8029988-0d54-4456-a259-03ef29fd61a2)
Then, to link it to the preview, set `preview.texture_frame` to the variable value in the Variable Placeholder panel:
![image](https://github.com/JannisX11/blockbench/assets/29278436/9ef25e36-81e8-4973-8216-3d7468eef027)

**Comment by Coderchris842** [comment]
I am using a generic model.

**Comment by Coderchris842** [comment]
Instructions cannot be used for a generic.
