### ISSUE TITLE
Painting on an individual block is Mirroring on a different part of body

### ISSUE THREAD

**Issue by PeterGriffinater** [JannisX11/blockbench#2261]
### What are you trying to do, and what do you expect to happen?

I’m trying to paint on a new block on a model i just added, i was expecting it to paint individualy

### What happens instead?

Whenever i try painting something, it keeps mirroring onto other random parts of a model that i’m sure aren’t linked in any way, because i didn’t copy/paste  anything, i added a whole new block, yet it won’t stop

### Model format in which the issue occurs

Projectile/3d gun model

### Blockbench variant

Program

### Blockbench version

Unknown

### Operating System

An app on ios

**Comment by JannisX11** [comment]
Not an issue, you just need to understand UV mapping. I recommend watching some beginner tutorials.
