### ISSUE TITLE
Issue Summary - Model Export Bug

### ISSUE THREAD

**Issue by smell-of-curry** [JannisX11/blockbench#2264]
### What are you trying to do, and what do you expect to happen?

Hello, I'm trying to export this model I made into a Minecraft Bedrock Entity Geometry. I have exported many models before and had no problems. However, this new model has been giving me some issues when exporting through Blockbench. It should just export the exact model with no problems.

![mewtwo](https://github.com/JannisX11/blockbench/assets/75345244/18c75fa2-528b-469e-80e4-5d0637aead9e)

### What happens instead?

However, when I export the model the model loses its legs. Resulting in a no-legged entity. 

I have attached the bbmodel that I am using, and the result I got when exporting it.
[Mewtwo_Model.bbmodel](https://cdn.discordapp.com/attachments/1226637543986954371/1226637638656589996/mewtwo_model.bbmodel?ex=66257e52&is=66130952&hm=6d42cd6d7fa65ec2cdda696612e0dd18236ce7052716c005eed86f15eab691ec&)

Exported file result:
[mewtwo.geo.json](https://github.com/JannisX11/blockbench/files/14898971/mewtwo.geo.json)

![image](https://github.com/JannisX11/blockbench/assets/75345244/64235307-e3bd-4f90-bb81-7e7c595e4406)
its

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 10

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
Not an issue, you have export disabled on some elements
![image](https://github.com/JannisX11/blockbench/assets/29278436/cd24a8b6-d6a8-4abe-8d1e-54931febe38b)

**Comment by smell-of-curry** [comment]
Thank you so much! Sorry about the post.
