### ISSUE TITLE
[Issue] Cant Export as Blockmodel or Save

### ISSUE THREAD

**Issue by Aaron2550** [JannisX11/blockbench#227]
I used the Desktop app for Win64, and when i try to click on export as Blockmodel or save, nothing happens although OptiFine JPM works and .obj too, heres my error log thingy https://i.imgur.com/eWqVKzb.png if yall got ANY idea, tell me i need to freaking export this model, it took me ages... thanks for any help

**Comment by JannisX11** [comment]
Fixed in 2.4.
