### ISSUE TITLE
Cannot drag cube UV with "Move Texture with UV" enabled

### ISSUE THREAD

**Issue by Cubouse** [JannisX11/blockbench#2277]
### What are you trying to do, and what do you expect to happen?

Click and drag the UV of a cube in the UV tab, when it has a texture assigned.

### What happens instead?

The UV is unmovable, whether the UV mode is Per-face or Box.

It does not seem to affect meshes, only cubes.

### Model format in which the issue occurs

Bedrock entity, Generic

### Blockbench variant

Program

### Blockbench version

4.10.0 Beta 1

### Operating System

W10

### Installed Blockbench plugins

N/A

**Comment by JWartofsky3** [comment]
I'm encountering this as-well. What was the fix? I'm unable to move any UVs in the bedrock entity format.

**Comment by Manik1348** [comment]
Тоже самое. Решили?
