### ISSUE TITLE
Rotating a 6-sided cylinder causes edges to become slightly uneven

### ISSUE THREAD

**Issue by aaronGlawson64** [JannisX11/blockbench#2281]
### What are you trying to do, and what do you expect to happen?

I have a cylinder that has been resized by selecting all of the faces with the "resize" tool. I'm trying to turn the cylinder 90 degrees on it's side by selecting all of it's faces and using the rotate tool, and then turn it 30 degrees so that one face lays flat along the x/z plane.

### What happens instead?

One face edge sits at 5.9067 on the Y-axis, while the opposite edge sits at 5.9134 on the Y-axis. It's not a huge difference, but is noticeable when the edge lies close to an edge that is level.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 10

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Cannot reproduce the issue on my end.
Make sure when you create the cylinder, "Align Edges" is enabled. Also make sure the pivot is at the center and has not been modified.

If this is still an issue, please send a video explaining how to reproduce it.
