### ISSUE TITLE
GIF transparency issue

### ISSUE THREAD

**Issue by YkVox** [JannisX11/blockbench#2283]
### What are you trying to do, and what do you expect to happen?

making a GIF animation using transparent textures does not render said textures as expected

_how the model looks in the editor_
![image](https://github.com/JannisX11/blockbench/assets/61479000/d67170a4-4b0d-49e5-ab11-e17dbe37ab26)

### What happens instead?

exporting it to gif cuts the transparent part of the textures using the Scene Recorder plugin

![Transposia_animation](https://github.com/JannisX11/blockbench/assets/61479000/af22f766-a3b0-4e6b-8526-0e6ce629fd3e)

and the default behavior of the GIF exporter gives for even worse results...
![animation2](https://github.com/JannisX11/blockbench/assets/61479000/52479a2f-1f78-474e-977d-9ec375561ba6)

i'd be glad for any help !

### Model format in which the issue occurs

.bbmodel

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 11

### Installed Blockbench plugins

Scene Recorder

**Comment by JannisX11** [comment]
GIFs don't support partial transparency. I would recommend adding a background image, or recording in APNG or PNG Sequence instead.
