### ISSUE TITLE
"Center View On Selection" keybind does not respect modifier keys 

### ISSUE THREAD

**Issue by Cart3r1234** [JannisX11/blockbench#2288]
### What are you trying to do, and what do you expect to happen?

I have "Center View On Selection" as Shift + C, and "Center Pivot" as C with no modifiers.  Pressing C alone should only center the pivot, and pressing Shift + C should center the view on the selection

https://github.com/JannisX11/blockbench/assets/69820300/9dbc9f3b-4158-4d00-a369-39e14b20369a

### What happens instead?

Both happen when shift is not held.

### Model format in which the issue occurs

All

### Blockbench variant

Website, Program

### Blockbench version

4.10 Beta, 4.9.4

### Operating System

Windows 11

### Installed Blockbench plugins

Reproduceable with a fresh install/no plugins

**Comment by JannisX11** [comment]
Not an issue. Shift is an optional modifier key, which you can tell from the fact that it is gray and in square brackets. It causes the camera to shift rather than rotate to center it.
Since optional modifiers cannot be reassigned, I would recommend using another modifier key such as Alt.

**Comment by Cart3r1234** [comment]
Ah, I wasn't aware that it had 2 behaviors depending on if shift was held or not, and didn't notice that optional/non-optional modifiers were displayed differently in the keybinds list.  Thanks
