### ISSUE TITLE
Layer perspective error

### ISSUE THREAD

**Issue by ghost** [JannisX11/blockbench#2293]
### What are you trying to do, and what do you expect to happen?

Layer perspective error, fix it

### What happens instead?

![1714004738](https://github.com/JannisX11/blockbench/assets/65935235/1f1b5d1e-1aee-4e26-bf8b-54974dc0b091)
Layer perspective error

### Model format in which the issue occurs

any

### Blockbench variant

Program

### Blockbench version

v4.10.0-beta.1

### Operating System

Windows 11 Pro Workstation 22635.3495

### Installed Blockbench plugins

Non

**Comment by JannisX11** [comment]
What is this? Is this supposed to be a bug report?
