### ISSUE TITLE
When Selecting All Faces Using All Faces Are Not Shown On The UV Overlay

### ISSUE THREAD

**Issue by simonpaulkeating** [JannisX11/blockbench#2294]
### What are you trying to do, and what do you expect to happen?

When selecting all faces using Ctrl+A not all the faces are shown on the UV window. If I select the faces manually one by one however, the faces each get highlighted on the UV window one by one as expected. I would expect that using select all faces would highlight all faces in the UV window just as if I had selected them one by one manually.

### What happens instead?

When selected all faces using ctrl+a or the menu option; only the first face selected is highlighted in the UV window.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 10

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Has already been fixed in the latest beta.

**Comment by simonpaulkeating** [comment]
Great! thank you so much!!
