### ISSUE TITLE
Plugin settings do not trigger `onChange()` when changed through the plugin settings tab.

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#2297]
Plugins that add custom settings get their settings added to the settings tab on their plugin page. If you change the setting from here, it does not trigger the `onChange()` function if you have that defined in your setting.

**Comment by Traben-0** [comment]
I've experienced this as well.

My first intuition for changing plugin settings was to do it in the plugins menu settings tab, which then didn't work without restarting BB
