### ISSUE TITLE
Layer perspective error

### ISSUE THREAD

**Issue by LingLing1301** [JannisX11/blockbench#2299]
### What are you trying to do, and what do you expect to happen?

Please fix it

### What happens instead?

Error:
![1714099535](https://github.com/JannisX11/blockbench/assets/65935235/29ae2562-f8e3-42ea-82bd-159b6c4a2074)

Normal should be like this:
![1714099557](https://github.com/JannisX11/blockbench/assets/65935235/d42e5323-f145-4360-8293-22fbdf03ff6e)

Models and image:
[tube_coral_fan.json](https://github.com/JannisX11/blockbench/files/15124703/tube_coral_fan.json)

![tube_coral_fan](https://github.com/JannisX11/blockbench/assets/65935235/d8ca4c8d-cde9-4d40-a550-bcb47e1785b7)

this is a model and a png image(include alpha channel), when i open in blockbench, actually its Layer perspective error, for normal, i should be able to see other cube texture behind transparent pixels, but in some cases, Blockbench cant show other cube texture behind transparent pixels, just only see the background

when size of image >1024x1024, and >5 cubes in a model, and that image include alpha channel, this problem will appear

not any (red) error messages in Dev Tools

### Model format in which the issue occurs

tube_coral_fan.json

### Blockbench variant

Program

### Blockbench version

4.10.0-beta.1

### Operating System

Windows 11 Pro Workstation 22635.3495

### Installed Blockbench plugins

Non

**Comment by JannisX11** [comment]
This is just an issue with the image that you are using. The background has a bit of transparent color.
You can easily fix this by going to paint mode, selecting the background using the Magic Wand tool, and pressing Delete.
