### ISSUE TITLE
[Issue] "Extrude from texture" dialogue doesn't close

### ISSUE THREAD

**Issue by FiskFille** [JannisX11/blockbench#23]
I've tried it out a couple of times - after clicking the scan button, the progress bar fills up. Presumably it's done its job and the extrusion works, but there is no way that I have found of actually closing the dialogue. It does not recognize any key presses aside from ENTER, which triggers the scan again, creating duplicates. Only way I've gotten rid of it is restarting the program entirely.

**Comment by modmuss50** [comment]
I can also confirm this, happens on both the downloaded app, and the web app.

**Comment by JannisX11** [comment]
Fixed in 1.4.2.
