### ISSUE TITLE
Issue SummaryCan't use tools that show up as "hidden"

### ISSUE THREAD

**Issue by Kekaki4** [JannisX11/blockbench#2304]
### What are you trying to do, and what do you expect to happen?

When I try to use this tool, it is marked as "hidden" and I cannot use it.

### What happens instead?

I can't use the tool

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 10 22H2

### Installed Blockbench plugins

None

**Comment by Kekaki4** [comment]
Example 
![изображение](https://github.com/JannisX11/blockbench/assets/165322026/0bed3224-1f9f-4027-8b9b-4d24ecce10e2)

**Comment by JannisX11** [comment]
It's totally normal that tools that are unavailable and hidden cannot be used. For example if they are not compatible with the current project type or nothing is selected.
