### ISSUE TITLE
Image editor error

### ISSUE THREAD

**Issue by Milouvert** [JannisX11/blockbench#231]
On a Mac (macOS 10.14 Mojave). Picking image editor on the Webapp doesn't seem to accept .app application files, which are Mac's executable files.

![capture d ecran le 2019-01-27 a 23 30 36](https://user-images.githubusercontent.com/38847520/51814924-bee52e80-228b-11e9-8cb8-51edefa2433e.png)
_(Choosing the editor)_
![capture d ecran le 2019-01-27 a 23 31 15](https://user-images.githubusercontent.com/38847520/51814949-e9cf8280-228b-11e9-8a57-729ddfa3a541.png)
_(Error: Can't find an image editor)_
![capture d ecran le 2019-01-27 a 23 35 23](https://user-images.githubusercontent.com/38847520/51815014-3ca93a00-228c-11e9-8628-7963de83b9f2.png)
_(Every app is grayed out, I can't choose any of them)_

**Comment by JannisX11** [comment]
You can't use an image editing program in the web app.
The file type "app" will be added in the next version.

**Comment by JannisX11** [comment]
Added ".app" in 2.4.
