### ISSUE TITLE
Model Is Clipping with itself inside the building but outside is fine

### ISSUE THREAD

**Issue by tuiio** [JannisX11/blockbench#2312]
### What are you trying to do, and what do you expect to happen?

I made a juggernog machine but its bugging out. also i cant join the discord, i think i got banned from when i got my account stolen and it spammed servers. plz consider unbanning me

![image](https://github.com/JannisX11/blockbench/assets/56172316/d3a03893-7cc2-4c43-ab42-a1682f342fce)
![image_2024-05-02_140240113](https://github.com/JannisX11/blockbench/assets/56172316/027eedda-b8bb-4d2e-9f6a-49def412bd1b)
![image2](https://github.com/JannisX11/blockbench/assets/56172316/dd7cadd3-bc23-4dd6-ad9e-b1ff4108016d)

### What happens instead?

it is clipping itself sometimes but not others

### Model format in which the issue occurs

Bedrock Block

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 11

### Installed Blockbench plugins

3d Text Generator

My Discord is: mazed_
or Mazed#7314

ID: <@402981809824071701>

**Comment by Nineforcestudios** [comment]
i suggest moving the text a bit further forward Cause its called Z-Fighting
