### ISSUE TITLE
Move tool no longer aligned with rotated cube on new update.

### ISSUE THREAD

**Issue by Twebster9000** [JannisX11/blockbench#2323]
### What are you trying to do, and what do you expect to happen?

The axis to move cubes should be aligned with the rotation of the cube, and was like this previously.

### What happens instead?

![Screenshot 2024-05-09 121714](https://github.com/JannisX11/blockbench/assets/63675090/ec7be3cd-2781-448f-b609-3930d1bfbefb)
Movement axis is not aligned to the rotation of the cube.

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Blockbench version

Blockbench v4.10.0

### Operating System

Windows 11

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
The default value has in deed changed, but this is not an issue. You can switch between transform spaces here in the toolbar.
![image](https://github.com/JannisX11/blockbench/assets/29278436/7d92c618-6314-4bf4-8b69-111708d6db10)
