### ISSUE TITLE
[Suggestion] Make the color picker take the color's alpha

### ISSUE THREAD

**Issue by atchimgripo** [JannisX11/blockbench#2328]
### Detailed description of your suggestion

it's a simple thing which some other programs already do, would make texturing with transparent colors a breeze, I hate the need to remember all the colors alpha in my mind, writing it somewhere else or using another program just to make a single pixel that I forgot.

**Comment by Cubouse** [comment]
@atchimgripo There is an option in the Settings you can toggle on to do just that, it's called "Pick Color Opacity", in the Paint category.
