### ISSUE TITLE
Mojamap 1.17 models exported improperly

### ISSUE THREAD

**Issue by SpiDrone** [JannisX11/blockbench#2330]
### What are you trying to do, and what do you expect to happen?

Export a .java file, it to export correctly.

This also effects previously working models, that I open and re-export.
And the issue goes away when going back to 4.9.4

### What happens instead?

Github isnt letting me upload an image, but the file is generating as
"public class tiny<T extends > extends EntityModel<T> {"
instead of 
"public class tiny<T extends Entity> extends EntityModel<T> {"

And other stuff is also missing below

### Model format in which the issue occurs

Modded Entity

### Blockbench variant

Program

### Blockbench version

4.10

### Operating System

Windows

### Installed Blockbench plugins

Seat Position + Hitbox

**Comment by JannisX11** [comment]
The two lines you provided are identical. Please add the actual differences.

**Comment by Twebster9000** [comment]
I am having the same issue as this person. After updating Blockbench and trying to export a java entity into another program (mcreator) I am given a error that the code is incorrectly written as "public class ModelIllager_Echo<T extends> extends EntityModel<> {"

**Comment by JannisX11** [comment]
The issue here is a bit unclear but there is a good change it has been fixed in 4.10. Let me know if it is still an issue.

**Comment by Twebster9000** [comment]
This was not an issue before updating to 4.10.0

**Comment by Twebster9000** [comment]
This has indeed been fixed.

**Comment by Synfinity** [comment]
having the same issue here.

**Comment by Arkaliasus** [comment]
so you finally fixed the thing i was talking about but ignored? and i can now update to the latest version? awesome ty
