### ISSUE TITLE
Exported Fbx And Objs +Z Is Wrong For Unity

### ISSUE THREAD

**Issue by Nineforcestudios** [JannisX11/blockbench#2344]
### What are you trying to do, and what do you expect to happen?

Importing my model into unity the front should be correctly facing +Z

### What happens instead?

Its Completely Facing the other direction 

### Model format in which the issue occurs

Obj & Fbx

### Blockbench variant

Program

### Blockbench version

4.10.1

### Operating System

Windows

**Comment by JannisX11** [comment]
Z+ is the direction that the blue arrow of the move gizmo faces in Blockbench. If you want it to face the other direction, you meed to rotate it. This does not sound like an issue with the program.

**Comment by Nineforcestudios** [comment]
> Z+ is the direction that the blue arrow of the move gizmo faces in Blockbench. If you want it to face the other direction, you meed to rotate it. This does not sound like an issue with the program.

I've tried that it still didn't work
