### ISSUE TITLE
[Issue] [Clone brush] Clone brush creates "ghost cubes" if placing cubes on restricted area

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#235]
Clone brush creates "ghost cubes" if placing cubes on restricted area, Just a visual bug.

Video: https://youtu.be/lWLd0B92-hw

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench-plugins/commit/251bb2fef31e1bc581418d5f4fed8442a40b1b0c
