### ISSUE TITLE
[IDEA] UI EDITOR/MAKER

### ISSUE THREAD

**Issue by Floog98** [JannisX11/blockbench#2351]
### Detailed description of your suggestion

A UI editor for items would be insane, used for things like Play buttons in a world. Also allowing the ability to create ui for items that will run commands with image buttons and also editing Minecraft default UI such as the crafting menu or the Play/Settings/Marketplace UI

**Comment by JannisX11** [comment]
This does not sound like it has anything to do with Blockbench.

**Comment by Floog98** [comment]
I was thinking it as a Wizard
