### ISSUE TITLE
Entity Model Collapse when I Enable Raytracing

### ISSUE THREAD

**Issue by yonnanadesu** [JannisX11/blockbench#2362]
### What are you trying to do, and what do you expect to happen?

I made a train model in Blockbench, and I imported it to MCBE version 1.20.81. I turned on raytracing, and I thought it will show up normally.

### What happens instead?

When its in vanilla graphics, the entity model will show up perfectly. However, when I enabled raytracing, the model collapse. 

### Model format in which the issue occurs

.json

### Blockbench variant

Program

### Blockbench version

4.10

### Operating System

WIndows 11

**Comment by JannisX11** [comment]
Not a Blockbench issue.
