### ISSUE TITLE
Lost model, only texture saved?

### ISSUE THREAD

**Issue by maggot55** [JannisX11/blockbench#2368]
### What are you trying to do, and what do you expect to happen?

Hey, i was trying to open up my model that i saved a couple months back. (took a lil break) but when I went to do that i couldn't find it, only the texture that i saved at the same time... this happaned to me a while back to but then i were able to get it back (by recent i think? dont really remember, but back then it was only lost between a couple of days, now it was months since i was last on blockbench) but this time i checked backup and recent also but i couldnt find it anywhere.. 

### What happens instead?

:( i assume i maybe did something wrong, but i also can't figure out what...? but also the earlier drafts of the mdoel got saved in the same way but did not dissapear, just that one most recent finished version. At this point im just desperate to get the model back... worked a long time on it. Is there some other way to get it back? idk by texture or something?.. would very much appreciate help

### Model format in which the issue occurs

obj

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

windows 11

### Installed Blockbench plugins

0

**Comment by JannisX11** [comment]
There's a backup folder, but it only goes back 30 days on default settings. Help > View Backups.
If you had a file but you don't remember where you saved it, maybe you forgot, or something else happened to the file. So this is most likely not an issue with Blockbench.
