### ISSUE TITLE
Move texture.png by holding the png in the paint section

### ISSUE THREAD

**Issue by aurora-1-2-3** [JannisX11/blockbench#2370]
### Detailed description of your suggestion

what the tile say. cant say more, for reference: like how we can move the model by holding the right click
![enderman](https://github.com/JannisX11/blockbench/assets/139906198/a0c557bd-07e3-4be0-810b-11b8b89579b8)
this can be implemented to:
![image](https://github.com/JannisX11/blockbench/assets/139906198/4ea7eb4c-91cb-4dd6-9416-5894a10d17bf)

**Comment by Cubouse** [comment]
In case you mean moving the UV with the texture, you can already do that:

Enable "**Move Texture with UV**" and the texture will follow when you drag the UVs.

If you just want to move the texture and not the UVs, go in the Paint tab and use the "Move Layer" tool. You can also do selections to move only some portions.
If you just want to move the UVs and not the texture, go in the Edit tab and move the UVs with "move Texture with UV" disabled.

**Comment by aurora-1-2-3** [comment]
No, I meant like, a way move the whole canvas just like how you can move the grid (model) with right click.

**Comment by Cubouse** [comment]
You can do that by clicking and dragging with the middle mouse button.

**Comment by aurora-1-2-3** [comment]
Oh ok, I'll try
