### ISSUE TITLE
Flip Animation does not swap with absence of keyframe

### ISSUE THREAD

**Issue by Cubouse** [JannisX11/blockbench#2372]
### What are you trying to do, and what do you expect to happen?

At a given timestamp, one side of a model has a keyframe (say, "leftLeg"), the other does not ('rightLeg").

I intend to use Flip Animation to swap the keyframes to the other side.

### What happens instead?

I expected there would be a swap, but the keyframes are simply duplicated.
I believe that when one side is empty, it is more intuitive and useful to remove the keyframes from the side that had them.

https://github.com/JannisX11/blockbench/assets/83140650/f2f6e5ab-fee4-4eda-a8ae-b6a819e71789

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

W10

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
I think that's a misunderstanding. The description of the "Flip Animation" action specifies that the selected keyframes will be copied over to the other side, not moved over. The purpose of this feature is to animate one side of the model first (like a complex wing flap with many moving parts) and then copy it over to the other side to save some time remaking it there.
