### ISSUE TITLE
Whenever I try to color a cube, every other cube gets colored aswell.

### ISSUE THREAD

**Issue by MolhemPlayz** [JannisX11/blockbench#2373]
### What are you trying to do, and what do you expect to happen?

I was trying to paint a model (made out of lots of cubes). I painted one cube, expecting for it to actually get painted.

https://github.com/JannisX11/blockbench/assets/136991729/503e4d54-b32e-42b2-a5b8-f9334db045d7

### What happens instead?

Instead of only the one cube getting painted, every other cube gets painted on the exact same pixel as on the one cube that i tried to paint.

https://github.com/JannisX11/blockbench/assets/136991729/859da558-1f2f-4cd1-a8ec-de2095300547

### Model format in which the issue occurs

.json

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

Windows 10

### Installed Blockbench plugins

(i installed blockbench yesterday, means i dont have any p

**Comment by JannisX11** [comment]
This is normal. You'll need a basic understanding of UV mapping. I recommend to watch a few beginner Blockbench tutorials. You can find good tutorials for your specific format here: https://www.blockbench.net/quickstart/
