### ISSUE TITLE
error when opening json model in the program

### ISSUE THREAD

**Issue by Yan1948** [JannisX11/blockbench#2374]
### What are you trying to do, and what do you expect to happen?

I want to import a model of a sword from a mod into the program to make a thumbnail for a video. I was hoping a white model would appear

### What happens instead?

![Captura de tela 2024-06-07 141438](https://github.com/JannisX11/blockbench/assets/154987973/73c1f495-c546-46a6-a009-1992e7705494)

### Model format in which the issue occurs

json

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

Windows

**Comment by JannisX11** [comment]
Model inheritance and the child model dialog that you showed are a normal feature of Minecraft's model format and Blockbench, and not a bug. If you need help using these features, I would recommend asking on the Blockbench Discord.
