### ISSUE TITLE
Settings disappears sometimes.

### ISSUE THREAD

**Issue by Trioplane** [JannisX11/blockbench#2382]
### What are you trying to do, and what do you expect to happen?

Tried to find the settings, its gone, Tried Search and Run Action: Settings, nothing happens. I expect it to open settings.
After restarting it came back, must be happening rarely

### What happens instead?

Nothing, It makes an error that `Format` is not defined in settings.js
![image](https://github.com/JannisX11/blockbench/assets/87922281/243c8a13-e6c7-4379-8362-045081933ab9)

### Model format in which the issue occurs

ALL

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

Windows

### Installed Blockbench plugins

Minecraft Title Generator, CEM Template Loader, Animated Java, Animation Sliders, MTools, Cameras, Colour Gradient Generator, Preview Scene Customiser, Outline Creator, Figura Model Format

**Comment by JannisX11** [comment]
In case anyone has this issue: You just need to restart the program and it'll work again.
