### ISSUE TITLE
Synced videos with animation

### ISSUE THREAD

**Issue by SammyForReal** [JannisX11/blockbench#2384]
### Problem describtion
Hello! Something I noticed while animating in Blockbench is that I cannot have a video being synced within the timeline, which really is a pity, as it would make it so much easier / helpful.

### Possible Solution
I'd suggest adding a way of adding a video to the scene, similar to how it works with images in the editor mode _(Or just it opening up a tab where it plays the video, thats good enough as well)_. Other programs like Blender do have this feature as well and it is widely being used by animators.

I hope this is possible and not asked too much.

**Comment by JannisX11** [comment]
This is possible since 4.10.
