### ISSUE TITLE
Bug:Block appeared out of thin air.

### ISSUE THREAD

**Issue by YYLWZDXPGD** [JannisX11/blockbench#2399]
### What are you trying to do, and what do you expect to happen?

I want to change the block.

### What happens instead?

After the change, a new block will appear out of thin air.

https://github.com/JannisX11/blockbench/assets/128379352/747ae13b-59fd-490e-af44-c5a9d662ed74

### Model format in which the issue occurs

Modded Entity

### Blockbench variant

Website

### Blockbench version

I don‘t know

### Operating System

iPad17.1 Safari

**Comment by JannisX11** [comment]
Well you have Mirror Modeling enabled. So it is to be expected that the right side of your model will be mirrored to the left side.
