### ISSUE TITLE
[Suggestion] Vertex snapping

### ISSUE THREAD

**Issue by SirBenet** [JannisX11/blockbench#24]
[Example in Unity](https://gfycat.com/TightSmugAsiaticwildass)

1. Press a key (e.g: `V`) to show vertices
2. Click one vertex on a cube
3. Drag over to another vertex on another cube
4. The first cube is moved so that the vertices align (move by `second vertex coords - first vertex coords`)

I found this convenience feature very handy for lining up objects how I wanted (especially if they're angled) when working with Unity. I don't think any of the other Minecraft model editors have this feature, so it'd be a useful extra.

**Comment by JannisX11** [comment]
SirBenet added this as a plugin. Going to close this issue for now.
