### ISSUE TITLE
Error with exporting blockbench model to .json extension in minecraft

### ISSUE THREAD

**Issue by KwanteQ07** [JannisX11/blockbench#2400]
### What are you trying to do, and what do you expect to happen?

I'm trying to export my model to .json in the texture pack, but instead I have a damaged block
![Zrzut ekranu (873)](https://github.com/JannisX11/blockbench/assets/160972018/76190d8d-9eb3-48d1-9db0-4dd1b3f203c2)

### What happens instead?

The error started when exporting the model to the Minecraft item/block .json, when I loaded everything in my texture pack, instead of my model a damaged black and pink block appeared

### Model format in which the issue occurs

.json

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

Windows 11 

### Installed Blockbench plugins

Minecraft entity wizard, CEM template loader, animated java, Fabric Modded Entity

**Comment by JannisX11** [comment]
This is likely an issue with your setup or your model, not with Blockbench itself. If you need help figuring out what is causing this issue, you can post it on the Blockbench Discord server or the Subreddit.
