### ISSUE TITLE
Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

### ISSUE THREAD

**Issue by Xdrk45** [JannisX11/blockbench#2403]
### What are you trying to do, and what do you expect to happen?

Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

### What happens instead?

Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

### Model format in which the issue occurs

Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

### Blockbench variant

Website

### Blockbench version

Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

### Operating System

Hi, could you help me? I use blockbench on my cell phone, and I ended up deleting a model of mine without saving, I wanted to know if there is any way to recover it?

**Comment by Cubouse** [comment]
If you don't see a message about recovering a model when you reopen Blockbench on your phone, it's gone.

To ask these kind of questions, don't use Github, use the [Blockbench discord](https://discord.gg/Kakusu6c)
