### ISSUE TITLE
I can't intergrate a pack

### ISSUE THREAD

**Issue by Phinixprono123** [JannisX11/blockbench#2407]
### What are you trying to do, and what do you expect to happen?

I was trying out block bench for the first time on the android app. I was watching a YouTube totrial to make a make a Minecraft bedrock but I can't intergrate into another pack the option is not in the android app and the web app.

### What happens instead?

The intergrate into another pack option is not the android app and the web app I don't if it is only happening to me or everyone.

### Model format in which the issue occurs

The intergration pack option is not there

### Blockbench variant

Website

### Blockbench version

It's the web app

### Operating System

Android

### Installed Blockbench plugins

Item wizard, block wizard, entity wizard

**Comment by JannisX11** [comment]
In order to use the integrate into pack option in the Wizard plugins, you need to use Blockbench on a PC.

**Comment by Phinixprono123** [comment]
> In order to use the integrate into pack option in the Wizard plugins, you need to use Blockbench on a PC.

Is there anyway to intergrate it with a android?
