### ISSUE TITLE
[Suggestion] option to export only visible nodes in GLTF ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [JannisX11/blockbench#2408]
### Detailed description of your suggestion

Hello, would it be possible to add an option to the GLTF exporter (and maybe to other formats) so that we can select if we want to export only visible nodes ?

https://github.com/JannisX11/blockbench/blob/813379d114aab14a2ff1e40e4bba6985dfa6844e/js/io/formats/gltf.js#L365-L377

**Comment by JannisX11** [comment]
I would say this is redundant because Blockbench already has export toggles in the outliner under advanced options that allow users to disable export of certain elements.
<img width="230" alt="image" src="https://github.com/JannisX11/blockbench/assets/29278436/81e1848b-eb31-40ee-a9f1-c2091407c343">

**Comment by SuperUserNameMan** [comment]
I shmwould say that it is a nice feature that wish i would have noticed before :-D
