### ISSUE TITLE
Pressing R or the rotate button closes image view

### ISSUE THREAD

**Issue by FoxGaal** [JannisX11/blockbench#2413]
### How it happens...

when you press R or the rotate keybind 

### Unwanted behaviour... 

the image view disappears and you cant find it again 

### Model format in which the issue occurs

bedrock skin

### Blockbench variant

Program

### Blockbench version

4.10.3

### Operating System

Windows 10

### Installed Blockbench plugins

titles generator

**Comment by JannisX11** [comment]
The 2D image editor is only available in Paint mode. Selecting an edit tool switches to Edit mode, which reconfigures the interface and hides paint tools. That's normal. You should still have the UV editor in edit mode where you can see your texture.

**Comment by FoxGaal** [comment]
Well then thats an interface and UI Issue there is no user feedback indicating anything happened
