### ISSUE TITLE
[Issue] Quad view opens in animation mode when using Tab keybind

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#242]
Animation keyframe window wont appear after using quad view.
Window will appear back when toggling to Edit/Paint then back to Animate.

How to reproduce issue:
- Create new entity model
- Go to animate window
- Enable quad view (Tab)
- Go back to default view

Using: Blockbench 2.3.2 desktop

![image](https://user-images.githubusercontent.com/44243757/51988255-ecf58900-24ac-11e9-856e-86e9fa12db2e.png)

**Comment by JannisX11** [comment]
Quad View should not be accessible in animation mode. Apparently I forgot to add conditions to the toggle action.

**Comment by iWackyMinecraft** [comment]
Quad view can also be enabled on display mode (like on GUI and 1st person preview which doesn't really make sense)

**Comment by JannisX11** [comment]
Fixed in 2.4.0.
