### ISSUE TITLE
It is not possible to export the model to other formats, the files are just empty

### ISSUE THREAD

**Issue by AnderHominem** [JannisX11/blockbench#2421]
### What are you trying to do, and what do you expect to happen?

I have created a model and want to export it to GLTF (also tried all other available formats) for further use. 

### What happens instead?

When exporting, a file is created, nothing suspicious happens, no errors or warnings, but when I try to open it, it is empty inside. This happens regardless of the selected format, and when trying to export to Sketchfab, the new model simply does not exist on the site, as if there was no export. When I created the model, I used the Linux version, but I also opened the model in Windows, but there is no export either, so I think it's not an OS problem. During the creation of the model, I have already successfully exported it several times, for some tests, the problem appeared near end, when I had already almost finished everything. I also checked the backups folder and found exactly two files, one before this bug and one after
[ander_hominem_bug_report_2models.zip](https://github.com/user-attachments/files/16201452/ander_hominem_bug_report_2models.zip)

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Linux Mint 21.3 and Windows

### Installed Blockbench plugins

colour gradien generator_texture stitcher_outline creator_voxel importer_missing texure highlighter_simplify models_groud plate editor_discord RPC_activity tracker_quick box-uv layout_cardinal_export to BlockModels.com

**Comment by JannisX11** [comment]
<img width="160" alt="image" src="https://github.com/user-attachments/assets/86f4a011-4de5-4fed-8a06-2e02f1cfe2fb">
If you press Enable More Options, you can see that "Export" is disabled on all elements in your model.
