### ISSUE TITLE
Bulk replace q.anim_time and q.life_time

### ISSUE THREAD

**Issue by Cubouse** [JannisX11/blockbench#2425]
### Detailed description of your suggestion

When making animations for the Bedrock entity format, I sometimes want to swap `q.anim_time` for `q.life_time` (or vice versa) in a bunch of keyframes.

I suggest adding a tool that finds both `q.anim_time` and `q.life_time` strings in every selected keyframes to replace them both to the same string (with a way to cycle through q.anim_time and q.life_time by reusing the tool, or by selecting one directly in a little menu).

It would be a big time saver when there are many keyframes to edit, doing it manually is tedious.

**Comment by JannisX11** [comment]
This is already possible, you can select a number of keyframes and use Edit > Find/Replace...
