### ISSUE TITLE
UV Unwrap freezes exponencially while trying to unwrap a big object

### ISSUE THREAD

**Issue by caioraphael1** [JannisX11/blockbench#2428]
While working on my new PR (#2427 ) for changes to the UV system, I noticed that big objects take longer to Create Texture, or just simply unwrap. 

The video below shows 2 identical objects with different sizes, the second one took so long to unwrap that i stopped recording.
 

https://github.com/user-attachments/assets/97e21afc-fb9d-4f2f-a42c-380d74ffdeae

### texture_generator.js / generateFaceTemplate()

The `face_group.matrix = getPolygonOccupationMatrix(face_uvs, face_group.width, face_group.height);` takes a LOT of time to do, and it's not a big deal to disable it completely in many cases. 

https://github.com/JannisX11/blockbench/blob/813379d114aab14a2ff1e40e4bba6985dfa6844e/js/texturing/texture_generator.js#L1174-L1182

The real problem tho happens when trying to allocate an empty slot for the faces

https://github.com/JannisX11/blockbench/blob/813379d114aab14a2ff1e40e4bba6985dfa6844e/js/texturing/texture_generator.js#L1241-L1250

The bigger the area occupied by each face, the more it takes to run through the space.

Disabling Combined Islands also improves a lot the time it takes to unwrap.

Considering all this, I had the idea to do one of the following:
- First, make the projection really small -> Auto UV -> scale to the pixel density.
- Or, improve the code so it can avoid wasting so much time running through so many coordinates. 

Tho, I don't know how to make the project small, or how to improve the math so it goes faster for bigger objects.

### Model format in which the issue occurs

Generic

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Win10

**Comment by JannisX11** [comment]
In 4.11 there will be a progress bar so you can see how long it takes and it doesn't feel like it's stuck. Plus you'll be able to cancel it anytime.
