### ISSUE TITLE
OptiFine animations get cloned on model change

### ISSUE THREAD

**Issue by iFlameWaterYT** [JannisX11/blockbench#2430]
### What are you trying to do, and what do you expect to happen?

Changing to another model, save animations and continued in the same group

### What happens instead?

Animations get saved, but also cloned to another group if you change something without clicking the original animations group

https://github.com/user-attachments/assets/8af99b71-3393-437e-b524-abc3dd424ec0

Sorry for the low fps of the video, my pc is bad and has problems recording

### Model format in which the issue occurs

OptiFine Entity (.jem)

### Blockbench variant

Program

### Blockbench version

Latest at issue creation (4.10.4)

### Operating System

Windows 11 (23H2)

### Installed Blockbench plugins

Minecraft Title Generator; GeckoLib Animations Utils; Minecraft Item Wizard; CEM Template Loader; Minecraft Block Wizard; EMF Animation Addon; OptiFine Player Models; Preview Scene Creator.

**Comment by aurora-1-2-3** [comment]
Finally fixed
