### ISSUE TITLE
Editing a model in Mirror Modeling mode causes existing UVs to become Mirrored

### ISSUE THREAD

**Issue by nanodeath** [JannisX11/blockbench#2434]
### What are you trying to do, and what do you expect to happen?

If I have a model where the mesh is symmetrical, but the texture is not, I [carefully](https://github.com/JannisX11/blockbench/issues/2433) use Create Texture while Mirror Modeling is off to generate a texture where the left and right sides are UV mapped independently. Then I do some painting, and realize I want to make a small change to the mesh. In this case, extrude a new face. I expect the face to be extruded and to have to remap any new faces myself, but for existing mappings to be largely unmodified.

### What happens instead?

If I'm extruding a new face while Mirror Modeling is enabled (which is what I want to do), it breaks all the existing UVs by making the right side mirror the left side.

[Screencast from 07-21-2024 06:40:12 AM.webm](https://github.com/user-attachments/assets/a840aa6a-6b0f-4bfa-bb4e-01690654f8d4)

What I'm guessing is happening is it's regenerating UVs using the current settings, and TBH I'm not 100% sure what magic I expect Blockbench to do to handle UV mapping when creating new faces after the texture has been created. But it's definitely not that.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Website, Program

### Blockbench version

4.10.4

### Operating System

Ubuntu 22.04

**Comment by JannisX11** [comment]
Mirror modeling always mirrors the entire element, and that includes UV maps. So this is working as intended.
