### ISSUE TITLE
reference images don't show when using any of the preview scene options

### ISSUE THREAD

**Issue by LeppyMC** [JannisX11/blockbench#2438]
### What are you trying to do, and what do you expect to happen?

reference images don't show when using any of the preview scene options. i have to switch in and out of the scene constantly when i should ideally be able to just see it constantly

### What happens instead?

the reference image disappears, but comes back when i go back to the default view

### Model format in which the issue occurs

Bedrock Block

### Blockbench variant

Program

### Blockbench version

Latest Release

### Operating System

Windows 10

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment]
Reference images appear behind the model and scene by default. So it's covered if you have a background. To make it visible you can set the reference image Layer to Above Model.
