### ISSUE TITLE
[Issue] Fill tool wont fill subpixel areas correctly

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#244]
Fill tool wont fill subpixel areas correctly.
This might be an intended feature, but i don't really see any use for this.

So i used a 16x16 texture then applied textures to 2 cubes with AutoUV, then i used fill tool.

Blockbench 2.3.2

![image](https://user-images.githubusercontent.com/44243757/52115333-061a4900-2617-11e9-92d0-a0896afd570b.png)

![image](https://user-images.githubusercontent.com/44243757/52115481-6610ef80-2617-11e9-876f-3f406e9ce5b1.png)

**Comment by JannisX11** [comment]
Fixed in 2.4.
