### ISSUE TITLE
Display preview of Java Edition item model does not support negative scale

### ISSUE THREAD

**Issue by GeForceLegend** [JannisX11/blockbench#2441]
### What are you trying to do, and what do you expect to happen?

When setting the scale property of a Java Edition item/block model to negative, it should look like mirrored with similar viusal effect of a model with negative size. It's minimum value is -4 according to zh wiki (en wiki just says it's maximum value is +4)
![2024-08-11_20 15 13](https://github.com/user-attachments/assets/56130915-92a3-4b44-a0b1-ea49539b9d68)

### What happens instead?

BlockBench just clamps it at 0, making the model be a plane, instead of making it same as how game renders it.
![20240811-201559](https://github.com/user-attachments/assets/5d724bf4-d4ae-44ea-ae2b-0743a9499c5f)

### Model format in which the issue occurs

Minecraft Java Edition item/block model

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows10 Home 22H2 19045.4529

**Comment by JannisX11** [comment]
Not an issue. You can enable mirroring in the Blockbench settings. It is disabled by default because Minecraft no longer renders it correctly.
