### ISSUE TITLE
Store extra unknown json data instead of ignoring and deleting them when saving models

### ISSUE THREAD

**Issue by GeForceLegend** [JannisX11/blockbench#2447]
### Detailed description of your suggestion

BlockBench **should** store the extra data while parsing json models, and save them along with known data when saving models. This keeps the best compatibility while model API has been updated, like the `light_emission` in latest Java Edition snapshot.

If BlockBench keeps ignoring and deleting unknown data, it will be very annoying after each model API update, as model creators may using provided new feature, but BlockBench deletes them every time saving model.

**Comment by JannisX11** [comment]
Additional root fields are already stored. Storing all additional data for each sub field is unrealistic due to how Blockbench handles data internally. Minecraft formats in particular have not changed much in recent years, so adding support for new features is not an issue at all.
