### ISSUE TITLE
[Issue] Negative cubes are displayed incorrectly on display mode

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#245]
Negative cubes are displayed incorrectly on display mode.

Using: Blockbench 2.3.2

**Edit mode:**
![image](https://user-images.githubusercontent.com/44243757/52181221-53a1dc00-27f8-11e9-8999-b1c60b08ae39.png)

**Display mode:**
![image](https://user-images.githubusercontent.com/44243757/52181258-aaa7b100-27f8-11e9-9879-d82cfb2fe33a.png)

**Ingame**
![image](https://user-images.githubusercontent.com/44243757/52181283-ea6e9880-27f8-11e9-8692-c14de0ab6e75.png)

**Comment by JannisX11** [comment]
That's interesting. I always thought models held as items would render both sides. That's why Blockbench does so too in display mode.

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
