### ISSUE TITLE
"Screenshot Model" button cuts off portion of model when in Display -> GUI.

### ISSUE THREAD

**Issue by TydiumToo** [JannisX11/blockbench#2450]
### What are you trying to do, and what do you expect to happen?

I was trying to screenshot a model in Display -> GUI for Java block/item, and it cuts off part of the model. I wanted it to include the whole model in the aspect ratio that its in. Im not entirely sure if this is intentional or not, and if it is intentional then atleast allow an option within the screenshot API to turn the crop off. 

Using `display_preview.screenshot({crop:false, height:64, width:64})` doesn't work either and still crops it out the photo. (It also ignores my height and width as well)

### What happens instead?

This is what happens when I try to screenshot. 
![image](https://github.com/user-attachments/assets/f1a58512-1ae2-4798-9942-696aa851d36e)

I wanna be able to use `display_preview.screenshot({crop:false, height:64, width:64})` to specifically generate screenshots with that size without cropping out the model. Pretty much zoom in to the model without cropping it out.

### Model format in which the issue occurs

Java block/item

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows

### Installed Blockbench plugins

None

**Comment by TydiumToo** [comment]
When doing `display_preview.screenshot({crop:true, height:64, width:64})` instead, it doesn't zoom in all the way but it accepts my width/height again.
![image](https://github.com/user-attachments/assets/3c28ce45-37dd-4c28-af54-04471293b0cb)

**Comment by JannisX11** [comment]
This is intentional when using the user-facing quick screenshot function. It's not intentional when using the API.
