### ISSUE TITLE
Anim Controller preview/editor in VSCode

### ISSUE THREAD

**Issue by AngeloVH** [JannisX11/blockbench#2456]
### Detailed description of your suggestion

The animation controller preview is amazingly useful, but, as a developer, I never use it because I always do something in parallel in VS Code. Given how Snowstorm is already an extension, having a similar feature for previewing animation controllers would help developers edit them and have an easier understanding of the flow of controllers, all while still in the primary development environment.

**Comment by JannisX11** [comment]
This is not within the scope of Blockbench, it's also not really a Blockbench suggestion.
The way I can address this use-case in Blockbench potentially is by adding a reload option for animations and animation controllers. That way you can edit the file in VS Code, but still live-preview in Blockbench after pressing Reload.
