### ISSUE TITLE
CEM format not respecting texture structure when no default texture is present.

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#2457]
### What are you trying to do, and what do you expect to happen?

This model has textures defined on subbones. It does not have a default texture assigned. When you open the model in Blockbench and save it, it should keep this structure. No default texture, and the texture stays assigned to the chosen subbones.
[stray.zip](https://github.com/user-attachments/files/16740277/stray.zip)

### What happens instead?

After opening the model and saving it in Blockbench, it makes this texture the default texture, and removes the texture from every subbone it was assigned to, breaking the model.

### Model format in which the issue occurs

OptiFine JEM

### Blockbench variant

Website, PWA, Program

### Blockbench version

4.10.4

### Operating System

Windows

**Comment by JannisX11** [comment]
![image](https://github.com/user-attachments/assets/46a8b96f-9f02-4a4d-ae3c-f7e78991c804)
Make sure this setting is disabled.
