### ISSUE TITLE
Add an option to close the Validator

### ISSUE THREAD

**Issue by Yuqsir** [JannisX11/blockbench#2458]
### Detailed description of your suggestion

When I was modeling a bedrock model ，I find the Validator keep texting issues，and make my blockbench stuck everytime when it is working.but my model is working good on my porject.I find out that it spend too many time on checking my animation uploaded from other software（like blender),just because the animation has lots of keyframes.Consider that many creators may dont need that to check their models,I wish to get an option to close that.

**Comment by JannisX11** [comment]
You can close the validator dialog using the "Close" button in the bottom right corner.

**Comment by Yuqsir** [comment]
No，I mean to let the validator stop scanning my model，not just close the dialog.
