### ISSUE TITLE
[Issue] Undo doesn't work while UV window or full view is active

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#246]
Undo doesn't work while UV window or full view is active.

How to reproduce issue:
- Go to paint mode
- Select paint brush
- Go to full view mode
- Paint
- Ctrl + Z doesn't work

Blockbench 2.3.2

**Comment by iWackyMinecraft** [comment]
Undo button on toolbar works, but it doesn't update the window.

**Comment by JannisX11** [comment]
Fixed in 2.5.
