### ISSUE TITLE
Performence problem inBlockbench

### ISSUE THREAD

**Issue by Yuqsir** [JannisX11/blockbench#2460]
### What are you trying to do, and what do you expect to happen?

Modeling, and the framerate is stable

### What happens instead?

the blockbench stuck every 30s.
here is my performenc trace when it stucked.
[Trace-20240826T231015.json](https://github.com/user-attachments/files/16750451/Trace-20240826T231015.json)

### Model format in which the issue occurs

bedrock medel

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows 11 23H2

### Installed Blockbench plugins

Geckolib animation utils,shape generator,cameras,optimize,brush plus,bakery,performence audit

**Comment by JannisX11** [comment]
What you are seeing are automatic backups to recover your work in case of a crash, power outage, etc. It should not take that long usually, it looks like your project is incredibly large. How many large textures do you have, and how many keyframes?

**Comment by Yuqsir** [comment]
I used six of 1k textures,and two 2k textures,my animation indeed has lot of keyframes.the whole project is 38MB.
But those didnt cause performence issues on my computer regularly,so I think setting a backup frequency of 30 seconds is a bit too short,Is there any way to change that?I can just found the Backup interval in settings,which I already set it in 30 min,didnt work  though.

**Comment by Yuqsir** [comment]
I mean the lagging annoying me more than losting pergrass,since the blockbench is way more stable than I thought(compare to blender),and I also have the habit of saving progress at any time.

**Comment by JannisX11** [comment]
I can add a setting to change the recovery point save interval.
