### ISSUE TITLE
Exporting a bedrock model does not save all its bones.

### ISSUE THREAD

**Issue by Xterionix** [JannisX11/blockbench#2461]
### What are you trying to do, and what do you expect to happen?

Trying to export a bedrock entity model.geo.json and expecting all the bones to be exported.

### What happens instead?

Not all the bones are actually being exported. Bones whose upper most root is bone 8 are exported while the others aren't.

![image](https://github.com/user-attachments/assets/c90a106d-312e-472d-ad62-75bcb29d6bd3)

The bbmodel (renamed to a .txt since github doesn't allow bbmodel uploads):
[Haiaosi_2.txt](https://github.com/user-attachments/files/16787145/Haiaosi_2.txt)

The file it exported:
[Haiaosi_2.geo.json](https://github.com/user-attachments/files/16787148/Haiaosi_2.geo.json)

### Model format in which the issue occurs

Bedrock Entity

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows 11

### Installed Blockbench plugins

Minecraft Title Generator, Geckolib, Color Gradient Tool, Seat Position + Hitbox, Bakery, Root Motion Extractor, Duplicate Bone Renamer, Bedrock Entity Model Presets

**Comment by JannisX11** [comment]
Not an issue. Your export toggle is disabled on most bones. You can re-enable it by turning on Outliner Options and clicking the button.
![image](https://github.com/user-attachments/assets/bd3da6af-ea2f-4f21-8434-a900671e89bb)
