### ISSUE TITLE
Forced Blockbench Update, App Uninstalled Itself

### ISSUE THREAD

**Issue by eyelesstenshi1** [JannisX11/blockbench#2462]
### What are you trying to do, and what do you expect to happen?

I had blockbench open, I closed it. It said that a new update was found and that it was going to update. I was trying to use the app.

### What happens instead?

The app uninstalls itself.

### Model format in which the issue occurs

N/A

### Blockbench variant

Program

### Blockbench version

The Latest Update

### Operating System

Windows

**Comment by JannisX11** [comment]
Try to restart your computer, and if that doesn't work, reinstall Blockbench.
Blockbench auto-updates itself, and if you open it while it's doing that or shut down your computer, it may display an error message, or in some cases fail to update. In that case you can just run the latest installer again and it'll fix the installation.
