### ISSUE TITLE
java skind arent 64 by 64

### ISSUE THREAD

**Issue by tremondos** [JannisX11/blockbench#2463]
### What are you trying to do, and what do you expect to happen?

i made a java skin and wanted to import it to the game

### What happens instead?

![anvilmam](https://github.com/user-attachments/assets/74d48478-efc7-4c79-997d-2093393fd0c9)
when putting it into minecraft or any skin editor it sayed that it isnt 32 by 64 or 64 by 64

### Model format in which the issue occurs

skin

### Blockbench variant

Program

### Blockbench version

4.10.9

### Operating System

windows

**Comment by JannisX11** [comment]
Minecraft already told you what the issue is. The file is 128 x 128. When you create a skin with that resolution in Blockbench it even gives you a warning that it won't work as a regular Minecraft skin.
