### ISSUE TITLE
Option to keep same preview angle when switching tab

### ISSUE THREAD

**Issue by Cubouse** [JannisX11/blockbench#2467]
### Detailed description of your suggestion

This option would let us keep the same camera zoom and angle in the preview when switching between different tabs.

---

It would be particularly useful to work with many models with slight geo/texture variations, all opened in different tabs.

This way we could have the same angle to look at them from instantly, to compare them, select specific geo elements to copy or delete, etc.

**Comment by JannisX11** [comment]
Added in 4.11.
