### ISSUE TITLE
Reference Images shown above Ground Plane

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#2477]
### Detailed description of your suggestion

Currently reference images can be on three layers:
- Behind Model
- Above Model
- Above Interface

These work great, however when a ground plane is introduced it makes any reference images tagged "Behind Model" be obstructed by the ground plane, making them completely obstructed in most cases. Above model fixes this, but then the reference images will also be shown on top of the model which may not be ideal either. 
It would be nice if there was a way - maybe through and additional layer option - to have it shown above the ground plane but below the player.

**Comment by JannisX11** [comment]
This is not possible, as explained here: https://github.com/JannisX11/blockbench/issues/1243#issuecomment-1006103452
