### ISSUE TITLE
Collapse All Groups

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#2478]
### Detailed description of your suggestion

When working with complex models, groups are commonly used to keep things clean and organized, however when there's a lot of groups/bones open at once it can make things hard to navigate. 
In order to combat this it would be nice if there was a "collapse all groups" feature that would do as the name suggests.(Moreso it'd be nice if there were more options for how groups were handled in situations like duplicating groups and selecting cubes since it can be irritating when a cube is accidentally selected and it opens up the entire path)

- I'm realizing i've been sending a lot of suggestions lately so sorry about that.

**Comment by JannisX11** [comment]
This exists already since 3.0.

**Comment by JannisX11** [comment]
But I appreciate the feedback!
I'll add a setting to disable element revealing on select in the outliner.
