### ISSUE TITLE
[Issue] UV copy paste text missing from full view window

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#248]
UV copy paste text missing from full view window.
On All window: ctrl + c/v does send text, but not with toolbar buttons.

![image](https://user-images.githubusercontent.com/44243757/52182027-7e446280-2801-11e9-855b-ed5eedb2f818.png)

![image](https://user-images.githubusercontent.com/44243757/52182031-843a4380-2801-11e9-8cb0-a2aa19dfeb6a.png)

**Comment by JannisX11** [comment]
Fixed in 2.5.
