### ISSUE TITLE
[Issue] Exporting `"rotation": {"angle": 0, ...}` Causes In-game Issues.

### ISSUE THREAD

**Issue by SaltSouls** [JannisX11/blockbench#2481]
### What are you trying to do, and what do you expect to happen?

Exporting a Minecraft block model should not export the rotation if the angel is 0.

### What happens instead?

When exporting a Minecraft block model, it will export the rotation even if the angle is 0. This causes issues with the vanilla lighting pipeline when the game goes to render that model.

### Model format in which the issue occurs

Java Block/Item

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Manjaro Linux x86_64

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment]
The reason that this is exported is to save the pivot points of the cube to the file. If the pivot is at 0,0,0 it won't save the rotation.

I'll add a setting to enable/disable pivot point export.
