### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by plush734** [JannisX11/blockbench#2483]
### What are you trying to do, and what do you expect to happen?
![Uploading 2024-09-12_13-55-05.png…]()

I decided to update the Blockbench version 4.10.4. after Blockbench is fully loaded, the installation itself starts and the program should work correctly

### What happens instead?

An error window is displayed, if you run it from the desktop, it writes the path to the program shortcut, and if you try to run it through the root folder, it writes that Blockbench is not a 32win application

### Model format in which the issue occurs

...

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

windows 7

### Installed Blockbench plugins

missing

**Comment by plush734** [comment]
scrinshot
![Uploading 2024-09-12_13-55-05.png…]()

**Comment by JannisX11** [comment]
Blockbench is not compatible with Windows 7. You can find instructions to use it on Windows 7 on the download page: https://www.blockbench.net/downloads
