### ISSUE TITLE
Record Gif not factoring in animation playback speed

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench#2484]
### What are you trying to do, and what do you expect to happen?

Record a gif with a slowed down(or sped up) animation by changing the playback speed. 

### What happens instead?

It records at the default animation speed. 

-- this is more of an oversight than a bug. 

### Model format in which the issue occurs

all

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows

**Comment by JannisX11** [comment]
Could not reproduce the issue.
