### ISSUE TITLE
Mirroring a mesh will clone the mesh and fuse it to the initial mesh

### ISSUE THREAD

**Issue by POWERUPT** [JannisX11/blockbench#2493]
### What are you trying to do, and what do you expect to happen?

I am trying to edit a mesh's vertices while mirroring it. I'd expect there to be a mirrored version of the mesh that appears, but won't be actually part of the source mesh.

### What happens instead?

Initially, I have a mesh that's not mirrored with mesh mirroring on.
Editing the mesh's shape will clone the mesh, but it will be part of the base mesh. Moving the mesh will also move the clone in the same direction, and both are highlighted, indicating they are both the same mesh. Sometimes moving the cloned mesh will also make another mirrored mesh.

![image](https://github.com/user-attachments/assets/b750decc-7f4e-46f2-b76e-393193db7cab)
![image](https://github.com/user-attachments/assets/3ad04a75-16f3-430d-9f8d-7565f57d3de2)
![image](https://github.com/user-attachments/assets/92973bc9-6b1c-494a-86bd-d62839ea2d81)
![image](https://github.com/user-attachments/assets/0c5a315c-8b25-4283-8080-1e35fe6ccad1)

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Blockbench version

4.11.0

### Operating System

Windows

### Installed Blockbench plugins

None

**Comment by POWERUPT** [comment]
This seems similar to #1957, but it's not quite the same. My cloned mesh is contained within the same mesh in the hierarchy.

**Comment by JannisX11** [comment]
If you want to mirror a mesh to the other side using mirror modeling, but you don't want it to be part of the same element, you can move the position (pivot point) of the mesh to the side. Meshes with a pivot point at X=0 are considered centered and are mirrored within themselves, which can be useful for central parts like torso, head etc.
