### ISSUE TITLE
selection of frame line direction

### ISSUE THREAD

**Issue by Grapes-purple** [JannisX11/blockbench#2499]
### Detailed description of your suggestion

like select which direction should the frames be horizontal or vertical.
![image](https://github.com/user-attachments/assets/28b74b9f-9ff6-45f3-b3f8-c67d2d318ee8)
or
![image](https://github.com/user-attachments/assets/ba71d21e-6bad-481e-af91-bfe305578594)

**Comment by JannisX11** [comment]
Duplicate of #2380
