### ISSUE TITLE
(Suggestion) Toggle Visibility on all keybind

### ISSUE THREAD

**Issue by gravyarts** [JannisX11/blockbench#2502]
### Detailed description of your suggestion

Toggle Visibility on all Elements keybind

There's two functions,
If there are elements already hidden, pressing the Toggle Visibility on All Elements keybind will first unhide all elements first, a second press will toggle visibility on all elements normally.

Took some screenshots in blockbench to hopefully better visualize and explain the suggestion.
https://youtu.be/ncam108ySS8

Why?
While there is a Toggle Visibility keybind, if you deselect the element and select a different element, there is no way to toggle the visibility back without reselecting the cube from the outliner.
I believe this'll also be helpful for those who are creating scenes and are constantly hiding and unhiding elements, this just lets them do that but more efficiently.

I hope I explained the suggestion well enough, cheers!

**Comment by JannisX11** [comment]
I think you could find a use-case for a lot of actions to have a variant that applies to all elements. But it's cleaner to separate those concepts (selection and action) and use Select All instead. In this case this would mean pressing Ctrl + A once to select everything and then using the regular Toggle Visibility action to toggle visibility.

**Comment by gravyarts** [comment]
I didn't even think about this for some reason, but that works perfectly, thanks.
I've been doing a lot of messing around in old level editors and I've gotten used to two hide and unhide keybinds lol.

Closing issue
