### ISSUE TITLE
blockbench overwriting texture reference

### ISSUE THREAD

**Issue by mrch0c0late** [JannisX11/blockbench#2503]
### What are you trying to do, and what do you expect to happen?

I have a parent model file for a flower pot in which I specified particles as: `"particle": "#flowerpot" `, so that it would use whatever texture I set `#flowerpot` to as the particles as well.

### What happens instead?

When I load said model in Blockbench and edit it in any way, it overwrites the  `"particle": "#flowerpot" ` to `"particle": "block/flower_pot" `.

### Model format in which the issue occurs

any

### Blockbench variant

Program

### Blockbench version

4.11.1

### Operating System

Win 11

**Comment by JannisX11** [comment]
Duplicate of #330
