### ISSUE TITLE
visual glitch

### ISSUE THREAD

**Issue by aurora-1-2-3** [JannisX11/blockbench#2507]
### What are you trying to do, and what do you expect to happen?

![image](https://github.com/user-attachments/assets/e1dac8a8-2064-4ede-a7c0-be13ad78122e)
the bar is glitched everywhere

### What happens instead?

the > sign is a bit offset on the [resize] bar

### Model format in which the issue occurs

everywhere

### Blockbench variant

Program

### Blockbench version

4.11.4

### Operating System

linux

**Comment by JannisX11** [comment]
I'm not seeing a glitch. Where is the glitch?

**Comment by aurora-1-2-3** [comment]
The bar's ">" sign is offset

**Comment by JannisX11** [comment]
Seems to be related to UI / screen scaling. Fixed it as much as possible within the limitations.

**Comment by aurora-1-2-3** [comment]
yeah its definitely the scaling
