### ISSUE TITLE
[Issue] Can't export to OBJ | Cannot read property 'id' of undefined 

### ISSUE THREAD

**Issue by IIeJImewek** [JannisX11/blockbench#251]
When i try to export the model to OBJ, it writes something like that.
![issue](https://user-images.githubusercontent.com/47460147/52499636-ec679b80-2bec-11e9-945d-ed90cead042a.PNG)

**Comment by JannisX11** [comment]
For now giving all faces a texture solves the problem.

**Comment by JannisX11** [comment]
Fixed in 2.5.
