### ISSUE TITLE
"Villager (New)" model is outdated, not matching with vanilla model

### ISSUE THREAD

**Issue by REMDRIFT** [JannisX11/blockbench#2512]
### What are you trying to do, and what do you expect to happen?

In MC 1.19, the body overlay of the villager model was extended downwards by two pixels to fix certain textures being cut off. The "Villager (New)" model in the skin format should match this.

### What happens instead?

The "Villager (New)" model does not match the current vanilla model. The body overlay is 18 pixels long on the Y axis when it should instead be 20.
![villager_comparison](https://github.com/user-attachments/assets/184c8ee4-ce7d-4565-ac23-47baa5d37fe3)

### Model format in which the issue occurs

Minecraft Skin

### Blockbench variant

Program

### Blockbench version

4.11.1

### Operating System

Windows

**Comment by JannisX11** [comment]
Seems to still be an issue in bedrock. Funny.
https://bugs.mojang.com/browse/MCPE-155044
