### ISSUE TITLE
Android file download issue

### ISSUE THREAD

**Issue by Gui64977** [JannisX11/blockbench#2519]
### What are you trying to do, and what do you expect to happen?

Download 2 or more files without issues on the website or web app

### What happens instead?

Example: i made 2 .png files 1.png and 2.png when i download any file when i try to download other the download don't appear(only appear when I restart the website or the web app)
I don't know that this occurs on PC or iOS

### Model format in which the issue occurs

Any

### Blockbench variant

Website, PWA

### Blockbench version

4.11.1

### Operating System

Android

**Comment by JannisX11** [comment]
This is most likely an issue with Chrome. You can try these steps: [https://support.google.com/chrome/thread/240279398/issues-downlaoding-files-in-chrome?hl=en#:~:text=Go%20to%20"Settings%20>%20Privacy%20and,"%20Click%20"Clear%20data."&text=Conflicting%20extensions%20might%20cause%20download,see%20if%20the%20problem%20persists](https://support.google.com/chrome/thread/240279398/issues-downlaoding-files-in-chrome?hl=en#:~:text=Go%20to%20%22Settings%20%3E%20Privacy%20and,%22%20Click%20%22Clear%20data.%22&text=Conflicting%20extensions%20might%20cause%20download,see%20if%20the%20problem%20persists).

**Comment by JannisX11** [comment]
Added a pop-up to select the file format before downloading as a workaround.
