### ISSUE TITLE
Export bug 4.11.1

### ISSUE THREAD

**Issue by Svyato88** [JannisX11/blockbench#2520]
### What are you trying to do, and what do you expect to happen?

Exporting a generic model to obj is not correct, when trying to export, all cuboids are slightly higher than where they should be. Everything worked fine in version 4.10

### What happens instead?

Exporting not correct
![зображення_2024-10-19_092342948](https://github.com/user-attachments/assets/08f1e689-50a4-4e21-8097-5df3f9447c5c)
![зображення_2024-10-19_092353270](https://github.com/user-attachments/assets/5b2abfe3-5ebe-440a-a1bc-cd2e221af6dd)

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Blockbench version

4.11.1

### Operating System

Windows 10

**Comment by JannisX11** [comment]
I can't reproduce the issue. Could you attach a model that is affected as bbmodel file?

**Comment by Moonspire** [comment]
I'm having this same issue on the Generic Model format on the 4.11.1 client application. I run Linux Mint. When opening an exported obj file in Blender it loads the file with the cuboids offset by about half a block with the mesh parts staying where they should be.
![image](https://github.com/user-attachments/assets/e22b0481-9121-45cc-aebb-e8a6329c6c01)
![image](https://github.com/user-attachments/assets/16026add-3265-4644-a23e-bf34132e2feb)
