### ISSUE TITLE
Not Able to import anything 

### ISSUE THREAD

**Issue by PolarFreddy** [JannisX11/blockbench#2522]
### What are you trying to do, and what do you expect to happen?

I tried to import a texture but all my images were greyed out and then I tried to import a model and the same thing happened 

### What happens instead?

Everything was greyed out and unable to be opened 

### Model format in which the issue occurs

All

### Blockbench variant

Website

### Blockbench version

Latest

### Operating System

Android

**Comment by JannisX11** [comment]
This is a regression on Android. It already happened once last year (#2004), they fixed it after several weeks. Hopefully they'll fix it again, for now try using a different browser.
