### ISSUE TITLE
I can't import files

### ISSUE THREAD

**Issue by Clydehendrick** [JannisX11/blockbench#2524]
### What are you trying to do, and what do you expect to happen?

I was trying to import a .json file, because i want to add more details to the model

### What happens instead?

It didn't let me import any file except images it is all locked

### Model format in which the issue occurs

Anything that has "." like .json, .geo, etc...

### Blockbench variant

Website, PWA

### Blockbench version

Latest

### Operating System

Android

### Installed Blockbench plugins

Nothing

**Comment by PolarFreddy** [comment]
I'm having the same problem but I can't import anything like textures .bbmodel .json anything

**Comment by S0nicCr8ft** [comment]
> I'm having the same problem but I can't import anything like textures .bbmodel .json anything

They banned importing files on Android

**Comment by PolarFreddy** [comment]
Oh ok is the ban permanent or was it by mistake something like that or was it intentional

**Comment by JannisX11** [comment]
Duplicate of #2522
