### ISSUE TITLE
SaveAs and FileName reverting when not supposed to

### ISSUE THREAD

**Issue by Arkaliasus** [JannisX11/blockbench#2525]
### What are you trying to do, and what do you expect to happen?

using 'Save As' to change the filename and have the actual name of the file change to the file name

### What happens instead?

the file name changes but not its 'title filename' in the recent models list (i have to roll over the model and check the entire path to make sure its the correct model)
EDIT: it also changes back to the previous filename if you dont save the texture locations when periodically saving the file

### Model format in which the issue occurs

all model types

### Blockbench variant

Program

### Blockbench version

4.9.4
(i cannot upgrade because the later versions of blockbench break MCreator after exporting to it)

### Operating System

Win10

### Installed Blockbench plugins

it happens with or without plugins
(Currently:  CEM Loader, Minecraft Title Generator, GeckoLib, Player Statue Generator, Shape Generator, Structure Importer, Bakery, Pie Menus)

**Comment by JannisX11** [comment]
Could you specify the file format? Different formats work differently so it would be good to know where you experienced an issue. An option called "Save As" only exists for textures, so it's unclear to me if you saved as project file, as a specific model file, or something else.

**Comment by Arkaliasus** [comment]
in java/block item as bbmodel, clicking 'save project as'  and when saving the project yes, the texture save windows come up but i cancel them as i do not need them to save, then the filename at the top changes back to its previous filename.
then when i got to 'export to JSON' it also uses the previous filename as well.

i apologise for my vagueness before

**Comment by JannisX11** [comment]
This was already fixed in 4.10.

**Comment by Arkaliasus** [comment]
> This was already fixed in 4.10.

unfortunately i've had to rollback to 4.9.4 in order to be able to export models correctly from blockbench into MCreator.
