### ISSUE TITLE
All my fun junk is gone

### ISSUE THREAD

**Issue by NiNonade** [JannisX11/blockbench#2530]
### What are you trying to do, and what do you expect to happen?

I was just modelling like normal and then I think I accidentally double-clicked one of my meshes (which just usually switches it from move mode to resize mode)

### What happens instead?

I can no longer see any of my groups or meshes in my sidebar. I can still model just fine, but like I can't group or select certain meshes in my sidebar anymore, now it just allows me to add stuff like it was a toolbar ig? Idk if I'm just an idiot and this is a feature (sometimes when I do stuff too quickly stuff disappears because my fingers are flying all over the place) or if it's an actual bug but like it shouldn't even be a thing if it IS a feature??? Like why would you have your app for modelling and animating make it harder to model and actually impossible to animate?
![Screenshot 2024-10-29 003307](https://github.com/user-attachments/assets/548cde0c-f94b-4850-ba3c-739a81a939fc)

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.10.4

### Operating System

Windows 11 on Dell

**Comment by JannisX11** [comment]
Can you share a picture of your entire screen?

**Comment by NiNonade** [comment]
> Can you share a picture of your entire screen?

![image](https://github.com/user-attachments/assets/1081b8f9-4488-4bc3-a26e-228a6d2bc666)
![image](https://github.com/user-attachments/assets/5cbc1d6c-a1db-4842-8f75-0f78f075d6ed)

**Comment by JannisX11** [comment]
Looks like you folded your left sidebar and rearranged some panels. You can revert your panel changes by pressing Help > Developer > Reset Layout and you can unfold your sidebar by pressing the arrow button in the bottom left corner.

**Comment by NiNonade** [comment]
Literally thank you sm (sorry for wasting your time with my slow brain)
