### ISSUE TITLE
Zombie's UV size is not matching with the base texture's UV size

### ISSUE THREAD

**Issue by SumRandomDewd** [JannisX11/blockbench#2535]
### What are you trying to do, and what do you expect to happen?

I'm trying to load the base Zombie's texture into the Zombie format, and it should load without any issues

### What happens instead?

The Zombie format uses a 64x32 texture, instead of the 64x64 the base Zombie texture uses, which causes the texture to appear weirdly. Screenshot below:
![image](https://github.com/user-attachments/assets/e8b8ec99-937f-439c-affb-f5d7c1915121)
Though it can be ignored easily by simply clicking the UV size in the top-left and changing it to 64x64, so it's not completely necessary to fix this bug.

### Model format in which the issue occurs

Zombie

### Blockbench variant

Program

### Blockbench version

4.11.1

### Operating System

Windows

**Comment by JannisX11** [comment]
Aha, another discrepancy between Bedrock and Java.
