### ISSUE TITLE
[Issue] Travis CI does not build Windows 32 bit binaries with a seperate name

### ISSUE THREAD

**Issue by loveGhb** [JannisX11/blockbench#254]
Download link to version Windows 32 2.4.0 (32 bit) does not work

![image](https://user-images.githubusercontent.com/21294689/53168141-0b9dfa00-35eb-11e9-9b86-0e8bd6cbc3c8.png)

**Comment by JannisX11** [comment]
Cause of this issue: https://github.com/electron-userland/electron-builder/issues/3574

**Comment by JannisX11** [comment]
Found a workaround.
