### ISSUE TITLE
[Issue] Extruded textures don't have their textures

### ISSUE THREAD

**Issue by eot13** [JannisX11/blockbench#255]
When I import an Extruded Texture it just doesn't have texture.

![capture](https://user-images.githubusercontent.com/22939718/53268141-93682f00-36e5-11e9-804b-21ff125db0eb.PNG)

Blockbench variant: Webapp and Desktop

**Comment by JannisX11** [comment]
Fixed in 2.5.

**Comment by eot13** [comment]
Thank's
