### ISSUE TITLE
Cannot install through deb file.

### ISSUE THREAD

**Issue by Shadowblitz16** [JannisX11/blockbench#2557]
### What are you trying to do, and what do you expect to happen?

I can't install on kubuntu 24.04
![image](https://github.com/user-attachments/assets/4032f835-840f-41fb-ab96-8fd8c488c95c)

### What happens instead?

Can't satisfy dependencies.

### Model format in which the issue occurs

NA

### Blockbench variant

Program

### Blockbench version

Latest

### Operating System

Kubuntu 20.04 aka Ubuntu 20.04

### Installed Blockbench plugins

NA

**Comment by JannisX11** [comment]
Can you see which dependencies are missing?
Try this: https://www.reddit.com/r/Kubuntu/comments/uagi8x/kubuntu_dependency_issue/

**Comment by Shadowblitz16** [comment]
> Can you see which dependencies are missing? Try this: https://www.reddit.com/r/Kubuntu/comments/uagi8x/kubuntu_dependency_issue/


`dpkg -i` worked
