### ISSUE TITLE
Animation record

### ISSUE THREAD

**Issue by foxitor** [JannisX11/blockbench#2562]
### Detailed description of your suggestion

when i need to record an animation i have no choice but to record a gif, i want to be able to save it in mp4 format.

**Comment by JannisX11** [comment]
https://www.blockbench.net/plugins/scene_recorder

**Comment by JannisX11** [comment]
Duplicate of #1521

**Comment by foxitor** [comment]
> https://www.blockbench.net/plugins/scene_recorder

thx!
