### ISSUE TITLE
Y axis move button not working

### ISSUE THREAD

**Issue by CyledTheRadioactive** [JannisX11/blockbench#2574]
### What are you trying to do, and what do you expect to happen?

I was creating a Luffy model but i cant move the body upwards.

### What happens instead?

Can't move a part upwards or downwards

### Model format in which the issue occurs

Json

### Blockbench variant

Website

### Blockbench version

I dont know which version

### Operating System

What is this?

### Installed Blockbench plugins

I installed some plugins

**Comment by JannisX11** [comment]
You can find the version number in Help > About.
Json is a file format, not a model format. Some formats have size limits, that's probably what you are seeing.
