### ISSUE TITLE
blockbench screen for modeling bug instead it goes to the bottom corner Phone I am using = HUAWEI NOVA 2 Lite

### ISSUE THREAD

**Issue by LittlePrinces001** [JannisX11/blockbench#2585]
### What are you trying to do, and what do you expect to happen?

I don't do anything and I just want to do modelling 

### What happens instead?

The screen is under the the corner so I can't make a model

### Model format in which the issue occurs

App And Blockbench Web

### Blockbench variant

Website

### Blockbench version

4.1.1.2

### Operating System

Android 

### Installed Blockbench plugins

Nothing

**Comment by LittlePrinces001** [comment]
![Uploading IMG-20241214-WA0613.jpg…]()

**Comment by JannisX11** [comment]
Is it this issue? https://github.com/JannisX11/blockbench/issues/2444

**Comment by LittlePrinces001** [comment]
Yes

**Comment by JannisX11** [comment]
Duplicate of #2444

**Comment by LittlePrinces001** [comment]
But The Blockbench Work On Mam 😡
