### ISSUE TITLE
Two finger zoom and pan not working on Paint mode in UV screen

### ISSUE THREAD

**Issue by mflux** [JannisX11/blockbench#2587]
### What are you trying to do, and what do you expect to happen?

Trying to navigate the UV panel using two fingers within paint mode. I expect it to work like Edit mode.

### What happens instead?

In the UV image editor, within Paint mode, two finger swipe to pan and zoom does not work. Something is capturing the input 
causing the entire screen to attempt shrink, rather than the expected behavior.

In Edit mode, that panel works correctly with touch, I can two finger pan and zoom perfectly.

### Model format in which the issue occurs

Generic

### Blockbench variant

Website

### Blockbench version

4.11.2

### Operating System

ipadOS

**Comment by JannisX11** [comment]
The default tool in paint mode is the brush. There is a navigation tool (hand icon) that you can select to navigate with one or two fingers. If you don't see this, enable Mobile Interface Mode in the settings.
