### ISSUE TITLE
[Issue] Paint tool doesn't work correctly when painting over transform indicators

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#259]
Paint tool doesn't work correctly when painting over transform indicators.

Video: https://youtu.be/I4j6hBxQ-Do
Image:
![image](https://user-images.githubusercontent.com/44243757/53757477-6de8db80-3ec4-11e9-97ad-56f56f8de98e.png)

Using Blockbench 2.4.0 Win10 Desktop

**Comment by JannisX11** [comment]
Fixed in 2.5.
