### ISSUE TITLE
[Issue] Face Borders inaccurate for paint tool

### ISSUE THREAD

**Issue by innova67** [JannisX11/blockbench#260]
Paint tools doesn't edit textures properly.
* paint bucket in face mode fills extra pixels from adyacent textures (paint tool have the same issue).
* paint bucket in cube mode doesn't fills certain faces of a cube.

video: https://imgur.com/2BcxMpt
![bug2](https://i.imgur.com/2BcxMpt.mp4)

extra pixels in texture: 
![bug1](https://user-images.githubusercontent.com/37458981/53845577-009a8080-3f80-11e9-9782-e6c3cb894ccc.png)

blockbench v2.4.0
Desktop version, windows 10 pro

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
