### ISSUE TITLE
Model cannot be copied

### ISSUE THREAD

**Issue by awsl1212** [JannisX11/blockbench#2601]
### What are you trying to do, and what do you expect to happen?

Models of the same format cannot be copied from another project

https://github.com/user-attachments/assets/b6eead6d-0eaa-444b-bca6-80abdfdfd2a3

### What happens instead?

Unable to copy

### Model format in which the issue occurs

bedrock

### Blockbench variant

Program

### Blockbench version

4.12.0Beta1

### Operating System

win11

**Comment by JannisX11** [comment]
Duplicate of 2600
