### ISSUE TITLE
[Issue] Textures reset to default naming when loading a model

### ISSUE THREAD

**Issue by Luke18033** [JannisX11/blockbench#261]
While editing my resource pack recently I discovered that I was using a very old version of Blockbench (1.11.x if not earlier). After updating to the latest version, textures will no longer load properly when opening most models. Specifically...

- All textures on the model will be replaced by the default multicolored missing texture
- The textures will still appear on the left panel, but all of the variables will be reset to the default numbering instead of what is set in the model file
- Upon saving the model, the `textures` block will be removed entirely and all of the texture variables on the model will be set to `#missing`

This affects all models which don't use the default texture naming scheme (a.k.a pretty much every model). This seems to affect both the desktop app and the web app, though I wasn't able to fully test the latter. Operating system is Windows 10. Nothing unusual appeared in the console.

Aslo, changing the names of missing textures to `#missing` just seems like bad design. There are so many cases when a texture might be "missing" as far as Blockbench is concerned but appear fine in-game. What if the model is used as a parent? What if the texture is from another resource pack? The older version of Blockbench I was using prior to installing the update didn't do this, and I cannot figure out why you would decide to implement this "feature".

For reference, [here](https://drive.google.com/open?id=1-xpQ4ARLyidav18AyzDciJKGwbc61jIw) is a model before opening it in Blockbench and [here](https://drive.google.com/open?id=1hGAl5F7tthzymXtdmQhoaV2c4Q_IyR24) is the same model after. The fact that such a major bug hasn't been reported yet makes me think that either something's wrong on my end, or it has been reported and I just didn't see the issue.

**Comment by JannisX11** [comment]
Fixed in 2.5.1.

**Comment by Luke18033** [comment]
Nothing has still been done about textures being renamed to `#missing`. This happens immediately when opening a model with faces that reference an invalid texture, and is a huge issue with models used as a parent. Is there some weird technical limitation that forces you to do this? I highly doubt it but I can't think of any other reason you would implement this.

**Comment by JannisX11** [comment]
When working on this, I did not optimize the system for models using the parenting feature that are spread across multiple files. But I get your problem.
The current situation is that faces that reference an existing texture will also be linked to that texture in Blockbench, while faces that reference a texture that might be included in the parent model, will not.
One possible solution for this problem would be to also load these implicitly referenced textures into Blockbench.

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
