### ISSUE TITLE
[Issue] Ghost cubes after undoing added model

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#263]
Ghost cubes after undoing added model

How to reproduce issue: 
- Add model
- Undo
 
Image:
![image](https://user-images.githubusercontent.com/44243757/54113799-c141b900-43f1-11e9-80f9-e7281f52ad35.png)

Blockbench 2.5.0

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
