### ISSUE TITLE
.jpm importing problem

### ISSUE THREAD

**Issue by MichalTygrys** [JannisX11/blockbench#266]
So, i was trying to import my .jpm file from another project, but it doesn't work, like at all. Am I doing something wrong? I was trying to go File>import>jpm but it isn't working. How do I import these?

**Comment by JannisX11** [comment]
To import model files, use File > Import Model.

**Comment by MichalTygrys** [comment]
I know, but importing jem and jep models is messed up

**Comment by JannisX11** [comment]
If you have a model file that you cannot open, please provide the broken model file here.
