### ISSUE TITLE
[Suggestion] Option to generate texture to the nearest power of 2.

### ISSUE THREAD

**Issue by TheCactus27** [JannisX11/blockbench#267]
When using the generate texture tool, I like to have my texture be the nearest power of 2 (i.e. 16x16, 128x128, etc) as the mod I model for requires textures to be in a power of 2. To avoid the hassle of trying to make a 48x48 texture fit in a 64x64 texture sheet, would it be possible to "lock" the texture to the nearest power of two?

**Comment by JannisX11** [comment]
Added in 2.6.0.
