### ISSUE TITLE
[Issue] Blockmode inflate resets after reopening file

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#269]
Blockmode inflate resets after reopening file

Before saving:
![image](https://user-images.githubusercontent.com/44243757/54267216-88d0e500-4581-11e9-93e3-a8473594d485.png)

After saving & reopened:
![image](https://user-images.githubusercontent.com/44243757/54267294-a140ff80-4581-11e9-828a-8a4cf4e7ea5b.png)

Blockbench 2.5.1

**Comment by JannisX11** [comment]
Works as intended. Blockmodels don't support inflate natively so it gets translated into the size.
