### ISSUE TITLE
[Issue] Selected cubes wont be unselected after selecting a group

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#270]
Selected cubes wont be unselected after selecting a group.
So basically it does a ctrl selection without pressing ctrl.
And when pressing ctrl, the cube will be unselected.

How to reproduce issue:

-select cube
-select group
-cube stays selected

![image](https://user-images.githubusercontent.com/44243757/54423212-d16ed680-4718-11e9-9c9b-997b815431fd.png)

Blockbench 2.5.1

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
