### ISSUE TITLE
I can't install BlockBench

### ISSUE THREAD

**Issue by SummerNugget** [JannisX11/blockbench#272]
I don't know what is happening so I can't put much info about it but everytime I try to open the installer it gives me a pop-up that says "Windows 7 or above is required." and then says close but I have Windows 10 not below Windows 7, I tried compatibility mode on Windows 7 and 8 but still the same response, downloaded BlockBench for 32-Bit Operating Systems still nothing, same response, can someone help me because I have seen good reviews about this program and I want to model something for a mod I am making and I need it like right now, a fast response to my issue is appreciated.

**Comment by JannisX11** [comment]
Solved on Discord server.
