### ISSUE TITLE
[Issue] Toggle UV Overlay glitch

### ISSUE THREAD

**Issue by kroer** [JannisX11/blockbench#273]
UV map disappears after moving (but returned to its original place) when texture area loose focus. It reappears if toggle UV overlay or resize texture area.

This bug also appears if press alt button when UI overlay is enabled. But texture area should receive focus at least once before alt pressing.

- Desktop 2.5.1
- Windows 10

Sorry for bad English.

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
