### ISSUE TITLE
[Issue] Color picker appears at wrong location if applied to UV window toolbars

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#274]
Color picker appears at wrong location if applied to UV window toolbars.

Image:
![image](https://user-images.githubusercontent.com/44243757/54495620-db95fe00-48ed-11e9-9cc2-3a27a83b52cf.png)

How to reproduce issue:
- Open full view
- Add color to toolbar
- Exit full view window
- Open color tool from paint window

Blockbench 2.5.1 Win10 Desktop

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
