### ISSUE TITLE
[Suggestion] Blockmodel to Bedrock Entity conversion

### ISSUE THREAD

**Issue by Xhrng** [JannisX11/blockbench#275]
I created a very detailed model for the Bedrock Edition of Minecraft, and I wanted to export it as a bedrock entity. However, when I went to export it, the option wasn't there. I assumed that I started creating the model by clicking "New Model" instead of "New Entity Model". I exported the model as a Blockmodel, and the texture as a PNG. I tried to convert it by creating a New Entity Model, then importing the old model and its texture. I opened the exporting dropdown menu, but the option to export as a Bedrock Entity wasn't there. In fact, upon trying the process again, I realized the option disappears right as you load in the Blockmodel. Long story short, I want to be able import a Blockmodel and then export it as a Bedrock Entity. Thanks!

**Comment by JannisX11** [comment]
You can go to File > Project and use the convert button there. The texture will not work the way it did in the block model and you will likely have to redo a few rotations and create a bone structure, but after you've done that, you will be able to export the model as an entity model.
