### ISSUE TITLE
[Issue] Color palette offset if using zoom

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#276]
color palette will be offset or scaled by few pixels if zoom is active.

Zoom on:
![image](https://user-images.githubusercontent.com/44243757/54518312-9cf35880-496c-11e9-8bd6-591643c209d7.png)

Zoom off:
![image](https://user-images.githubusercontent.com/44243757/54518337-ae3c6500-496c-11e9-8254-29008cd541cf.png)

Blockbench 2.5.1

**Comment by JannisX11** [comment]
Fixed as well as possible in 2.6.0.
