### ISSUE TITLE
[Issue] Undo wont update on paint tools with opened models

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#277]
Undo wont update on paint tools on opened models.

How to reproduce issue:
- Open random model from recent
- Use any paint tool on already existing texture
- Undo wont update model (it did undo but doesn't visually update it), looks fine after reopening file.

Video: https://youtu.be/LiNOdHuuP3Q

Using: Blockbench 2.5.1 Desktop (Windows)

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
