### ISSUE TITLE
[Issue] Textures menu moving out

### ISSUE THREAD

**Issue by Captainjej** [JannisX11/blockbench#280]
Hello. i have that's strange problem.
My textures on texture menu selection moving out from their positions ant this make hard for choose them and make hard orientation.
I use Dekstop blockbench dekstop, but thats bug being on webapp too.
My OC is Windows10 professional
Monitor resolution 1600x900

![image](https://user-images.githubusercontent.com/48762711/54692313-64fc3900-4b57-11e9-8352-f371023aaeff.png)

**Comment by JannisX11** [comment]
Closed due to inactivity.
