### ISSUE TITLE
[Issue] Model disappears when going to display mode while moving camera

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#281]
Model & gird disappears when going to display mode while moving camera.

How to reproduce issue
- move camera (left or right click)
- press 3 while moving camera

Video:
![issue](https://user-images.githubusercontent.com/44243757/54986595-9cd20900-4fbb-11e9-98fa-6e426d15e3e9.gif)

**Comment by JannisX11** [comment]
Fixed in 2.6.0.
