### ISSUE TITLE
[Issue]UV interface question

### ISSUE THREAD

**Issue by GreenChennai** [JannisX11/blockbench#282]
UV interface (whether in the main interface or open a separate UV window),When choosing a grid (such as 16x16), it seems that it is not always possible to successfully switch to the selected grid.
And
There is an error exporting the .jpm file,All elements are misplaced,May be related to the center of rotation?

**Comment by JannisX11** [comment]
The grid issue will be fixed in 2.6.1. Please create another issue for the jpm missplacement if you still get that problem.
