### ISSUE TITLE
Modelling particle issue

### ISSUE THREAD

**Issue by supershadowx** [JannisX11/blockbench#283]
I am a noob at this, I just started yesterday, so any suggestions or help I'd appreciate being as simple as possible. I have also seen that there are some similar issues posted here but none have the solution I am looking for.

Anyways, so I wanted to add 3D handles to my doors, but of course all the doors have a parent model, but the handles are different. To get round this, I copied and renamed the parent door models, and edited the acacia door model to recognise the new parent. I edited all the new acacia parent models to have 3d handles, and after a few trial and errors got it to work fine.

Until I broke a door.

I have the typical purple/black break particles, and I cannot for the life of me fix it. I added the "particle": "block/blablafilename" in the correct position in the .json file, first for the new parents, then for the acacia model, and then for both. When I add this line in, it seems to break the model completely and the whole door is a purple and black mess. I delete the line, all is good but no particle.

I have researched and researched and my only thought is it is something to do with the fact I took door_whatever and changed that to be the new parent for the acacia door. 

Perhaps its too advanced for me, I don't know. All I want is for the particles to work! Thanks D:

**Comment by JannisX11** [comment]
My guess is that you didn't use correct JSON. Use this tool to validate your JSON code: https://jsonlint.com

**Comment by JannisX11** [comment]
Also, please ask on the Discord server (http://discord.blockbench.net) if you need help with modeling.
