### ISSUE TITLE
[Suggestion] Tris/Vertices Count

### ISSUE THREAD

**Issue by TheCactus27** [JannisX11/blockbench#284]
Have a section in the toolbar or somewhere else that displays how many Tris, Vertices and other model information.

**Comment by JannisX11** [comment]
Gonna expand on the idea, maybe for a future update. I could Imagine it would be a little popup that appears when you click on the element count
*Bone count
*Faces
...to be continued

**Comment by JannisX11** [comment]
Added in 3.0.
