### ISSUE TITLE
[Issue] Switching to entity/block mode doesn't switch mode for other users on sessions

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#285]
Switching to entity/block mode doesn't switch mode for other users on sessions.

How to reproduce issue:

- Create session
- Project > to entity/block model
- Doesn't update for all users

Blockbench 2.6.0

**Comment by iWackyMinecraft** [comment]
Same thing with adding block models on entity mode.

**Comment by JannisX11** [comment]
Fixed in 3.0.
