### ISSUE TITLE
[Issue] Cube and group renaming gets interrupted by actions by other users

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#286]
Cube and group renaming gets interrupted by actions by other users.

How to reproduce issue:
- Create session
- Create a group/cube
- User1: Start renaming cube
- User2: Do an action (example move cube location)
- User1's renaming gets interrupt

Blockbench 2.6.0

**Comment by JannisX11** [comment]
Fixed in 2.6.5.
