### ISSUE TITLE
[Issue] Cube color or texture changes wont update for other users

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#288]
Cube color or texture changes wont update for other people until cube is updated again.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44243757/55723422-bc345180-5a11-11e9-9557-5efe2198ae16.gif)

Blockbench 2.6.0

**Comment by JannisX11** [comment]
Fixed in 2.6.5.
