### ISSUE TITLE
[Issue] Scale gets increased while dragging UV

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#291]
Horizontal scale gets increased while dragging UV
Used 48x texture but i saw it happening to other people also (with different resolutions)

![uv_issue](https://user-images.githubusercontent.com/44243757/55749720-53b59680-5a4a-11e9-8e81-a7be3efc9048.gif)

Blockbench 2.6.0

**Comment by iWackyMinecraft** [comment]
Looks like this is caused by decimals. Set your UV scale to 1.46 for example.

**Comment by JannisX11** [comment]
Fixed in 2.6.5.
