### ISSUE TITLE
[Issue] Resize or move is not 1px

### ISSUE THREAD

**Issue by Milouvert** [JannisX11/blockbench#294]
MacBook Air, macOs 10.14.3, Desktop version.

When I try moving or resizing, since the last update, I cannot resize for exact pixels, unless it's a multiple of 8.

![Capture d’écran, le 2019-04-11 à 20 25 36](https://user-images.githubusercontent.com/38847520/56004200-00388800-5c98-11e9-8c02-3336fe63defc.png) (after one scale) on X.

**Comment by JannisX11** [comment]
The amount it moves depends on your grid. You can change the snapping grid in the settings. Open the settings, go to the "Snapping" category and change the "Grid Resolution" to 16.
