### ISSUE TITLE
[Issue] Cannot unselect when dragging/rescaling/rotating cubes with tools.

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#297]
Cannot unselect when dragging/rescaling/rotating cubes with tools.

Blockbench 2.6.5

**Comment by iWackyMinecraft** [comment]
Well it happens with all tools (recale, rotate also)

**Comment by JannisX11** [comment]
Does this still happen in Blockbench 2.6.5? Cannot reproduce.

**Comment by iWackyMinecraft** [comment]
Sorry added wrong version. Happened on 2.6.5 Now that i restarted it wont happen again, not sure what caused it
