### ISSUE TITLE
[Issue] Confusing colours on blank elements

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#3]
![image](https://user-images.githubusercontent.com/8559428/26944946-8358cdc8-4c8a-11e7-9811-0908de4b5af7.png)
As you can see there are 3 elements.

![image](https://user-images.githubusercontent.com/8559428/26944974-97fd657c-4c8a-11e7-92ce-0b0927600705.png)
If you look at it from this angle you can see that you can hardly distinguish how many elements there are and how they are placed.

I would suggest that you give each new element (maybe duplicates get the same colour) a random colour that is **flat** so that there is no confusion.

**Comment by JannisX11** [comment]
Added for the next version (1.6.6 or 1.7)
