### ISSUE TITLE
[Issue] Extrude Image dialog has old style dropdown 

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#304]
The dropdown menu in the Extrude Image dialog differs from the new style:
Old:
![image](https://user-images.githubusercontent.com/29360565/56085308-1b92c700-5e41-11e9-91fc-eb7a2ad46abe.png)
New:
![image](https://user-images.githubusercontent.com/29360565/56085314-2c433d00-5e41-11e9-8110-5e36ae3ac336.png)

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
