### ISSUE TITLE
[Issue] Problem with export JEM

### ISSUE THREAD

**Issue by A2va** [JannisX11/blockbench#307]
The size values heigh and depth are reversed on the JEM file.
Example:
![Capture](https://user-images.githubusercontent.com/49582555/56214533-5cb3f280-605e-11e9-9313-6bd65435c7a2.PNG)
![2019-04-16_15 37 09](https://user-images.githubusercontent.com/49582555/56214536-5e7db600-605e-11e9-9d32-f68d591a4b36.png)
![Capture2](https://user-images.githubusercontent.com/49582555/56214540-60477980-605e-11e9-86e8-3b6a2997d99f.PNG)

And if I invert the values of height and depth
![Capture3](https://user-images.githubusercontent.com/49582555/56353360-7cb7f300-61d1-11e9-8035-253e6243ea44.PNG)

![2019-04-16_15 45 22](https://user-images.githubusercontent.com/49582555/56214766-c16f4d00-605e-11e9-810c-7b8bd29861a1.png)
Inverting it works

**Comment by A2va** [comment]
For the second text sreenshot. I was wrong. It's supposed to be him.
![Capture3](https://user-images.githubusercontent.com/49582555/56214978-29be2e80-605f-11e9-9ff6-d3261360fb05.PNG)

**Comment by JannisX11** [comment]
The values represent width, height and length in that order. So the original output 12, 1, 8 is correct. The fact that it looks correct by switching the number is just a coincidence and doesn't always work.

I think your issue is that you are replacing a bone that is rotated by 90 degrees by default (e. g. "body"). That's why it looks off.

**Comment by A2va** [comment]
In the rotation options everything is at 0. I do not understand what's going on unless it's optifine

**Comment by JannisX11** [comment]
It's Optifine that rotates any bones by default.
To create it looking the right way, first rotate the body bone by x: -90°, then create your model. Before you export the model, set the rotation back to 0.
Fun fact: This weird mechanic is how the creeper was born originally.

**Comment by A2va** [comment]
Ok thanks for your help
