### ISSUE TITLE
[Issue] Textures can't be seen 

### ISSUE THREAD

**Issue by DatDopeBro** [JannisX11/blockbench#308]
I have recently encountered an issue which occurs when I attempt to create a texture for my model. The whole model changed according to the background color I have selected instead of the original color which indicates the part of the model. I am currently using v2.6.6 and have only recently encountered such issue.
![zombie v1 8 - Blockbench 19_04_2019 22_16_47](https://user-images.githubusercontent.com/12470479/56428214-2d68e400-62f1-11e9-9e74-d2bc9fb4e8bf.png)
![zombie v1 8 - Blockbench 19_04_2019 22_17_41](https://user-images.githubusercontent.com/12470479/56428229-3a85d300-62f1-11e9-8f21-8f4bc533dafd.png)
![zombie v1 8 - Blockbench 19_04_2019 22_18_01](https://user-images.githubusercontent.com/12470479/56428239-3fe31d80-62f1-11e9-8684-6f013409e984.png)

**Comment by JannisX11** [comment]
The element colors are just temporary colors to help you differenciate your cubes. You have to create your texture yourself.
