### ISSUE TITLE
[Issue] Cannot drag UV area outside of UV box when zoomed in

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#309]
Cannot move the UV area by dragging outside of the UV selection when zoomed in enough.
Texture used: 48x

Looks like the drag area somehow changes position or something.

![issue](https://user-images.githubusercontent.com/44243757/56428366-cbe04f80-62c7-11e9-9e97-9b754d1d2542.gif)

Blockbench 2.6.6

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
