### ISSUE TITLE
[Issue] [Plugin] Clone brush doesn't paste inflated cubes correctly

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#318]
Clone brush doesn't paste inflated cubes correctly.
![E](https://user-images.githubusercontent.com/44243757/56811537-972d4480-6841-11e9-9c66-999f2adc3773.gif)

**Comment by JannisX11** [comment]
Please post on the plugin repository: https://github.com/JannisX11/blockbench-plugins/issues
