### ISSUE TITLE
[Issue] Editing origin with number values moves cubes

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#319]
Seems like editing origin on rotated cube moves the cube, but origin tool works fine.
Using blockmode.

![issue](https://user-images.githubusercontent.com/44243757/56835720-b3e76d80-687d-11e9-91f0-c42e1d769345.gif)

Blockbench 2.6.6

**Comment by JannisX11** [comment]
Works as intended. Because the origin tells the rotated element around which point to rotate, this will also affect the element's global position.
