### ISSUE TITLE
[Issue] Blockbench's MoLang parser is case sensitive

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#320]
If we test a model in-game with animations that have expressions like `mAtH.cOs()`, it will work just fine because it internally gets converted to `math.cos()`. However, this is not the case with Blockbench, where a small capitalization error can break the whole animation.
![2019-04-27_19-57-59](https://user-images.githubusercontent.com/29360565/56852676-74249280-691e-11e9-858c-9ff7fea2649e.gif)

**Comment by JannisX11** [comment]
Didn't know Molang was case insensitive.

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
