### ISSUE TITLE
[Suggestion] Ability to add extra optifine JEM data

### ISSUE THREAD

**Issue by Zeevruchtje** [JannisX11/blockbench#323]
Having the ability to add extra json data to parts of an an optifine model, like:

- Attach: true or false
- Animations array
- Rotation (so you can rotate the body 90 degrees back on export, which is necessary for some models)

Having this functionality saves the hassle of having to add this data to the .jem file manually every time an optifine model is exported.

**Comment by JannisX11** [comment]
Support for these fields has now been added in 4.0, although "attach" has no UI to change it directly in Blockbench. Additionally, the plugin https://www.blockbench.net/plugins/cem_template_loader now adds an animation editor that allows animations to be edited and previewed inside Blockbench.
