### ISSUE TITLE
[Issue] Invalid .bbmodel files with saving

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#324]
Invalid bbmodel files with saving:

How to reproduce issue:

- Create a .bbmodel file
- Add new cube
- Save file
- Open file again

![image](https://user-images.githubusercontent.com/44243757/56960956-192baf00-6b5b-11e9-9776-576bfa378cfa.png)

**Comment by iWackyMinecraft** [comment]
Broken file ```{"elements":[{"from":[0,0,0],"to":[1,1,1],"color":3,"faces":{"north":{"uv":[0,0,1,1],"texture":"#missing"},"east":{"uv":[0,0,1,1],"texture":"#missing"},"south":{"uv":[0,0,1,1],"texture":"#missing"},"west":{"uv":[0,0,1,1],"texture":"#missing"},"up":{"uv":[0,0,1,1],"texture":"#missing"},"down":{"uv":[0,0,1,1],"texture":"#missing"}}},{"from":[0,0,7],"to":[1,1,8],"color":3,"faces":{"north":{"uv":[0,0,1,1],"texture":"#missing"},"east":{"uv":[0,0,1,1],"texture":"#missing"},"south":{"uv":[0,0,1,1],"texture":"#missing"},"west":{"uv":[0,0,1,1],"texture":"#missing"},"up":{"uv":[0,0,1,1],"texture":"#missing"},"down":{"uv":[0,0,1,1],"texture":"#missing"}}}]}``` just placed 2 cubes

**Comment by iWackyMinecraft** [comment]
Looks like this only happens on blockmode

**Comment by JannisX11** [comment]
Yeah, this makes a lot of sense.

**Comment by JannisX11** [comment]
Fixed in 2.6.7.
