### ISSUE TITLE
[Issue] Entity .bbmodel gets saved as bedrock entity model with quick save

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#325]
How to reproduce issue:

- New entity model
- Add cube
- Save Project (.bbmodel)
- Add another cube
- Quicksave (CTRL + S)
- Model gets saved as "bedrock entity model" but doesn't save it anywhere? (and .bbmodel doesnt get updated)

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
