### ISSUE TITLE
[Suggestion] option to split template textures on blockmode

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#326]
Option to split template textures on blockmode

When creating large models it would be nice to have many small textures instead of 1 large one:

![image](https://user-images.githubusercontent.com/44243757/57027814-19ed3f80-6c46-11e9-9053-d355259d322b.png)

**Comment by JannisX11** [comment]
Why though?

**Comment by iWackyMinecraft** [comment]
Wouldn't texture atlas be more compressed if there was many small images instead of one large?

**Comment by JannisX11** [comment]
No, it would not be more space efficient. The current template generator fits parts of the texture in all sorts of small spaces. That could not happen if each little part of the template would only contain a few cubes.
In some cases, this might save a bit of border around the bigger templates, but that doesn't carry as muchweight.
Additionally, smaller templates would have problems containing few very large cubes. Those cubes could not be fully mapped, unless Blockbench would generate different sizes of textures, which would be even more complicated.

The only way to compress the templates even more right now would be to dissolve the current upside.down-T shape and place each face individually. But that idea will become obsolete with some of the changes planned for 2.7.
