### ISSUE TITLE
Colors Are Back To Default After Exportation As A Model

### ISSUE THREAD

**Issue by Fadi2003** [JannisX11/blockbench#33]
Basicly everytime I try to export a model that I create, it just shows up like in the default colors in the editor, but in minecraft it shows up pink and black every single texture of it, 
![image](https://user-images.githubusercontent.com/29684241/27513529-54ed8b90-591e-11e7-92cb-a936c3e674d8.png)

![image](https://user-images.githubusercontent.com/29684241/27513532-65133bf0-591e-11e7-82f9-629e75b92cd7.png)

**Comment by JannisX11** [comment]
It looks like it can't find your textures, Save the textures inside a folder in the textures folder of your resource pack, then double click the texture in Blockbench and load the texture from your resource pack.

**Comment by Fadi2003** [comment]
This dosn't seem to work, is there a way to contact me, I have discord and skype, ill give you the names

Discord : Fadi2003#0368
Skype : Fadi2003 SkypePicture : White Wall
