### ISSUE TITLE
[Issue] UV Absolutely Unusable

### ISSUE THREAD

**Issue by jamesxsc** [JannisX11/blockbench#331]
Desktop app. No errors in console. I can't scale UV to allow all faces of my entity model to map to one texture. See the below screenshot for the size of just one cube on the UV window and no option to scale it.
![](https://i.615283.net/u/c84eec.png)

**Comment by JannisX11** [comment]
Bedrock models use a special UV mapping mechanic called Box UV. You cannot change the UV of individual faces. You can only assign a spot on the texture map to each cube, the game will then pick the mapping for the individual faces as shown in the colored overlay. The scaling of the faces will happen based on the texture resolution specified in the project settings.

**Comment by jamesxsc** [comment]
Its a java entity model... I saved it as such. How do i make sure its not bedrock?
