### ISSUE TITLE
[Issue] Scale keyframe only saves the x value

### ISSUE THREAD

**Issue by clarence112** [JannisX11/blockbench#334]
Blockbench variant: Webapp
Operating System: ChromeOS, Windows 7, Windows 8.1

**Steps for reproduction:**
- Create a new entity model
- Create a bone and cube
- Create a new animation
- Add a scale keyframe to the bone
- Set the keyframe's x, y, and z values, for example, x: 1.01, y: 1.02, z: 1.03
- Save the project
- Open the project
- Select the keyframe, it's values are now x: 1.01, y: 0, z: 0

**Comment by JannisX11** [comment]
Fixed in 2.6.7.
