### ISSUE TITLE
[Issue]Texture template gives some faces 0 or Negative UV

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#335]
- When creating a new  texture, and selecting Template, some faces are given a UV size of 0 or a negative UV size.
- Desktop 2.6.6
- Windows
![image](https://user-images.githubusercontent.com/7155747/57989760-a5036d80-7a6d-11e9-89ee-eab8caef84b3.png)

**Comment by iWackyMinecraft** [comment]
Templates do not work for cubes that are smaller than 1, you could try scaling your model with `transform>scale...`

**Comment by Gamebuster19901** [comment]
> Templates do not work for cubes that are smaller than 1, you could try scaling your model with `transform>scale...`

Unfortunetly that causes the model to scale outside the canvas

**Comment by JannisX11** [comment]
Templates are not really optimized for block/item models right now. I will work on it in the future. Negative UV sizes are nothing unusual btw, it just means that the texture is mirrored.
