### ISSUE TITLE
[Suggestion] Compress texture without creating duplicate textures for co-located UVs

### ISSUE THREAD

**Issue by MrSquishyDev** [JannisX11/blockbench#336]
It's currently possible to compress an existing texture by creating a compressed template texture while the original texture is loaded.  If the existing texture has multiple cubes mapped to the same UV coordinates the compressed result will duplicate those textures and and assign each cube unique UV coordinates.  This can significantly increase the size of the resulting texture file.

Having a toggle (or changing the default behavior) so that the compressed texture doesn't unnecessarily duplicate cube UVs would be helpful.

**Comment by JannisX11** [comment]
Added in 3.0.
