### ISSUE TITLE
[Issue] Painting after editing a texture on other program will undo edits made in that

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#337]
Painting after editing a texture on other program will undo edits made in that

How to reproduce issue:
- New entity model
- Add cube
- Create a texture template
- Paint something on models with Blockbench
- Save texture
- Edit texture (used paint.net)
- Paint something on paint app
- Save
- Draw something on Blockbench
- Progress made in paint.net will be gone
- You currently have to undo (to get progress made in paint back) then draw again to avoid this issue

![issue)](https://user-images.githubusercontent.com/44243757/58368086-aeb72600-7ef0-11e9-99b7-ad383b8ed884.gif)

Blockbench 2.6.6

**Comment by iWackyMinecraft** [comment]
Bug on "blockmode" also, not just entity mode

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
