### ISSUE TITLE
[Issue] Cannot rename animations, cubes or groups with F2

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#340]
Animations cannot be renamed by pressing F2.
Cubes & groups cannot be renamed on Paint or Animate tabs with F2.

![image](https://user-images.githubusercontent.com/44243757/58500808-9f9fd480-818b-11e9-8602-9e7c8269a356.png)

Blockbench 2.6.6

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
