### ISSUE TITLE
[Suggestion] Animation export for Sketchfab upload

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#341]
Not sure if currently possible but exporting entity animations to Sketchfab with "Sketchfab upload" could be nice.

**Comment by JannisX11** [comment]
Could be possible. I think this would involve exporting one individual model per frame, but I would have to look into it.

**Comment by MEEPofFaith** [comment]
It would probably significantly increase the amount of time it takes to upload, but will definitely make things look so much better.

**Comment by JannisX11** [comment]
Added in 3.4.
