### ISSUE TITLE
Vertex snapping is randomly SLIGHTLY off

### ISSUE THREAD

**Issue by Stryker242** [JannisX11/blockbench#344]
Sometimes, when using vertex snapping, the positions are slightly off. Snapping again fixes the problem. This happens about 60% of the time.

**Comment by Stryker242** [comment]
Would you like me to submit a video demonstrating the issue?

**Comment by JannisX11** [comment]
Does this still apply in 3.0.2?

**Comment by Stryker242** [comment]
Yes, it does.
- John Liu, CEO
Vulcan Technologies Inc.

**Comment by Stryker242** [comment]
Hmn, issue seems to have been resolved in update 3.0.3. Thank you!
- John Liu, CEO
Vulcan Technologies Inc.

**Comment by Stryker242** [comment]
The issue seems to have reoccurred randomly. Certain files do not have the issue, while others do. Do you need a video to confirm/identify the issue?

**Comment by JannisX11** [comment]
Please attach steps to reproduce or a video.

**Comment by Stryker242** [comment]
There are no "steps to reproduce", as it occurs randomly. Attached is a video. You will notice that the position coordinates are slightly misaligned on first snapping, then aligns correctly when I've snapped it again.
[2020-02-23 14-35-12.zip](https://github.com/JannisX11/blockbench/files/4242387/2020-02-23.14-35-12.zip)

**Comment by JannisX11** [comment]
Fixed a related issue #540 so this one should be fixed too.
