### ISSUE TITLE
[Issue] Pasting textures cannot be undone on entity mode

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#347]
Pasting textures cannot be undone on entity mode

How to reproduce issue:
- Create a entity model
- Create a texture/template
- Copy cube textures with CRTL+C
- Paste cube textures to another cube CTRL+V
- Undo wont work

Blockbench 2.6.6

**Comment by JannisX11** [comment]
Fixed in 2.6.7.
