### ISSUE TITLE
[Issue] Non zoomed UV can be dragged

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#349]
Non zoomed UV can be dragged

How to reproduce issue:
- Create a texture
- Put UV area on top or left side
- Drag UV area to other side

![issue](https://user-images.githubusercontent.com/44243757/58795801-4826bc00-8604-11e9-9ed7-6041ce83865d.gif)

Blockbench 2.6.6

**Comment by JannisX11** [comment]
Fixed in 3.0.0.
