### ISSUE TITLE
[Issue] Item Texture

### ISSUE THREAD

**Issue by Dino1469** [JannisX11/blockbench#350]
I'm making a resource pack using block bench my first couple models work but now the rest are turning into a giant chest
![2019-06-03_18 30 43](https://user-images.githubusercontent.com/44007922/58838794-b7fd6c80-862d-11e9-88c3-4170860d56e8.png)
![2019-06-03_18 31 10](https://user-images.githubusercontent.com/44007922/58838797-baf85d00-862d-11e9-8f97-8cf20a6eb73d.png)

**Comment by JannisX11** [comment]
I can't do anything with this issue report. For modeling help, please use the discord server and not the issue section.
