### ISSUE TITLE
[Issue] Textures saved by external programs are incorrect when they are loaded

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#351]
- If an saved by an external program is loaded into BlockBench when you select [Open Model], the colors are incorrect. Both Paint.net and Microsoft paint believe that the silver color in the image I have provided below is [r137, g135, b131]. However when loaded into blockbench, the color is changed to [r150, g141, b119]. 

-Strangely, if you save the miscolored image via blockbench, the color is saved correctly as [r137, g135, b131].

- Blockbench variant: Desktop
- Operating System: Windows

Before loaded into blockbench:
![barrel](https://user-images.githubusercontent.com/7155747/59080140-48011780-88b5-11e9-9748-fccc6a0e7e6b.png)

After loaded into blockbench (see how left side of the model doesn't match the right side, I only edited the image used on the left part of the model with an external program):
![image](https://user-images.githubusercontent.com/7155747/59080454-c3af9400-88b6-11e9-9db5-e4068505913f.png)

**Comment by JannisX11** [comment]
Cannot reproduce. For me, the color remains the same through Blockbench and an image editing program. Make sure this is not an issue with your image editor and you are not using a colormap.

By the way, I strongly discourage the usage of Microsoft Paint. It's a toy, nothing more.

**Comment by Gamebuster19901** [comment]
> By the way, I strongly discourage the usage of Microsoft Paint. It's a toy, nothing more.

I only used microsoft paint to see if it was my image editor. I can confirm it's not.

I have recorded a video demonstrating the issue. Take special note of 2:14 when I save the image inside blockbench, it reverts back to its normal colors in the blockbench editor.

https://www.youtube.com/watch?v=LPzymgsAQZE&feature=youtu.be
