### ISSUE TITLE
[Suggestion] Relative rotation gizmo

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#353]
Relative rotation gizmo

Like on blender if you switch between global and normal
![image](https://user-images.githubusercontent.com/44243757/59869142-506c4e80-939b-11e9-8c72-dd60f273916a.png)

**Comment by omuhu** [comment]
If I could up-vote I would, this is a feature I have been waiting for since I first discovered blockbench.

**Comment by RishiMenon2004** [comment]
So, when will this be implemented in BB?

**Comment by JannisX11** [comment]
Added in 3.6.
