### ISSUE TITLE
[Suggestion] Noise transparency randomness range

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#354]
A way to edit noise transparency randomness range (example from 100-0 to 100-40).

Currently (2.6.7) Painting thin lines can leave spots that barely change which means i have to paint some spots over 3 times. Randomness range editor would reduce repetitive painting by a lot.

![image](https://user-images.githubusercontent.com/44243757/60120979-c3eed100-978a-11e9-9936-89d8b2b63d60.png)

**Comment by JannisX11** [comment]
Added in 3.0.
