### ISSUE TITLE
[Suggestion] Toggle keybind for grid visibility

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#355]
Toggle keybind for grid visibility

**Comment by VulpTheHorseDog** [comment]
Seconded. It's quite irritating as a modeller for several projects to have to go into the settings and expand the right tab, then click the right checkbox every single time I want to hide/show the grid. It's a small thing, but when you do it a lot it really adds up.

Other grid related keybinds or buttons may also be helpful to some folk.
