### ISSUE TITLE
[Issue] Block rotation doesn't limited

### ISSUE THREAD

**Issue by IdaeroAce** [JannisX11/blockbench#359]
Blockbench dekstop 2.6.7, windows 7
When first time i use this, i can rotate without limit. On another session, new model, i got message that rotate is limited because Minecraft limitation, so only can do one axis and 22.5 degree. And then, on this session, the limit is gone. I curios and tried to import it to minecraft and its creepy (previously is not) -_- Restarting doesnt fix it, and on setting its already turned on.

![image](https://user-images.githubusercontent.com/30546508/60758827-e1068800-a045-11e9-93b6-2f1f5437c389.png)

Hmm... actually, it work if its on file- new- new model, but doesnt work on new entity. I should be using entity for bedrock, right? (actually i only open existing model)

**Comment by JannisX11** [comment]
Yes, you should use entity models for bedrock edition. Entity models don't have the classic rotation restriction.
Please use the Blockbench Discord server for help in the future.
