### ISSUE TITLE
[Suggestion] Axis gizmo should be bigger on mobile

### ISSUE THREAD

**Issue by leoste** [JannisX11/blockbench#373]
it is hard to get a good grip on resize squares and I sometimes instead move the display around. My suggestion is that default size for them should be larger on mobile to avoid such issues.

Attach screenshot
![image](https://user-images.githubusercontent.com/35530198/61481348-c5ce3d80-a9a0-11e9-9576-0745436492f0.png)

**Comment by JannisX11** [comment]
It works pretty well with my finger size and my phone. If anyone needs it any bigger, it can be changed in the settings.
