### ISSUE TITLE
[Issue] Grid is too high in other modes

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#374]
South, North, East, and West side views are not centered and the grid is too high in Bedrock Model, Bedrock Legacy Model, Modded Entity, and OptiFine Entity.

![a2](https://user-images.githubusercontent.com/32020441/61551614-7fadc400-aa0a-11e9-9c71-82309a54f3ac.png)
![2b](https://user-images.githubusercontent.com/32020441/61551619-80def100-aa0a-11e9-8aa3-74a3ff55ff21.png)

**Comment by JannisX11** [comment]
Fixed in 3.0.4.
