### ISSUE TITLE
[Issue] When i paint eyes other parts of the model also paint ?!

### ISSUE THREAD

**Issue by GionX** [JannisX11/blockbench#375]
Hello , when i try to paint some parts , example : eyes , some parts of the model like legs also become painted , that's annoying because maybe eyes are black but legs are white .... 

![Screenshot_1](https://user-images.githubusercontent.com/53112404/61576648-ce2b9300-aadc-11e9-800b-d38e37774c84.png)

![Screenshot_2](https://user-images.githubusercontent.com/53112404/61576649-cff55680-aadc-11e9-80ab-57d8ab0f4ec9.png)

**Comment by JannisX11** [comment]
Multiple cubes can be assigned to the same spot on the texture. Further help on the Discord server.

**Comment by devinebuns** [comment]
Hi I also have the same problem when I paint my leg it paints the back of my characters back I don't know how to fix it also cause I'm brand new to blockbench, I'd appreciate the help thank you

**Comment by kingb511** [comment]
I am also having the same problem
