### ISSUE TITLE
[Issue] File extensions are not automatically added on Linux

### ISSUE THREAD

**Issue by D4RKAR117** [JannisX11/blockbench#378]
- Any kind of file writing or save (like save project, take screenshot) with exception of model exports doesnt write the file extensions
**Example**

- **Project Save**
Must save as `ProjectFile.bbmodel` , but saves as `ProjectFile`

- **Screenshot**
Must save as `Screenshot.png`, but saves as `Screenshot`

-  Using Desktop  App
- Ubuntu 18.04.2 LTS X64 Using Blockbench 3.0.2 Deb Package

**Comment by JannisX11** [comment]
Fixed in 3.0.3.
