### ISSUE TITLE
[Issue] Exporting Bedrock Entities

### ISSUE THREAD

**Issue by wiiv** [JannisX11/blockbench#379]
- When exporting some entities with parent child hierarchy causes the saved file to generate split hierarchy for each of the child parts.

How is should look:
<img width="364" alt="Blockbench_2019-07-20_13-20-59" src="https://user-images.githubusercontent.com/2374092/61583147-4603b880-aaf1-11e9-9fbf-0c5905b10575.png">

How it looks after exporting and opening:
<img width="365" alt="Blockbench_2019-07-20_13-22-06" src="https://user-images.githubusercontent.com/2374092/61583153-66cc0e00-aaf1-11e9-94ab-9f17659af001.png">

- Blockbench Desktop 3.0.2
- Windows 10

**Comment by JollyajaX** [comment]
Also experiencing the issue. Repro steps for me, personally:

1. Open bedrock legacy model
2. Add a new bone
3. Ctrl+Z to revert adding that new bone
4. Save (CTRL+S)
5. Re-open or open in a text editor and observe duplicate bones

**Comment by JannisX11** [comment]
Fixed in 3.0.3.
