### ISSUE TITLE
[Issue] RendererModels aren't initialized in the correct order when exporting a modded entity to .java

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#382]
Supply the following information:
- The java file that results from exporting a modded entity as a .java file is invalid. The resulting code attempts to access some fields before they're initialized.

- As you can see from this commit: https://github.com/Gamebuster19901/ONIs-Arsenal/commit/d6283292f34b755372ca6b5c2fd4cdf582a924b9, the initialization of some fields must be moved for the java file to become valid java code.

- Blockbench variant: Desktop
- Operating System: Windows

Here is the .bbmodel file: [Needle.zip](https://github.com/JannisX11/blockbench/files/3424746/Needle.zip)

**Comment by Gamebuster19901** [comment]
Also note: I'm modding in a 1.14 environment, so as such, some class names are different.

**Comment by JannisX11** [comment]
Fixed in 3.0.4.
