### ISSUE TITLE
[Suggestion] Tooltips should/could show keybindings

### ISSUE THREAD

**Issue by manxboy** [JannisX11/blockbench#383]
It's kind of hard learning all of the keybindings as a new user, as I have to keep referencing the keybinding menu. It would be very useful if there was a way to show the current keybinds in the tooltips of actions, like `Move [v]` or `Reset Camera [Numberpad 0]`.

p.s. other than that wonderful app. This is the most solid Minecraft model making app I've come across!

**Comment by JannisX11** [comment]
Added in 3.4.
