### ISSUE TITLE
[Issue] Bedrock 1.12.0 format rotated cubes have inverse Z rotation ingame

### ISSUE THREAD

**Issue by AngeloVH** [JannisX11/blockbench#385]
Some cubes get their rotation around the origin inversed so a cube with a 45-degree angle would become -45
The origin point stays normal
Everything looks good in backbench, ingame it looks broken.
Doesn't happen to most of the cubes.

Bedrock Entity Model
Win 10

**Comment by JannisX11** [comment]
Fixed in 3.0.5.
