### ISSUE TITLE
[Suggestion] "Full view" mode

### ISSUE THREAD

**Issue by innova67** [JannisX11/blockbench#387]
This is a suggestion related to the interface by adding a **Full View** mode [ TAB or shift+TAB  shortcut ] which hides/minimizes all panels.
### actual screen:
![basic_hud_blockbench](https://user-images.githubusercontent.com/37458981/62094328-b7a6d980-b24a-11e9-8a2f-cecf783f464d.png)
### extended mode screen:
![extended_hud_blockbench2](https://user-images.githubusercontent.com/37458981/62094733-26386700-b24c-11e9-93d6-5459e0b12eb6.png)

Useful for:
- have a better view of the whole model
- modeling large projects
- work better in small windows/devices in general
- have more space to work on textures
- maybe even have a "preview mode" (using the gif recorder rotation effect to rotate the model in this hypothetical full view)
**The main idea is a concept extracted from the "hide panels" option in Photoshop Cs6**

**Comment by JannisX11** [comment]
I have two features in planning that would make something similar possible. Will probably be implemented in one of the upcoming updates.

**Comment by JannisX11** [comment]
Implemented in 3.8 as "Fold Sidebars".
