### ISSUE TITLE
[suggestions] Make rotations of an object possible for all 360°

### ISSUE THREAD

**Issue by Icondor15** [JannisX11/blockbench#39]
i find it frustrating that you can turn an object only up to 45° on each axis... i suggest it would be better if you could turn the object all 360° for each axis and turn the object on more than only 1 axis.

**Comment by JannisX11** [comment]
Rotation is limited to one axis and 22.5° steps by the Minecraft JSON block model format. You can still rotate an object more than 45° with Edit > Rotate. The slider only stands for the "official" limited rotation though.
