### ISSUE TITLE
[Issue] Modifying the layout crashes the app

### ISSUE THREAD

**Issue by moskaoff** [JannisX11/blockbench#393]
When trying to modify the UI/Accent/Bright UI/etc's color crashes the application (Desktop) on macOS Mojave (10.14.5).
Can't get the error from the console.

Blockbench 3.0.6.

**Comment by JannisX11** [comment]
I tested it (same OS version) and for me it does not crash the app. But I can't use the built in color picker. I will replace the native color picker with the built in one, which will solve both these issues and make the color picker more consistend across multiple platforms and browsers.

**Comment by JannisX11** [comment]
Fixed in 3.1.
