### ISSUE TITLE
[Issue] Multi-selection on Mac is done with Ctrl rather than Command

### ISSUE THREAD

**Issue by Luke18033** [JannisX11/blockbench#396]
On Mac, multi-selection is done by holding down Ctrl and selecting multiple objects. This is contrary to Finder and most other Mac applications, which use Command for this. Blockbench *does* use Command for key combinations, which makes this even more confusing. I am using the latest Blockbench version (3.0.6).

**Comment by JannisX11** [comment]
Fixed in 3.1.
