### ISSUE TITLE
[Issue] Line brush doesn't work sometimes correctly when clicking near face side

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#397]
Line brush doesn't work sometimes correctly when going from side to side
Used 48x texture

![null](https://user-images.githubusercontent.com/44243757/62888704-85b46d80-bd48-11e9-9786-0e667cea3627.gif) 

Blockbench 3.0.6

**Comment by JannisX11** [comment]
Fixed in 3.1.
