### ISSUE TITLE
[Issue] Resizing calculations are incorrect 

### ISSUE THREAD

**Issue by LiberViator** [JannisX11/blockbench#399]
The problem is how resizing changes the size.
When I'm trying to resize cubes or when I use "Origin to Geometry" it gives me such values:

<img width="227" alt="Screenshot 2019-08-13 at 21 11 12" src="https://user-images.githubusercontent.com/54078423/63217058-08259e80-c148-11e9-8c6d-4799c547aae6.png">

That's how it look like in game:

![2019-08-17_23 40 11](https://user-images.githubusercontent.com/54078423/63217108-913cd580-c148-11e9-837b-e70e7040ebbd.png)

**It's not fixing by changing "Grid Resolution".**

<img width="541" alt="Screenshot 2019-08-13 at 21 11 30" src="https://user-images.githubusercontent.com/54078423/62966079-f45bfe80-be0e-11e9-93b3-904028b5363b.png">

Hope you can fix it 🙏

🛋 Blockbench Desktop variant
💻 MacBook Pro, macOS Mojave 10.14.6

**Comment by JannisX11** [comment]
I cannot reproduce this issue. Please post detailed steps to reproduce and test this in a second installation of Blockbench (e. g. Webapp) to see if it has to do with your installation.
