### ISSUE TITLE
[Suggestion] "Apply Texture to All Faces" automatically assigns correct UV

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#4]
When you select "Apply Texture to All Faces" your UVs are often stretched so I have to go through every side and click "Auto-Size" which is a hassle. Maybe I'm doing something wrong though.

**Comment by JannisX11** [comment]
If you enable Auto UV in the cube settings (which is on by default) the uv will automatically adjust each time you resize the element. Applying a texture does not affect UV position, so it will use the uv from before.
