### ISSUE TITLE
[Issue] Entering custom values in "Move" and "Scale"

### ISSUE THREAD

**Issue by Mittagskogel** [JannisX11/blockbench#40]
Entering custom values in "Move" and "Scale" is very glitchy due to the way the values update in real time. For example, entering a value of 1.5 in any of the fields is nearly impossible.

**Comment by JannisX11** [comment]
Are you sure you are in the latest version (1.5.0) ?

**Comment by Mittagskogel** [comment]
Yes, I am referring to the web app, version 1.5.0.

**Comment by JannisX11** [comment]
Sorry but this works perfectly fine for me.
Does that mean you are not able to enter letters into the text field? Because you should be able.

**Comment by Mittagskogel** [comment]
This is what I do:
1. Add Cube (in the Outliner).
2. Click in Scale X to select the value.
3. Type "1", then ".", then "5".
After each character, the cursor jumps back to the beginning and the text is reformatted, so in the end, what actually happens after each character is: "1", "0.1", "50.1". After this, this, it "autocorrects" again, so that the final value is 32, because 50 is obviously much too large. (It autocorrects to 32 because I have set the scale to 0.5, and I am using the 32x32 grid)

Of course, dragging or clicking the arrows works just fine, also for decimal values, but it would be nice if typing in the values normally would also be possible.

I am using Mozilla Firefox 54.0.1 32-bit

**Comment by JannisX11** [comment]
Thanks for the detailed explaination. The issue apparently only occurs in Firefox.
I will try to fix it of course, but I suggest to take a look at Chrome or Opera. Blockbench looks a lot better in them.

**Comment by JannisX11** [comment]
Fixed in 1.6.5
