### ISSUE TITLE
[suggestion] Animation-editor for java-entities

### ISSUE THREAD

**Issue by Drachenbauer** [JannisX11/blockbench#401]
Hello

I think, it maybe a good idea to add a feature to create animations for java-entity-models.
It should work almost like the existing one for json-animations, but should have slots for the different thinge, a minecraft player can do:
-walking/flying
-elythra-gliding
-sitting
-sneaking
-swimming
-use normal items/building/mining
-attack with a sword, axe, pickaxe, hoe or shovel (not sure, if this is different to normal item use)
-attack with a trident (also not sure, if this is different to normal item use)
-throw a trident
-block with a shield
-shoot with a bow
-shoot with a crossbow

And if some of theese animations are set and the user saves the model, it will place the command-lines for theese animations inte a matching method in the java-file.

I think, this wil be very helpful for modders, who want to create very unique player-models.

Best reguardes Maxi

**Comment by JannisX11** [comment]
Animations for modded java entities are now possible with Geckolib: https://github.com/bernie-g/geckolib/wiki/Getting-Started

**Comment by Mulakk** [comment]
We can't anymore, so how can we do this now ?
