### ISSUE TITLE
[suggestion] New entity java-version for 1.14

### ISSUE THREAD

**Issue by Drachenbauer** [JannisX11/blockbench#402]
Hello

I think, it´s time to add the project-type 1.14-java-entity

It should convert to a 1.14 compatible java-class:
"ModelRenderer" is now renamed to "RendererModel".
And in the class-header, where it extends EntitieModel, there are now pointy bracets wich hold the name of an entity-class, that should use the model.
And in the render-method, there is also the name of this specific entity-class used.
The software can generate that name from the model-name by adding "Entity" behind it.
If the model-name already ends with "Model", it should replace this with "Entity" in this two locations in the code.

Best reguards Maxi

**Comment by JannisX11** [comment]
Added in 3.2.
