### ISSUE TITLE
[Issue] Animations from previous versions are deleted

### ISSUE THREAD

**Issue by CraftologicalMC** [JannisX11/blockbench#404]
BlockBench model files with animations created in version 3.0.6 will no longer work when opened in version 3.1.0 of BlockBench. All of the keyframes are deleted and if you try to export the animation, it will produce an empty json file. A work around is to downgrade to version 3.0.6, export the animation file, update to version 3.1.0, then import the animation file. 

If you load a model file which has animations, using version 3.1.0, then save the model in this version, then go back to version 3.0.6, all of your animations will be deleted.

- Blockbench variant: Desktop
- Operating System: Windows 10

**Comment by CraftologicalMC** [comment]
The issue was tagged with **Unable to reproduce**, so I've created a quick example model in version 3.0.6 to show the issue.

_Steps to reproduce:_
- Load the model (example_model_3.0.6.bbmodel) in version 3.0.6 of blockbench, observe the animations are working & exporting produces the correct .json file.
- Upgrade to version 3.1.0, load the model and observe the animation frames are deleted and exporting produces an empty .json file.

*Extra note - You can downgrade back to v3.0.6 and the animations will still work, however, if you save the model in version 3.1.0, then downgrade back to v3.0.6, the animation will be lost.*

Hope this helps!

[example_model_3.0.6.bbmodel.zip](https://github.com/JannisX11/blockbench/files/3530282/example_model_3.0.6.bbmodel.zip)

**Comment by JannisX11** [comment]
Fixed in 3.1.1.
