### ISSUE TITLE
[Issue] Inflating Entities

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#405]
I'm making something (specifically, turning my Minecraft skin into creepers) and the size of the texture makes the model really small, so I try using the Inflate in the Size section, but the proportions of things get kinda messed up...

![Issue Image 1](https://user-images.githubusercontent.com/54301439/63319020-64fe9180-c2cd-11e9-8555-4119d42e7476.png)
![Issue Image 2](https://user-images.githubusercontent.com/54301439/63319022-68921880-c2cd-11e9-8b89-108f9354fe15.png)
![Issue Image 3](https://user-images.githubusercontent.com/54301439/63319025-6af47280-c2cd-11e9-91a2-8c5c991e8e1d.png)

I hope this is a possible fix, or if there is a solution to my problem that it can be provided.

Edit: I'll try looking at Zombie and Baby Zombie models for a possible solution.

Edit 2: I changed "64, 32" in the json to "128, 64" and it fixed everything.

**Comment by JannisX11** [comment]
Inflate adds a specific value to the size in each direction. This means that the proportions of the cube will change. The inflate function wasn't made to be used on the entire model to change the resolution, it was made for things like hat layers on humanoid models.
