### ISSUE TITLE
[Issue] Broken inflating tool

### ISSUE THREAD

**Issue by moskaoff** [JannisX11/blockbench#406]
This issue is happening sometimes using a Bedrock (Legacy) Model. I feel like it's completely random (or maybe not?) but I was able to reproduce it without knowing how. I simply created a new cube in a group and tried modify the inflate value. 
As you can see in the video below, the inflate value can't modified and set random value (25.1 here). Sometimes it was 7.5, 11, 8.7...
Video: https://cdn.discordapp.com/attachments/314078934155132948/612674880936214541/inflate_bug.mp4

This issue is maybe related to #405, but looks like it's not exactly the same problem as mine.

Blockbench 3.1.0 (software), macOS Mojave.

**Comment by MEEPofFaith** [comment]
I just watched your video, and it isn't the issue I had. It is. however, much weirder that my problem.

**Comment by AngeloVH** [comment]
Same issue, however when i drag the bone i want to inflate into the origin grid 16x16 area the inflate works as normal, when i move a bone outside that region it breaks

**Comment by JannisX11** [comment]
Fixed in 3.1.1.

**Comment by moskaoff** [comment]
It's worse. The tool is completely broken on Bedrock Legacy Model.
