### ISSUE TITLE
[Issue] Broken vertex snapping on rotated cubes/groups

### ISSUE THREAD

**Issue by moskaoff** [JannisX11/blockbench#407]
As the title says, this issue is happening when you are trying to use the vertex snapping tool on a cube in a rotated group or just a cube in a Bedrock (Legacy) Model and have move relative set on.

Here is a video:
https://cdn.discordapp.com/attachments/314078934155132948/613326050172338224/broken_vertex_snap.mp4

Blockbench 3.1.0, macOS Mojave.

**Comment by JannisX11** [comment]
Fixed in 3.1.1.

**Comment by moskaoff** [comment]
Still (even more) broken. Format: Bedrock Legacy Model.
Video: https://cdn.discordapp.com/attachments/314078934155132948/623977699588964362/really_broken_vertex_snap.mp4
