### ISSUE TITLE
[Issue] Blockbench doesn`t load

### ISSUE THREAD

**Issue by Nomit333** [JannisX11/blockbench#408]
Hello,

I`m using the Desktop App and it woudn`t even load in.
I installed the right Version for my Operating System (Windows 7 (Ultimate) 32x Bit.
I can start it but then is says "An error occurred while Loading Blockbench" Button 1 Reload
Button 2 Quit
Whole App :
https://ibb.co/KLLj8YV
The Error Messages ;
https://ibb.co/YW4NKrV
After i Pressed Reload these Error Messages are there ;
https://ibb.co/k4NNjvW

I hope you can find an solution for it.
Please Email Me Timon.wegner2006@gmail.com

**Comment by JannisX11** [comment]
Please download and run the latest installer from https://blockbench.net again. This should solve the issue.

**Comment by Nomit333** [comment]
Thanks for the Help

JannisX11 <notifications@github.com> schrieb am Do., 22. Aug. 2019, 13:12:

**Comment by R7X2** [comment]
> Please download and run the latest installer from https://blockbench.net again. This should solve the issue.

yeah i tried doing that but it did not work "i have the same error 'cannot read properties of null"

**Comment by ToiletGaming3000** [comment]
blockbench won't load for me. Its not working.
