### ISSUE TITLE
[Issue] Optifine Entity Models Outdated

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#409]
After finding my own fix to my previous problem  (#405), I finished my project and exported it as an Optifine JEM. When I tried to run it in Minecraft 1.14 (I had optifine), it says that it's for an older version of Minecraft and is incompatible.

![The Folder](https://cdn.discordapp.com/attachments/418621268682866690/613486590660182019/unknown.png)
The file exported is a .jem file. The only problem I could think of is it's not supposed to be a .jem file.

![Resource Pack Option Section](https://cdn.discordapp.com/attachments/418621268682866690/613484488512765982/unknown.png)

I'll try turning the .jem into a .json, and if that works, I'll turn this into a suggestion.

Edit: Turned .jem files into .json files. Still "incompatible"

**Comment by JannisX11** [comment]
This is an issue with the resource pack itself, not with the .jem file. Change the format_version in the pack.mcmeta file in your resource pack to 4.
For further questions. please use the modeling discord server: http://discord.blockbench.net

**Comment by MEEPofFaith** [comment]
> This is an issue with the resource pack itself, not with the .jem file. Change the format_version in the pack.mcmeta file in your resource pack to 4.
> For further questions. please use the modeling discord server: http://discord.blockbench.net

I see what you mean. I didn't know that that was important and stuff. Thanks. :)
