### ISSUE TITLE
[Suggestion] Open .class files ?

### ISSUE THREAD

**Issue by Matthysse** [JannisX11/blockbench#410]
Hello!

I have an old .class model file from a mod and i would like to open it and convert it in a .json file, is it possible ?

**Comment by JannisX11** [comment]
Added in 3.2.

**Comment by Strange-Aeonx** [comment]
I'm unable to open any .class files in Blockbench, did they remove it or am I just opening the wrong thing?

**Comment by JannisX11** [comment]
You can open specific versions of .java files. Class files cannot be opened. When creating .java files, make sure to also save your projects as a .bbmodel file so that you can reopen it later on.
