### ISSUE TITLE
[Suggestion] Open and edit multiple models at the same time (tabs)...

### ISSUE THREAD

**Issue by FoxShadew** [JannisX11/blockbench#411]
On desktop version, you can only edit one model at a time. This frustrates me as I can't open a reference model without having to save and close the model I'm editing... Most IDE's have an ability to open files in separate tabs, allowing you to open two files and edit them simultaneously... This would be very handy to have in blockbench though...

**Comment by JannisX11** [comment]
You can open two instances of Blockbench at the same time. Press the middle mouse button on Blockbench in the task bar or open a model in Blockbench from the explorer.

**Comment by JannisX11** [comment]
Added in 4.0.
