### ISSUE TITLE
[Issue] Legacy mode paint grid wont detect changed bone position

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#412]
Legacy mode paint grid wont detect edited bone position.
![image](https://user-images.githubusercontent.com/44243757/63638644-bde67500-c693-11e9-9d85-af0f8876629a.png)

3.1.0

**Comment by moskaoff** [comment]
Can confirm

**Comment by JannisX11** [comment]
What do you mean by "Legacy mode"? I don't think i have added a legacy mode for the paint grid. Or are you talking about the MC Bedrock legacy format? In that case, cannot reproduce the issue.

**Comment by moskaoff** [comment]
The Bedrock legacy format yeah, really easy to reproduce for me using rotated bones

**Comment by JannisX11** [comment]
Fixed in 3.2.
