### ISSUE TITLE
[issue] Broken Entity Model...?

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#414]
I don't even know why this is happening, but here:

This is what the model is supposed to look like:
![Creeper MEEP Model](https://cdn.discordapp.com/attachments/418621268682866690/615054578882183178/unknown.png)

After I export it as an Optifine JEM File, I get a normal looking file:
![creeper.jem](https://cdn.discordapp.com/attachments/418621268682866690/615053203049807889/unknown.png)

The weird problem comes if I put creeper.jem back into Blockbench. I get a weird abomination that looks like this:
![The fork is this](https://cdn.discordapp.com/attachments/418621268682866690/615053322889461760/unknown.png)

If I export that, I get a file that saved with the weird changes.
![Borken](https://cdn.discordapp.com/attachments/418621268682866690/615053539613605928/unknown.png)

The new .jem file includes the weird added groups and broken coordinates, and I have no idea why there is this problem or how to fix it. If it's a glitch, could you fix it? If it's not, can I have a solution?

I need halp.

_I'm starting to regret trying to turn creepers into my Minecraft skin..._

Edit1: Saving it as a Blockbench Model and then loading that .bbmodel file works to create a correct model.

Edit2: If I don't have the textures mirrored, it loads properly. But I want the textures mirrored so that they aren't reversed/flipped the wrong direction. But then again, I could just pop up paint.net and flip some textures... I'll try just mirroring one texture in Blockbench and see what happens.

Edit3:
Everything except what I mirrored breaks.
![Just Leg0](https://cdn.discordapp.com/attachments/418621268682866690/615061131459035136/unknown.png)
![Just Body](https://cdn.discordapp.com/attachments/418621268682866690/615061268444872726/unknown.png)

Due to the fact that the mirrored ones survived the weird translationing, I'm gonna try mirroring everything again.

Edit4:
Answer: It spontaniously fixed itself for no apparent reason.
![Fixed](https://cdn.discordapp.com/attachments/418621268682866690/615062183088488458/unknown.png)

If I were to guess what the problem was, I would guess the problem was I had multiple Blockbenches open at once, and having the same project on both causes problems.

Edit5: Ok, disregard what I just said. The Blockbench Model was already mirrored, so I was just unmirroring it.

**Comment by MEEPofFaith** [comment]
Don't you hate it when you try to do something, but everything that could possibly go wrong goes wrong.

**Comment by JannisX11** [comment]
Sorry for the issues with the format. JEM is a really difficult format to work with, I will try to make it a bit more reliable sometime.
