### ISSUE TITLE
[Issue] UV changes position when re-scaling small UV selections down

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#415]
Dragging 32x+ UV on sides moves UV out of boundaries

![issue48](https://user-images.githubusercontent.com/44243757/63962956-95e48080-ca9c-11e9-8ed5-09244d343971.gif)

used 32x texture
Desktop Win10 64

**Comment by iWackyMinecraft** [comment]
![issue49](https://user-images.githubusercontent.com/44243757/63963292-61bd8f80-ca9d-11e9-8d55-b63711947ad5.gif)

**Comment by JannisX11** [comment]
Can no longer reproduce in 3.8, seems to be resolved.
