### ISSUE TITLE
[Issue] Paint grid wont update correctly on paint mode

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#419]
Paint grid wont update when on paint mode

Snap resolution 48
![issue50](https://user-images.githubusercontent.com/44243757/64062375-38604900-cbee-11e9-93b7-cbc9ca8281a7.gif)

snap resolution 16
![issue51](https://user-images.githubusercontent.com/44243757/64062430-d7854080-cbee-11e9-8961-ebe270dc929b.gif)

Java block/item model
Blockbench 3.1.1

**Comment by iWackyMinecraft** [comment]
Also happens with Undo
![issye53](https://user-images.githubusercontent.com/44243757/64062646-ae19e400-cbf1-11e9-9065-fa6821451264.gif)

**Comment by JannisX11** [comment]
Fixed in 3.2.
