### ISSUE TITLE
[Issue] Painting on missing textures is possible

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#420]
Painting on missing textures is possible
Undo wont remove edited textures

the missing texture was a 128x template so the grid is wonky

![issue52](https://user-images.githubusercontent.com/44243757/64062532-3a2b0c00-cbf0-11e9-8df9-43699fd4636d.gif)

Java block/item mode
version: Blockbench 3.1.1b

**Comment by JannisX11** [comment]
Fixed in 3.1.1.
