### ISSUE TITLE
[Issue] Paint grid wont detect texture UV

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#422]
Paint grid wont detect texture UV

![issue54](https://user-images.githubusercontent.com/44243757/64062806-4ca74480-cbf4-11e9-9eae-4fbd022b2c77.gif)

Java block/item
Blockbench 3.1.1b

![image](https://user-images.githubusercontent.com/44243757/64079797-9a0adb00-ccf4-11e9-918b-a114397435b9.png)
![image](https://user-images.githubusercontent.com/44243757/64079800-ac851480-ccf4-11e9-809f-415736a01192.png)
![image](https://user-images.githubusercontent.com/44243757/64079818-fa9a1800-ccf4-11e9-8b8e-204d28c30fd1.png)

**Comment by JannisX11** [comment]
Right now Blockbench generates a grid out of the overall UV coordinates.  Support for mixels will be added later. Sorted as a bug because mixels are expected to work in paint mode.

**Comment by JannisX11** [comment]
Fixed in 3.2.
