### ISSUE TITLE
[Issue] Blockbench project model doesn't save Project texture resolution

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#423]
Blockbench project model (.bbmodel) doesn't save Project texture res

![image](https://user-images.githubusercontent.com/44243757/64062914-de638180-cbf5-11e9-9d19-30a2f6bea576.png)
 Blockbench 3.1.1

**Comment by JannisX11** [comment]
Fixed in 3.1.1.
