### ISSUE TITLE
[Issue] Images not loading when opening a json file

### ISSUE THREAD

**Issue by ToastedLoaf** [JannisX11/blockbench#43]
When i load a json file, none of the images used gets loaded, instead a red circle with an exclamation mark is shown. I have to manually remove and add the textures again for them to reappear. 
Is this a bug, or simply just not a feature?

![screenshot](https://user-images.githubusercontent.com/29837391/27770418-b6ce9004-5f3e-11e7-8f45-413b63194c5c.png)

**Comment by JannisX11** [comment]
Blockbench tries to find the texture in the according folders of your resource pack. If the texture is not in your resource pack, you can double click the texture to change it's file.

**Comment by ToastedLoaf** [comment]
The files is there, but it didnt load.

**Comment by JannisX11** [comment]
Is the model file in "models/block" or "models/item" and the texture in "textures/<folder>"?
"<folder>" being the folder that is referenced in the model file, e.g: "blocks/stone" would be "textures/blocks/stone.png"
