### ISSUE TITLE
[Issue] Wrong UV on valid OptiFine JPM

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#440]
The UV is messed up on these valid OptiFine JPM models when importing.

![cow2](https://user-images.githubusercontent.com/32020441/64149024-b59be180-cdd9-11e9-82d7-80297e76880c.png)
[rid_cow_head.txt](https://github.com/JannisX11/blockbench/files/3568029/rid_cow_head.txt)
[rid_cow_tail_0.txt](https://github.com/JannisX11/blockbench/files/3568030/rid_cow_tail_0.txt)
[changed jpm extension for upload]

**Comment by JannisX11** [comment]
Fixed in 3.1.1.
