### ISSUE TITLE
[Issue] OptiFine JEM- exporting messes up the UVs

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#446]
![image](https://user-images.githubusercontent.com/32020441/64390643-83b59580-cffa-11e9-85e8-5ea3a6ab8b79.png)
![2019-09-05_16 31 20](https://user-images.githubusercontent.com/32020441/64390671-9f20a080-cffa-11e9-9fe5-aaefad64cfa0.png)

Exporting messes up the UVs and the UVs for transparent faces are still exported.

**Comment by JannisX11** [comment]
Fixed in 3.2.2.
