### ISSUE TITLE
[Issue] OptiFine JEM- some UVs are imported wrong

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#447]
![image](https://user-images.githubusercontent.com/32020441/64390959-b4e29580-cffb-11e9-842d-009c5f5dd559.png)
UVs of some faces are imported wrong, missing faces on import aren't transparent, and the UVs for transparent faces are still exported.

![cow2](https://user-images.githubusercontent.com/32020441/64391108-5a960480-cffc-11e9-9ff2-d5c5478937c0.png)
[cow_jem.txt](https://github.com/JannisX11/blockbench/files/3581587/cow_jem.txt)

**Comment by JannisX11** [comment]
Fixed in 3.2.2.
