### ISSUE TITLE
[Suggestion] Animated texture playback using settings from .mcmeta file

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#450]
Would it be possible for Blockbench to detect the animation .mcmeta file on animated textures so that if an animated texture had a special animation that wasn't just one frame after the next, it would actually play them in the order specified in the file as well as any custom frame time settings on the frames that have it specified?

I don't know whether or not this is possible, but I'll put it out there as a suggestion.

**Comment by ElsewhereHere** [comment]
Would also love to suggest support for flipbook_textures.json for Bedrock ❤️

**Comment by JannisX11** [comment]
Added in 4.5.
