### ISSUE TITLE
[Issue] Add model imports same texture again when it already exists

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#453]
Add model imports same texture again when it already exists
![issue59](https://user-images.githubusercontent.com/44243757/65337489-ed27cd80-dbd0-11e9-80a0-2faeb316ffc3.gif)

Blockbench 3.1.1

**Comment by iWackyMinecraft** [comment]
I have a multi-part model that is made out of 24 3x3x3 cubes. I thought that importing all models into 1 model, then assembling it in free model would be a great way to paint it. but it didn't really work when there's 10+ same textures on the texture panel. Deleting them didn't fix it because they have different variables.

**Comment by JannisX11** [comment]
Fixed in 3.2.
