### ISSUE TITLE
[Issue]Entity Modeling Java and Optifine

### ISSUE THREAD

**Issue by Calebplaysgames** [JannisX11/blockbench#454]
Optifine and Java entity modeling is broken, like severely broken. not for the animating part, but when I import someone elses entity into my mods or into blockbench or create an entity then export then import it comes in looking all broken like its been flattened and turned and some peices are like far away from the middle.

**Comment by JannisX11** [comment]
This issue report is too unspecific to draw any conclusions. I will be working on those formats in future updates so these issues will probably be resolved at some point.
