### ISSUE TITLE
[Issue] Rotated elements wont move relative to the group when using arrow keys

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#455]
Rotated elements wont move relative to the group when using arrow keys

![issue60](https://user-images.githubusercontent.com/44243757/65384445-35f39980-dd2b-11e9-8a05-bfc46aeb26fe.gif)

Blockbench 3.1.1

**Comment by JannisX11** [comment]
Fixed in 3.2.
