### ISSUE TITLE
[issue] Player Display Sides Swapped (Minor)

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#458]
The left and right sides of the body are swapped.
![Heavenly Sword](https://user-images.githubusercontent.com/54301439/65575187-1a9fae80-df24-11e9-8db3-b002cdffa504.gif)
You can kinda see behind the arm how the sides were swapped.

**Comment by MEEPofFaith** [comment]
Also, the color I chose for the mouth of my skin appears white for some reason.
Actually, it appears to be more like transparent.

**Comment by JannisX11** [comment]
Fixed in 3.2.
