### ISSUE TITLE
[Issue] Numbers

### ISSUE THREAD

**Issue by PillFall** [JannisX11/blockbench#46]
When you create a new model, sometimes the numbers starts to be *rounded*. It is annoying, especially when you work with small things and enlarges the output *.json.

For example, you are working on a computer's mouse, you would have to work with decimals, after you sightly put it on the place, one of the numbers that indicate the element's position or size is 1.5, but you move -0.1 the element and the values changes to 1.39999999999* or 1.40000000000*, where the * are a random number. This also ocurs when you goes up, or with integer numbers.

**Comment by JannisX11** [comment]
Here is an explaination why this is happening:
https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by PillFall** [comment]
Yes, but, why it still persist even when I change it manually? It not supposed a reasignation of the variable? I mean, when you get the error, you change the value manually, for example, you obtain 0.4000000002, and you change it for 0.4 or 0.3, or whatever, and it didn't change, when deselect and select again, it still say 0.4000000002.

**Comment by JannisX11** [comment]
Fixed in 1.8. Badly rounded numbers might still appear in exported json but not inside Blockbench anymore.
