### ISSUE TITLE
[Issue] Particle not exported if unused in the model (Minor, but a little annoying)

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#463]
If your block/item model has a particle set, but it isn't used in the model, (Maybe the particle you set is the original texture, but you then use parts of that texture to actually make your model.) when exported as a .json, it isn't included in the export.

So maybe unused textures in the model are removed unless it's used for the particle.

**Comment by JannisX11** [comment]
Fixed in 3.2.
