### ISSUE TITLE
[Suggestion] Don't run line brush if the line goes through 2 cubes

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#475]
Don't run line brush if the line goes through 2 cubes

I sometimes draw lines without noticing and its annoying to remove
![issue62](https://user-images.githubusercontent.com/44243757/66830741-e0dc2980-ef5e-11e9-9277-b25338549064.gif)

**Comment by JannisX11** [comment]
Added in 3.2.
