### ISSUE TITLE
Bug block bench (the pack is withdrawing)

### ISSUE THREAD

**Issue by ChupaShups** [JannisX11/blockbench#476]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any error messages, please attach a screenshot of it to your issue.

Supply the following information:
- Detailed description of your issue
- Blockbench variant (Webapp/Desktop)
- Operating System

Hi i have a big problem, when i export to blockbench and i put the texture pack the pack gets removed without any reason. For more information I have a computer with windows 10.
I am on the version 2.6.7 (even with the last one it does not function)

(With optifine the pack does not get off but I have that [instead)]
![image](https://user-images.githubusercontent.com/56738232/67117814-d9798200-f1e3-11e9-90c4-b6488416355d.png)

Thanks for your help.

ChupaShups

**Comment by JannisX11** [comment]
I can not tell what your issue is, but it is most likely not an issue with Blockbench. Please ask in one of the help channels on the [Modeling Discord](http://discord.blockbench.net).
