### ISSUE TITLE
[Issue] Save As saves deleted geometry (modded entity, import, delete)

### ISSUE THREAD

**Issue by Elenterius** [JannisX11/blockbench#477]
- Blockbench Desktop Version 3.1.1
- WIN 10
- Plugins: Mod Utils @JTK222

I'm using the Mod Utils Plugin to import Techne Files in the Modded Entity Mode. Since i have several models to import and i have to be in a modded entity project to be able to use the import i was using this workflow:

1.  Create new modded entity project
2. Import a techne model
3. Edit the project file name and geometry name
4. Use **Save As** to save the model

Everything works fine till now.

Now Loop 5-8 (once is also enough for the bug)
5. delete all geometry and groups in the current porject
6. Import a techne model
7. Edit the project file name and geometry name
8. Use **Save As** to save the model

Result: 
The saved bbmodel file contains the geometry of the previously deleted model(s). Also the "deleted" geometry doesn't show up in the Outliner tree view.  (even if you select  the deleted geometry )
![image](https://user-images.githubusercontent.com/6061273/67165058-fbf4d200-f380-11e9-8fee-5b8b3c354305.png)

**Comment by JTK222** [comment]
Hm... tbh, I have no Idea what might be causing it.
However, I sadly can't test it. I don't have any Techne models.
So I'd appreciate if you could attach 2 techne models so I can try to find a solution.

**Comment by Elenterius** [comment]
Here are the files.
[techne_and_bbsaves.zip](https://github.com/JannisX11/blockbench/files/3752243/techne_and_bbsaves.zip)

I imported & saved Analyzer.tcn first. When you check the json of the solidification_furnace.bbmodel you can see that the elements array contains the geometry of the previous model and are not referenced from the outliner attribute which probably results in them not being shown in the outliner tree view in the app. 
Moreover all geometry is also listed twice in the elements array. Which probably causes this when i load the files and turn them invisible (also you can only delete the elements visible in the tree view).
![image](https://user-images.githubusercontent.com/6061273/67231621-f01c1500-f43f-11e9-8c6b-9945730916ad.png)

**Comment by Elenterius** [comment]
Since any imported and saved techne model has double entries in the elements array. I'm guessing that in Blockbench there must also be two identical entries for each element. Just that only one entry is shown in the outlined tree view and when I delete the elements the others still remain. In conclusion, the techne import is likely bugged.
