### ISSUE TITLE
[Issue] Change north arrow color with grid color

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#478]
Change north arrow color with grid color
![image](https://user-images.githubusercontent.com/44243757/67184757-1ebcd000-f3ed-11e9-9720-ca88e3f7e18d.png)
![image](https://user-images.githubusercontent.com/44243757/67184771-27ada180-f3ed-11e9-9380-0ac4a3b995df.png)

**Comment by JannisX11** [comment]
Fixed in 3.2.
