### ISSUE TITLE
[Suggestion] Scroll support for list selectors

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#479]
When hovering a list selector and using scroll wheel, it would change the mode
Basically just saves 2 extra clicks
![image](https://user-images.githubusercontent.com/44243757/67191706-c12f8000-f3fa-11e9-8261-55849a2f7d7e.png)

Example paint.net got this feature

**Comment by JannisX11** [comment]
Added in 3.2.
