### ISSUE TITLE
[Suggestion] Combine Overwrite model and Save project into a single save action

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#480]
Combine overwrite and save project into a single save action

Currently there is:

**Overwrite file:** (which is for format default, example .json)
**Save project:** (which overwrites .bbmodel)

Why not combine these features so that:

- When opening .bbmodel, CTRL+S would save it as project .bbmodel
- When opening .json, CTRL+S would save it as .json
- When making a new file, CTRL+S would save it as format default (example .json)

**Comment by JannisX11** [comment]
Users might want to save models in other formats as .bbmodel, for example .java models or block models. Using .bbmodel as a default for the free format could work though.
