### ISSUE TITLE
[Suggestion] Palette tab

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#483]
![image](https://user-images.githubusercontent.com/44243757/67618766-54eabd00-f7fc-11e9-989c-82012c438dc3.png)

So there would be an palette option next to color
Recent colors would still appear on the side

**plus icon** - add a new color to the selected slot
**folder** - import palette
**palette** - export palette
**arrow** - reset palette to default

**Comment by JannisX11** [comment]
Is there like a common / industry standard palette format that could be used?

**Comment by iWackyMinecraft** [comment]
No not really, but something like this could be cool https://htmlcolorcodes.com/color-chart/

**Comment by JannisX11** [comment]
Added in 3.2.
