### ISSUE TITLE
[Issue] UV backround color is sometimes incorrect

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#484]
![image](https://user-images.githubusercontent.com/44243757/68086725-77fa1a00-fe57-11e9-9bee-3561cbd81c0e.png)

After reopening:

![image](https://user-images.githubusercontent.com/44243757/68086729-7e889180-fe57-11e9-9a69-66c69e457751.png)

Blockbench 3.1.1
used Java block/item mode

**Comment by JannisX11** [comment]
Fixed in 3.2.
