### ISSUE TITLE
[Issue] Biome-dependant blocks (leaves, grass, vines, etc.) turned to gray when modeled

### ISSUE THREAD

**Issue by Ceejay2004** [JannisX11/blockbench#485]
![2019-11-05_17 48 16](https://user-images.githubusercontent.com/57391869/68197619-69068b00-ff6f-11e9-8d0b-eec81c99b324.png)
![2019-11-05_17 48 29](https://user-images.githubusercontent.com/57391869/68197620-699f2180-ff6f-11e9-83f7-81426fa92097.png)

**Comment by iWackyMinecraft** [comment]
This happens because you didn't enable tint on the model faces.

Tint can be enabled from UV editor: 
![image](https://user-images.githubusercontent.com/44243757/68215490-03a2b080-ffe8-11e9-8f7a-99afc14c6338.png)

Please use the Minecraft modeling discord for help
 [http://discord.gg/fZQbxbg](url)
