### ISSUE TITLE
[Issue] Camera locks into place in "Quad-View"

### ISSUE THREAD

**Issue by TimeLordian01** [JannisX11/blockbench#489]
In the latest Blockbench, desktop version 3.1.1 , using the "Quad-view" feature can sometimes lock into place whilst positioning and moving a background image. How to re-create:
- Import an image to a face (N,E,S,W)
- Scale the image to what you want
- Select "Position"
- Select "Set Position"
- Keep Moving and testing until you see that the camera is no longer movable

My Current Operating System is Windows 10.
System Specs:
- Intel I3 4160 4th Generation Chip
- NVIDIA GTX 750 Graphics
- 16GB DDR3 RAM

**Comment by ConnorBP** [comment]
Is this while moving uv quads? Because that has caused my main 3d view to be immovable on the latest binary release. Not sure if that is the same issue as yours. 

Windows 10 pro (version 1909) with gtx1080 intel 7700k, and 32gb ram

**Comment by JannisX11** [comment]
Fixed in 3.2.
