### ISSUE TITLE
Mobile version not working properly 

### ISSUE THREAD

**Issue by MLGMagicHoodini** [JannisX11/blockbench#492]
So recently I was gone try the mobile version of blockbench on my phone (Huawei P8 lite 2018) and for some reason the whole page appears out of proportion and I can't manage to do anything even tried switching to desktop mode but still no fix 
![Screenshot_20191125-194941](https://user-images.githubusercontent.com/52632295/69573255-a5049d00-0fbd-11ea-9653-445e1364ff1a.jpg)

**Comment by JannisX11** [comment]
Try to hold the phone in portrait mode and reload.

**Comment by JannisX11** [comment]
The mobile UI will probably get another update some time in the future but for you will just have to use larger displays or portrait mode.
