### ISSUE TITLE
[Issue] Center pivot doesn't work correctly when on multiple parent folders

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#493]
Center pivot doesn't work correctly when on multiple parent folders
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/44243757/69899766-ad6d2700-1373-11ea-80a3-238ecb6c925f.gif)

![image](https://user-images.githubusercontent.com/44243757/69899784-ee653b80-1373-11ea-9b13-38bfc8c769ba.png)

Blockbench 3.1.1

**Comment by JannisX11** [comment]
Fixed in 3.2.2.
