### ISSUE TITLE
[Issue] Hidden separators re-appear when resetting toolbar

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#497]
Hidden separators re-appear when resetting toolbar
Box UV Editor
Blockbench 3.1.1
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/44243757/70265800-d3dff780-17a3-11ea-863f-34bbb9d7f202.gif)

**Comment by JannisX11** [comment]
Fixed in 3.2.2.
