### ISSUE TITLE
[Issue] Unable to select element in 3D work place

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#498]
Windows 10 Desktop version

If you repeatedly select an element by clicking the cube, then delete it, sometime after 10+ times you are no longer able to select elements.

**Comment by iWackyMinecraft** [comment]
I thought I was just insane but this keeps also happening to me

Just press control, and it will register clicks again, @ewanhowell5195

**Comment by JannisX11** [comment]
Closed due to inactivity.
