### ISSUE TITLE
Texture leaves some flaws and invisible parts in json object

### ISSUE THREAD

**Issue by Kirooh** [JannisX11/blockbench#499]
I model the object perfectly, but when creating and applying the texture, the program makes some parts invisible and mirrors the texture from some parts to others, so when I try to paint some parts, it ends up painting another part as well.

![Captura de Tela (13)](https://user-images.githubusercontent.com/58734840/70533318-9f6b9300-1b37-11ea-85cf-80f38113b3f3.png)

![Captura de Tela (14)](https://user-images.githubusercontent.com/58734840/70534880-bb246880-1b3a-11ea-937e-e1df5f999699.png)

![Desktop 2019 12 10 - 10 22 09 02](https://user-images.githubusercontent.com/58734840/70535141-43a30900-1b3b-11ea-95d9-6eaca9e1498c.gif)

Blockbench Desktop 3.1.1
Windows 10
Java Block/Item

**Comment by JannisX11** [comment]
The template generator uses Box UV, which means that you can't have faces that are less than one block big in either direction.
