### ISSUE TITLE
[Bug?] Weird UV-Copying

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#5]
![image](https://user-images.githubusercontent.com/8559428/26945507-461a310c-4c8c-11e7-85f0-73cb7f7771b9.png)
I pressed Shift+Ctrl+C on the left pillar and pasted it on the right pillar with Ctrl + V. As you can see, the 1 pixel big side has a stretched UV, which is not the same as the first one.

**Comment by JannisX11** [comment]
Copy-pasting UVs only applies to the selected side currently. Every-side copy-paste is planned though.
