### ISSUE TITLE
[Issue] UV Editor pushes texture selection off-screen

### ISSUE THREAD

**Issue by The-Fireplace** [JannisX11/blockbench#50]
On lower resolution displays (I assume this isn't a problem on higher-resolution displays, I haven't had a chance to try on one), the UV editor is so large that the texture selection area is pushed off-screen.
![image](https://user-images.githubusercontent.com/5914284/28595700-9dcbdc6e-715a-11e7-8a9e-84b93a8a54dd.png)
My monitor resolution is set to 1216x676.

**Comment by JannisX11** [comment]
This is why you can zoom out in the view menu.
