### ISSUE TITLE
[Issue] Name sanitizing in outliner is not global

### ISSUE THREAD

**Issue by NyarlathoCotovoy** [JannisX11/blockbench#500]
1. When naming a folder on russian language, the first letter of the name disappears.
2. Does not work: View> Interface scale> Reset scale.
OC: Windows

P.S. How to use toolbar customization? For example, I select "create animation" and it is shown to me: "hidden" how to make it appear on the toolbar?

**Comment by JannisX11** [comment]
I cannot reproduce the second issue. Please double check that you are actually zoomed out or in before and if the issue still occurs, please create a new separate issue.

**Comment by JannisX11** [comment]
Fixed in 3.2.1.
