### ISSUE TITLE
[Issue] Issue with JEM submodel translation

### ISSUE THREAD

**Issue by damjanblazevic** [JannisX11/blockbench#502]
so basically this is my optifine .jem model in blockbench and the same model in game.
![2019-12-20_18 01 57](https://user-images.githubusercontent.com/59095443/71270936-18969180-2353-11ea-8ccf-72a1f0f53103.png)
![iron](https://user-images.githubusercontent.com/59095443/71270937-18969180-2353-11ea-9f3a-6c15133fcf22.png)

**Comment by JannisX11** [comment]
Please send the project file of your model.

**Comment by damjanblazevic** [comment]
[123.zip](https://github.com/JannisX11/blockbench/files/3991962/123.zip)

i guess this is how im supposed to send it @JannisX11

**Comment by JannisX11** [comment]
Fixed in 3.2.2.
