### ISSUE TITLE
[Issue] "Overlaping" texture during template generation.

### ISSUE THREAD

**Issue by SDArthur** [JannisX11/blockbench#503]
OS: Windows 10.
Desktop Version.

While trying to create a template, the different parts of the textures were overlaping eachother in a weird way. I just started using the program today and this can very well be a problem on my part since I didn't find a similar problem anywhere. I don't mind sharing the model file of necessary.

Edit: I didn't chage any settings while creating the template.

![Overlaping1](https://user-images.githubusercontent.com/24768100/71390156-efd5fc80-25dd-11ea-978b-95397f2f74c6.png)
![Overlaping2](https://user-images.githubusercontent.com/24768100/71390157-efd5fc80-25dd-11ea-8d3a-dfa031d249c3.png)

**Comment by JannisX11** [comment]
This is not an issue with Blockbench, but with the Box UV system itself.

From the Blockbench FAQ:
> The size of cubes is floored for the UV map calculation. This means that any size smaller than 1 will result in a 0 pixel wide UV map, which will look glitchy. To prevent this make sure all of your cubes are at least 1 unit long in each direction. To create smaller cubes, use the Inflate slider.
