### ISSUE TITLE
[Issues] UV overlay doesn't resize itself correctly when zoomed in

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#505]
UV overlay doesn't resize itself correctly when zoomed in

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/44243757/71767877-beccc480-2f19-11ea-9ff3-7648340586f0.gif)

3.2.2

**Comment by JannisX11** [comment]
Fixed in 3.3.
