### ISSUE TITLE
[Issue] Can't Import .obj files or any models

### ISSUE THREAD

**Issue by Proton1295** [JannisX11/blockbench#506]
Hi, i'm using the latest version of Blockbench Desktop on Windows 10, and i can't import any model. If i hover on the "import" button, it gives me no options.

Here is a screenshot: https://imgur.com/HLYLP2T

Thank you in advance!

**Comment by JannisX11** [comment]
Blockbench does not support the format OBJ. To load a model, use "Open Model".

**Comment by JK0011GaMiNgG** [comment]
lol

**Comment by alirahnamax** [comment]
how we can import obj models in to blockbenchh ?
