### ISSUE TITLE
Gif Compression

### ISSUE THREAD

**Issue by MEEPofFaith** [JannisX11/blockbench#508]
It seems as if if textures have a similar color to the background when making a gif, they become transparent.

This gif has compression set to 0, so maybe it won't have transparency. It's hard to really check.
![test](https://user-images.githubusercontent.com/54301439/72195915-b5d06d00-33c9-11ea-9957-f679dc902c63.gif)

After filling all transparent stuff with white, it looks like this.
![test](https://user-images.githubusercontent.com/54301439/72195940-efa17380-33c9-11ea-8d5c-20545f497fcd.gif)

So yea, auto-transparency makes textures of simular colors to the background transparent.

**Comment by JannisX11** [comment]
Fixed in 3.4.0.
