### ISSUE TITLE
[Issue] Inner cube textures don't render inside an outer cube with transparent texture

### ISSUE THREAD

**Issue by The-Fireplace** [JannisX11/blockbench#51]
To reproduce: Create a large cube, then apply a texture with transparency, such as Glass. Then, create a cube inside it. When you apply textures to the inner cube, you can't see them from outside the outer cube.
![image](https://user-images.githubusercontent.com/5914284/28596223-12dbe740-715d-11e7-95d8-41199078c02d.png)

**Comment by JannisX11** [comment]
This is a WebGL bug. Related SO post: https://stackoverflow.com/questions/8763603/transparent-textures-behaviour-in-webgl

**Comment by sNrVJx** [comment]
But this is fixable, the devs need to render each element sorted by step (depth) as stated in the stack post.

**Comment by EternalBlueFlame** [comment]
First off I need to note I have some decent GL experience (from modding/rewriting the minecraft vanilla/flans render to heck and back), but no web GL experience.
I had similar issues with my render for Traincraft, and I disabled culling selectively to fix it (that way some parts could cull and others wouldn't to improve performance).

From what I'm reading in the WebGL API you can do `gl.disable(gl.CULL_FACE);` to disable it fully when you want, and 
`gl.enable(gl.CULL_FACE);
gl.cullFace(gl.BACK);`
To re-enable it. Which should be a very easy fix that you could just make a toggle for in the program settings on whether or not to allow culling.

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/cullFace

**Comment by JannisX11** [comment]
I tested this and unfortunately it does not fix the problem of this issue report. It seems to force all materials to render from both sides, which THREE.js jas a way of changing for materials individually. Rendering of the back side can still be buggy.

**Comment by EternalBlueFlame** [comment]
Well that's a bummer. The only other idea I have would be the blend mode.
`
gl.enable(gl.BLEND);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);`

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc

**Comment by JannisX11** [comment]
> Well that's a bummer. The only other idea I have would be the blend mode.
> `gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);`
> 
> https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc

Nope, this changes nothing.

**Comment by RedGalaxySoftware** [comment]
Three.js already enables blending... It's the alpha test function of OpenGL that can solve the problem. 

The alpha function skips overwriting the depth buffer when transparency of a material exceeds a lower limit. Three.js allows this using the `alphaTest` property in a material: [https://threejs.org/docs/#api/en/materials/Material.alphaTest](https://threejs.org/docs/#api/en/materials/Material.alphaTest). This value is the minimal alpha that the texel on the texture should have to render.

Minecraft itself uses this too. Once you'll render the block in Minecraft you'll see it right. That's because Minecraft uses an alpha-test reference value which is a little more than zero (0.1 or so...).

This value could be a setting in the blockbench's settings, so users could turn this off for translucent textures, where this would cause another bug again.

**Comment by JannisX11** [comment]
The alphaTest value does not change anything unfortunately.
Sort Objects is already enabled and it fixes some issues, but not this specific one.

**Comment by RedGalaxySoftware** [comment]
I have been messing around with three.js, although not with the source code of blockbench. But it seems to work for me in my simple scene, and also on the simple material examples of three.js (change some other enum values in the examples there, then it will work)...

**Comment by RedGalaxySoftware** [comment]
Modified the source code of what is now on GitHub and got it working!

Current online web app (in Firefox), without modified source code:
![Screenshot 1](https://user-images.githubusercontent.com/11669132/47607258-04d8ef00-da1e-11e8-94cb-58c6737700ff.png)

My modified version (in the same Firefox):
![Screenshot 2](https://user-images.githubusercontent.com/11669132/47607269-21752700-da1e-11e8-91e7-54ee9d3f8b27.png)

Added code (line 174 in js/textures.js):
![Screenshot 3](https://user-images.githubusercontent.com/11669132/47607330-b546f300-da1e-11e8-91bb-3a3ffd9947c5.png)

**Comment by JannisX11** [comment]
> Modified the source code of what is now on GitHub and got it working!

Ah nice, now it works for me aswell. I am not sure why it didn't work previously, but now that I added the alpha test property directly when constructing the material, it shows an effect. I will add this in the next version, thanks a lot!

**Comment by LowPolyPixl** [comment]
Hello,

I'm new to all of this, but this solution is exactly what I was looking for. I tried clicking on the link and it took me to a 404 error page. Understanding this is years old, can someone please point me to where I can learn to apply the code that solved this issue?

**Comment by justADeni** [comment]
@LowPolyPixl damn i just came here also looking for a solution, also clicked that link, also got 404 and also would like little bit of help. 

@JannisX11 you marked this as resolved. Is this option present in the config (I can't find it), and why is this issue still open?

**Comment by JannisX11** [comment]
This issue was in regards to alpha test textures. Blend textures still have issues. There is no good automatic solution (https://www.khronos.org/opengl/wiki/Transparency_Sorting), but a manual render order setting would be an option.

**Comment by FoxSamu** [comment]
@LowPolyPixl @justADeni
It's been nearly 5 years since I suggested the change, and I've changed names several times since then because of some structural changes in my life. Therefore the link may be dead but you're in luck because the fork is still there: https://github.com/FoxSamu/blockbench. You just needed to use my new name. :P

**Comment by for-comments** [comment]
Any tips for the web version?

**Comment by for-comments** [comment]
Any tips for the web version? I'm trying to make a slime version of a blaze with entity wizard and the inner cube only renders when looking to an upward angle.
