### ISSUE TITLE
[Suggestion] Be possible to change the tintindex of a tinted face

### ISSUE THREAD

**Issue by NathanPB** [JannisX11/blockbench#512]
Hello, I'm quite new to Minecraft modding and I found this tool a few weeks ago, and its being awesome. However even if vanilla Minecraft doesn't even use more than one index of the ``tintindex`` feature, the game still supports the use of as much indexes as we want, making possible to modders create items composed with different materials, for instance.

Blockbench does not support this. I've been discussing in the official Discord and ``JTK222 | Lukas
#7285`` helped me on using the Tint feature and explained me that we can't change the default index of zero because the vanilla game doesn't use more than this.

So I suggest adding a configuration box to allow changing the ``tintindex`` property of a face. Keeping the default of zero to not confuse old users of the tool, but allowing a property popup or something to change the index for modders use.

**Comment by JannisX11** [comment]
Added in 3.4.
