### ISSUE TITLE
[Issue] Animations overwriting

### ISSUE THREAD

**Issue by StarkTMA** [JannisX11/blockbench#515]
When having multiple animations in the Animate Tab, and trying to edit only one animation then hitting "CTRL+S". Sometimes only that animation gets saved but the rest get deleted! they just appear empty when opened again in blockbench or in an IDE.
This is sometimes frustrating and annoying and time consuming when you don't have a copy of the animations file.
I've had this issue a lot of time, Blockbench is amazing. but this bug is annoying! Hope it gets fixed soon

**Comment by JannisX11** [comment]
Is this because you are opening the animations together with another model that does not have all the required bones?

**Comment by StarkTMA** [comment]
No, animations for the same model.
But that happens sometimes too

**Comment by JannisX11** [comment]
That's interesting. I'm working with animations daily and I've never had one disappear. Can you tell if the keyframes were displayed correctly in Blockbench right before exporting? So, in other words, is this an importing or an exporting issue?

**Comment by StarkTMA** [comment]
Exporting. Here's the exact steps that sometimes causes it.

-I import a model which automatically imports animations associated with it.
-I go to the Animate tab.
-I choose 1 animation and do some edits on it.
-CTRL + S
-Only that animation gets its key-frames saved while the rest lose all of their content.

**Comment by Leykit** [comment]
I agree, such a problem may occur, the animation persists and the points in it disappear. Once I lost a week of work because of this. I was furious. But after that I’m more careful with saving the animation and this never happened again.

**Comment by JannisX11** [comment]
Fixed in 3.5.
