### ISSUE TITLE
Project Resolution for 2nd Template Textures

### ISSUE THREAD

**Issue by Kas-tle** [JannisX11/blockbench#517]
### Detailed description of your issue

When creating a second template texture for cubes not encompassed by the first template texture, the project resolution is updated to the resolution of the new template. However, the UV values for existing cubes encompassed by the first texture are not properly updated to reflect this.

Reproduction Steps:
1. Select Java Block/Item as the format and accept the default settings.
2. Create a 1 by 1 cube.
3. Generate a template, using the default settings with the 1 by 1 cube selected.
4. Note the texture resolution in File > Project Settings.
5. Create an 8 by 8 cube.
6. Generate a template, using the default settings, with the 8 by 8 cube selected.
7. Note that the texture resolution in File > Project Settings has been updated.
8. Observe the UV map of the 1 by 1 cube and note that the UV values were not scaled to reflect the new texture resolution.

### Blockbench variant (Webapp/Desktop)

Blockbench Desktop 3.3.1

### Operating System

macOS Mojave 10.14.6

**Comment by JannisX11** [comment]
Fixed in 3.4.0.
