### ISSUE TITLE
[Issue] Add native dark mode support for macOS

### ISSUE THREAD

**Issue by rinrincodes** [JannisX11/blockbench#520]
On the desktop version of blockbench on macOS Catalina 10.15.3 in the latest update being 3.3.1 and in earlier versions prior to that, the app still does not support the native dark mode found in macOS Mojave, Catalina and soon in later versions of macOS onwards. Electron has recently supported this functionality as it has to be defined in the app's main property list file to be able to work. More information about it can be found at this link:

https://www.electronjs.org/docs/tutorial/mojave-dark-mode-guide

**Comment by JannisX11** [comment]
Blockbench has a dark theme by default. That's why it would be unnecessary to listen to the system preference, because it would be in dark mode either way.

If you want to use the default mac OS colors or you want to use a light theme, you can do that with a custom theme. But I don't recommend the latter because Blockbench doesn't look that great in light mode.

**Comment by rinrincodes** [comment]
@JannisX11 the theme isn't the problem btw as this clearly has to do with the native UI elements in the macOS UI not adapting to dark mode while on dark mode. These screenshots clearly show what I'm trying to talk to you about:

<img width="1440" alt="blockbench_no_dark_mode_2" src="https://user-images.githubusercontent.com/7041850/73602660-9f32b700-452c-11ea-87b0-b59a8dd4a612.png">
<img width="1440" alt="blockbench_no_dark_mode_3" src="https://user-images.githubusercontent.com/7041850/73602661-9f32b700-452c-11ea-8307-d11b5c86ff4d.png">
<img width="1440" alt="blockbench_no_dark_mode" src="https://user-images.githubusercontent.com/7041850/73602662-9f32b700-452c-11ea-8a08-9db7301457cf.png">
<img width="882" alt="blockbench_no_dark_mode_4" src="https://user-images.githubusercontent.com/7041850/73602747-65ae7b80-452d-11ea-895f-95b2dc76cf10.png">

**Comment by Offroaders123** [comment]
Do you know if this was resolved @rinrincodes? I was curious because there didn't seem to be a response on whether the issue was fixed after your post with the screenshots.

**Comment by rinrincodes** [comment]
> Do you know if this was resolved @rinrincodes? I was curious because there didn't seem to be a response on whether the issue was fixed after your post with the screenshots.

This issue has already been fixed and resolved a while back as an older build of Electron during that time didn't have Apple's own dark mode support. Newer builds onward now support dark mode by default.
