### ISSUE TITLE
[Issue] Nothing is rendering.

### ISSUE THREAD

**Issue by tobyplowy** [JannisX11/blockbench#521]
- Blockbench variant Desktop (Newest skin update)
- Operating System windows

I seem to be having an issue after updating blockbench to the new skin update.
I don't know why but nothing is rendering. The UI looks fine but there is no model rendering.
![image](https://user-images.githubusercontent.com/16853304/73608962-259cd680-45c9-11ea-8183-9837a872b088.png)
This also happens for other models even if I select the skin option in the new file drop down.
![image](https://user-images.githubusercontent.com/16853304/73609037-f20e7c00-45c9-11ea-886c-0cb829e78cde.png)
As you can see I can still interact with the model. I can select parts and i can draw on it. I just can't see it.

Also blockbench worked fine before doing the update.
I hope that it can be resolved soon because i need blockbench to work and I'm really looking forward to the new skin features.

**Comment by tobyplowy** [comment]
Also I have no plugins installed.

**Comment by JannisX11** [comment]
Please check your console for error messages. You can open the console by pressing Ctrl + Shift + i.

**Comment by tobyplowy** [comment]
Like this?
![image](https://user-images.githubusercontent.com/16853304/73610527-a0212280-45d8-11ea-956f-dbc8124880f4.png)
I'm not a programmer so I'm not sure what any of this is.

**Comment by tobyplowy** [comment]
@JannisX11 If you need anything else feel free to ask me =D

**Comment by JannisX11** [comment]
Thanks, this helps.

**Comment by tobyplowy** [comment]
When will the version with the fix be available? I kinda need blockbench for work related things. Also thanks for the amazing program!!!

**Comment by tobyplowy** [comment]
@JannisX11 Any way that I can fix this myself?
I would love to use the new skin update features.

**Comment by JannisX11** [comment]
Fixed in 3.4.0.

**Comment by tobyplowy** [comment]
@JannisX11 I is indeed. Thanks!
