### ISSUE TITLE
[Suggestion] External export format that supports rotation / pivot points / hierarchy

### ISSUE THREAD

**Issue by NelkGames** [JannisX11/blockbench#522]
Hello, I have a question and I would like some help.
I'm looking to export some models that I made in the program to Blender, but I don't know which is the best solution, I tried .Obj, but the points of origin of the objects are all in the center of the cube. I would like some advice on how to export the models or some correction for the problem with the .obj file, Thanks for your attention.

- Blockbench Desktop (3.3.1)
- Windows 10

**Comment by JannisX11** [comment]
OBJ models don't support pivot points according to my research. I am not sure if there is another format that could be implemented that has support for origins (and ideally for group hierarchy in general)

**Comment by NelkGames** [comment]
oh, well... thanks for the help :D

**Comment by JannisX11** [comment]
Added glTF export in 3.4.
