### ISSUE TITLE
[Suggestion]Write a blockbench that supports minecraft version 1.8.9

### ISSUE THREAD

**Issue by ChillsLove** [JannisX11/blockbench#523]
Now there are still many players playing minecraft 1.8.9, even more than 1.9~1.15. In addition, it is difficult to find other model software supporting minecraft 1.8.9 on the market. I believe that if it is written, more users will use blockbench. I hope you will adopt.

**Comment by JannisX11** [comment]
Blockbench won't support MC Java 1.8. The version was already outdated years ago when Blockbench was first released. On the other hand, there is nothing stopping you or anyone else as a third party developer to create a Blockbench plugin to add support. After all, the only thing that has changed are the left and right hand display settings.

**Comment by ChillsLove** [comment]
thx for your reply.

**Comment by dmitriJ2101** [comment]
we are waiting for support for version 1.8..
