### ISSUE TITLE
[Issue] When opening a .bbmodel with multiple textures, assigned textures are reset

### ISSUE THREAD

**Issue by ElsweyrMC** [JannisX11/blockbench#524]
- Detailed description of your issue
When opening a .bbmodel file, all cubes use the first texture in the list as opposed to keeping their assigned texture. The only fix is selecting the groups/cubes, right clicking the intended texture and selecting 'Apply to Cubes'. See attached image:
<img width="1504" alt="Capture" src="https://user-images.githubusercontent.com/58707237/74067066-9b33e880-49b5-11ea-91f2-362e09ac437e.PNG">

(BB does not save which cubes use which texture and instead applies only the first texture to all cubes)
Perhaps similar to [Issue 501](https://github.com/JannisX11/blockbench/issues/501) 

- Blockbench variant (Webapp/Desktop)
Desktop
- Operating System
Windows 10

**Comment by JannisX11** [comment]
Please specify which model format you are using. You can find it in the Project settings under File > Project...

**Comment by ElsweyrMC** [comment]
It is a 'Free Model'. I did however convert it from a Bedrock entity, not sure if that has any effect.
The UV seems to be behaving like a Bedrock model (a single combined UV as opposed to separate adjustable faces) so perhaps this is more an issue with the conversion? Would explain why it only wants one texture file

**Comment by JannisX11** [comment]
Yeah, that explains it.

**Comment by JannisX11** [comment]
Fixed in 3.4.0.
