### ISSUE TITLE
[Issue] Converting from entity skin to block/item model squishes model to fit size

### ISSUE THREAD

**Issue by SmashinSkull** [JannisX11/blockbench#525]
When converting a model from an entity skin to a block/item model using the convert function the model is squished inside of itself to fit in the space provided. The model also cannot be scaled down when in the entity skin format without the angles and positions of the blocks going all over the place. This makes it so that there is no way to have one of these models as an item/block without lots of time and effort remodeling an entity that is already there.

**Comment by JannisX11** [comment]
You can check "Deactivate Size Limit" in the settings for special cases like this.
