### ISSUE TITLE
[Suggestion] Improve auto cullface functionality

### ISSUE THREAD

**Issue by Luke18033** [JannisX11/blockbench#529]
The auto cullface button seems to have been lazily implemented, as clicking it will always set it to the face's direction, with no regard for whether or not it should actually be culled out in that case. This should only occur if the face is located at the edge of the block, otherwise set it to none. It would also be nice if this button were in a more convenient location, and could be made to apply to all faces on the selected cubes...

**Comment by JannisX11** [comment]
This has been added in 4.5 as Tools > Set Cullfaces Automatically.
