### ISSUE TITLE
[Suggestion] Export with "parent":"block/block" by default

### ISSUE THREAD

**Issue by The-Fireplace** [JannisX11/blockbench#53]
This allows custom blocks to look right when they are not placed in the world. Dropped on the ground, held in the player's hand, etc.
So instead of
`"credit": "Made with Blockbench, a free, modern block model editor by JannisX11",
	"textures": {`
it would export like this
`"credit": "Made with Blockbench, a free, modern block model editor by JannisX11",
	"parent": "block/block",
	"textures": {`

**Comment by JannisX11** [comment]
Good idea but I don't think this should be default behaviour. It is easy enough to go to File > Project... and set the parent model to block.

**Comment by The-Fireplace** [comment]
Can the user set it as the default behavior in the settings, then?
