### ISSUE TITLE
[Issue] Selecting multiple bones in outliner only highlights the last selected

### ISSUE THREAD

**Issue by omuhu** [JannisX11/blockbench#530]
Blockbench 3.3.1 (Desktop)
Windows 10

**Summary:**
CTRL + clicking on bones in the outliner panel doesn't highlight all selected bones

**Reproduction:**
1. create a new bedrock entity
2. create 2 bones, not nested
3. add cubes to each bone
3. click on one bone
4. CTRL + click on the second
5. see results (all cubes are selected, but only one bone is highlighted)

**Comment by JannisX11** [comment]
Blockbench is built from the ground up in a way that only one group can be selected at a time. That is necessary to make a lot of the tools that Blockbench provides work in a predictable
