### ISSUE TITLE
[Suggestion] Round Decimal Cubes

### ISSUE THREAD

**Issue by Kanzaii** [JannisX11/blockbench#535]
From what i experimented, if the cubes have decimal number like (0.1256987) the texture will loses some of  their faces in the Minecraft if the model is in 128 resolution (more than x32+). Even tough the model has been optimized (Culling, Remove Faces, Disable UV Snap, Disable Tint/Shading, etc)

My suggestion is add 2 round option :
1. The first round option, it will be round 0.125 size to 1 (Anything that has 0 at the front will round that to 1)
2. The second round option is a normal rounding. For example if the the size of the cubes is 1.1256987 it will normally round that to 1.

Since the Minecraft bedrock work fine with decimal less than 3 digit but for more than 3 digit decimals work fine for game entity or item.

**Comment by JannisX11** [comment]
Please specify which Blockbench model format and which number on the cube you are talking about.

**Comment by Kanzaii** [comment]
Blockbench Format : Bedrock Legacy Model
Number On The Cube : On cube has 5 or 9 more digit decimals
Reason : Converting from OBJ ==> Voxel ===> Element ===> JPM (Cubik Studio)
              Converting JPM ===> Bedrock Legacy Model

**Comment by JannisX11** [comment]
In the Bedrock legacy format, any faces with a side length of less than 0 don't reliably show up, because the value gets rounded down to 0. To work around this, either use the Inflate option, or create a regular "Bedrock Model" and disable Box UV.
