### ISSUE TITLE
[Suggestion]Flip animations when flipping bones

### ISSUE THREAD

**Issue by Qapslock** [JannisX11/blockbench#536]
When working on animations like walking etc., it can be where helpful to negate (*-1) the values of the two remaining axes you are not flipping over.
So far, named bones are switched from left -> right and vice versa when flipping something over the X-axis which is already very helpful.
My suggestion would be to also "flip" the animations with the method above.
Though I do understand that it is not always useful to negate those axes. My solution would be to having it optional maybe through a popup or checking a checkbox to enable/disable it.

**Comment by JannisX11** [comment]
I don't see that being useful in a lot of cases. Generally the app is designed to first design the model, then start working on the animation. Whether that's one person designing the model and another person creating animation, or just the same person but another step. For example, when opening a model, animations aren't even loaded before switching to the animations tab. And copying a bone doesn't copy the animations. You can flip keyframes individually, I think that's powerful enough.
