### ISSUE TITLE
the models do not load

### ISSUE THREAD

**Issue by LeuloGames** [JannisX11/blockbench#539]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by LeuloGames** [comment]
![Sin título](https://user-images.githubusercontent.com/61807634/75929240-e6bfa200-5e4e-11ea-92ec-559033e41aea.png)

**Comment by JannisX11** [comment]
Please provide more info, e. g. the model you are trying to load.
