### ISSUE TITLE
[Issue] Editing a texture externally breaks its UV editor

### ISSUE THREAD

**Issue by KaruzoHikari** [JannisX11/blockbench#542]
If you edit a texture externally, and that texture is currently being used in a model you have opened, it says "File not found" and you can't see the preview in the UV editor either.
"Right click -> Refresh" on the texture does nothing, the only thing that works is reopening Blockbench or relocating the texture.
In previous versions the file would be autorefreshed.
However you can still interact with it and the changes will be reflected on the actual model.
![image](https://user-images.githubusercontent.com/35693714/76146832-9cc8fd00-6096-11ea-8122-132dca7ec9c4.png)

- Blockbench version: 3.4.0 Desktop
- OS: Windows 10

**Comment by JannisX11** [comment]
Fixed in 3.4.1.
