### ISSUE TITLE
[Issue] Odd behaviour with large brush/eraser scales

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#546]
Error when trying to erase on the texture
![image](https://user-images.githubusercontent.com/44243757/76171582-9f5e4c00-6195-11ea-9498-48baa982c1dc.png)
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/44243757/76171645-31feeb00-6196-11ea-9286-335b9b068039.gif)

.bbmodel download
https://cdn.discordapp.com/attachments/686322454049587219/686324048531161209/problem.bbmodel

Seems to only happen with brush scale 4+

Might be related to Texture boundaries, If I move the UV slightly away from the corner, it works better. But I still get those random spots that do not paint well
![image](https://user-images.githubusercontent.com/44243757/76171697-d2eda600-6196-11ea-8d0b-302812e512b9.png)

Blockbench 3.4.0

**Comment by iWackyMinecraft** [comment]
Also i tested removing all plugins and still happening

**Comment by JannisX11** [comment]
Fixed in 3.4.1.
