### ISSUE TITLE
[Issue] Axis control wont change position when moving a locator

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#547]
Axis control wont change position when moving locator

Blockbench 3.4.0

**Comment by iWackyMinecraft** [comment]
![image](https://user-images.githubusercontent.com/44243757/76222583-75ec0180-6223-11ea-830d-aeacf74f644a.png)

**Comment by JannisX11** [comment]
Fixed in 3.4.1.
