### ISSUE TITLE
Loading cubes with UV defined for any face breaks other faces without UV

### ISSUE THREAD

**Issue by zero318** [JannisX11/blockbench#549]
When opening/importing a block model, if any faces of a cube have UV data, all other faces of that cube without UV data will default to "uv": [0, 0, 1, 1].

This is most easily seen with the vanilla models for the dried kelp block and scaffolding.
![image](https://user-images.githubusercontent.com/20288925/76255632-e1829e80-6224-11ea-9503-324a596e3737.png)
![dried_kelp_block](https://user-images.githubusercontent.com/20288925/76255277-4d183c00-6224-11ea-8489-05d7c83412f5.png)![scaffolding](https://user-images.githubusercontent.com/20288925/76255274-4c7fa580-6224-11ea-8b6f-21f393379af4.png)

The vanilla model for dried kelp defines the faces like this:
"faces": {
  "down":  { "texture": "#down", "cullface": "down" },
  "up":    { "texture": "#up", "cullface": "up" },
  "north": { "texture": "#north", "cullface": "north" },
  "south": { "uv": [16, 0, 0, 16], "texture": "#south", "cullface": "south" },
  "west":  { "texture": "#west", "cullface": "west" },
  "east":  { "uv": [16, 0, 0, 16], "texture": "#east", "cullface": "east" }
}
But loading and saving the model results in this output:
"faces": {
  "north": {"uv": [0, 0, 1, 1], "texture": "#north", "cullface": "north"},
  "east": {"uv": [16, 0, 0, 16], "texture": "#north", "cullface": "east"},
  "south": {"uv": [16, 0, 0, 16], "texture": "#north", "cullface": "south"},
  "west": {"uv": [0, 0, 1, 1], "texture": "#north", "cullface": "west"},
  "up": {"uv": [0, 0, 1, 1], "texture": "#up", "cullface": "up"},
  "down": {"uv": [0, 0, 1, 1], "texture": "#down", "cullface": "down"}
}

**Comment by JannisX11** [comment]
Fixed in 3.4.1.
