### ISSUE TITLE
[Issue] Model Is Not Shown in Display

### ISSUE THREAD

**Issue by TheNonee** [JannisX11/blockbench#550]
http://prnt.sc/repiuq

- In Preview the model is not showing after update from 3.1.0 to 3.4.1
After restarting app its work but wen i clicking the edit or paint and etc and back to display its not showing the model again
- JSON

- Blockbench Desktop 3.4.1 (Lastest)
- Windows 10

**Comment by Cassiobsk8** [comment]
Happening to me too

**Comment by JannisX11** [comment]
Fixed in 3.4.2.
