### ISSUE TITLE
[Suggestion] Find biggest or smallest cubes with the same name

### ISSUE THREAD

**Issue by Kanzaii** [JannisX11/blockbench#552]
Greatly, Blockbench comes with features that can find cubes with specific UV or Same Name. I have skin models that converted OBJ (blender) to 1x1 Cubes Element using Javascript with each cubes has name with the same color. for example if the color hex of the cube is 161616 so the cube name also 161616.

The problem is when i convert it to bedrock legacy models, the UV was totally changed. So i had to resize the texture more bigger, because of the skin resolution was limited to 128x, i had to "saving" the texture with other texture. The Main problems here is i cant tell how big the cubes on each color. So i have suggestion, what if Blockbench has features that can find the biggest cubes or smallest cubes on specific color or the cubes that has the same name?

I know its sounds dumb but its really helping me out on Minecraft Skin or Entity Modelling. Thank you for your time. :D

**Comment by JannisX11** [comment]
If you have experience using Javascript, you can write a Blockbench plugin to do this. This is way to specific and niche to be added to the base program.
