### ISSUE TITLE
[Suggestion] Add Bedrock 1.0.6 Model To Convert Project

### ISSUE THREAD

**Issue by Kanzaii** [JannisX11/blockbench#553]
skin model. So please add this :D the title says it all BTW.

[geometry.txt](https://github.com/JannisX11/blockbench/files/4334107/geometry.txt)

**Comment by JannisX11** [comment]
The geometry format in that file is called "Bedrock Legacy". The additional skin metadata won't be added because skin geometries are not officially supported.
