### ISSUE TITLE
[Issue] Decimal places of cube size and position are locked together.

### ISSUE THREAD

**Issue by clarence112** [JannisX11/blockbench#556]
Affects: Chrome webapp on Windows

When I move a cube by any amount ending with a decimal on any axis and then resize it, the size of the cube on that axis becomes locked to a multiple of 1 plus the decimal. 

For example: if I were to take a 1x1x1 cube and move it 0.5 along the x axis, if I tried resizing it I could only get 0.5, 1.5, 2.5, etc...

**Comment by Titus-Armillius** [comment]
I can confirm this also.

**Comment by clarence112** [comment]
Oh I forgot to mention: I was working on a 1.12 Java entity

**Comment by Carro1001** [comment]
This also happens on the desktop app

**Comment by Spyeedy** [comment]
Even though this is marked as a confirmed issue, I would like to add on with some footage I recorded regarding this bug, just to demonstrate how it happens.

I have only used the **Java Block/Item** and **Modded Entity** modes. Only **Modded Entity** mode has this bug.

https://streamable.com/h91amq

**Comment by JannisX11** [comment]
Fixed in 3.5.
