### ISSUE TITLE
[Issue] Weird Visual Program Glitch

### ISSUE THREAD

**Issue by Duwnn** [JannisX11/blockbench#559]
I am having a visual glitch that just happens throughout the program. Nothing specific is making it happen within the program, I don't think. And I have the new update. I don't know exactly what caused it because I haven't used it in awhile. But I thought re-downloading would fix it and it didn't. And when I move my cursor over it it disappears. 

![75a7a0d0031c234a1f6d60411118af40](https://user-images.githubusercontent.com/62370642/77035137-32f7ff80-6982-11ea-8a15-3346cc3787d3.png)

**Comment by Yuuki-kito** [comment]
Did you install Microsoft Visuals 2010-2019?

**Comment by Duwnn** [comment]
> Did you install Microsoft Visuals 2010-2019?

what do you mean Microsoft visuals. I have Microsoft visual studio, and I didn't have to download visuals before.
