### ISSUE TITLE
[Sugestion] Resize UV For Bedrock Legacy

### ISSUE THREAD

**Issue by Yuuki-kito** [JannisX11/blockbench#564]
Like in Bedrock format 1.12, you can resize the UV with proportional. Sadly, Bedrock 1.12 format doesnt support for custom skin geometry (It will blank) except for entities/mobs. If possible please add a feature for Resizing UV with proportioanally on Bedrock Legacy Format. Im tired with the UV that makes me need to resize the textures more bigger.

**Comment by JannisX11** [comment]
The old Bedrock geometry format does not support per-face UV mapping.
