### ISSUE TITLE
[Suggestion] Combine textures into atlas when exporting to OBJ

### ISSUE THREAD

**Issue by andywatts** [JannisX11/blockbench#567]
Exporting as OBJ results in several texture files with MTL entries.

Has any one explored packing textures into a single atlas? or have suggestions for scripting this?

With this feature I could switch from Cubik Studio to Block Bench

**Comment by JannisX11** [comment]
Any reason why you don't want multiple materials?

**Comment by andywatts** [comment]
Roblox and my own tools expect a single material.

**Comment by JannisX11** [comment]
You can select everything and generate a texture template. Note that this will only support one consistent resolution.
"Create Texture" > Check "Template" > Confirm.
