### ISSUE TITLE
[Issue] Export to Java does not support models for 1.15.2

### ISSUE THREAD

**Issue by Geometrically** [JannisX11/blockbench#568]
**Detailed description of your issue:** The way that models are made in code has completely changed in 1.15. Sadly, Blockbench's export does not have support for this new format. The Blockbench Java export needs to be updated to match 1.15.

**Model format in which the issue occurs:** .JAVA

**Comment by JannisX11** [comment]
This does not qualify as an issue. 1.15 is work in progress.
