### ISSUE TITLE
Opening index.html on the local computer does not display its software information properly

### ISSUE THREAD

**Issue by GreenChennai** [JannisX11/blockbench#569]
Opening index.html on the local computer does not display its software information properly
I know this is not a bug
But some users can use the web version if the software is not available

But due to China's access to Github is too slow
I plan to use it offline for others
However, this cannot make it work normally (there is no problem with the function, that is, the software language information is not displayed)

**Comment by JannisX11** [comment]
You need to use either Electron or a local webserver to run Blockbench locally. I personally use XAMPP:
https://www.apachefriends.org/index.html
