### ISSUE TITLE
Проблемы со структурой кода после сохранения файлов .JSON

### ISSUE THREAD

**Issue by Ac9I** [JannisX11/blockbench#570]
Код всех моделей которые я сохраняю имеют вид 
как на 1 скриншоте, но у всех людей что я просил показать что у них выглядит нормально как на скриншоте 2... из-за этого совершенно невозможно ничего нормально делать. уже совсем не знаю что с этим делать .
![0hSBLEnyeEU](https://user-images.githubusercontent.com/62737164/77765214-f8abf380-704e-11ea-9cdc-64363316a0a7.jpg)
![0g3L-A-Sr2Q](https://user-images.githubusercontent.com/62737164/77765216-fb0e4d80-704e-11ea-8396-71b074166966.jpg)

**Comment by JannisX11** [comment]
Not English

**Comment by Ac9I** [comment]
> не английский

Sorry, I fixed it! ( how did I manage it )
