### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Samuel06x** [JannisX11/blockbench#571]
My problem on blockbench is if I want to texturize a geometry.json file, but if I then want to import the texture to the same geometry.json again, the texture is completely buggy, I know that there is something about the uv, but I also know not why. 2 days ago the textures all went away. I did not change the uv either and 1 day later the textures were bent at the same time, you could maybe insert a function where you could renew the uv like new or a function where it resets everything to blockbench ?

Here you can see the video: https://www.youtube.com/watch?v=6kC2JZPA2-8
geometry.json file : https://pastebin.pl/view/8f0c5f0c

**Comment by JannisX11** [comment]
When you save the texture, make sure to also save the model.
In the video, when you created the model, the project resolution (top left) was 128x128. When you opened the model again, the resolution was 64x64 because either you didn't save the model or you used another version.
