### ISSUE TITLE
Problems with the code structure after saving files .JSON

### ISSUE THREAD

**Issue by Ac9I** [JannisX11/blockbench#572]
The code for all models that I save looks like
as in 1 screenshot, but all the people that I asked to show that they look normal as in screenshot 2... because of this, it is absolutely impossible to do anything normally. I don't know what to do with it anymore .
![0g3L-A-Sr2Q](https://user-images.githubusercontent.com/62737164/77778367-f3a46f80-7061-11ea-9d73-8efd4342f0ba.jpg)
![0hSBLEnyeEU](https://user-images.githubusercontent.com/62737164/77778386-f737f680-7061-11ea-90e7-162300d27b40.jpg)

**Comment by JannisX11** [comment]
You can disable minified output in `File` > `Settings` > `Export` > `Minified Export`.
