### ISSUE TITLE
[Issue] Converting Skin to Java Block/Item causes the UV editor to not update

### ISSUE THREAD

**Issue by KarBoy2314PL** [JannisX11/blockbench#573]
- make a new skin, choose a mob (ill chose bat)
- go to file -> convert project and select Java/Block Item
- notice how there are 2 number fields in the uv editor instead of 4
- you can't tap on uv window
- realise that there's a uv overlay

after saving and reopening the model in question, the uv editor is back to normal

- Blockbench variant - Desktop
- Operating System - Windows 10

**Comment by JannisX11** [comment]
Skins use the "Box UV" mapping system, since all skin textures use it and it is a lot easier to remap textures. If you want to use the manual per-face UV system, you can go into the Project settings and disable "Box UV".
