### ISSUE TITLE
[Suggestion] Isometric renders support

### ISSUE THREAD

**Issue by RedGalaxySW** [JannisX11/blockbench#575]
The Minecraft wiki and some wiki's from mods expect pages about a specific thing to have an isometric render in its infobox. These isometric renders are hard to create, you will need blender or something similar but importing/editing minecraft-like models here is a complete mess. Blockbench has much easier support on exporting isometric renders: is it possible to add an option in the screenshot menu to export an isometric render with a specific size?

**Comment by JannisX11** [comment]
If you go to the display settings (for MC Java item models) and select the GUI slot, if you then capture a screenshot, it will use orthographic projection and it will be automatically be cropped to the actual slot. Does that help?

**Comment by RedGalaxySW** [comment]
Yes that works for Java block/item models... It would still be a useful feature to have it for every model, especially entities

**Comment by JannisX11** [comment]
Added in 3.5.
