### ISSUE TITLE
[Issue] UV wont reposition correctly when re-doing template that requires a different resolution

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#577]
UV wont reposition correctly when re-doing template that requires a different resolution

There seems to be a bug when you generate template, but if it needs to make it larger or smaller than it currently is (because the user possibly added more elements, and it wasn't able to fit those to the current texture resolution), it will mess up the UV

How to reproduce:

Create a model
Create a template
Add enough new cubes that the template needs to generate a larger texture
Create a template

Or

Shrink a template from **power of 2** or **compression**

Videos:
https://streamable.com/v55y6t 3.2.2
https://streamable.com/9w0jza 3.3.0 and above

Blockbench 3.4.2

**Comment by iWackyMinecraft** [comment]
This works fine on 3.4.0 version

**Comment by iWackyMinecraft** [comment]
Bug seems to happen between 3.2.2 - 3.3.0

Works fine on 3.2.2
Breaks on 3.3.0

**Comment by JannisX11** [comment]
Fixed in 3.5.

**Comment by moskaoff** [comment]
Breaks again on 3.5.1

**Comment by iWackyMinecraft** [comment]
Broken on 3.5.1 With UV Temaplates
