### ISSUE TITLE
Steve & Alex texture files TOO LARGE!

### ISSUE THREAD

**Issue by Sonti560** [JannisX11/blockbench#582]
I can use the Alex skin as a good slim skin template (Unlike Nova skin) and want to use Blockbench as a skin creator. But the texture files are TOO LARGE! Who knows? Maybe all the skin entity skins are too large! Nova Skin somehow doesn't have this problem! Please do something about this!

**Comment by JannisX11** [comment]
Please provide more information by describing your problem in more detail or by providing a screenshot.

**Comment by iWackyMinecraft** [comment]
Uploading a skin that is larger than 8 kilobytes gives the upload error of: "File is too large"
Apparently the .png Blockbench generates are heavy for some reason?

@Sonti560 you can probably fix this issue by opening the model on paint.net or gimp, then saving again.
