### ISSUE TITLE
Error has occurred on startup? Please help!

### ISSUE THREAD

**Issue by ZackapooMC** [JannisX11/blockbench#585]
On start up, it says "An error occurred while loading Blockbench".

**Comment by JannisX11** [comment]
Are you on the latest version? If so, try to update your graphics drivers.

**Comment by ZackapooMC** [comment]
I am. I think its the pc I'm on because it works on my sisters pc so yeah it's okay but thanks for the help and I will try to update my drivers. Thanks!
