### ISSUE TITLE
[Issue] Dialog pops up when I update a texture from my image editing software.

### ISSUE THREAD

**Issue by nongfu88** [JannisX11/blockbench#586]
Whenever I update my texture (by exporting it from my image editing software) a dialog pops up which reads "Would you like to update the project resolution to the resolution of this texture? Click 'Cancel' if your texture has a higher resolution than normal." 

Video of the issue:
https://www.youtube.com/watch?v=5a2KqioRoJU&feature=youtu.be

- I use Blockbench Desktop App
- This issue is for Bedrock entity editor
- If I accept and click "Update" then the UV resolution scales to the resolution of the texture, and consequently the UV coordinates become incorrect.
- If I click "Cancel" the dialog closes, but when I export my texture from my image editing software again it reappears.

I love and have donated to Blockbench, and for me, simply an option to disable this dialog would make it perfect. I've asked about this issue several times in the discord server over the past year but have never gotten any substantial response, so I am sending this here.

**Comment by JannisX11** [comment]
Fixed in 3.5.
