### ISSUE TITLE
[Issue] Download button does nothing in WebApp with Chrome 59.0.3071.115 (32-Bit)

### ISSUE THREAD

**Issue by Jak544** [JannisX11/blockbench#59]
This issue happens regardless of what is in the actual model.

UPDATE: I've discovered it does not work with Firefox either.

**Comment by JannisX11** [comment]
I did a hitfix for now. I will officially fix it in the next version (probably 1.8.2)

**Comment by JannisX11** [comment]
Fixed in 1.8.2
