### ISSUE TITLE
CEM Animations deleted upon saving

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#591]
Upon exporting a jem file that originally had animation data in it, the animation data gets removed. Dont know how else to put it. Animation data there when opening, gone after saving.

Windows 10
Blockbench 3.4.2

**Comment by NitroCipher** [comment]
Lol, came to report this as well

(This is Zenith btw)

**Comment by ewanhowell5195** [comment]
same happens with the "scale" tag
