### ISSUE TITLE
[Issue] Unintended behavior when using 'Mirror Painting'

### ISSUE THREAD

**Issue by Powerbyte7** [JannisX11/blockbench#592]
I've been using Blockbench a lot for creating skins and I think there's a bug with 'Mirror Painting' in the paint tab. When using this option at certain brush sizes the mirroring will sometimes be off with one pixel when using even number brush sizes.

Examples:
https://imgur.com/a/Po9Na8O

Model format: Default steve skin with 'Pose' unchecked
Version: Blockbench 3.5.0 for Desktop (.deb)
OS: Ubuntu 18.04

**Comment by Powerbyte7** [comment]
Thanks for the quick fix! :D

**Comment by groovdigit** [comment]
I am having the same problem but can't see the fix mentioned above. How do I fix this problem myself?
