### ISSUE TITLE
[Issue] Inventory display glitch

### ISSUE THREAD

**Issue by KiroTheBlueFox** [JannisX11/blockbench#599]
There is a rendering glitch in the display tab -> inventory display :
When moving the camera, the model moves completely smoothly, but not the bakground image (Inventory, 3x3 or HUD, does the same with all of these).
To be more precise : 
- If the background doesn't touch any border on each axis, it will move smoothly on that axis.
- If it touches any of the borders, then it will move pixel by pixel and get scaled weirdly when I move on that axis

It acts like if it wanted to align perfectly the pixels that touch the border to the border, which is desyncing the model and the background and doing some weird movements and scaling, and the model then looks like offset weirdly even tho the translations didn't change.

Here is a video of it in action : https://streamable.com/cys73t

Version : 3.4.2 (Latest)

**Comment by KiroTheBlueFox** [comment]
EDIT : With the HUD image, it does it with half-pixels because the image might be twice bigger than the other (pixel = 2x2px if you get what I mean)

**Comment by JannisX11** [comment]
This is how pixelated rendering in Chrome works unfortunately. I will leave this in Won't Fix until I find a fix or Chrome allows to change this behavior.It should generally not be a big problem since it only occurs when you are zoomed in.

**Comment by JannisX11** [comment]
No longer an issue.
