### ISSUE TITLE
[Issue] Modded entity in 1.14 isn't exporting Java with radians

### ISSUE THREAD

**Issue by tprk77** [JannisX11/blockbench#601]
Modded entities exported for 1.14 have weird rotations whenever they are non-zero.

The issue apparently has to do with degree/radian conversion.

Steps to reproduce:

* Make a Modded Entity for 1.14 project
* Make a model with 90 deg rotated part
* Export Java
* Observe `90.0F` written to file
* "Open Model" with the Java source you just exported
* Observe loaded rotation of approximately `5156` (`90 / pi * 180 = 5156.62`)

It appears the "1.14" template should have `radians: true` but it looks like it's missing?

Thank you for making such a great tool!

**Comment by JannisX11** [comment]
Fixed in 3.5.2.
