### ISSUE TITLE
[Suggestion] Support more than 1 tint (change tint to a number instead of a boolean)

### ISSUE THREAD

**Issue by Joeywp** [JannisX11/blockbench#602]
By default, the "tint" in blockbench is a boolean which would convert to tintindex=0 in the JSON, but for CustomModelData there are some items such as FireworkStar which allow for tintindex to be either not set, 0 or 1, so that's 3+ states which isn't possible with Blockbench by default because it uses a boolean value for tint. My suggestion would be to support multiple tints so that you don't have to edit the JSON by hand to apply tints that are not covered by Blockbench 3.5.1 and lower. This would be also be useful to mods which potentially support even more tints.

Or in short: Vanilla MC supports more tints than just "not set" and "0", but BlockBench doesn't support that

Related but different issue: https://github.com/JannisX11/blockbench/issues/512

**Comment by JannisX11** [comment]
This seems to be a duplicate of #512 , which was added in 3.4. The setting is a bit hidden because few will have the need to add it. Add the "Tint Index" slider to your UV editor toolbar and use it to change the tint index. The value -1 means unset.

**Comment by Joeywp** [comment]
I think you misunderstood the issue. The thing is, in Vanilla MC, some items use tintindex=0, some use tintindex=1, but blockbench only allows for tintindex=0 (when the tint checkbox is on) or nothing/not set (when tint checkbox is off), but for example with custom firework star models that won't work, because it uses tintindex=1

**Comment by AlgebraManiacABC** [comment]
Bump; As of 5.1.4, there is only a tint checkbox on the UV face. The exported json results in a tintindex of 0 all the time. For objects with multiple tints, we cannot change the tintindex of a particular face.

**Comment by JannisX11** [comment]
> Bump; As of 5.1.4, there is only a tint checkbox on the UV face. The exported json results in a tintindex of 0 all the time. For objects with multiple tints, we cannot change the tintindex of a particular face.

This is quite an old issue. The method I posted above still works, but the easiest way to set up tint index values now is in the Face Properties section of the UV panel.
