### ISSUE TITLE
[Issue] gLTF export doesn't include animation

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#604]
In Blockbench: 
![uwu_1](https://user-images.githubusercontent.com/32020441/80632681-724b4e80-8a0c-11ea-8543-e303f65f997c.gif)

In Blender: 
![uwu_2](https://user-images.githubusercontent.com/32020441/80632683-74151200-8a0c-11ea-8480-1d65ebdcc318.gif)

Might also affect sketchfab upload

**Comment by JannisX11** [comment]
Fixed in 3.5.2.
