### ISSUE TITLE
[Suggestion] A way to view simple CEM Animations within blockbench

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#605]
I understand you not adding all of them (as its very complex) but just the ability to view simple things would still be game changing.

**Comment by JannisX11** [comment]
Added into the CEM Template Loader plugin now: https://www.blockbench.net/plugins/cem_template_loader
I do not think it makes sense to implement this directly into Blockbench, and the plugin does a great job with animations.
