### ISSUE TITLE
[Issue] Model looks different in Blockbench vs in Minecraft

### ISSUE THREAD

**Issue by ShabanPlayz** [JannisX11/blockbench#606]
Hi I made a model and it looks different in Blockbench vs ingame, here is a resourcepack with the model (it uses vanilla 1.15.2 textures and is emerald ore model): 
[issue.zip](https://github.com/JannisX11/blockbench/files/4562444/issue.zip)

**Comment by JannisX11** [comment]
Please attach some screenshots to show what looks different.
