### ISSUE TITLE
[Issue] Small block movements for modded entities no longer work.

### ISSUE THREAD

**Issue by LyLinx** [JannisX11/blockbench#608]
Okay so I just updated to BB 3.5.2 and the control key and the shift key no longer allow cubes to be edited in 0.05 or 0.25 increments, instead the block glitches and doesn't respond properly and makes it huge
![image](https://user-images.githubusercontent.com/59287512/80801070-30a0dc00-8ba3-11ea-85a8-c0e88f68cfe8.png)

![image](https://user-images.githubusercontent.com/59287512/80801084-3991ad80-8ba3-11ea-8622-6216dfde5191.png)

![image](https://user-images.githubusercontent.com/59287512/80801089-3f878e80-8ba3-11ea-8304-12defe96f467.png)

**Comment by JannisX11** [comment]
Decimal numbers in cube positions still work. Decimal sizes are disabled since they are not compatible with the UV system of the format.
