### ISSUE TITLE
[Issue] Integer size lock is always enabled for JPM

### ISSUE THREAD

**Issue by LordPotato17** [JannisX11/blockbench#609]
I was told to post this issue from a modeling pro on the discord. 

So a few updates ago the ability to use decimals in JPM models was removed and limited to whole numbers, I was told this was because those models only support whole numbers. However, I have found that isn't the case. 

As can be seen, by these screenshots the element in question is using decimal sizes yet in-game it appears just as it does in blockbench. Something that "could not happen". Perhaps the modeling restrictions for entities need to be revisited. 

![Screenshot (324)](https://user-images.githubusercontent.com/64657698/80828492-f9362d80-8baa-11ea-834d-609736bffb09.png)

![Screenshot (323)](https://user-images.githubusercontent.com/64657698/80828485-f63b3d00-8baa-11ea-9960-bb2ebaaf0fa2.png)

**Comment by JannisX11** [comment]
Fixed in 3.5.3.
