### ISSUE TITLE
Plugin window won't close

### ISSUE THREAD

**Issue by JustTimm** [JannisX11/blockbench#61]
click on plugins but I can not close the window in any way. https://gyazo.com/cfc3f5a38bd4badee712709e5650d5c7

**Comment by GitWither** [comment]
Can't reproduce, works fine for me.

**Comment by JannisX11** [comment]
Please send a screenshot of the console (Press Ctrl + i)

**Comment by JustTimm** [comment]
The problem is suddenly gone ...

2017-08-06 18:45 GMT+02:00 JannisX11 <notifications@github.com>:
