### ISSUE TITLE
MCreator won't Support 1.15.2 Models.

### ISSUE THREAD

**Issue by JNtheWolf** [JannisX11/blockbench#611]
When I try to upload my Blockbench models to MCreator, they do not load. A MCreator developer told me that 1.15.2 models do not work in MCreator as it is 1.14.4. I just want to know how to create models for 1.14.4 Minecraft. Thanks!

**Comment by JannisX11** [comment]
Please use the Discord server for modeling help: http://discord.blockbench.net
