### ISSUE TITLE
poly_mesh bones

### ISSUE THREAD

**Issue by wuweixingtian** [JannisX11/blockbench#617]
The new "poly_mesh" model can produce more detailed models than the previous "cubes", and it is recommended to add support for this model

**Comment by wuweixingtian** [comment]
Converting to the poly_mesh model using the obj file requires little modification

**Comment by iWackyMinecraft** [comment]
You can convert OBJ:s to bedrock poly mesh with Bridge
https://github.com/bridge-core/bridge./releases/tag/v1.5.0

**Comment by JannisX11** [comment]
Duplicate of #555
