### ISSUE TITLE
[Suggestion] Paint bucket erase mode

### ISSUE THREAD

**Issue by AngeloVH** [JannisX11/blockbench#618]
Ability to erase texture from whole faces, or certain colors.
It would help with texturing 2d cubes or anything where transparency is involved.

**Comment by Qapslock** [comment]
Just wanted to push this suggestion as it is almost one year old, and it would be insanely helpful to have the erase tool also appliable on the bucket tool.

**Comment by PoolloverNathan** [comment]
bump
