### ISSUE TITLE
[Suggestion] Save animation states as separate models

### ISSUE THREAD

**Issue by Ligua-beep** [JannisX11/blockbench#620]
So I'm making a complex model of a mob with 2 stages [Bedrock edition entity] which has an animation that starts as A and transitions into B, the animation is really complex and I now need the final stage of all the cubes that form the model in the shape of state B in a separate .bbmodel file, I don't know if it's possible to do, but I would really appreciate a feature to copy the position of all bones in a certain point of an animation and past it into the "Edit" tab model.

I've seen myself moving the parts manually and trying to eyeball it but I can't get them in the perfect position I put them in when I animate it, some would argue that I could have animated it at the same time that I peformed the same changes on another identical model, but even this is a difficult and time consuming process.

I like how the animated state stays in paint mode, maybe there's a way to have that in edit mode?

**Comment by JannisX11** [comment]
This seems like an edge case. Usually you can just save an animation with that pose and play it on loop. I'll still add this to the list.

**Comment by Ligua-beep** [comment]
> This seems like an edge case. Usually you can just save an animation with that pose and play it on loop. I'll still add this to the list.

Yeah, I thought of that, It's just the programmer asked me for a separate model, it would be awesome if you add it though!

**Comment by JannisX11** [comment]
Added in 4.1.
