### ISSUE TITLE
[Issue] export .obj with blockbench to Autodesk Maya but can't open hypershade

### ISSUE THREAD

**Issue by MrSwtz** [JannisX11/blockbench#621]
I found the issue while open hypershade in Maya for add textures to the model. it error says "Invalid object name: 0"
(update HyperShade in List.mel line 27: Invalid object name: 0)

I have opened .mtl and .obj file. in file .mtl I found code newmtl name "0" and another newmtl name "none" but code in .obj file running "usemtl 0" not "usemtl none" this make error object name in Maya

and I try to change the word "usemtl 0" to "usemtl none" it's working!

is it possible that you can develop blockbench can import .obj in Maya better

**Comment by JannisX11** [comment]
"none" is an untextured face, while "0" usually refers to your first texture. Can you confirm that a number at the start of the material name causes the error message? The OBJ specification does not require a specific name scheme, but if this is a common issue I can add a workaround.

**Comment by MrSwtz** [comment]
https://imgur.com/sKGwZw7
According to my understanding. refer to the attached picture. firstly, I export .obj file form Blockbench and next import it to Autodesk Maya. a model can import but can not open hypershade for add textures to the model. the error message says"Invalid object name: 3" 3 name can not work.

in .mtl file, the names are in the type of number, not word and I try to change all "newmtl" name to

newmtl 1 -> newmtl t1
newmtl 2 -> newmtl t2
newmtl 3 -> newmtl t3
newmtl 4 -> newmtl t4
newmtl 5 -> newmtl t5
newmtl 6 -> newmtl t6

and change words "usemtl" in .obj file

usemtl 1 -> usemtl t1
usemtl 2 -> usemtl t2
...

and it works!
look like Maya not allow name is the type of number (maybe? I'm not sure)

**Comment by JannisX11** [comment]
Fixed in 3.6.
