### ISSUE TITLE
[Issue] Black background on exported images/Model screenshot loses transparency

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [JannisX11/blockbench#626]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

So i was making renders for MInecraft and i ran into a problem.Whenever i took a screenshot of a model it would eventually end up with a black background.

Here are some example screenshots:
![flare](https://user-images.githubusercontent.com/43296868/81501044-aa099e80-9308-11ea-825b-2991a4dd3c6b.png)
![pike_20](https://user-images.githubusercontent.com/43296868/81501049-afff7f80-9308-11ea-9815-46977408e83b.png)
![pike_21](https://user-images.githubusercontent.com/43296868/81501053-b55cca00-9308-11ea-9990-51fae0b29f47.png)
![c_jellyfish](https://user-images.githubusercontent.com/43296868/81501493-39b04c80-930b-11ea-9125-7506fd31f09b.png)
![c_jellyfish_white](https://user-images.githubusercontent.com/43296868/81501505-4e8ce000-930b-11ea-8188-6004cfc6443f.png)

**Comment by JannisX11** [comment]
These examples do not have a black background though?
