### ISSUE TITLE
[Issue] Stuck view when setting block size to 0

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [JannisX11/blockbench#629]
Each time I accidentally set one of the x,y,z sizes of the block to 0, the view rotate to 2D (which is fine) but when I set it back, there's no way to rotate the view anymore, even when making a new file. I have to restart the program for it to work.

**Comment by JannisX11** [comment]
Cannot reproduce. Please specify your platform and which keys and buttons you are using exactly.
