### ISSUE TITLE
Rotation Tool (Transform > Rotate) doesn't work properly

### ISSUE THREAD

**Issue by Henrique3310** [JannisX11/blockbench#63]
**[EDIT]** Found the reason of the problem. The **origin of rotated elements don't change**, they stay in the same place. This messes up the model. **THE SAME HAPPENS FOR FLIP TOOL**.

Currently all of the rotation options in the Transform > Rotate menu are broken. They don't rotate rotated elements (as in the 45°, 22.5° rotations).

Example:

Original Model
![image](https://user-images.githubusercontent.com/5795764/29100035-66563ec0-7c7f-11e7-9fdc-e26468043e83.png)

After Transform > Rotate > Rotate CW (Y axis)
![image](https://user-images.githubusercontent.com/5795764/29100041-712fc398-7c7f-11e7-9353-b3650ac4aee7.png)

Similar outputs happen for all the rotation options.

**Comment by JannisX11** [comment]
Fixed in 1.9
