### ISSUE TITLE
[Suggestion] Optimise more for game engines

### ISSUE THREAD

**Issue by vybr** [JannisX11/blockbench#630]
Hi, I've been toying around with Blockbench for a short while and it seems like exactly what I need to speed up the workflow for my game. I'm using it with the Godot game engine and I noticed after importing some models that a material is created for each face. So one block/cube will have 6 different materials in the engine (and in Blender), despite it sharing the same texture. 
I downloaded a motorbike model made with Blockbench from Sketchfab and it had over 400 surfaces/materials in Godot. This is a problem because it increases the number of draw calls by a lot, which brings down the fps. It also makes it difficult to edit materials in the engine because I have to scroll through a bunch of them to find the correct one.

I was wondering if an optimisation could be made here so it works better with game engines?
Thanks!

**Comment by JannisX11** [comment]
I have never used Godot, but there is actually only one material created per texture. This works with all 3D applications that I have tested so far, including Blender and Sketchfab. I have also tried to re-download a Blockbench model from Sketchfab, and it keeps the material. So this must be an issue with Godot. You can test the model on Sketchfab for example to find out if it actually has too many materials.

**Comment by vybr** [comment]
I created a single block and exported as a obj and a gltf, the obj has one material in Blender but the gltf still shows 6 materials with the same name.
As for Godot, I'll probably just clean it up with a script.
