### ISSUE TITLE
[Issue] Block Model not using custom selected textures from default pack

### ISSUE THREAD

**Issue by theDaleighChronicle** [JannisX11/blockbench#636]
Hello. Recently, I've been working with Minecraft json models. I am using the Windows 64bit desktop program in the latest version. When creating a bookshelf model, I've been using both the default bookshelf texture and the default oak planks texture. I have it mapped so that it looks for the textures in the current texture pack under assets/minecraft/textures/block, so the structure is correct. The model works in hand, as shown in the screenshot, but the placed model won't use the custom UV mapping with the oak planks texture. Would love some assistance. 

![InBlockBench](https://user-images.githubusercontent.com/26281804/82168527-31f92680-987c-11ea-9378-8f7ee01e5310.png)
![2020-05-17_20 16 49](https://user-images.githubusercontent.com/26281804/82168507-286fbe80-987c-11ea-8f19-18ec7c155c30.png)

**Comment by dragonmaster95** [comment]
make sure the model file is in models/block and not just in models/item (nearly every item of a block uses the block model for its item form by default anyways)

**Comment by theDaleighChronicle** [comment]
The model is in both, so that isn't the issue.

**Comment by dragonmaster95** [comment]
And you are sure they are the exact same file? (and not 2 different versions of the same model)
To make sure they are the same, have only the model in the models/block folder, and no bookshelf model in the models/item folder.

**Comment by theDaleighChronicle** [comment]
And there is no way to disable the connect textures, is there?

**Comment by dragonmaster95** [comment]
Esc > Options > Video Settings > Quality > Connected Textures: OFF
