### ISSUE TITLE
Flip tool (Transform > Flip) doesn't flip textures

### ISSUE THREAD

**Issue by Henrique3310** [JannisX11/blockbench#64]
Title says it all. None of the options in the Transform > Flip menu cause any effect on textures. 

Example:

Original cube
![image](https://user-images.githubusercontent.com/5795764/29100162-5beb8584-7c80-11e7-9715-900238180b3c.png)

After Transform > Flip > Flip X
![image](https://user-images.githubusercontent.com/5795764/29100174-6ab7cb68-7c80-11e7-8143-85834c67706c.png)

Notice the pattern in the texture doesn't flip as well.

**Comment by JannisX11** [comment]
Fixed in 1.9. (Going to leave this open until it comes out)
