### ISSUE TITLE
[Suggestion] Remove rotation line in json files if the angle is 0

### ISSUE THREAD

**Issue by ze-or** [JannisX11/blockbench#640]
I noticed that many of the voxel elements in json files exported from Blockbench have the line for rotation even though the angle is set to 0(meaning the entire line is completely unnecessary)

It seems wasteful to have that line and I found myself manually removing it when I get the chance to.

**Comment by JannisX11** [comment]
The line is saved to preserve the pivot point, which is important if you want to work on an exported model later on and you don't want to save it as a separate project file.
