### ISSUE TITLE
[Issue] Cannot create Edit Session

### ISSUE THREAD

**Issue by leapacho** [JannisX11/blockbench#641]
So basically i wanted to modelate with my friend on Edit session, but when i tried i couldn't connect with them. I also tried to disable my firewall, it didn't work. I tried multiple times before and this was the output on the console:
![image](https://user-images.githubusercontent.com/53064426/83207175-e7539600-a128-11ea-8d40-3367f8a929e7.png)
i don't really know what's causing it. 

Blockbench Info:
3.5.2
Desktop
Plugins:
Discord RPC
Screencast keys
The Guessing Game
OS:
Windows 10 Pro

**Comment by JannisX11** [comment]
The connection server is down. Which is a public server that is not hosted by me. (The server is just for establishing the connection, data goes straight from client to client)
I might end up hosting my own server for this if they do not get this fixed.

**Comment by leapacho** [comment]
ok thanks!

**Comment by JannisX11** [comment]
Related to https://github.com/peers/peerjs/issues/671

**Comment by JannisX11** [comment]
Blockbench now has it's own signaling server, the issue will be resolved in 3.6.

**Comment by leapacho** [comment]
Thanks!
