### ISSUE TITLE
[Issue] No grids, how can i turn it on? or it's a bug?

### ISSUE THREAD

**Issue by mamankmantap** [JannisX11/blockbench#644]
I'm using the latest blockbench, 3.5.3. I checked the settings about grids, but i can't see my grids and its making it harder for me to create. I downloaded this blockbench, not using webapp. I downloaded this windows 64 bit installer version 3.5.3

Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz
64bit
Windows 10
Geforce GTX 1050

![123341982189](https://user-images.githubusercontent.com/66214027/83356797-a1016f80-a392-11ea-8f56-ea1556ef3485.PNG)

I hope this image can explain.. and i hope you can understand
![124124212422](https://user-images.githubusercontent.com/66214027/83356909-5df3cc00-a393-11ea-9268-2e6bafc06636.png)

[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench. - (It's the latest version)
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue. (There's no error messages)

**Comment by JannisX11** [comment]
Fixed in 3.5.4.
