### ISSUE TITLE
[Issue] Shading does not resemble the shading used in Minecraft

### ISSUE THREAD

**Issue by Goodlyay** [JannisX11/blockbench#645]
The brightness of the sides of the cubes when "View" -> "Shading" is enabled does not match the brightness used in Minecraft. Furthermore, even with shading disabled, it is impossible to find a "Brightness" setting that actually faithfully represents the texture's real colors. It has some kind of color grading that makes either lights too light, or darks too dark.

Here is my texture:
![image](https://user-images.githubusercontent.com/7892772/83366331-34bb4780-a363-11ea-8ce9-96197ec4ad81.png)

Here is what I see with shading enabled:
![image](https://user-images.githubusercontent.com/7892772/83366339-47ce1780-a363-11ea-9235-726f3d06e1a3.png)
Note the blown out brights on top and the barely different darkness on the X-side quad vs the Z-side quad.

Here is (roughly, as even with shading disabled the colors aren't accurate to the texture) what I expected to see:
![image](https://user-images.githubusercontent.com/7892772/83366361-70561180-a363-11ea-8d46-f42a0a57001f.png)
Simulated by manually adding Minecraft-style shading to the texture and turning shading off in view.
![image](https://user-images.githubusercontent.com/7892772/83366405-b3b08000-a363-11ea-9b89-9a557919f761.png)

**Comment by JannisX11** [comment]
Approximated the shading as well as possible in 3.6. Different Minecraft versions and model renderers have different shading values, so I used an average.
