### ISSUE TITLE
[Suggestion] Tabs

### ISSUE THREAD

**Issue by moskaoff** [JannisX11/blockbench#646]
Being able to open more models at the same time
<img width="1445" alt="blockbench_concept_tabs" src="https://user-images.githubusercontent.com/19352571/83532984-4e899580-a4ef-11ea-82a6-2b0184206684.png">

**Comment by iWackyMinecraft** [comment]
I think it would be better to have a full folder explorer on blockbench, which would make editing packs easy.

**Comment by moskaoff** [comment]
Like bridges., it has tabs and a folder explorer, it would be really nice

**Comment by JannisX11** [comment]
Duplicate of #411
