### ISSUE TITLE
Shadow/Light Visibility on Minecraft

### ISSUE THREAD

**Issue by Vaipah** [JannisX11/blockbench#648]
How can i fix this? Pls Help Me.

![Schermata 2020-06-05 alle 21 54 36](https://user-images.githubusercontent.com/66493065/83917425-27dd9000-a777-11ea-8ccf-8128bbe3616f.png)

![Schermata 2020-06-05 alle 21 55 18](https://user-images.githubusercontent.com/66493065/83917476-3fb51400-a777-11ea-9990-0fbd8ebe2e97.png)

**Comment by JannisX11** [comment]
Unrelated, please use the discord server: http://discord.blockbench.net
