### ISSUE TITLE
"Ghost cubes" and other issues after filling the outliner with a single group

### ISSUE THREAD

**Issue by Henrique3310** [JannisX11/blockbench#65]
I found a small bug on the outliner. if you make a group that has so many elements that there's no empty space left in the outliner, then you duplicate all the elements,

- You will not be able to remove the duplicates from the group as there will be no empty space in it
- Creating a new cube creates a "ghost" cube, which literally can't be selected (clicking it does nothing BUT it does appear in the UV editor) and doesn't appear in the outliner.

After collapsing the group (and thus leaving empty space in the outliner), I can add cubes normally again, however the ghost cubes stay un-selectable and don't appear anywhere in the outliner.

**Comment by JannisX11** [comment]
Please try to reproduce this issue in the current version.
