### ISSUE TITLE
[Issue] Modded Entity Mode for 1.15 doesn't support floats for element size

### ISSUE THREAD

**Issue by Elenterius** [JannisX11/blockbench#652]
Version: 3.5.4
Model format: Modded Entity Mode for MC 1.15

Since Minecraft Java 1.15 uses now floats for the dimensions of cubes (width, height, depth) I expected blockbench to allow floats but instead it still uses ints for the element size.
![Annotation 2020-06-12 200025](https://user-images.githubusercontent.com/6061273/84532906-68915800-ace7-11ea-8ff5-844292ef52f4.png)

---

what i like to happen in the future:

![blockbench](https://user-images.githubusercontent.com/6061273/84533217-f40ae900-ace7-11ea-8e5b-cff405f8089c.png)
should lead to this export result
```java
foobar.addBox(-0.775F, -0.2375F, -1.7125F, 0.625F, 0.625F, 0.625F, 0.0F, true);
```
---

current export result for mc java 1.15 since floats are not supported
```java
foobar.addBox(-0.775F, -0.2375F, -1.7125F, 0.0F, 0.0F, 0.0F, 0.0F, true);
```

**Comment by JannisX11** [comment]
Element sizes now use floats, but box UV mapping does not floor those numbers in 1.15, so elements with float sizes are impossible to texture most of the time. Until this is resolved, Blockbench won't be able to export float sizes.

**Comment by Elenterius** [comment]
thx. Thats fine i'm aware of the uv mapping issue, at least it will work inside blockbench and i don't have to resort to scaling or converting between formats. :) 
It's a rare use case for me anyways.
