### ISSUE TITLE
[Suggestion] Proper 2D texture editor

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#653]
**Current Problems with BB**

Not easy to make accurate color & brightness tweaking (Also the plugin can be laggy and slow)
No good way to make item and GUI textures, or just plain pixel art
Current sidebar 2D canvas preview too small to make accurate selecting with copy paste tool or shape tool
No Checkerboard or all paint tools on UV Full view

**What would be new:**

New Texture editing window
Bigger texture canvas/preview
Layers (Would be nice in 3D too!)
Custom Brushes (Both 3D & 2D)
Brush Editor
Brush import/export
Better Color/Bright editing (Currently a plugin)

**Other suggestions:**

Lasso Select
Selection only color editing & Painting
Magic Wand Select With Tolerance
Invert Selection
Color/Bright Curves
Stretch & Rescale selection
Background references
Tiling mode for making seamless textures
Multiple textures on a single canvas
Quickcopy canvas texture to clipboard
Generate collage of your textures (Like a pack showcase)
Open folders

Concept i made, popup window probably isn't the best way to implement this menu, maybe just a different mode window along with animate, paint, edit tabs could work too
![image](https://user-images.githubusercontent.com/44243757/84709955-e6659580-af6b-11ea-8e5d-73aa72417200.png)

With descriptions:
![image](https://user-images.githubusercontent.com/44243757/84711415-f92d9980-af6e-11ea-97bf-62f1a7ab9416.png)

**Well, why not just use gimp, ps or pdn?**

better keybind system
way more customizable
no app loading times
Custom Brushes could be used in 3D
Overall faster to work with
Textures get backup-ed to the same file as the model
Easy to learn

**Comment by JannisX11** [comment]
:)

**Comment by JannisX11** [comment]
Added in 4.4.
