### ISSUE TITLE
[Issue] Modded Entity does not handle loose cubes properly for 1.12.2 (3.5.4)

### ISSUE THREAD

**Issue by SpaceMinere** [JannisX11/blockbench#655]
An alternate version of this bug was reported as [https://github.com/JannisX11/blockbench/issues/637](url) where loose cubes did not export with the model. The reply in this thread explained the fix as "All cubes in entity models need to be inside a bone. This is still an issue since it should generate a bone for loose cubes, but if you correctly add your cubes to bones, you won't come across it." It was reported as fixed in 3.5.3.

In the 1.12.2 modded entity exporter, it creates a bone called bb_main when exported, which is presumably what the loose cubes are supposed to be regrouped to according to the previous issue; however, the cubes are not added to bb_main; leaving it an empty bone with no cubes, and causing loose cubes to be lost. If I am not mistaken, loose cubes should be added to bb_main when the model is exported.

(Blockbench 3.5.4 on Windows 10 desktop)

**Comment by JannisX11** [comment]
Fixed in 3.6.
