### ISSUE TITLE
[Issue] Drop down menu bug

### ISSUE THREAD

**Issue by RyanGar46** [JannisX11/blockbench#656]
OS - Window 10
Blockbench - Windows App 3.5.4

Issue:
the drop-down menu in the image is incorrectly sized. the arrow is over the text. by the way, I have auto cullface and tint added to that area if that helps.

![blockbench_issue](https://user-images.githubusercontent.com/67124977/85071750-f6f15800-b185-11ea-91d4-ca069605e385.png)

**Comment by JannisX11** [comment]
Fixed in 3.6.
