### ISSUE TITLE
[Issue]Model won't display body correctly

### ISSUE THREAD

**Issue by DemonKiller365-Create** [JannisX11/blockbench#659]
So, when I use block bench to edit textures while there on models I couldn't see the body correctly compared to what it looks like in Minecraft, and it's driving me crazy. Specs-wise I'm using the vanilla resource and behavior pack 1.14.30 and format version 1.18.0 due to the fact that the Minecraft add ons documentation says to not change the format unless you have a good reason too I'm also using visual studio code to edit .json files. Sorry, I don't have the pack finished but you find the textures and models at minecraft.net/addons and then download the resource pack and navigate from there thanks ahead of time for your support! oh and my operating system is windows and I'm using the desktop app.

**Comment by JannisX11** [comment]
If you want to texture Minecraft entities, you can use File > New > Skin instead and select the correct base model. Some default models do unfortunately have an incorrectly rotated body.
