### ISSUE TITLE
[Issue] Extruding issues

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#66]
![image](https://user-images.githubusercontent.com/8559428/29249419-b80470da-802f-11e7-9c44-c8b3170e3d6b.png)
![image](https://user-images.githubusercontent.com/8559428/29249422-bd465cd4-802f-11e7-86ae-f3970b9d717a.png)
If you extrude a texture the backside is flipped.

**Comment by JannisX11** [comment]
This is an issue with the rotation tool, not with image extrusion.

**Comment by JannisX11** [comment]
Fixed in 1.9
