### ISSUE TITLE
incorrect display of the model guardian

### ISSUE THREAD

**Issue by Olenik636** [JannisX11/blockbench#660]
incorrect display of the model when exporting to bedrock model in Minecraft bedrock edition the model is distorted

**Comment by JannisX11** [comment]
Please add more informations + screenshots.

**Comment by Olenik636** [comment]
I save the guard model as bedrock geometry and create a texture pack, but
when I open it, the model breaks. everything is shown in the video
 g.mp4
<https://drive.google.com/file/d/1stRg55SpSBguSJP6G23j4jK5by2M4Mfk/view?usp=drive_web>


вс, 28 июн. 2020 г. в 17:03, JannisX11 <notifications@github.com>:

**Comment by JannisX11** [comment]
The skin models are not meant to be exported for Minecraft. To do that, use the Entity Wizard plugin: https://aka.ms/mcentitywizard
