### ISSUE TITLE
[Suggestion] hold_on_last_frame support in animations

### ISSUE THREAD

**Issue by tryashtar** [JannisX11/blockbench#663]
As of Bedrock 1.16, the animation `loop` property now has three options: `false` (reset to initial pose when complete), `true` (loop), and `"hold_on_last_frame"` (stay on final pose when complete).

Currently, Blockbench discards this option when loading animations, changing `hold_on_last_frame` to regular `true` looping. So after saving again, the animation is somewhat broken.

Changing the UI from a checkbox to something else in order to support this would be nice, but at the very least I think it should be preserved when loading and re-saving.

**Comment by tryashtar** [comment]
I should have known 😄

**Comment by JannisX11** [comment]
Added in 3.6.
