### ISSUE TITLE
[Issue] Exporting 1.15 models leaves no imports (3.5.4)

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [JannisX11/blockbench#666]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

So I was making some models for a Minecraft project of mine for 1.15, but when I open the model file in a text editor, the imports were missing. This doesn't happen for 1.12/probably 1.14. I've only seen it on 1.15.

**Comment by JannisX11** [comment]
None of the Modded Entity export version in the latest version of Blockbench generate any imports. This is in order to maximize compatibility and is intentional. You can easily generate the required imports in a Java IDE.
