### ISSUE TITLE
[Issue] UV map of wavefront obj export is broken for minecraft forge 1.12.2-14.23.4.2759

### ISSUE THREAD

**Issue by xunto** [JannisX11/blockbench#668]
**Blockbench variant**: webapp, current, 3.5.4

It looks like uv map when exporting free model to obj is upside down when it's loaded in minecraft forge mod (forge 1.12.2-14.23.4.2759).

This is original model: [target.zip](https://github.com/JannisX11/blockbench/files/4874688/target.zip)
![image](https://user-images.githubusercontent.com/5288053/86529725-ab47e980-bebb-11ea-82e6-425f52d30235.png)

This is how it looks like this ingame:
![2020-07-05_12 31 14](https://user-images.githubusercontent.com/5288053/86529709-93706580-bebb-11ea-9a8a-92b75cf4c981.png)

Now if I change it a little bit, choosing following area as a texture: [target(4).zip](https://github.com/JannisX11/blockbench/files/4874700/target.4.zip)
![image](https://user-images.githubusercontent.com/5288053/86529744-cdda0280-bebb-11ea-853e-3e58f54d1656.png)
![image](https://user-images.githubusercontent.com/5288053/86529746-d29eb680-bebb-11ea-98f3-669a027ccfb3.png)

It looks ok (but as you can see, other textures still aren't mapped correctly):
![2020-07-05_12 35 45](https://user-images.githubusercontent.com/5288053/86529781-31fcc680-bebc-11ea-91d9-b57f78803e4f.png)

I'm not sure it's blockbench issue and isn't forge issue as the way they load obj always seemed strange to me but they won't fix it anyway so maybe some workaround can be added here. Also uv map looks ok in blender (though I'm not expert in this sort of things).

**Comment by JannisX11** [comment]
This is definitely an issue with Forge. A quick Google search brought up this: https://forums.minecraftforge.net/topic/59046-solved-uvs-getting-flipped-on-custom-obj-model/

**Comment by xunto** [comment]
Ah, ok, sorry! I didn't find it. Sorry for wasting your time.
