### ISSUE TITLE
[Issue] Could not change selected face in uv editor by mouse wheel 

### ISSUE THREAD

**Issue by GeForceLegend** [JannisX11/blockbench#669]
Could not change selected face in uv editor by rolling mouse wheel.
![20200705175029](https://user-images.githubusercontent.com/41003546/86530064-114a6600-bee8-11ea-86c5-adb3743fa1a7.png)
This does not happen in 3.5.0.
Affects block model editing of MCJE

![20200705174535](https://user-images.githubusercontent.com/41003546/86530043-ea8c2f80-bee7-11ea-937a-66abcc1381e9.png)

Desktop App, Windows10 1909

**Comment by JannisX11** [comment]
Fixed in 3.6.
