### ISSUE TITLE
Wireframe is too weak

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#67]
![image](https://user-images.githubusercontent.com/8559428/29249461-3f41ff40-8030-11e7-8efc-df78d7d23699.png)
If the element is alone the blue outline is thick enough to show where it ends but once another element is next to it it is almost impossible to tell where the border is. My suggestion would be to make an option in the settings where you can set the thickness of the wireframe.

**Comment by JannisX11** [comment]
I will look into this further. Problem so far was this: https://stackoverflow.com/questions/11638883/thickness-of-lines-using-three-linebasicmaterial

**Comment by JannisX11** [comment]
I'm going to close this for now. It has been implemented according to the Three.JS docs. That it does not work is an issue with windows. The current line width combined with anti aliasing is usually clear enough.
