### ISSUE TITLE
Issue: Blockbench 3.5.4 is missing brush mode option.

### ISSUE THREAD

**Issue by aCatman** [JannisX11/blockbench#671]
Just opened Blockbench for the first time after installing it months ago and it updated to 3.5.4.  All descriptions and tutorials I can find indicate it has a brush mod with choice of round or noise.  It is not in my installation.  As attachment shows, this is on a Windows 10 desktop running Boot Camp on an Apple Mini computer.

![Blockbench 3 5 4 Capture1](https://user-images.githubusercontent.com/67944388/86728964-c9a80500-bfe1-11ea-85eb-2ad1cd5f666b.JPG)

**Comment by JannisX11** [comment]
Round is default, noise has been removed months ago. Works as intended.
