### ISSUE TITLE
[Issue] Opening .bbmodel files on macOS loads Blockbench but not project

### ISSUE THREAD

**Issue by fadookie** [JannisX11/blockbench#678]
On Blockbench 3.6 for macOS, `.bbmodel` files now are associated with Blockbench. However when I click one, it opens blockbench but the project doesn't load, it just displays the start screen. When blockbench is already open with or without a project loaded, clicking one has no effect.

**Comment by bernie-g** [comment]
Just wanted to add that this happens on windows too, not specific to mac
