### ISSUE TITLE
[Suggestion]  Add option to round all coordinates N decimals

### ISSUE THREAD

**Issue by BillyGalbreath** [JannisX11/blockbench#68]
I found a few models online that I am playing with and I noticed they use an insane amount of data in their coordinates with no gain. I would love if BlockBench would round these numbers automagically for me because it's quite a time consuming task when trying to keep a resource pack filesize down.

Example:
"uv": [3.000999927520752, 0.5009999871253967, 12.99899959564209, 2.499000072479248],

Should round to:
"uv": [3, 0.5, 13, 2.5],

This dramatically reduces filesizes when coupled with the one-liner json option.

Example of a model I found that works brilliantly with rounded coordinates (I manually converted them in Gedit) https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/custom/hat_cloak.json

**Comment by JannisX11** [comment]
There is now a plugin called "Experimental JSON Exporter" that does this. It will be default in the next Blockbench version.

**Comment by CREEATION** [comment]
Wait, there are plugins for Blockbench? Where?

**Comment by JannisX11** [comment]
Added in Blockbench 1.11.6
