### ISSUE TITLE
Blockbench Built-In Updater

### ISSUE THREAD

**Issue by DolphinFlopFish** [JannisX11/blockbench#683]
The Blockbench Built-In updater is not working

**Comment by JannisX11** [comment]
Please provide more details. Which version are you currently on, do you have auto updates enabled in the settings, does the updating notification in the Help menu appear after restarting, are there any error messages in the console (Help > Developer > Dev Tools)?

**Comment by Gekocaretaker** [comment]
I have the same bug. I am on the version 3.5.4 and am using windows 10 64x. The updater will not work and tells you to go to the downloads page to manually download 3.6.4

**Comment by RyanGar46** [comment]
Gekocaretaker, this probably because it is so outdated that it does not with the newer version.
