### ISSUE TITLE
UV mapping scale

### ISSUE THREAD

**Issue by jay58831** [JannisX11/blockbench#684]
Hi. Im trying to create a texture for my modded entity model and it work but as soon as i edit the texture and then import the texture on blockbench or on mcreator The texture doesn't fit with my model anymore. I tried to put the scale of the texture and the scale of the project equal but it doesn't work.

this is my model with a normal template texture:

![Annotation 2020-07-21 201536](https://user-images.githubusercontent.com/68626492/88130283-f84fdf00-cb8e-11ea-962b-39b78f9d2f59.png) 

And this is my texture after i editied it and import it on my model:

![Annotation 2020-07-21 202046](https://user-images.githubusercontent.com/68626492/88130561-bd9a7680-cb8f-11ea-9c80-65704315a3bb.png)

Can i get help please.

i found this video on youtube this is exactly the issue i'm having but i still can't find how to fix it:

https://youtu.be/6kC2JZPA2-8

**Comment by jay58831** [comment]
Hi. Im trying to create a texture for my modded entity model and it work but as soon as i edit the texture and then import the texture on blockbench or on mcreator The texture doesn't fit with my model anymore. I tried to put the scale of the texture and the scale of the project equal but it doesn't work.

this is my model with a normal template texture:

Annotation 2020-07-21 201536

And this is my texture after i editied it and import it on my model:

Annotation 2020-07-21 202046

Can i get help please.

I found this video on youtube and it exactly what is happening to me.

**Comment by JannisX11** [comment]
When you generate a new texture template, you need to save the texture AND the model file in order to keep the new UV mapping. At least that appears to be the issue in the Youtube video.

**Comment by jay58831** [comment]
okay perfect thankss!!!
