### ISSUE TITLE
[Issue] Loading an empty .json file loses edit/paint/display tabs after entering display mode

### ISSUE THREAD

**Issue by archee1** [JannisX11/blockbench#685]
If loading an empty json file into blockbench once you enter display you cant enter any other edit modes other than the start splash screen. this will still occur if you create elements edit UV's or use paint mode.

**To reproduce:**
1. create a .json file consisting of just "{}"
2. load the file into blockbench
3. enter the 'display' edit mode
4. all modes on mode select should now be gone aside from start.

OS windows10, BBv3.6.3

**Comment by JannisX11** [comment]
That is actually sort of intended. If a JSON file doesn't contain any information, Blockbench cannot figure out what kind of model it is and therefore goes into "no project" mode. I suppose it is not intended that the tabs do not update instantly.
