### ISSUE TITLE
[Issue] Moving on with Linux to v 3.6.3

### ISSUE THREAD

**Issue by scrouthtv** [JannisX11/blockbench#688]
Hello,

I have a question regarding running Blockbench on Linux. For all recent releases, there were .deb files for Linux:
![image](https://user-images.githubusercontent.com/23227405/88379889-f01cbd00-cda3-11ea-85a3-bb17d8367f23.png)
However for the newest version (3.6.3), they are missing:
![image](https://user-images.githubusercontent.com/23227405/88379945-062a7d80-cda4-11ea-8c69-45a709313d78.png)

Is Linux not supported anymore? Am I missing anything? Can I / do I have to build it myself and if yes how (I don't know much about JS)?

I am running `Linux 5.7.9-arch1-1 x86_64`.

**Comment by JannisX11** [comment]
Sorry that was an issue in the latest build. Linux binaries will be uploaded again with the next patch.
