### ISSUE TITLE
[Issue] Scale tool does not respect inflation for uniform scaling

### ISSUE THREAD

**Issue by fadookie** [JannisX11/blockbench#689]
For issues, please provide the following informations:
- Detailed description of your issue

When scaling uniformly using scale tool, box inflation is not adjusted to compensate resulting in a broken-looking model:

https://cdn.discordapp.com/attachments/314078934155132948/736629303311204502/2020-07-25_19-01-17.mp4
https://cdn.discordapp.com/attachments/314078934155132948/736627724814123048/bow-scale2.gif

- Model format in which the issue occurs:

All, including free models

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop): All (found on Desktop)
- Operating System: All (found on macOS)

**Comment by MarneticM** [comment]
Topic closed, yet the issue is still persistent. When I create hexagon from cylinder, then I select all 6 top faces and and use Insert Selection, when I scale it up or down it distorts some parts of the model, even with holding ctrl and shift with res set to 1024.

**Comment by JannisX11** [comment]
> Topic closed, yet the issue is still persistent. When I create hexagon from cylinder, then I select all 6 top faces and and use Insert Selection, when I scale it up or down it distorts some parts of the model, even with holding ctrl and shift with res set to 1024.

Different issue, you are probably talking about https://github.com/JannisX11/blockbench/issues/1796
