### ISSUE TITLE
[Issue] Screen not loading

### ISSUE THREAD

**Issue by Gnardqu** [JannisX11/blockbench#691]
![image](https://user-images.githubusercontent.com/68906825/88663980-f21dad80-d10e-11ea-9a45-f17adf9ecca5.png)

This is the error I am facing right now I want to use the application version because its better but this bug or error happened and I dont know how to fix. I installed the application nothing less but when it opens it only shows black or white screen and even if you wait for a while it stays the same. I updated my driver, my operating system is Windows 7 64-bit and the blockbench application is updated to its fullest. Please help me with this one i tried the web version and I quickly fell in love with it.

**Comment by brickyboy09** [comment]
did you try to uninstall and reinstall?
