### ISSUE TITLE
[Issue] texture not showing

### ISSUE THREAD

**Issue by sanstheWARRIOR** [JannisX11/blockbench#692]
When I export my mod in .json format, the texture does not show and I don't know why. This appened with all the models, please can you tell me why this appens?

**Comment by JannisX11** [comment]
Since this happens outside of Blockbench, it is not a Blockbench issue. Textures not showing up can have many different reasons depending on where and how you are loading them. Please ask on the Blockbench discord server: http://discord.blockbench.net
