### ISSUE TITLE
[Issue] Texture Exporting

### ISSUE THREAD

**Issue by Maxredinfinity** [JannisX11/blockbench#694]
When i create my texture template for my mobs and export it. the .png file doesn't get created i tried searching and restarting but nothing works.

same thing happened with Java/Block Item.

**Comment by JannisX11** [comment]
Cannot reproduce the issue.

**Comment by McKushly** [comment]
This issue just started happening for me also about 2 days ago. Can't save textures for my models.

**Comment by GamerPrim572** [comment]
This same problem also started to happen to me a few days ago in blockbench (in the exe version, not the online one).

**Comment by V0pT** [comment]
I've been having the same issue. It'll save the project and export as json just fine, but the actual textures refuse to export. No error message, they just don't show up.
