### ISSUE TITLE
[Suggestion] Way to search for missing texture files

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#695]
I have this Blockbench project with over 100 textures, and when I want to save, it wants me to save everything one by one. And I have to do this every time when I switch computers, example when I want to work on my laptop.

It would be nice to have a feature to save everything to a folder, or have find missing files feature like on Blender.

**Comment by JannisX11** [comment]
I would recommend to not save the textures externally and just keep them in the bbmodel file (use Save Project because Save Model saves every file including textures).

Also, there is a way to change the textures folder for loaded textures, it's called Change Texture Location.

Hope this helps
