### ISSUE TITLE
Bedrock models bump to 1.16+ (current 1.12)

### ISSUE THREAD

**Issue by towuk118** [JannisX11/blockbench#698]
For issues, please provide the following informations:
- **config format update to 2 (1.14+ version minecraft)!!! (current version 1 [1.12])**

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant: Desktop
- Operating System: Win10 pro latest

**Comment by JannisX11** [comment]
1.12 is still the most recent iteration of the geometry format. Format version does not mean the current game version but the version in which the version of the format was introduced.
