### ISSUE TITLE
[Issue] New Tabula format isn't recognized by Blockbench

### ISSUE THREAD

**Issue by CammiePone** [JannisX11/blockbench#699]
So basically I tried importing a 1.15 Java entity model into Blockbench, and the bones showed up, but not the cubes. I then tried with a 1.12 model, and it imported the cubes, just not correctly. Everything was in the wrong place with the wrong rotations.

1.15 model:
![image](https://user-images.githubusercontent.com/16853086/89751608-ce5b4f80-da9e-11ea-8b43-f787b9638d88.png)

1.12 model:
![image](https://user-images.githubusercontent.com/16853086/89751612-d2876d00-da9e-11ea-9113-c2589bb6e1ed.png)

**Comment by JannisX11** [comment]
Would help if you could attach the model so that I could test this.

**Comment by CammiePone** [comment]
Sorry about that, wasn't sure if the modeler would be fine with posting them, but just asked and they gave the go-ahead. Here you go. Also got the bbmodel file if you need them. I went to grab the xenomorph one as well, but for some reason it imported fine for me, but not the artist, but I'll send it just in case (GitHub won't let me upload them directly, so I had to put them in a zip)
[funky models.zip](https://github.com/JannisX11/blockbench/files/5052609/funky.models.zip)

**Comment by JannisX11** [comment]
Make sure they are running the latest version of Blockbench.

**Comment by CammiePone** [comment]
We're both in 3.6.5, which is why the difference in our .java imports surprised me. According to the app and site that's the latest, but I do believe I saw something about a 3.6.6 release being out?

**Comment by JannisX11** [comment]
And I found out why your model could not be imported. It was made in Tabula with a new version that is not yet supported.

**Comment by CammiePone** [comment]
That was the case for the Dark Young, but the Black Dog was one of the oldest models for Bewitchment back when it was for 1.12 and before 1.13 came out, and I had the same problem with importing it as I did the Dark Young.

Though it's possible she updated the model sometime recently and that messed up its ability to be imported into Blockbench. Either way, thanks for looking into this, you're the best!
