### ISSUE TITLE
[Suggestions] Tooltips

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#7]
Some options are not self-explanatory, e.g. "Cullface" or "Ambient Occlusion" or just some things that need to be explained. So it would be nice if you could hover over the text and a tooltip would appear that would give a short description of what it does. Of course a way to turn it off if you already know these things would be great 😄

**Comment by JannisX11** [comment]
Implemented in Blockbench 2.0 and will be improved over the next versions.
