### ISSUE TITLE
tabula to blockbench 

### ISSUE THREAD

**Issue by Accentaur** [JannisX11/blockbench#700]
pardon me but i cant seem to open a 1.15.2 tabula model in the 1.15.2 blockbench  any suggestions
and yes i have the plug in
okay i get it the plug-in needs updated

**Comment by Hyakkii** [comment]
Maybe Tabula have different Format. Currently only Java and Optifine model that supported.

**Comment by JannisX11** [comment]
The plugin is now updated.

**Comment by Accentaur** [comment]
thanks

**Comment by Accentaur** [comment]
well thats a shame all have to be edited in tabula now before just sending them into block bench  oh well guess u cant have it do both version huh
