### ISSUE TITLE
[Sugesstion] JSon Animation Importer

### ISSUE THREAD

**Issue by MC874** [JannisX11/blockbench#702]
There's a lot of other Animation Format but the major uses for the Animation is OBJ and Json Animation

--------------JSon Animation (Non-Minecraft Format)
- Allow to Import THREE.js JSon Animation Format (or OBJ Animation if possible)
- If its impossible because of different rigs and Bones Format. Maybe add per geometry animation :
  >Its used multiple Geometry (Rotation, Size, UV and Etc) so the Geometry will change on each Frame Animation (Its possible using THREE.js Morph Animation)
  >Add convert option to convert Imported Animation Format into MoLang or Minecraft Readable Animation.

**Comment by JannisX11** [comment]
This should technically be possible, but I don't see a lot of use cases for it right now. I will probably not work on this any time soon, but if you want you can implement it a a plugin.
