### ISSUE TITLE
model won't load on blockbench

### ISSUE THREAD

**Issue by MiahDragon** [JannisX11/blockbench#709]
i have this .java model which i want to import onto blockbench so i can edit it. but even though it imports nothing shows up on the grid. 
here is the model i would like to use https://github.com/MiahDragon/DML/blob/master/src/main/java/wolfshotz/dml/client/model/DragonModel.java

**Comment by JannisX11** [comment]
Only .java models that were created in model editors such as Blockbench, Tabula, Cubik Studio etc. are supported.
