### ISSUE TITLE
[Issue] Blockbench bug or other???

### ISSUE THREAD

**Issue by guccimanezz** [JannisX11/blockbench#710]
I made a reconstruction of the geomancer skin from minecraft dungeons and decided to put it in minecraft. It worked perfectly in blockbench and everything matched, when I put it in minecraft it didn't have a necklace and beard (those are the only things I added to the skin)
![Geomancer by me](https://user-images.githubusercontent.com/69871397/90559433-e10c0d80-e19d-11ea-975c-030103fa3cc0.png)

![Screenshot_4](https://user-images.githubusercontent.com/69871397/90559446-e8cbb200-e19d-11ea-9b38-b81205e9f289.jpg)

**Comment by JannisX11** [comment]
Hi, for modeling help please use the Blockbench Discord server (http://discord.blockbench.net) and specify the Minecraft version as well as your model file.
