### ISSUE TITLE
[Feature Request] Allow custom definition of power when creating textures

### ISSUE THREAD

**Issue by Xenophilicy** [JannisX11/blockbench#718]
Hello there, I am working on a model that is too complex for a `64x64^4` (which is not currently supported by BlockBench anyway) texture but does not fit correctly on a `128x128^2` texture. 

PocketMine (my server software) requires that models (or in this case skins) be `128x128^4` or `64x64^4` and considering my model doesn't fit on a `64x64^4` texture, I would need `128x128^4`. I tried using `256x256^1` but obviously there's no way that the game will behave with a texture size that simply isn't supported (the cubes and texture mapping doesn't match up). This would allow me to make more complex models while still using `128x128^4` textures. 

Thanks in advance for your time.

**Comment by JannisX11** [comment]
I don't really understand the question or what the feature would be. You can load textures of any size into Blockbench. I am not sure what these measurements are, `64x64^4` spelled out would be `64 x 16777216`, that's about 256 megapixels, which theoretically works, but is probably way to large to conveniently edit in most image editing software.

**Comment by Xenophilicy** [comment]
I read something wrong, plus I found my own workaround, and my issue was worded incorrectly, I'm sorry for wasting time. Thanks for a great software 👍
