### ISSUE TITLE
[Issue] Some tooltips do not allign with screen resolution

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#72]
![image](https://user-images.githubusercontent.com/29360565/29871316-9fc0ce38-8d8b-11e7-9c08-e00377f68ff1.png)
![image](https://user-images.githubusercontent.com/29360565/29871328-a7fe0bf6-8d8b-11e7-851a-a1b18c29e9c8.png)
![image](https://user-images.githubusercontent.com/29360565/29871788-61dfe0e8-8d8d-11e7-96dc-ac0b270d4d11.png)
![image](https://user-images.githubusercontent.com/29360565/31586144-650c4982-b1cd-11e7-9c9d-60ec25311c83.png)

**Comment by JannisX11** [comment]
Fixed in 1.11
