### ISSUE TITLE
[Suggestion] Cem Animations

### ISSUE THREAD

**Issue by SLimeyMC** [JannisX11/blockbench#721]
New tabs for Optifine Models called Graph. Where it have a graph with calculator tabs to show the movement, then there a preview to see the movement applied to the models, It also contains a table of Constants Float, Renders parameter, Entity parameter (float and boolean), Operator, Boolean function, and Function.

Hope it gets added to the new Version.

**Comment by JannisX11** [comment]
Added into the CEM Template Loader plugin now: https://www.blockbench.net/plugins/cem_template_loader
I do not think it makes sense to implement this directly into Blockbench, and the plugin does a great job with animations.
