### ISSUE TITLE
[Suggestion] Loop Cuts for Cubes

### ISSUE THREAD

**Issue by radzo73** [JannisX11/blockbench#724]
**What?** Loop Cuts are an easy way to take a rectangular prism, and split it into two (or more) equal parts, keeping the UVs intact. (Think of Blender's Loop Cut function, but it separates the object into two objects.)

**How?** It would be a button under Edit or Transform. It would show a preview of where it will cut depending on where your mouse is. Scrolling would define how many cuts there would be (minimum one to split into two objects). Again, think of Blender's Loop Cut function.

**Why?** Convenience.

**Comment by ProNoob135** [comment]
My (limited) workflow heavily relies on loop cuts and they would speed up my modeling immensely.
As it is, I spend a lot of time copying cubes and then resizing the original and copy to add a split where I need it.
