### ISSUE TITLE
[Suggestion] Categorized actions on toolbar customization menu

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#726]
Categorize actions on toolbar customization menu to things like "Animation, Painting, Exporting, UV Editing"

This would reduce having hidden features that users are not aware of.

Also this would give the possibility to highlight / feature certain categories that are relevant to that toolbar.

**Comment by Formula350** [comment]
# +1
As a new user to Blockbench, this would be quite beneficial and helpful I think.

Could easily be as simple as indentation: 
* Major Category `[General | Editing | Painting | Animating]`
    * Minor Category `[Element | Color | Bone | etc...]`
        * Name of Tool
        * Name of Option/Setting 
        * Name of Gizmo 
        * other/etc...

Or a more user-friendly UI implementation with collapsible categories:
v Major Category `[General | Editing | Painting | Animating]`
    v Minor Category `[Element | Color | Bone | etc...]`
        * Name of Tool
        * Name of Option/Setting 
        * Name of Gizmo  
        * other/etc...

*("Tool", "Option/Setting", "Gizmo" being all the things currently visible in the list; ie "Move X", "Saturation Value", "Pivot X")*
