### ISSUE TITLE
[Issue] The installer is stuck half way for me and isn't downloading anymore. It's been at it for 3 days.

### ISSUE THREAD

**Issue by EliPro414** [JannisX11/blockbench#728]
I recently started downloading blockbench and it was going good until it got half way and then it just stopped. I let it sit for a couple of days to see if it was just being slow but it didn't download anymore.

![Blockbench Setup  9_25_2020 12_06_50 AM](https://user-images.githubusercontent.com/46505846/94316490-70050600-ff52-11ea-9e14-b2fc0ef8bca0.png)

**Comment by JannisX11** [comment]
Hello, is this your first time installing Blockbench? Or did you have it installed previously and then manually removed the installation files?

**Comment by EliPro414** [comment]
> Hello, is this your first time installing Blockbench? Or did you have it installed previously and then manually removed the installation files?

I've previously had it installed and then later deleted it. This is my second time downloading it.

**Comment by JannisX11** [comment]
Please read this thread for instructions on how to fix this: https://github.com/electron-userland/electron-builder/issues/4057

And for future reference, to delete a program properly to prevent issues like this, uninstall it from the Windows settings.

**Comment by EliPro414** [comment]
bro thx so much. Won't do that again.
