### ISSUE TITLE
Plugins not appearing

### ISSUE THREAD

**Issue by GreenFax** [JannisX11/blockbench#735]
The plugins I am installing won't appear in Filter. I installed CEM Template Loader, and that shows up. However, when I install any other plugin, it doesn't show up anywhere, and I can't use it. Even when I re-install it or reload the program.

Any idea of why this is happening and how to fix it? (When I uninstall CEM and then install another plugin, it also won't show up anywhere.)

**Comment by JannisX11** [comment]
Can you specify which plugin you are talking about?

**Comment by GreenFax** [comment]
GeckoLib Animation Utils.

**Comment by JannisX11** [comment]
To create a GeckoLib project, first select File > New > Animated Java Entity. Then you can use the tools and options the plugin provides.
