### ISSUE TITLE
[Issue] Texturing isn't working. 

### ISSUE THREAD

**Issue by SunnyCirrus** [JannisX11/blockbench#739]
To start, I'm just going to be honest. I'm not sure if this is an issue or just user error. 

Anyways, When I go under the 'Edit' tab and make a new texture, nothing shows up and the model is see-through with blue lines (In the picture.) I'm sorry if this isn't an actual problem and is just me making a mistake somewhere, but I've tried to relaunch the program and look on google for solutions but I can't find anything on it.
![no texture](https://user-images.githubusercontent.com/72773330/96208361-50527380-0f3b-11eb-967f-95f8030baac7.JPG)

**Comment by JannisX11** [comment]
From the Blockbench Discord FAQ:

*The size of cubes is floored for the UV map calculation. This means that any size smaller than 1 will result in a 0 pixel wide UV map, which will look glitchy. To prevent this make sure all of your cubes are at least 1 unit long in each direction. To create smaller cubes, use the Inflate slider.*

Depending on which format you are using, per-face UV mapping might be supported. To enable it, go to File > Project and uncheck "Box UV".
