### ISSUE TITLE
[问题]作者这软件我怎么装了显卡驱动就打不开了？？？

### ISSUE THREAD

**Issue by Stardragon-hengxiaozi** [JannisX11/blockbench#740]
一直给我报错，请问可以给我一个解决方案吗？
附图:
![image](https://user-images.githubusercontent.com/56478781/96359902-70a44d00-114a-11eb-85cb-f36794c90fa0.png)

**Comment by JannisX11** [comment]
Issues must be written in English.

**Comment by Stardragon-hengxiaozi** [comment]
Oh, I'm sorry. I asked a question for the first time. I don't know

From Baidu translator

**Comment by Stardragon-hengxiaozi** [comment]
Now I use the translation machine to tell you, if there are mistakes, I have no way, because my English is not good

From Baidu translator

**Comment by Stardragon-hengxiaozi** [comment]
[question] how can I not open the driver of the video card when I install this software?

This is the translation of the title

From Baidu translator

**Comment by Stardragon-hengxiaozi** [comment]
I will report an error as soon as I open it. Can you give me a solution?

This is content translation

From Baidu translator

**Comment by Stardragon-hengxiaozi** [comment]
I don't know what's going on

From Baidu translator
