### ISSUE TITLE
Won’t load?

### ISSUE THREAD

**Issue by crazygamerdude17** [JannisX11/blockbench#748]
I was planning on modeling something for a pack I’m making but when I went on and clicked open web app it just gave me an image that in the top left corner said “BlockBench” and had the BlockBench logo in the middle, I tried 3 different browsers, I tried on pc, I always got the same thing, can this be fixed please?

**Comment by YoshiRulz** [comment]
Same.
![Screenshot_20201026_172521](https://user-images.githubusercontent.com/13409956/97144701-a384bb80-17b0-11eb-81c2-7af561abfe08.png)
UA is `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`.

**Comment by crazygamerdude17** [comment]
> Same.
> ![Screenshot_20201026_172521](https://user-images.githubusercontent.com/13409956/97144701-a384bb80-17b0-11eb-81c2-7af561abfe08.png)
> UA is `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`.

Yea I got that exact thing, I would have sent an image but i didn’t know how lol

**Comment by JannisX11** [comment]
Try again now on the latest version

**Comment by YoshiRulz** [comment]
Works now, thanks.
