### ISSUE TITLE
[Issue] Export to Bedrock .json issue

### ISSUE THREAD

**Issue by ZeReaperDark** [JannisX11/blockbench#75]
Hello,
I have create a model based on the Vindicator (from a Bedrock .json) and I export it. But I modified the model and in same time I have delete the file that I downloaded. But now, when i wants to export to Bedrock .json it do anything so I exported to Java .json but it would don't work with Bedrock version so I ask if it's possible to convert a java .json to a Bedrock .json because I tried but I don't work :/

**Comment by JannisX11** [comment]
Yes, you can convert a block model to a bedrock entity model. Just make sure to use the right format, put everything into groups with the name of the corresponding bone and configure the north texture uv.

More Info: http://blockbench.net/docs.html#export

**Comment by ZeReaperDark** [comment]
Hello,
In wait I have redo the exact model (with the help of the java in an other widow) but I can't export the new in Bedrock version :/ I haven't import others models.

**Comment by ZeReaperDark** [comment]
I found the issue : after few tests, I have delete 12 blocks and replace them by adding relatively their color on the texture of my mob and the export work ! Even with the java model !

So the issue should be a limitation of the web version or a glitch when you add blocks to a model on the web version (even if I have increase the line limitation to 300).
