### ISSUE TITLE
[Issue] Animation keyframe ordering sorted as string rather than number

### ISSUE THREAD

**Issue by Thelonedevil** [JannisX11/blockbench#752]
When creating an animation that has a keyframe at 10 seconds or later the resulting animation json has the keyframes in the wrong order.
 
This is with BlockBench 3.7.1 with both a Bedrock Model and a GeckoLib model

Example:
```
{
	"format_version": "1.8.0",
	"animations": {
		"animation.model.new": {
			"animation_length": 10.64,
			"bones": {
				"bone": {
					"scale": {
						"0.0": [1, 1, 1],
						"10.64": [1, 1, 1],
						"5.2": [16, 16, 16]
					}
				}
			}
		}
	}
}

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench/commit/aab79b3d3202ed092c848567ec7f94b8bfa9d0eb
