### ISSUE TITLE
[Issue] Display/First person: Normal, Bow, Crossbow.  Mirrored/Incorrect position

### ISSUE THREAD

**Issue by Gixuu** [JannisX11/blockbench#760]
I set my gun in normal position like how you view first person shooter. Then I set the position for bow and crossbow in the way I want it to be and I notice that they're not on the exact same position the way I put it them. They all move whenever I move one of them it's like mirror mode. Can you fix it? : /

**Comment by JannisX11** [comment]
No, it is not possible to define separate positions for whether an item is held as a bow or crossbow. In "Display" mode, if you look at the bar that is labeled "Slot", those are all the slots that you can select. The bar below just lets you select a reference to position the model more easily.
