### ISSUE TITLE
[Issue] Blockbench icon disappears from taskbar when relaunching for an update

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#764]
Blockbench icon disappears from taskbar when relaunching for an update

Blockbench 3.7.4
Windows 10

**Comment by JannisX11** [comment]
This is caused by an electron builder issue https://github.com/electron-userland/electron-builder/issues/2514. They are working on a fix.

**Comment by JannisX11** [comment]
Should be solved in 3.8 due to electron builder update
