### ISSUE TITLE
[center view on selection] Hotkey does not exist on QWERTY keyboards

### ISSUE THREAD

**Issue by dosuserx** [JannisX11/blockbench#766]
i tried to look up what the "cross" key refers to but google came up with nothing. this "/" is what the key actually triggers this function. we call it a slash in the usa. i tried +, =, x, X and \ keys before i tried the / key. this could be more clear to americans if the symbol in question was written their instead of a regional, nonspecific name.

thank you for your time. i already love this program.

**Comment by JannisX11** [comment]
I removed the keybinding, I might have to change the way keybindings are stored in the future to improve support for special character keys.
