### ISSUE TITLE
Image Extrusion Error

### ISSUE THREAD

**Issue by CosmicjLightning** [JannisX11/blockbench#77]
Basically when I try to extrude the image in the past it worked fine. Now when I try nothing shows up, just a texture file in the corner and a group saying the name but no blocks. I thought by uninstalling and re-installing would of fixed it. If there was a way to remove the settings file, it might fix it. I'm not positive though. Any help would be appreciative.

**Comment by JannisX11** [comment]
Could you provide the texture that you are trying to convert and the Blockbench version?

**Comment by CosmicjLightning** [comment]
1.19.1 is the version and here is the images

![image](https://user-images.githubusercontent.com/28400798/30760552-e5535efc-9f97-11e7-9b9f-48ef12f79fe7.png)

![image](https://user-images.githubusercontent.com/28400798/30760566-ee47f680-9f97-11e7-908e-fa3f4c4fae74.png)

just in case links above don't work

https://imgur.com/qHIrr7P
https://imgur.com/edRBWa9

but i did find a work around. I used the ladder that I did in the past as for the models on rails and changed the image to the ones above though I had to change the ladder model as well but it worked. So no big issue. 

Also when editing some models from minecraft, in order to rotate downwards you have to rotate twice and press undo once.

**Comment by JannisX11** [comment]
Fixed in 2.2.
