### ISSUE TITLE
The filters not Works ;-;

### ISSUE THREAD

**Issue by FrangoFBI1** [JannisX11/blockbench#770]
I am trying to use the filters to create a model for my channel, but that not works! The button "filter" but not open a new filters to use

**Comment by JannisX11** [comment]
Which filter are you trying to use? Not all are available in all formats. Some are installed by specific plugins.

**Comment by cedral** [comment]
I think he might be talking about nothing dropping down when you click the filter menu
![NoFilterMenu](https://user-images.githubusercontent.com/3732140/101287766-ee362200-37b7-11eb-9be6-6b782d32b012.png)
as apposed to the transform menu which does display a menu when you click it. 
![TransformMenu](https://user-images.githubusercontent.com/3732140/101287795-30f7fa00-37b8-11eb-8fc2-32f535b3534c.png)

**Comment by JannisX11** [comment]
Yes, when the filter menu is empty because no filters are available, it doesn't spawn a dropdown menu.

**Comment by cedral** [comment]
I figured it out. you moved plugins.

**Comment by FrangoFBI1** [comment]
I've always used generate shape on my cell phone, but I'm not even
able to open the filter tab, so I'm having to open it using the file
tab. And when I managed to put the shape generator, it didn't work,
but it always worked


Em Sáb, 21 de nov de 2020 15:33, JannisX11 <notifications@github.com>
escreveu:

**Comment by FrangoFBI1** [comment]
I can acess the filter using the "archive" and going in "extensions"

Em Dom, 6 de dez de 2020 18:40, Codex Games FBI1 <frangolinnno@gmail.com>
escreveu:
