### ISSUE TITLE
Hello, I have a problem, when I click, the entity for mods, I create a model, and the version for which this entity, put Forge 1.12 or Forge 1.14 then I go to blockbench, the version is changed to Forge 1.15, and I can't upload it, this model, to other programs, since the model is on Forge 1.15. Desktop, Windows 10

### ISSUE THREAD

**Issue by Zhekca** [JannisX11/blockbench#773]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by JannisX11** [comment]
Invalid issue format

**Comment by Zhekca** [comment]
> Недопустимый формат выпуска

So, I choose my desired version and most likely the block bench resets it, then which version of blogbench does not reset the model version?

**Comment by JannisX11** [comment]
If you save it as "File" > "Save Project", it will keep the version. Exports as .java do not keep the version. Projects do keep it.
