### ISSUE TITLE
[Issue] Pivot tool movement arrows do not align correctly with rotation in Local

### ISSUE THREAD

**Issue by This-Guy-Yea** [JannisX11/blockbench#774]
^ Weird. If, in Edit mode, you go into Pivot Tool and have selected "Local", the movement arrows do not rotate accordingly. This works correctly in Move. This is particularly annoying for rotated things that have their pivot point changed in any way because you have to precisely move the pivot to exactly where you want it because that's the only way okay thanks.

I'm using Windows 8 (I didn't choose that btw, this is a family PC)

![what](https://user-images.githubusercontent.com/75096376/100390814-89334b80-3096-11eb-8547-3cd202dafff2.png)
(Picture doesn't show it, but pivot axis aligns correctly ([here](https://prnt.sc/vqtdql), arrows are from Move))

**Comment by Luizilipe** [comment]
It's the same problem for me (I use Android)

**Comment by Luizilipe** [comment]
Really, but for me this bug also occurs with the Rotate tool.

**Comment by JannisX11** [comment]
This is intended behavior since the pivot point is essentially applied before the rotation. But I will look into switching this behavior and whether that is more user friendly.
