### ISSUE TITLE
Mobile Texturing Problems.

### ISSUE THREAD

**Issue by Destroyer021620** [JannisX11/blockbench#777]
Good Day all, I have been met with an unfortunate Bug recently, where I am unable to add new textures to models, I can create new textures, or import new ones easily, but connecting that texture to the model seems to be impossible now. This issue started coming about after the new online Blockbench Mobile update. Since I use the website version of Blockbench to make my models, it is a shame that I cannot continue like I could in the past. If someone is able to get to issue I am having, I would be greatly appreciated, as my time on my pc is limited, but I can model on my phone whenever, so is much more helpful when modeling.
Thank you all in advance, and best wishes, Destroyer.

**Comment by Destroyer021620** [comment]
In addition to this problem, I have also found that typing in the numbers for translation, and the size of the parts, it will usually disregard anything you type in. Whole numbers work fine, but as soon as I put decimals, well it goes into panic mode by the looks of it, take today for instance, I wanted a cube to be 0.25 blocks from the base, so I set the value accordingly, and then the cube vanished, and when I looked at the same value again, it said 31.675 which, as you can probably assume, is a tad irritating when trying to model something. I hope that both of these can be looked at soon, and hopefully fixed. Thank you again

**Comment by JannisX11** [comment]
I cannot reproduce either of the issues.
