### ISSUE TITLE
Can we have blockbench on phone?

### ISSUE THREAD

**Issue by SnowKiteQwQ** [JannisX11/blockbench#779]
it's not so convenient for the uses don't have computer sometimes

**Comment by Destroyer021620** [comment]
Well, there isn't Blockbench for Phone per say, but if you use the online blockbench, which I use for all my models, you can use it on your mobile device. Which, to be honest isn't too hard, and isn't as difficult as you'd expect. Although the recent updates to blockbench have made it harder, with the coordinates just randomly changing, and the inability to actually texture the model anymore on mobile. Either way, I hope this helps you, especially with how convenient it is for me.
