### ISSUE TITLE
 installation error

### ISSUE THREAD

**Issue by Kortez121** [JannisX11/blockbench#781]
![Снимок](https://user-images.githubusercontent.com/76004110/102115129-2c80b080-3e4c-11eb-8775-7c12f4765443.JPG)

computer parameters.
processor AMD Phenom ii x4 b25

metric fee.
Acer WMCP 78M

Video card.
NVIDIA GeForce 9200

Ozy.
3 gb ddr 2

I am sorry for the mistakes I am writing through a translator.

**Comment by JannisX11** [comment]
Older Nvidia graphics cards are not supported. The upcoming version of Blockbench will have a workaround. You can potentially use the web app at https://web.blockbench.net

**Comment by Kortez121** [comment]
When will the new version be released?

**Comment by JannisX11** [comment]
Probably early next year
