### ISSUE TITLE
Resize option will not go into decimals

### ISSUE THREAD

**Issue by eternalbluepetya** [JannisX11/blockbench#783]
You know, I assumed this would be a very common question that could be answered easily because I thought I just didn't have some setting turned on, but nada. I have seen not a single question asking this. Whenever I try to resize a cube, even if I press shift or ctrl, the block doesn't go any more specific. Can it just... not do that? Or...

**Comment by JannisX11** [comment]
There are certain formats that don't accept floats as size values. Blockbench stops users from entering floats to prevent invalid models.
