### ISSUE TITLE
[Suggestion] Fabric Java Entity Model Export

### ISSUE THREAD

**Issue by CammiePone** [JannisX11/blockbench#784]
Pretty much as the title says, I'd love it if those of us that use Fabric could get an export option for entity models that uses Yarn mappings so we don't have to spend the time converting MCP to Yarn mappings.

If this has been asked before, I apologize, but Github's search function didn't yield any issues with this to my surprise.

**Comment by JannisX11** [comment]
There is a plugin that adds Fabric export options: File > Plugins... > Available > "Fabric Modded Entity".
