### ISSUE TITLE
Blockbench to Tabula exporter 

### ISSUE THREAD

**Issue by Jr202020** [JannisX11/blockbench#786]
A feature that allows for blockbench model to be exported back to the commonly used tabula as it already works the other way around it’s impossible to get models back to tabula

**Comment by JannisX11** [comment]
Well once you have brought models into Blockbench, you can continue to edit them in Blockbench so there is not really a need to bring them back into Tabula. I definitely won't add this to Blockbench, if anything it could be an idea for the "Mod Utils" plugin.

**Comment by ShadesOfBlueStudios-BabbyBlue** [comment]
> 
> 
> Well once you have brought models into Blockbench, you can continue to edit them in Blockbench so there is not really a need to bring them back into Tabula. I definitely won't add this to Blockbench, if anything it could be an idea for the "Mod Utils" plugin.

well some mods require tabula's model file type, like the updated hats mod.
