### ISSUE TITLE
Unexpected token in json at position 53

### ISSUE THREAD

**Issue by wooow55** [JannisX11/blockbench#787]
there is any thing wrong in position 53?

{
  "skins": [
              "geometry.ByDFFSenkoSan": {
		"texturewidth": 128,
		"textureheight": 128,
		"visible_bounds_width": 2,
		"visible_bounds_height": 3,
		"visible_bounds_offset": [0, 1.5, 0],
		"bones": [
			{
				"name": "body",
				"pivot": [0, 24, 0],
				"cubes": [
					{"origin": [-4, 12, -2], "size": [8, 12, 4], "uv": [16, 16]},
					{"origin": [-1, 22, 1.5], "size": [2, 1, 1], "uv": [39, 126]},
					{"origin": [-1.5, 19, 1.5], "size": [1, 3, 1], "uv": [41, 124]},
					{"origin": [-2, 22, 1.5], "size": [1, 1, 1], "uv": [41, 124]},
					{"origin": [-3, 21, 1.5], "size": [1, 1, 1], "uv": [41, 124]},
					{"origin": [0.5, 19, 1.5], "size": [1, 3, 1], "uv": [41, 124]},
					{"origin": [1, 22, 1.5], "size": [1, 1, 1], "uv": [41, 124]},
					{"origin": [2, 21, 1.5], "size": [1, 1, 1], "uv": [41, 124]},
					{"origin": [-1, 13, 2], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-2, 12, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 12, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 13, 3], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 13, 3], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 12, 4], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 12, 4], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 11, 3], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 11, 3], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 10, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 10, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [1, 11.5, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [1, 12.5, 3.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 13, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 13, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 14, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 14, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-1, 9, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-1, 10, 3], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-1, 12, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-1, 11, 4], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-3, 12.5, 3.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-3, 11.5, 2], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 14, 4], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 14, 4], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 13, 6], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 13, 6], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 15, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 15, 5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 14, 6], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0, 14, 6], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 16, 7.5], "size": [2, 2, 2], "uv": [98, 87]},
					{"origin": [0, 16, 8.5], "size": [2, 2, 1], "uv": [119, 87]},
					{"origin": [0, 16, 6], "size": [2, 2, 1], "uv": [112, 98]},
					{"origin": [-2, 16, 6], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-1, 14, 6.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2, 18, 7.9], "size": [2, 2, 2], "uv": [120, 80]},
					{"origin": [1, 14.5, 5.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [1, 13.5, 4.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [0.5, 15.5, 6.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-2.5, 15.5, 6.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-3, 13.5, 4.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-3, 14.5, 5.5], "size": [2, 2, 2], "uv": [82, 101]},
					{"origin": [-1, 13.5, 3], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-1, 14.5, 4], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-1, 15.5, 5], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-1, 16.5, 6], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [-1, 18.5, 7.9], "size": [2, 2, 2], "uv": [120, 80]},
					{"origin": [-1, 18.5, 7.9], "size": [2, 2, 2], "uv": [120, 80]},
					{"origin": [-0.5, 15, 7], "size": [1, 2, 2], "uv": [82, 101]},
					{"origin": [-0.3, 19, 8.5], "size": [1, 2, 2], "uv": [120, 80]},
					{"origin": [-0.7, 19, 8.5], "size": [1, 2, 2], "uv": [120, 80]},
					{"origin": [0, 18, 7], "size": [2, 1, 2], "uv": [120, 80]},
					{"origin": [0, 18.5, 7], "size": [2, 1, 2], "uv": [120, 80]},
					{"origin": [-2, 18, 7], "size": [2, 1, 2], "uv": [120, 80]},
					{"origin": [-2, 18.5, 7], "size": [2, 1, 2], "uv": [120, 80]},
					{"origin": [0, 18, 7.9], "size": [2, 2, 2], "uv": [120, 80]},
					{"origin": [-0.5, 18.7, 9.2], "size": [1, 1, 1], "uv": [123, 81]},
					{"origin": [0, 22, -2.2], "size": [1, 1, 1], "uv": [23, 54]},
					{"origin": [-1, 22, -2.2], "size": [1, 1, 1], "uv": [24, 54]},
					{"origin": [-2, 23, -2.2], "size": [1, 1, 1], "uv": [24, 54]},
					{"origin": [1, 23, -2.2], "size": [1, 1, 1], "uv": [24, 54]},
					{"origin": [2, 20, -2.1], "size": [1, 4, 1], "uv": [124, 65]},
					{"origin": [-3, 20, -2.1], "size": [1, 4, 1], "uv": [124, 65]},
					{"origin": [2, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [1, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [0, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [-1, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [-2, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [-3, 14, -2.3], "size": [1, 6, 1], "uv": [23, 23]},
					{"origin": [-5, 12, -2.5], "size": [4, 2, 1], "uv": [0, 125]},
					{"origin": [1, 12, -2.5], "size": [4, 2, 1], "uv": [0, 125]},
					{"origin": [1.5, 10.5, -4], "size": [4, 2, 1], "uv": [0, 125]},
					{"origin": [-5.5, 10.5, -4], "size": [4, 2, 1], "uv": [0, 125]},
					{"origin": [1, 10.8, -3.5], "size": [1, 2, 1], "uv": [0, 125]},
					{"origin": [-2, 10.8, -3.5], "size": [1, 2, 1], "uv": [0, 125]},
					{"origin": [4.4, 10.8, -3.5], "size": [1, 2, 1], "uv": [0, 125]},
					{"origin": [-5.4, 10.8, -3.5], "size": [1, 2, 1], "uv": [0, 125]},
					{"origin": [-1, 12, -2.4], "size": [2, 2, 1], "uv": [0, 122]},
					{"origin": [1.3, 17.3, 6.7], "size": [1, 1, 1], "uv": [104, 94], "inflate": -0.3},
					{"origin": [-1, 12, -2.4], "size": [2, 2, 1], "uv": [0, 122]},
					{"origin": [0, 16, 7.5], "size": [2, 2, 1], "uv": [111, 87]},
					{"origin": [-2, 16, 6.5], "size": [2, 2, 1], "uv": [82, 101]},
					{"origin": [1.3, 17.3, 6.8], "size": [1, 1, 1], "uv": [104, 94], "inflate": -0.3},
					{"origin": [1.3, 17.2, 6.8], "size": [1, 1, 1], "uv": [104, 94], "inflate": -0.3},
					{"origin": [1.3, 17.2, 6.7], "size": [1, 1, 1], "uv": [104, 94], "inflate": -0.3}
				]
			},

**Comment by JannisX11** [comment]
https://jsonlint.com
