### ISSUE TITLE
[Suggestion] Noise/Gradient painting

### ISSUE THREAD

**Issue by Venom-1462** [JannisX11/blockbench#789]
Noise or Gradient painting - basically this can be a checkbox on each paint mode
it basically randomizes the color that we paint but the colors are basically similar to the color we choose
the more noise value , the more will be the difference in the colors to the original color chosen
To test this you can try the noise option in planet minecraft's advanced skin painter

I must say this will be a very helpful feature in blockbench because its mostly used to make minecraft models and this would help in making textures and also kind of helpful in shading

**Comment by JannisX11** [comment]
Not planning to add this.
