### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by HEALPony** [JannisX11/blockbench#799]
Hello, Ive been currently having issues with blockbench and idk what to do. The error code says: "The application was unable to start correctly (0xc000007b). Click OK to close the application."
I have used blockbench a lot, and ive never ran into this issue until reinstalling java. My friend told me to try this different version of java and im guessing that version of it broke the application. Ive uninstalled the application and java and reinstalled one or the other to see if anything changes. Nothing. It still doesnt work even with current version of java. What do I do?

**Comment by JannisX11** [comment]
Blockbench does not depend on Java so Java installations should not directly affect it.
Try to Google the error code and you should find some guides on how to resolve it. This is a Windows issue so unfortunately I can't do much more than that.
