### ISSUE TITLE
[Suggestion] Texture string names and texture paths

### ISSUE THREAD

**Issue by Yulife** [JannisX11/blockbench#8]
1) Renaming texture strings: Blockbench defaults the name to #0 but it would be nice to edit it in the program to keep it organized when you have multiple textures. 
    Maybe adding a fifth button here with the name "Rename texture string" 
![image](https://user-images.githubusercontent.com/8559428/26946050-35e53b54-4c8e-11e7-8ca7-2c2e0f80f601.png)

2) Renaming texture paths: If you locate through explorer it still would show a missing texture in my mod (due to how it is handled via code) so it would nice to edit that inside the modeller as well. On the pic before,    maybe a sixth button called "Rename texture path" or combined with 1) in a single button.

3) Edit JSON manually button: could have several uses, checking formatting, changing numbers manually, etc. Clicking this would make the JSON appear in a popup

**Comment by JannisX11** [comment]
Added in 1.4.0
