### ISSUE TITLE
canvas not working in web app layout

### ISSUE THREAD

**Issue by gitupwithit** [JannisX11/blockbench#80]
Hello,

I am unable to see the canvas (I think) in the web app. In general, the layout seems weird. It was working fine yesterday fwiw. Is there some way to reset the layout? Thanks!

![image](https://user-images.githubusercontent.com/32688796/31413122-d8b233ba-ade5-11e7-8d27-01ed4e29f1ff.png)

![image](https://user-images.githubusercontent.com/32688796/31413137-e9c6acc6-ade5-11e7-8380-d1b8344c5572.png)

**Comment by JannisX11** [comment]
This looks like a broken css grid feature in Chrome. I don't know how to fix that but here are a few ideas:
- Reload the page with Ctrl + F5
- Enable "Swap SIdebars" in the Blockbench settings
- Reinstall Google Chrome

**Comment by gitupwithit** [comment]
Thank you! It is a work PC, I'll try your suggestions and update the bugtracker when I get back there.


I work at Toronto Public Library. We have some hour of code programs coming up, would you be ok if I do a course for kids/teens on blockbench? We don't charge fyi.


Thanks for blockbench!


-Victor


________________________________

**Comment by gitupwithit** [comment]
Thanks, tried the first 2 suggestions, no luck. I'm on a work computer so reinstalling Chrome isn't an option. If I zoom out really far I can see the canvas though!

![image](https://user-images.githubusercontent.com/32688796/31689158-93024cde-b35c-11e7-99e2-e733b8006a5c.png)
