### ISSUE TITLE
[Issue]Get “cube.parent” would cause "Maximum call stack size exceeded" 

### ISSUE THREAD

**Issue by Rayhc66** [JannisX11/blockbench#800]
try to get cube.parent in the plugins, it would cause stack size exceeded.

![image](https://user-images.githubusercontent.com/32349803/104150789-054edc00-5416-11eb-80ee-35e1030bc2db.png)

**Comment by JannisX11** [comment]
Missing context

**Comment by Rayhc66** [comment]
I tried to get cube.parent in traversing cubes in each group of Outliner.root. 
![image](https://user-images.githubusercontent.com/32349803/104263202-10f8dc00-54c4-11eb-9dfd-2aa1bc4fa184.png)
![image](https://user-images.githubusercontent.com/32349803/104263282-43a2d480-54c4-11eb-966c-cfcc81fdd107.png)
![image](https://user-images.githubusercontent.com/32349803/104263353-6a610b00-54c4-11eb-8799-0b83274d8843.png)

**Comment by JannisX11** [comment]
Are you sure the error message comes from these code snippets? Or are you trying to convert them to JSON somewhere?

**Comment by Rayhc66** [comment]
Yeah, try to export to json.

**Comment by JannisX11** [comment]
Okay that makes sense, you cannot stringify Blockbench's internal data structures directly because they may be recursive.

If you need more help, you could ask in the plugin dev channel on the Blockbench Discord server: http://discord.blockbench.net
