### ISSUE TITLE
[Suggestion] Fix: Icon of Blockbench not visible on Linux

### ISSUE THREAD

**Issue by Feefkroete** [JannisX11/blockbench#802]
I've found a mistake in the blockbench.desktop file which is located in /usr/share/applications:
While the path to the actual Icon is `/usr/share/icons/hicolor/0x0/apps/blockbench.png` the .desktop file refers to a file called "blockbench" without a path.
The correct file should be:

[Desktop Entry]
Name=Blockbench
Exec=/opt/Blockbench/blockbench %U
Terminal=false
Type=Application
Icon=/usr/share/icons/hicolor/0x0/apps/blockbench.png
StartupWMClass=Blockbench
Comment=Model editing and animation software
Categories=3DGraphics;

Would be nice if this is fixed by the developer but it's also pretty easy to fix as a user^^

**Comment by JannisX11** [comment]
Looks like the issue has been fixed in electron-builder recently (https://github.com/electron-userland/electron-builder/pull/5385).
Will wait for the new release of that package.

**Comment by Feefkroete** [comment]
Nice to hear^^
And if it's not your code messing things up it's even easier for you^^
Thanks for the effort you put into this project!

**Comment by JannisX11** [comment]
Should be solved in 3.8 due to electron builder update
