### ISSUE TITLE
Blockbench Texture Glitch

### ISSUE THREAD

**Issue by V2Playz** [JannisX11/blockbench#803]
How do I fix this texture overlay glitch?
![Untitled design](https://user-images.githubusercontent.com/68616374/104751918-9e823900-571b-11eb-9afc-15a0498bc818.png)

**Comment by JannisX11** [comment]
Z-fighting is caused by two planes occupying the same position in space, while having different textures. You can prevent this by offsetting one of the conflicting elements by a small amount.
