### ISSUE TITLE
I Can't Export Java Entity with Animations

### ISSUE THREAD

**Issue by CJoshuaHD** [JannisX11/blockbench#804]
How about, I have seen many videos about Blockbench in which when creating ¨a free model¨ they can make animations, I love that my entities can be animated, the problem comes when I want to export the identity, in the videos that I have seen it leaves them ¨ Export with Java Entity¨ but in the blockbench that I have installed I don't get any option like that.

I have tried with the plugins that the application brings but I have not been able to do anything, if you can help me I would appreciate it very much.
I have the blockbench with version 3.7.5
![hhjgjghb](https://user-images.githubusercontent.com/77566372/104834753-24f76180-5867-11eb-909d-c7a327669147.png)

![scdscfvds](https://user-images.githubusercontent.com/77566372/104834796-5ff99500-5867-11eb-993c-553126344f1f.png)

**Comment by JannisX11** [comment]
Blockbench uses different formats that can each export different file types. Generic "free" models cannot be exported to Minecraft.
If you want to use animations, you can use GeckoLib. The website explains how to use it to create models and animations: https://geckolib.com/en/latest/
