### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by iRainDropp** [JannisX11/blockbench#806]
I know this is definitely not the place whatsoever to be posting this problem but at this point I have no way of reporting it at all. I was banned from the discord server for asking for help and then a member of your Discord server jumped at my throat and was talking down to me because "I didnt use the correct channel" so we had a small little argument and then it was over. After that your helper by the name of Dragonmaster95 replied to our conversation and told me that I was the only one at fault and that I should've understood and used the help channels correctly. I explained to him how the channels are confusing as they are right under FAQ and seem as specific cannels for FAQ and he just kept arguing with me and talking down to me like I was stupid for not knowing, eventually I sent a long paragraph outlining why I didn't use the help channel and instead the general and it was bc of confusion and then he just kicked me from the Discord server. I joined back and got annoyed at him for kicking me and asked if he liked being reported, he just kept being rude to me and eventually banned me for no reason at all. I do not think this is right at all and I think this staff member should either be punished or removed. 

You can remove this issue as soon as you read it or instead you can just add me on Discord, my tag is iRainDrop#0001 and I can explain the whole thing there. Or you could even check out your audit logs/general chat logs.

Thanks in Advance ~ Austin

**Comment by JannisX11** [comment]
From what I have seen, the action fell within the discretion of that moderator. This was not about commenting on the layout of the server, but about the general tone of conversation, which we have server rules about.

And you are right, this is not the correct place for this.
