### ISSUE TITLE
[Issue] Edit Session Connection Issues

### ISSUE THREAD

**Issue by Raycka13** [JannisX11/blockbench#808]
(Forgot to set the title, it's about the session on the bedrock model creator)

When a friend come to help me make models, I create a session and send him the code. But after a time, he's disconnected but the client says that we are 2 and when he join again we are 3 in the session and he can not anymore place cube/paint/... it not showed for other. In the chat we see that the friend join/leave multiple times.
I  work in the Bedrock model creator.

![a supp2](https://user-images.githubusercontent.com/63111883/105163443-36b16100-5b14-11eb-81f3-2d538b28e3f2.png)

**Comment by Mr-Comand** [comment]
I found the problem that the website it is getting the ID from does not have a certificate. https://blckbn.ch:9000/sessions/edit_session/id
You need to go to this website: https://blckbn.ch:9000/sessions/edit_session/id and allow the certificate then it will work.
