### ISSUE TITLE
[Suggestion] Voxelize all the things like in Cubik!

### ISSUE THREAD

**Issue by Panossa** [JannisX11/blockbench#81]
I think the title says it all. Please add those cool voxelizing features Cubik has. It's the only thing my designers need to move on from there to Blockbench.

**Comment by JannisX11** [comment]
This is not the direction that I want to go in with Blockbench. There are plugins that can import voxel files and there will be updates or other plugins related to this in the future. But I won't turn it into a voxel editor.
