### ISSUE TITLE
[Issue] How can I create an entity model in Fabric

### ISSUE THREAD

**Issue by xtexChooser** [JannisX11/blockbench#819]
As the title, how can I create an entity model and use it in Fabric?

**Comment by xtexChooser** [comment]
And, I also can not install any plugins.
Desktop, Win7 32bit, 3.7.4, I am trying to download 3.7.5

**Comment by JannisX11** [comment]
There is a Fabric plugin that adds the option to export yarn mappings.

**Comment by xtexChooser** [comment]
> There is a Fabric plugin that adds the option to export yarn mappings.

But I can not add plugins.
Nothing happens after I click.

**Comment by xtexChooser** [comment]
> There is a Fabric plugin that adds the option to export yarn mappings.

![BlockBench](https://user-images.githubusercontent.com/46394906/106411488-60f20f80-6480-11eb-82c9-f78050578ec4.gif)

**Comment by xtexChooser** [comment]
I opened DevTools Console.
When I try add plugin by URL:
Refused to execute script from 'https://raw.githubusercontent.com/JannisX11/blockbench-plugins/master/plugins/modded_entity_fabric.js?_=1612150226956' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

When I try add plugin in GUI:
events.js:187 Uncaught Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201)

**Comment by xtexChooser** [comment]
I can add the plugin when I downloaded JS file

**Comment by JannisX11** [comment]
This sounds like an issue with the internet connection. Is https://www.jsdelivr.com is any way restricted or unavailable at your location?

**Comment by xtexChooser** [comment]
> This sounds like an issue with the internet connection. Is https://www.jsdelivr.com is any way restricted or unavailable at your location?

No, I can open jsdelivr.com, cdn.jsdelivr.net.
I am in China but I have the proxy in America. I tryed to disable my proxy but it also did not work.
I also can open raw.githubusercontent.com.
I think BlockBench are not using the proxy but I can open jsdelivr without proxy.

**Comment by xtexChooser** [comment]
Oops, I open the Network tab in the developer tools.
I can see error message in the Console but there are no any requests in the Network tab.
I can prove the proxy is work with BlockBench now.

I debugged in the developer tools.
The plugins are downloaded from github raw but not jsDelivr

**Comment by xtexChooser** [comment]
After I changed raw.githubusercontents.com to cdn.jsdelivr.net in the DevTools, I can add plugins successful.
