### ISSUE TITLE
[Issue] Skin preview is broken if player have Minecon 2011 Capes

### ISSUE THREAD

**Issue by barraIhsan** [JannisX11/blockbench#825]
Using blockbench version 3.7.5 Windows 10 Home

I don't know if this bug also happened to other capes, but I only find this bug appear with minecon 2011

I was changing the display skin in the `File > Preferences > Setting > Preview > Display Skin`. When I change in to any player skin that have minecon 2011 capes. Its broken.
Examples :

(AntVenom Skin, which have minecon 2011 capes)
![image](https://user-images.githubusercontent.com/57800056/107165589-eed07c00-69e5-11eb-865b-fe20ad21f645.png)
![image](https://user-images.githubusercontent.com/57800056/107165594-f859e400-69e5-11eb-9760-73654807a6ac.png)

(Xisuma Skin, which doesn't have minecon 2011 capes)
![image](https://user-images.githubusercontent.com/57800056/107165651-2808ec00-69e6-11eb-9306-255e01eebb77.png)
![image](https://user-images.githubusercontent.com/57800056/107165657-2f2ffa00-69e6-11eb-9a15-351ce7a9a3e9.png)

**Comment by JannisX11** [comment]
The old skin format that uses 64x32 images is not supported. The fact that the player is wearing a specific cape is just coincidence.
