### ISSUE TITLE
Incompatible with model loaders from forge

### ISSUE THREAD

**Issue by pythonSux** [JannisX11/blockbench#826]
When making block or item models, forge mod developers sometimes want to use special model loaders for their models. Forge provides multilayer models but there is also the possibilty for modders to make their own model loaders. When importing model jsons Blockbench should ignore model loaders entirely instead of just not loading / failing to load the model, which is what happens right now. It is really annoying since the dev has to manually remove all of the model loader stuff to edit the model, and then add the model loader to the json again after they are done editing it.

**Comment by JannisX11** [comment]
There is already a plugin to support "multilayer" models. If you want to add support for other format modifications, feel free to create a new plugin: https://documentation.blockbench.net
