### ISSUE TITLE
[Issue] Dialog file type doesn't open a window, and using multiple folder/file types in dialog only allows for input to be shown in the last folder/file box

### ISSUE THREAD

**Issue by hyperbeem** [JannisX11/blockbench#827]
issue location: desktop

## file
When using the 'file' type in a dialog, clicking on the generated box results in an error with loading a file, even though no file is select.

Console output 
![bug](https://i.imgur.com/Xu1BWwx.png)

being caused by line 172 in dialog.js, as this is not opening a file explorer to select a file, just assuming it already exists

```javascript
case 'file':
 Blockbench.import({
  resource_id: data.resource_id,
  extensions: data.extensions,
  type: data.filetype,
  startpath: data.value
 }, fileCB);
break;
```

current work around in dev build is to replace that with the following
```javascript
case 'file':
 ElecDialogs.showOpenDialog(currentwindow, {
  properties: ['openFile'],
  defaultPath: data.value
 }, (filePaths) => {
  if (filePaths) fileCB([{ path: filePaths[0] }]);
 })
break;
```

## multiple folder/file inputs
When using multiple file/folder inputs in a dialog, any value added from those is placed in the last input regardless of if clicked. This is due to it being set in the data object, but only being set in the 'input' object.
The input object is the last input of the form that contains file/folder/save (line 168 of dialog.js), thus only being displayed in the last one

```javascript
function fileCB(files) {
 data.value = files[0].path;
 // this is the last input of the form that is file/folder/save
 input.val(data.value);
 dialog.updateFormConditions()
}
```

## pulling from forms
When pulling data from forms the 'value' of an 'input#' element is being searched for (line 287 in dialog.js) and not having its value pulled from the data object itself, making the bug above more prevalent.

Although this might require rewriting this entire method to correctly support such as change.

```javascript
// fix for file/folder/save
result[form_id] = data.value
```

```javascript
	getFormResult() {
		var result = {}
		if (this.form) {
			for (var form_id in this.form) {
				var data = this.form[form_id]
				if (typeof data === 'object') {
					switch (data.type) {
						default:
                                                        // OLD: result[form_id] = data.bar.find('input#'+form_id).val()
                                                        result[form_id] = data.value
							break;
						case 'info':
							break;
						case 'textarea':
							result[form_id] = data.bar.find('textarea#'+form_id).val()
							break;
						case 'select':
							result[form_id] = data.bar.find('select#'+form_id+' > option:selected').attr('id')
							break;
						case 'radio':
							result[form_id] = data.bar.find('.form_part_radio#'+form_id+' input:checked').attr('id')
							break;
						case 'number':
							result[form_id] = Math.clamp(parseFloat(data.bar.find('input#'+form_id).val())||0, data.min, data.max)
							break;
						case 'vector':
							result[form_id] = [];
							for (var i = 0; i < (data.dimensions || 3); i++) {
								let num = Math.clamp(parseFloat(data.bar.find(`input#${form_id}_${i}`).val())||0, data.min, data.max)
								result[form_id].push(num)
							}
							break;
						case 'color':
							result[form_id] = data.colorpicker.get();
							break;
						case 'checkbox':
							result[form_id] = data.bar.find('input#'+form_id).is(':checked')
							break;
					}
				}
			}
		}
		return result;
	}
```

**Comment by JannisX11** [comment]
Hi, the first issue is not an issue, it looks like you just forgot to specify a list of extensions in the form.
I was able to reproduce the other issues.

**Comment by hyperbeem** [comment]
After you point out, I can see that the first issue is not an issue, but something I didn't read into as much as I should. However, I believe then that documentation might be at fault for that point as there is no mention of an extension option in the dialog documentation.

Ignoring that issue, issue 3 is fixed by fixing the fileCD function. 
In my dev build I fixed that by simply using the data object to access the bar to place the text in correctly. see below
```javascript
function fileCB(files) {
 data.value = files[0].path;
 data.bar[0].children.item(1).value = data.value;
 dialog.updateFormValues()
}
```
