### ISSUE TITLE
[Suggestion] Relative Auto UV auto-update

### ISSUE THREAD

**Issue by TheDoctorLink** [JannisX11/blockbench#83]
Basically, adding a checkbox (or something similar) so relative auto UV can be applied automatically when you move/resize and element, instead of having to apply it every time you change an element.

**Comment by JannisX11** [comment]
Added in 1.10.0: The auto uv toggle in the outliner now has 3 states: One for fixed uv, one for pinned auto uv (the old one) and one for relative position-sensitive auto uv.
