### ISSUE TITLE
unable to open png files

### ISSUE THREAD

**Issue by skineditor** [JannisX11/blockbench#833]
Hello, I'm a blockbench new user and I found an issue

It work perfectly and I started to make my own minecraft skin. So I wanted to make a mcpack file and to import it in minecraft, and to do that, the skin has to be in PNG file. So I rename my bbmodel file into PNG file and it worked but when I try to open the file in my computer, it says "it looks like we don't support this file format". So I wanted to know if it's an issue or if there's a way to turn bbmodel files into openable PNG ones.

thank you for helping me resolving this issue, bye

**Comment by JannisX11** [comment]
bbmodel files are Blockbench projects, PNGs are images. Just renaming them won't change that. If you want to export a skin, you need to export the texture:
![image](https://user-images.githubusercontent.com/29278436/109483384-722e3c00-7a7f-11eb-8a53-660f6e333af4.png)

**Comment by skineditor** [comment]
thank you i'll try it
