### ISSUE TITLE
[Issue] Edit session (Create session no results)

### ISSUE THREAD

**Issue by mesl** [JannisX11/blockbench#835]
![image](https://user-images.githubusercontent.com/10009454/109599485-8f184d00-7b1b-11eb-84c8-f8c273251fb1.png)

For issues, please provide the following informations:
- Detailed description of your issue

Pressing create session will not provide you with a token, it will instead throw an error telling me that it can't get a token

- Model format in which the issue occurs 
Java

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
Desktop
- Operating System
Windows10

**Comment by JannisX11** [comment]
Fixed today.

**Comment by Mr-Comand** [comment]
it doesn't work for me either:
Error:
Error in edit session: Error: Could not get an ID from the server.
    retrieveId https://web.blockbench.net/lib/peer.min.js:64
    u https://web.blockbench.net/lib/peer.min.js:64
    u https://web.blockbench.net/lib/peer.min.js:64
    u https://web.blockbench.net/lib/peer.min.js:64
edit_sessions.js:63:12
    start https://web.blockbench.net/js/edit_sessions.js:63
    emit https://web.blockbench.net/lib/peer.min.js:46
    emitError https://web.blockbench.net/lib/peer.min.js:66
    _abort https://web.blockbench.net/lib/peer.min.js:66
    i https://web.blockbench.net/lib/peer.min.js:66

**Comment by Mr-Comand** [comment]
I found the problem the website from which it gets the ID has no certificate.  https://blckbn.ch:9000/sessions/edit_session/id

**Comment by JannisX11** [comment]
Solved again

**Comment by WetFartsBeLike** [comment]
> Solved again

The certificate expired three days ago
