### ISSUE TITLE
Model Dissapearing

### ISSUE THREAD

**Issue by SpongeBobMYT** [JannisX11/blockbench#836]
Usualy when I open Blockbench it says you forgot to save or something and I can open the model but it is not saying that. and my model is not fully gone but some of it is gone. I saved it before and it's still there but the button to recover it is gone so I cant get the newest added stuff to the model and the model is realy big (sorry for the bad grammar)

**Comment by JannisX11** [comment]
If you are in the desktop app, you can go to Help > Open Backup Folder to recover your model file. If not, please make sure to save regularly.
