### ISSUE TITLE
[Issue] colour picker does not update when selecting colour from palette

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#837]
colour picker does not update when selecting palette

performed with generic model and per-face UV
1) create texture
2) go to palette tab
3) choose colour from palette
4) paint onto cube whilst still in palette tab
5) go back to colour picker and see glitch

note: colour picker seems to update to correct position if the side panel is resized

https://user-images.githubusercontent.com/38400400/109725104-8a4daa80-7ba8-11eb-9fa3-c15fc6a5843b.mp4

**Comment by JannisX11** [comment]
I had this a couple of times, but I cannot deliberatelly reproduce it.

**Comment by Magicmaan** [comment]
> I had this a couple of times, but I cannot deliberatelly reproduce it.

yeah, its next day now and I can't seem to reproduce it anymore. I restarted the app several times yesterday to verify the glitch so idk whats changed

**Comment by Magicmaan** [comment]
figured it out, should be reproduceable

1) create texture
2) go to palette tab
3) select colour and paint onto cube
4) switch back to the "Edit" tab
5) switch back to paint picker tab
6) see glitch

https://user-images.githubusercontent.com/38400400/109795627-0da1e700-7c0f-11eb-8827-8a487b4af321.mp4

i've been able to reproduce this 100% of the with restart of app and such

**Comment by JannisX11** [comment]
Thanks, glad someone finally got behind this.
