### ISSUE TITLE
[Issue] move and pivot tool has weird behaviour when parenting multiple rotated groups 

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#838]
pivot tools has weird behaviour when parenting multiple rotated groups 

performed in generic model, however have also personally witnessed in modded entity
1) layer atleast 2 groups, with bottom most group having object inside
2) rotate the group with object inside
3) go to group above that
4) set pivot mode to local
5) pivot will change orientation as if it was from the bottom most group

https://user-images.githubusercontent.com/38400400/109725903-bc134100-7ba9-11eb-8b94-9871821bb28d.mp4

**Comment by JannisX11** [comment]
This seems to be already fixed in 3.8.
