### ISSUE TITLE
[Issue] Custom Leaves model missing texture, even when referencing directly back to MC directory

### ISSUE THREAD

**Issue by theDaleighChronicle** [JannisX11/blockbench#842]
I have an old model I made with blockbench a while ago. I've tried loading it in again and updating it. It's just a few flat planes to make the leaves look fluffy, but for some reason, it won't reference to the leaf textures, and just shows a missing texture, even though I'm referencing the #all.

- Blockbench Desktop
- Windows 10

**Comment by JannisX11** [comment]
If you attach the resource pack, I can look into the issue. But you can always just re-import the texture into Blockbench.

**Comment by theDaleighChronicle** [comment]
[Chronicler Custom Models.zip](https://github.com/JannisX11/blockbench/files/6120391/Chronicler.Custom.Models.zip)

**Comment by JannisX11** [comment]
The texture files are provided by the "child" models, like "oak_leaves.json". The main leaves model doesn't really have an actual texture. You can load one in manually if you need it for reference, but in game it's handled by the parenting system.
