### ISSUE TITLE
[Issue] Making a Piglin skin has improper texture

### ISSUE THREAD

**Issue by Pythagoras-314** [JannisX11/blockbench#846]
When making a new Piglin skin, there are some things that are different compared to other mob skins or the vanilla texture. First off, the face already has eyes on it, which other mobs do not possess. Second, the ears are off to the right side, while in the vanilla texture they are right below the snout. Third, the texture is a 128x64 texture, while the vanilla texture is 64x64. This means that 1. importing a Piglin texture that is edited from the vanilla texture layout will stretch it out, and the ears will not render, as Blockbench thinks they should be off to the right side when in reality they are below the snout.

**Comment by Pythagoras-314** [comment]
I checked the most recent version of Blockbench, this has not been fixed. Maybe there could be two versions of the Piglin texture, one for Java and one for Bedrock?

**Comment by dragonmaster95** [comment]
@Pythagoras-314 It seems to look fine to me in the newest version. Tried it both with the Java default texture and the Bedrock default texture of 1.16
![image](https://user-images.githubusercontent.com/19812714/115236307-84416800-a11b-11eb-9049-688f815a0949.png)

**Comment by Pythagoras-314** [comment]
Jannis Fixed it in the latest version most likely. Imma go check myself.

**Comment by Pythagoras-314** [comment]
Just checked, Jannis did edit the model to not only fix it but also add the second layer.
