### ISSUE TITLE
[Suggestion] Improved accessability for mobile users

### ISSUE THREAD

**Issue by Snufie** [JannisX11/blockbench#848]
There are things that BB’s WebApp has that are not made for mobile users. These should probably be improved.
- Scrolling through the Outliner or Animation menu’s is not possible if the visible part of the Outliner or Animation menu is filled with objects (see picture 1). To improve this maybe a scrollbar on the left side of the Outline and the right side of the Animation menu will make scrolling much more mobile friendly (see picture 2).

**Comment by JannisX11** [comment]
This was added in 3.8 and an additional issue with scrolling through animations will be resolved in 3.8.1
