### ISSUE TITLE
[Suggestion] [Instruction?]

### ISSUE THREAD

**Issue by LCoul03** [JannisX11/blockbench#849]
Hello,

I am looking to use both 3D and 2D textures/ models within the same area.

Firstly we would like to have a single model such as a coke can which is 3D, fully textured, and custom.
When held in the right hand it would appear 3D, and as we designed it.

However, if the user looked in their inventory rather than seeing a pre-generated 3D model that is difficult to see we would like to display a nice custom-made 2D icon.

So we would like to add specifically a texture in the GUI that is only visible in the GUI.

		"gui": {
(e.g. the texture would go here and it would pull from a texture file and display over the model?)
		}

This method was used back in 1.7.9? I believe. Just wondering if there is an existing way to format the JSON to create this and if not if it was possible to create an alternative.

Thanks

**Comment by LCoul03** [comment]
In shorter terms.

The trident.
It has a 3D model, but retains a 2D icon in the GUI.

**Comment by JannisX11** [comment]
You can ask on the Blockbench Discord server which has dedicated help channels for the Minecraft formats.
http://discord.blockbench.net

**Comment by LCoul03** [comment]
Yeah,

Many people have asked. Thought I would come here as no one had the answer in that area.

Any information would be appreciated.

**Comment by JannisX11** [comment]
This issue tracker is about bugs and suggestion for Blockbench, it's definitely not about Minecraft resource packs.
