### ISSUE TITLE
BlockBench 1.9.1 for Mac?

### ISSUE THREAD

**Issue by Boundarybreaker** [JannisX11/blockbench#85]
I'm on Mac, and whenever I open Blockbench it prompts me to update to 1.9.1. However, doing that breaks the whole app, just showing raw HTML text instead of the page. Is there some issue preventing it from being updated to 1.9.1?

**Comment by JannisX11** [comment]
There is now an installer for 1.10.2. In that version you will be able to update once there is a new version.
