### ISSUE TITLE
some problem about blockbench

### ISSUE THREAD

**Issue by yhzcake** [JannisX11/blockbench#852]
when I install blockbench 3.7.*,I had installed blockbench 3.6.6 ,so there is some problem about it.
![屏幕截图 2021-03-14 202533](https://user-images.githubusercontent.com/80627671/111068369-72a8e700-8503-11eb-8444-0d8d48d27f38.png)
and I download an installer of 3.6.6 ,but it cannot work .it stop about less 50%
when i tried install a 3.6.6 after i have installed 3.8.2 ,it leave a 3.6.6 ,i can uninstall it finally.
now i have only 3.8.2

**Comment by JannisX11** [comment]
So it seems like you solved the problem by yourself?

**Comment by yhzcake** [comment]
yes , but i think it really a problem . actually i solved it when i write this issue.
it's a miracle
