### ISSUE TITLE
Issues exporting blockbench animations to glTF

### ISSUE THREAD

**Issue by ShargonHT** [JannisX11/blockbench#856]
Hi everyone,

So basically, the issue is around the eyelids of this orca.

The animation in Blockbench looks as desired:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/81093832/111911120-0f1b3e00-8a5c-11eb-9817-998a30fdd208.gif)

But at the time I export to glTF this happens, previewed in Sketchfab (see the squares on the bottom, which are the eyelids displaced):
![Orca_GIF_issue](https://user-images.githubusercontent.com/81093832/111911453-9fa64e00-8a5d-11eb-986e-9a4afd56df3f.gif)

I was wondering if this is a problem of the software or a mistake from my side.

Thanks before hand.

**Comment by JannisX11** [comment]
Fixed in 3.8.3
