### ISSUE TITLE
Windows 10 Black Screen Problem

### ISSUE THREAD

**Issue by HelpmePleaseIBeg** [JannisX11/blockbench#86]
I cant add cubes or edit anything
![aids](https://user-images.githubusercontent.com/33565809/32687134-02ee79f2-c6cf-11e7-996a-ff0599dfb690.PNG)

**Comment by JannisX11** [comment]
Press Ctrl + Shift + i and take a screenshot of the console.

**Comment by HelpmePleaseIBeg** [comment]
@JannisX11 
![2017-11-23](https://user-images.githubusercontent.com/33565809/33177169-251a1940-d07b-11e7-86fa-7041dc3bf9de.png)

**Comment by JannisX11** [comment]
Please click on "Console" in the top right corner and then take a screenshot.

**Comment by HelpmePleaseIBeg** [comment]
@JannisX11 
![2017-11-23](https://user-images.githubusercontent.com/33565809/33177348-c3294aca-d07b-11e7-91e1-d34265bc5113.png)

**Comment by JannisX11** [comment]
This is the exact same picture. I can't help you like this.

**Comment by HelpmePleaseIBeg** [comment]
Oops
![2017-11-23 1](https://user-images.githubusercontent.com/33565809/33177441-09a52b22-d07c-11e7-9747-84a4e52bae41.png)

**Comment by JannisX11** [comment]
That's better. Please scroll all the way to the top of the console so that I can see the root error messages.

**Comment by HelpmePleaseIBeg** [comment]
![2017-11-23 2](https://user-images.githubusercontent.com/33565809/33177556-7188b998-d07c-11e7-82fa-471c3cc70796.png)

**Comment by HelpmePleaseIBeg** [comment]
@JannisX11  How you figured out the problem yet?

**Comment by JannisX11** [comment]
This is an issue with your graphics drivers and with electron. Try to update your graphics drivers. If that doesn't help, you can use the web version. You can find it on http://web.blockbench.net

**Comment by HelpmePleaseIBeg** [comment]
Thanks for your help
