### ISSUE TITLE
credits breaks blockmodel file minecraft 1.16.5

### ISSUE THREAD

**Issue by h3tR3m1s** [JannisX11/blockbench#862]
Found out that the credits in the json file stop the model from getting loaded in minecraft java 1.16.5.
I suggest making it a comment instead.

**Comment by JannisX11** [comment]
Cannot reproduce this issue. Do you have a modded minecraft client maybe?

**Comment by h3tR3m1s** [comment]
I use minecraft forge 1.16.5
> Cannot reproduce this issue. Do you have a modded minecraft client maybe?

**Comment by JannisX11** [comment]
Anyways, in case you need a solution now, you can remove the credit text in the settings.
