### ISSUE TITLE
Animation Problems

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#863]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by MusicScience** [comment]
Oh

**Comment by MusicScience** [comment]
Sorry I'm new here

**Comment by JannisX11** [comment]
Well, you need to describe your issue, otherwise I cannot do anything about it.

**Comment by MusicScience** [comment]
Is this OK if I ask

I need hemp with Blockbench
If you save all animation the animation will not save, so I just save all
animations one by one
