### ISSUE TITLE
[Issue] Issue manually setting values

### ISSUE THREAD

**Issue by tyler137313** [JannisX11/blockbench#869]
I've been having an issue recently where it is very difficult to manually edit the values by clicking on the box so I can type in the number's needed. Rarely, the cursor will appear in the box and let me type but mostly it doesn't or even reset the value to 0 if I click to quickly. Is this a common issue or something that is just happening with me.

This happens with both the blockbench webapp and desktop app on windows. This also only started happening recently (past few days)

**Comment by JannisX11** [comment]
Click once to select, double click to reset the value. Hope that helps.

**Comment by tyler137313** [comment]
The problem is clicking on the box doesn't seem to register. The left-right arrows that let you drag to move the value up in down always seem to interfere with clicking on the box.

**Comment by JannisX11** [comment]
I cannot reproduce the issue. Maybe you are moving the mouse while clicking?

**Comment by tyler137313** [comment]
Well hopefully this was just temporary because I changed nothing and now I can click on the boxes like I used to be able to. So I'm not having the issue anymore
