### ISSUE TITLE
[Suggestion] Add non-cubic cubes.

### ISSUE THREAD

**Issue by vovkasolovev** [JannisX11/blockbench#870]
I would like to be able to create other 3D objects other than cubes, preserving the simplicity of working with cubes. 

I see two options for implementation:

1) Add all sorts of non-cubic cubes. Objects that fit into the bounding box of existing cubes. In this way, the mechanics of working with cubes will be preserved.

or

2) Add possibility to move object vertices along the edges and faces of the bounding box of the cube, so as not to break the plane of faces consisting of two triangles each.

This would allow making triangular prisms, pyramids, skewed parallelepipeds. It would allow you to solve the z-fighting problem by moving the points of one object onto the faces of another. It would allow making models not only from minecraft style cubes, but also in other lowpoly styles, which would make Blockbench a handy tool for any mobile games.

![blockbench-noncubes](https://user-images.githubusercontent.com/1765916/113780441-e374a500-9737-11eb-8b0a-1e4b862f1b1d.jpg)

**Comment by Pythagoras-314** [comment]
Obviously you can’t do this for any MC model, most likely only for generic models.

**Comment by MC874** [comment]
The solution is obviously using Polymesh model, since MC can also support that.

**Comment by JannisX11** [comment]
Added in 4.0.
