### ISSUE TITLE
1.7.10 Models From Java Mods aren't loading up correctly why tho?

### ISSUE THREAD

**Issue by rogeliomateo7** [JannisX11/blockbench#871]
I have issues with some of the models that are from 1.7.10 mods I don't get it how come it doesn't load up correctly help plz T_T 
![Screenshot_20210407-161216_Chrome](https://user-images.githubusercontent.com/78458081/113928204-73f4c900-97bc-11eb-93b0-e9003e927d36.jpg)

**Comment by JannisX11** [comment]
Can you attach the model?

**Comment by rogeliomateo7** [comment]
I don't think so
