### ISSUE TITLE
[Issue] Blockbench does not start correctly (0x0000007b)

### ISSUE THREAD

**Issue by joejoemars1357** [JannisX11/blockbench#876]
I am unable to start blockbench on my computer (excluding the web app) and when I try to start it, I get the error code 0x0000007b. I can't seem to find any information about the error but that doesn't surprise me anymore because I'm notoriously bad at looking for information.
![Screenshot of Error](https://user-images.githubusercontent.com/63826429/114480642-8f9b0d80-9bc8-11eb-8008-d25e1a05a4ba.png)

I'm using windows 10 and both the installed version and portable version of blockbench do not run.

**Comment by JannisX11** [comment]
Check out this guide: https://windowsreport.com/program-doesnt-start-error-0x000007b/
You can skip step 1 because Blockbench is designed to run on both archs.

**Comment by JannisX11** [comment]
Closed as likely unrelated to Blockbench itself.
