### ISSUE TITLE
[Issue] GPU error when opening Blockbench desktop

### ISSUE THREAD

**Issue by Chikorita-Lover** [JannisX11/blockbench#879]
When opening Blockbench desktop, a GPU error pop-up appears and the program will not start, no matter how much I retry. Blockbench works just fine on the web app. My operating system is Windows 10 OS Version 2009 (Build 19042.928). I attempted to ask for help in the Discord server but to no avail.

## Screenshots of errors
![image](https://user-images.githubusercontent.com/68617589/115099626-c476cf80-9efc-11eb-8d29-5ed23383cb9b.png)
![image](https://user-images.githubusercontent.com/68617589/115099692-25060c80-9efd-11eb-9597-5b6db6dcabed.png)

**Comment by JannisX11** [comment]
Did you try to update your graphics driver? Which graphics card do you use? Is this the installed or the portable version of Blockbench?

**Comment by Chikorita-Lover** [comment]
I really don't know anything about a graphics driver/card and would prefer to leave that alone. I think this is the portable version but I'm not entirely sure, how would I check?

**Comment by JannisX11** [comment]
If you start the app from the start menu / taskbar / desktop shortcut it's the installed app. If you start it from an exe file, it's portable.

**Comment by Chikorita-Lover** [comment]
Seems like it's the installed app.
