### ISSUE TITLE
[Suggestion] Photoshop-like resize options

### ISSUE THREAD

**Issue by Qapslock** [JannisX11/blockbench#887]
When modeling you often have cubes which you want to resize in 2,4 or 6 directions. An option to resize in many directions when holding a hotkey like in Photoshop would be great.

Imagine a 6x6x1 cube, you hold *hotkey* and it rescales the 6x6 axis 1 pixel into each direction to a 8x8x1 cube, so you don't have to make your cube one pixel bigger 4 times.
This could also be combinable with the shift and control resolution hotkeys

**Comment by JannisX11** [comment]
Problem is, there are no more modifier keys left.

**Comment by MC874** [comment]
What about key combination? or is it also sufficient?
