### ISSUE TITLE
[Issue] Incorrect default isometric angle

### ISSUE THREAD

**Issue by Pomik108** [JannisX11/blockbench#888]
I have found out that the default blockbench "isometric" render is not actually perfectly isometric, as explained here: https://www.blender3darchitect.com/architectural-visualization/create-true-isometric-camera-architecture/  
The default angle should be 54.736°, 0°, 45° instead of the one Blockbench is using.

Here is a visual comparison of a grass block "isometrically" rendered in Blockbench and an oak log rendered perfectly isometric in Blender:
![Snímek obrazovky 2021-04-25 v 22 57 08](https://user-images.githubusercontent.com/59484948/116141151-99e4fd80-a6d8-11eb-868b-181d562b2ce8.png)

**Comment by Heath123** [comment]
What BlockBench is rendering now seems to match with the incorrect 60°, 0°, 45° image on the site
