### ISSUE TITLE
[Issue]The first view of the model in the game can't be displayed normally

### ISSUE THREAD

**Issue by nowl233** [JannisX11/blockbench#891]
he first view of the model in the game can't be displayed normally which has never been encountered before 
The model is made by magica voxel and imported into blockbench with plug-ins. There was no problem before, but it couldn't be displayed correctly in the last month
This only happens in the first person and in the display box
`
![QQ截图20210501015523](https://user-images.githubusercontent.com/68501733/116735102-a80c8400-aa20-11eb-9df4-0b5c0e73fc24.png)
![QQ截图20210501015540](https://user-images.githubusercontent.com/68501733/116735111-a9d64780-aa20-11eb-9e1f-783edf0e5afb.png)
![QQ截图20210501015651](https://user-images.githubusercontent.com/68501733/116735113-aa6ede00-aa20-11eb-903a-f1c8e3acba04.png)
![QQ截图20210501015705](https://user-images.githubusercontent.com/68501733/116735114-ab077480-aa20-11eb-9c0a-d6cdd6152ff7.png)

`

**Comment by JannisX11** [comment]
For modeling and implementation help please ask on the Blockbench Discord server: http://discord.blockbench.net
