### ISSUE TITLE
[Issue] Broken UVs on planes when exporting model as GLTF file, but not as OBJ file

### ISSUE THREAD

**Issue by Powerbyte7** [JannisX11/blockbench#893]
I have this model which doesn't play well with the GLTF exporter, all of its planes have their UVs broken in the exported mesh file and I can't figure out a good reason why. I've been able to reproduce the issue on this model with both GLTF files and the Sketchfab exporter (Which I presume uses GLTF), but the exported OBJ file seems fine. I've viewed the resulting meshes on both Sketchfab and Blender. I've only been able to reproduce the issue on this single model though, which is rather odd.

![image](https://user-images.githubusercontent.com/40431794/117504379-a263f080-af82-11eb-913e-f24ddcb929b0.png)

![image](https://user-images.githubusercontent.com/40431794/117505008-a47a7f00-af83-11eb-9dec-95d75a8b8079.png)

[Here's the project file](https://github.com/JannisX11/blockbench/files/6444169/GLTFwithBrokenUVs.zip), I hope you'll be able to make sense of it. As it's only this single model it might not be worth prioritizing though.

Steps to reproduce:
1. Export GLTF and OBJ mesh files
2. View them in Blender or a different 3D package
3. The GLTF has partially broken UVs, but the OBJ file is fine

Blockbench Version: 3.84 (Desktop)
OS: WIndows 10
Model type: Generic model with per-face UVs
Texture size: 97x100

**Comment by iWackyMinecraft** [comment]
I think the main problem is the unusual texture size, trying 100x100 or 128x128 may give you better results
