### ISSUE TITLE
[Suggestion] Make screenshot background transparent.

### ISSUE THREAD

**Issue by cesouRED** [JannisX11/blockbench#897]
Can you make screenshot background transparent. Black background is annoying because when you try to detour image the interpolation create a black ugly outline.
Please.
![Capture d’écran 2021-05-18 124122](https://user-images.githubusercontent.com/60568418/118639067-c8d22900-b7d7-11eb-95e2-f7fa6f00325b.png)

**Comment by JannisX11** [comment]
Screenshot backgrounds are already transparent. Make sure to save the screenshot directly as a file since some image editors don't support pasting transparent images.

**Comment by cesouRED** [comment]
oops I'm sorry
