### ISSUE TITLE
[Issue] The changelog content doesn't fit in the changelog window

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#90]
The changelog doesn't fit inside its window making it impossible to read.
![image](https://user-images.githubusercontent.com/29360565/33449395-e85a908c-d608-11e7-83d6-29882f05e001.png)

**Comment by JannisX11** [comment]
I need to remember that there are people with smaller screens...

**Comment by HelpmePleaseIBeg** [comment]
It says my computer is not compatible with WebGL

**Comment by HelpmePleaseIBeg** [comment]
I assume you cant do anything abut that

**Comment by MCrafterzz** [comment]
Maybe make it scrollable? Then it would work for everyone. Just an idea

**Comment by JannisX11** [comment]
Fixed in 1.10.3
