### ISSUE TITLE
[ISSUE] Block Face Size is Sampling an Area Larger Than Intended

### ISSUE THREAD

**Issue by Formula350** [JannisX11/blockbench#901]
**- Detailed description of your issue**
    The Block Face is properly located in the Texture Map *(UV Map?)*, having the correct sizes set; however, Blockbench is applying a Horizontal and Vertical Face Size that's **+0.01** greater-than what I have set. This causes there to be a small, almost imperceptible strip of color (or transparency) to show up on the immediate edges of my blocks, that is 'bleeding-over' from the neighboring pixel's color in my texture.

Most of the time this goes unnoticed since the colors are so similar, or because of the transparency which allows you to see whatever face is behind it, but issue gets amplified in situations where you may recycle a small area of a texture face for some other unrelated block. For example I was making a 3D nose and setting the faces of those blocks right next to the solid black Eye color, which even though the Face is set to `1, 1`, it's actually sampling `1.01, 1.01` and applying that to by 1x1 block's face.

*[NOTE: GitHub and my Browser are not wanting to play well together currently, so things like using the formatting menu or the ability to edit a post do not work. I don't know if that extends to inserting/attaching images, but hopefully not.]*
Here's an example where I've taken a block (2x1 in this case) and zoomed in with Orthographic Camera enabled, to prevent clipping, then colored the neighboring pixels of my texture to an extreme color so that it makes it clearly evident. I then took another face and did similar, although it's +X side is opposite to where this is happening so that Purple line doesn't show up in this pic, but it IS there and would be present if I also applied it to the other face. (I opted not to do all three visible faces as doing that swamps out the color contrast)

As you can see, there is not only the Red from +X and Yellow from +Y bleeding over, but also that corner filled in with Black from the pixel kitty-corner to what's selected.

CAVEAT: I don't actually know if this extends into Minecraft, as I'm making a model for a friend and I lack MC to test this model/texture in game. So for all I know, it's just a Blockbench rendering issue... But, it may not be!

**- Model format in which the issue occurs**
    Bedrock Model
    64x64 Texture (made inside Blockbench)

**- Blockbench variant (Webapp/Desktop)**
    Desktop, Win10, Blockbench v3.8.4

**Comment by Formula350** [comment]
Well the upload doesn't seem to have worked, so lets try this instead? (*should* work... I hope... heh)
![Bug Report Image](https://cdn.discordapp.com/attachments/765012057807781888/846132228408082449/Blockbench_Texture_Face_Issue.png)

**Comment by Formula350** [comment]
Related to issue #599 by chance? 
The video in that one is no longer available so I couldn't watch it to really confirm or not. It sounds similar in a way, but I have no idea what they're referring to when talking about the Inventory in Blockbench *(being a year ago, I guess it's possible they're referring to something that was removed/renamed... `*shrug*`)*.

It almost sounds similar, but at the same time it sounds waaay different. heh

**Comment by JannisX11** [comment]
I cannot reproduce the issue that is shown in the screenshot. Maybe you can attach the model file to help reproduce it.

If this is an issue, it is likely not related to 599. In 599, the image in question uses an entirely different system for positioning.
