### ISSUE TITLE
[Suggestion] Spacing option in Toolbars

### ISSUE THREAD

**Issue by Formula350** [JannisX11/blockbench#902]
**- Detailed description of your issue**
Menu system does not recognize multiple Separators placed when doing Customize. 
Only one Separator is recognized in between any two points, thereby prohibiting the use of additional Separators to increase spacing.

Example:
On the "ANIMATIONS" menu, mine is as such:
Import Animation, Export Animation, Add Animation, <Animation Length>, Save All, Record GIF

I customize it to make it less likely I'll mis-click what I want, by setting it up like this (shortening names for legibility):
`Import, Export, █, █, █, Add, Length, Save All, Record GIF`
But it *turns out* like this...
`Import, Export, █ Add, Length, Save All, Record GIF`

**- Model format in which the issue occurs **
*Unrelated to modeling.*

**Comment by Formula350** [comment]
SUGGESTION:
Perhaps allow the Seperator to have a customizable width, if making it support multiple separators is problematic?

Also, an additional Separators that can `Align Left` and `Align Right`?
Example:
-Say I have `Tool 1, Tool 2, Tool 3, Tool 4, Tool 5, Tool 6` in a the Menu (lets say the one above the model display port since it's the widest)
-I want to add `Tool 7, Tool 8, Tool 9`, but they are more for my own convenience and have nothing to do with the others in the group.
-Instead of having something like literally 75 Separators applied, OR even one "Adjustable" separator like in my first suggestion, I can simply add a single "`Align Right`" separator, which will always keep any tools on the right of this separator pushed to the extreme-right of the menu box. Then unlike a fixed-width Adjustable separator, this will dynamically auto-adjust no matter what width I have the window set to, or even Blockbench's main window size.
-In the customization menu it'd then look something like this, where `▶█` represents the "Align Right" separator:
`Tool 1, Tool 2, Tool 3, Tool 4, Tool 5, Tool 6 ▶█ Tool 7, Tool 8, Tool 9`
... which would display as something like:
`Tool 1, Tool 2, Tool 3, Tool 4, Tool 5, Tool 6                           █                           Tool 7, Tool 8, Tool 9`

**Comment by Formula350** [comment]
Fudge. Well thanks Markdown Code-wrap for not preserving my spaces lol -_-
*(As I mentioned in my other issue, my browser isn't jiving with GitHub lately, preventing me from utilizing a lot of stuff such as Editing my posts... If this doesn't work, just imagine 25 spaces added to L and R of that block)*
Last line, Take 2!
```Tool 1, Tool 2, Tool 3, Tool 4, Tool 5, Tool 6                         █                         Tool 7, Tool 8, Tool 9```

**Comment by JannisX11** [comment]
Separators are not intended for spacing, that's why multiple adjacent separators collapse into one.
I'll keep this as a suggestion to add a "spacing" item for toolbars.
