### ISSUE TITLE
[Issue] Color picking on custom background freezes

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#903]
When clicking on custom background with color picker the program freezes for roughly 15-30 seconds.
![image](https://user-images.githubusercontent.com/68472867/119278982-d5e78180-bbf6-11eb-91e1-74e9fe9ec4cd.png)
- Desktop
- Windows 10

**Comment by JannisX11** [comment]
Does it still happen if you uninstall the Discord RPC plugin?

**Comment by pixelstoriez** [comment]
Yes

**Comment by JannisX11** [comment]
What is the resolution of the background image? Does it happen with all background images?

**Comment by pixelstoriez** [comment]
The resolution of the image is 9619x3093 but on smaller images (like around 600x600) it works fine

**Comment by JannisX11** [comment]
I managed to make it faster, but the main issue seems to be that the image is just really large.
