### ISSUE TITLE
[Suggestion] Relative file paths for textures in .bbmodel files

### ISSUE THREAD

**Issue by 0ffz** [JannisX11/blockbench#906]
Currently the generic model format saves texture file paths as absolute paths in the model file. This makes collaboration difficult, as the file path will be different on different machines. An option to encode models with relative file paths would be much appreciated. I believe this should be the default behaviour, but backwards compatibility should be considered.

**Comment by JannisX11** [comment]
Implemented in 73b4aec0c75d08ac2044e2866b91ae6ec26d1ec8 for release in 3.9.

**Comment by 0ffz** [comment]
Thanks a ton! Just for reference is this a setting that needs to be toggled on, or is this how all texture paths will be saved going forward?

**Comment by JannisX11** [comment]
Blockbench will always save both the absolute and relative path. If the absolute path fails on load, it will use the relative path.

**Comment by 0ffz** [comment]
That sounds good, thanks.

Though I do want to add, this may lead to unexpected behaviour when someone copies a project file and textures, and expects the copied textures to be used, when in reality the originals are and any updates they make to the new files are seemingly not reflected in the model. 

I suggest changing the order to prioritize relative paths to avoid this.
