### ISSUE TITLE
Copy and paste tool

### ISSUE THREAD

**Issue by blackstarmc** [JannisX11/blockbench#908]
Hello, I've been trying the copy paste tool, and it doesn't work (I'm in the latest version of blockbench) I would like to know if it's possible to copy and paste textures from one page to another. What I want to do is copy the head of my skin to put it on another page where I am making a Halloween variant so I don't have to reproduce the head pixel by pixel. I would welcome some help or explanation.

**Comment by PoolloverNathan** [comment]
Make a cube, apply the textures to two adjacent sides, select the first **side**, use the selection tool to select what you want to copy, and click the second **side**.
