### ISSUE TITLE
Can't make minecraft skin and load to bedrock or java

### ISSUE THREAD

**Issue by LittleLightz** [JannisX11/blockbench#909]
Hi there, so, I have made a skin. I have made a skin in the skin creator on block bench. I have worked with the https://www.chronicoverride.com/ support team, on discord. and we don't know if it is an issue on your end or theirs
we know its not probably an issue o their end, but maybe with yours
I made the skin, and it won't load with their loader, but I made a test skin with planet Minecraft HD, and it worked with loading. I also tried loading following this video . [](https://www.youtube.com/watch?v=tH4DkOMfYu8&list=PLMtgDbP-W0-kkstSFrpAYg4k6QERuDiRl)
This video I followed, but had trouble with the downloading of the notepad files
(got installer by following link in the video)
How do I make my skin from your blockbench work? I know that the system 
Chronicoverride uses for uploading skins work, but not with blockbench. how do you suppose I upload skins from your blockbench... I am not sure if I can or not.
please help me, so I can upload from block bench. I would love to upload from  block bench, but I don't know if your system is working or now
*not
please help

- BlockbenchDesktop
- windows 10 for MSI GE66 Raider

**Comment by JannisX11** [comment]
In order to use Minecraft skins, create a skin, then go to File > Export > Export Minecraft Skin. Then select it in the Minecraft Java launcher or in the wardrobe in Bedrock.

**Comment by LittleLightz** [comment]
> In order to use Minecraft skins, create a skin, then go to File > Export > Export Minecraft Skin. Then select the PNG file it in the Minecraft Java launcher or in the wardrobe in Bedrock.

I did that, it says its not a Minecraft skin,

**Comment by LittleLightz** [comment]
I used a hd skin, and it did not work

**Comment by LittleLightz** [comment]
I did that, but it did not work (I used the 124x skin . It wont work
