### ISSUE TITLE
Absolute paths are bad

### ISSUE THREAD

**Issue by Darwin1546** [JannisX11/blockbench#913]
**Problem:**
Currently BB tries to load texture from folder, that is attached to this texture and skipping texture, that is stored in bb model file. And this is so wrong.
Situation: my modeller sends me new version of model, i see this:
<img src="https://user-images.githubusercontent.com/63585283/121393682-2d217c00-c983-11eb-896f-3a708211a95f.png" width="300">
And i have to delete old texture file from folder to see this:
<img src="https://user-images.githubusercontent.com/63585283/121394576-0fa0e200-c984-11eb-9777-4db6c72cf260.png" width="300">

Exact same bbmodel file, but i removed the file
![изображение](https://user-images.githubusercontent.com/63585283/121394811-50006000-c984-11eb-9a7b-71a773b7db1a.png)

**Solution:**
We should be able to strip that useless absolute path information from bbmodel file or just ignore it somehow.
And why do we even need that absolute paths?

**Comment by JannisX11** [comment]
Blockbench 3.9.1 prioritizes relative paths over absolute paths.
