### ISSUE TITLE
[Suggestion]Open .json file by double click the desktop files or right click and open

### ISSUE THREAD

**Issue by XiLaiTL** [JannisX11/blockbench#914]
In early vision, Blockbench can open .json files in the Explorer of windows, so I associated the .json files with Blockbench and when I double click the .json files, it opens as soon as renders the models.
However, the 3.8.4 Blockbench can't open files in these way but need users firstly open Blockbench and secondly open files in Blockbench menus. If you just right click the .json files in Explorer and choose Blockbench to open, it would not truly open the models but just open Blockbench.
I think it will be convenient as the way of opening files can be added again.

By the way, I had thought and have tried to work on making the Blockbench the vscode plugins, as it will be convenient for models makers to manager the models, by just opening the Blockbench in the vscode. However, I am so unskilled about the framework of vscode plugins and blockbench. In my early work, I suppose to add the Blockbench web in the vscode and open it in vscode as both wirtten in electron, but I am failed. Yet, it is exactly possible!
If you have time, I think it is a great way. Or adding the files manager is also a probably way.

- Model format in which the issue occurs .json( java model ) 
- Blockbench variant: Desktop
- Operating System: Windows 10

**Comment by JannisX11** [comment]
Opening any files via right click and Open With is supported and works fine for me.

**Comment by XiLaiTL** [comment]
Oh, I delete the files under the AppData/Roaming/blochbench and now it works!

By the way, if you have time to write blockbench as a plugin of vscode, it will be very nice!

**Comment by JannisX11** [comment]
I think Blockbench is too complex to work as a VSCode extension.

**Comment by XiLaiTL** [comment]
Yeah! But as it can be work as a webapp, I think it is possible to work on vscode. In my last try, I just use the web browser of vscode to run blockbench.

**Comment by XiLaiTL** [comment]
Yeah! But as it can be work as a webapp, I think it is possible to work on vscode. In my last try, I just use the web browser of vscode to run blockbench.
