### ISSUE TITLE
[Issue] Zoom does not work at all.

### ISSUE THREAD

**Issue by cole00cole00** [JannisX11/blockbench#916]
I could not find this issue in all that I scrolled through.

I am using the desktop app - only downloaded it yesterday. I have windows 7.

I started and have loaded in other models fro bedrock entities and I can't get any zoom to work, not with reassigning hot keys nor buttons added to toolbar. I thought I's just work bigger then shrink when needed but the scaling makes a mess of even basic player model with I try make it much smaller.
![image](https://user-images.githubusercontent.com/73656869/122014017-15724980-ce02-11eb-8681-56c19e4b7377.png)

**Comment by cole00cole00** [comment]
Tested web version same issue - so opened web version on my phone - it lets me pinch zoom but still the zoom buttons do nothing.

**Comment by JannisX11** [comment]
The zoom buttoms currently only control the UV editor. They will also work for the 3D preview and the timeline in the upcoming update 3.9.

**Comment by vinnyg0621** [comment]
I was trying to scale my model in a Minecraft item frame, but then I couldn't scroll down to the 3rd scale!!

**Comment by JannisX11** [comment]
Zoom buttons now work for the 3D preview and timeline in 3.9.

**Comment by JannisX11** [comment]
> I was trying to scale my model in a Minecraft item frame, but then I couldn't scroll down to the 3rd scale!!

You should be able to scroll down by touching on the text labels. If you are still having problems with this, please open a separate issue.

**Comment by kokoduckie** [comment]
I have same issue but with web
