### ISSUE TITLE
Import extruded texture not working 

### ISSUE THREAD

**Issue by GBV1436** [JannisX11/blockbench#918]
[Issue]
Import extruded texture function not working on Blockbench v3.8.4.  Trying to import a 16x16 px png so that I can resize and reposition it.  Thanks
![Screen Shot 2021-06-16 at 8 58 43 p m](https://user-images.githubusercontent.com/52811577/122223737-0a90e500-cee6-11eb-8ff4-1bff5305b72d.png)

**Comment by JannisX11** [comment]
Please include the format you are working in, the texture file you are trying to import, and describe what happens instead.

**Comment by GBV1436** [comment]
Hi JannisX11, not sure what you mean by what format, but attaching the texture file now.  
![banana](https://user-images.githubusercontent.com/52811577/122323686-10281280-cf5a-11eb-8c62-0e2aa4e8e6e7.png)

I'm not sure if this helps, but I'm on a Mac with High Sierra 10.13.6.  When I import, it comes up with the texture (attaching screen capture) but when I click scan and import, it just goes back to the New/Recent screen.  Is there something I'm doing wrong?
![BB import extrude image scan screen](https://user-images.githubusercontent.com/52811577/122324220-04891b80-cf5b-11eb-9698-6a32177a96bc.png)
![BB new-recent screen](https://user-images.githubusercontent.com/52811577/122324265-17035500-cf5b-11eb-8d24-504bb481d570.png)

**Comment by JannisX11** [comment]
You need to create a new project by selecting one of the formats on the start screen. After that, you can import. I will make sure to communicate this more clearly in a future update.

**Comment by GBV1436** [comment]
Oh, okay will try that.  Thanks heaps for sharing your app.  I’d heard
about it a couple of years ago but when I finally tried it, found how
amazing it is.
Cheers
gbv1436
