### ISSUE TITLE
I hope the tagged color of animation frame could be saved，they will dispear every time I restart the project.Thanks!

### ISSUE THREAD

**Issue by purpleeyedboy** [JannisX11/blockbench#919]
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System
![image](https://user-images.githubusercontent.com/37564087/122513502-0fb47800-d03d-11eb-8acc-b35a25a10f29.png)

**Comment by JannisX11** [comment]
Minecraft Bedrock animation files do not and cannot store color information. If oyu want to keep the colors, save your project via File > Save Project.
