### ISSUE TITLE
Install plugins not working

### ISSUE THREAD

**Issue by ihakukyou** [JannisX11/blockbench#921]
When I click on install buttons of File-Plugins nothing happens

- Blockbench variant Desktop version 3.8.4
- Operating System Windows10

**Comment by JannisX11** [comment]
Which plugin cannot be installed, specifically? Or does this affect all plugins?
Also, please attach a screenshot of the Blockbench console. You can open the console by going to Help > Developer > Open Dev Tools and switching to the Console tab. Red messages are relevant.

**Comment by JoshiWorld** [comment]
jquery.js:2 GET file:///C:/Users/User?_=1633261900351 net::ERR_FILE_NOT_FOUND
send @ jquery.js:2
ajax @ jquery.js:2
S.<computed> @ jquery.js:2
getScript @ jquery.js:2
(anonymous) @ plugin_loader.js:73
install @ plugin_loader.js:72
(anonymous) @ plugin_loader.js:118
setTimeout (async)
(anonymous) @ plugin_loader.js:117
emit @ events.js:327
endReadableNT @ internal/streams/readable.js:1327
processTicksAndRejections @ internal/process/task_queues.js:80
plugin_loader.js:120 Uncaught (in promise) undefined
