### ISSUE TITLE
No build for M1 Macs

### ISSUE THREAD

**Issue by cbyrneee** [JannisX11/blockbench#923]
**Detailed description of your issue**: 
Currently, blockbench is an Intel based application meaning that it requires to be run under rosetta 2 emulation. This isn't ideal as rosetta 2 can cause extra battery drain in my experience. It would be ideal if it was packaged as a "universal" application containing both an Intel version and M1 version. Electron 11 adds support for this, more information can be found [here](https://www.electronjs.org/blog/apple-silicon).

Blockbench does launch under rosetta 2 emulation, but it would be ideal for all users if a native version was available.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/71222289/123007146-9dcb8e00-d3b0-11eb-8fef-14a0d54b0385.png">

**Model format in which the issue occurs**: n/a

**For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations:** 
- Blockbench variant (Webapp/Desktop): Desktop
- Operating System: macOS 11.4, MacBook Air 2020 M1

**Comment by JannisX11** [comment]
Added in 3.9.
