### ISSUE TITLE
[Issue] [Beta] Selecting Default keymaps on "Keybind Preference" menu does not work

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#925]
Selecting Default keymaps on "Keybind Preference" menu does not work

![image](https://user-images.githubusercontent.com/44243757/123243639-e3d93c80-d4eb-11eb-8438-450a04c96719.png)

How to reproduce issue:
- Select some other keymap (for example blender)
- Select one of the Default keymaps
- No confirmation message, except the blockbench success one

**Comment by JannisX11** [comment]
Selecting a keymap will now close the menu on the start screen, so this won't be an issue.
The idea is that when users update to this version, but they already have some keybindings defined, they can just swotch to the Default (Mouse) to change the viewport controls but leave their other controls untouched.
Selecting a keymap from the keybindings menu will change all keybindings.
