### ISSUE TITLE
[Suggestion] Save previous gif recording options during session

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#928]
Save previous gif recording options during session.
Its often very likely that I need to re-take a gif and need to re-enter all options again

**Comment by MidNite00** [comment]
I work with a team and take 5-10 gifs a day sometimes, having this feature would be immensely helpful. Bonus points for the ability to save the angle/camera placement you were at in the last GIF taken as well for exact comparison shots.
