### ISSUE TITLE
[Issue] The button "Origin to Geometry" does not work at all

### ISSUE THREAD

**Issue by Henrique3310** [JannisX11/blockbench#93]
**Issue Description:**

The button "Origin to Geometry" does not work. When clicked, it moves both the element and the origin in a very unpredictable way, moving both to an almost seemingly random place.

Before clicking the button:

![image](https://user-images.githubusercontent.com/5795764/33960779-f411ebee-e032-11e7-9575-6b1db9deac77.png)

Expected behavior (the origin moves to where the element is located):

![image](https://user-images.githubusercontent.com/5795764/33960858-39206c60-e033-11e7-860e-d12d199a3dc6.png)

What actually happened (both move to a seemingly random location):

![image](https://user-images.githubusercontent.com/5795764/33960898-525fb67c-e033-11e7-8c2e-6e9bbbba0b02.png)

**Blockbench Variant:**

Desktop

**Operating System:**

Windows 10

**Comment by JannisX11** [comment]
This was wanted behavior that makes sense with the way the model format works. But it will be changed in the next update to match the behavior the majority of users would expect.

**Comment by JannisX11** [comment]
Fixed in 1.10.3
