### ISSUE TITLE
[Issue] Cannot open or edit .tga files from blockbench

### ISSUE THREAD

**Issue by Wackyblocks** [JannisX11/blockbench#932]
Cannot open or edit .tga files from blockbench

![image](https://user-images.githubusercontent.com/44243757/123253534-41728680-d4f6-11eb-9727-15d61b0b6990.png)

![image](https://user-images.githubusercontent.com/44243757/123253559-49cac180-d4f6-11eb-924b-8cd3d95a0efb.png)

Blockbench beta3.9-1

**Comment by JannisX11** [comment]
This is because TGA files are not fully supported, they can only be imported. Works as intended.
