### ISSUE TITLE
[Issue] Exporting (any) Model to glTF Format does not attach any Material

### ISSUE THREAD

**Issue by yanasakana** [JannisX11/blockbench#941]
In the latest version, `3.9.0`, exporting any model format to a glTF file does not work as intended when loaded in Blender. Prior to the update, exporting would attach a material properly. This is no longer the case.

 Left `3.9.0`, Right `3.8.4`
![image](https://user-images.githubusercontent.com/85486781/123630512-7a4a7e00-d7ca-11eb-8b1e-9f610619c29f.png)

**Comment by uItimatech** [comment]
I think I have a similar problem when exporting on sketchfab, the export might use glTF too.
