### ISSUE TITLE
3d modeling textures help [pink and black ]

### ISSUE THREAD

**Issue by KhrisMarin** [JannisX11/blockbench#942]
hello good I need to report a bug about the texture since I want to make several mods of weapons and 3d tools but when exporting it to Mcreator the texture comes out in purple and black and I have made the model more than 10 times and it still looks bugeado some solution since I did not find anything useful on the internet ...

**Comment by JannisX11** [comment]
For modeling help, please use the Blockbench Discord server: http://discord.blockbench.net
