### ISSUE TITLE
Bb Error in Android Even In Browser

### ISSUE THREAD

**Issue by DevCliq511** [JannisX11/blockbench#947]
I Cant Open Blockbench In Android But Still I Have Strong Internet Connection but it says "an error occured while loading blockbench in web app even in Browser.
My Device Model:Smasung SM-G530H
Android Version: 4.4.4
Im Hoping It Will Been Fixed...

[Blockbench](web.blockbench.net) 
![Screenshot_2021-06-30-21-07-54-1](https://user-images.githubusercontent.com/86767312/124093082-181fa080-da8a-11eb-8f6d-9a692b906c41.png)

**Comment by JannisX11** [comment]
You should now be able to see a more precise error message when trying to open Blockbench. Please post another screenshot of the error message.

**Comment by JannisX11** [comment]
Fixed
