### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by Yashaku** [JannisX11/blockbench#95]
Hi I'm new to all this I made mobs and saved them like the videos and they work awesome, but when I make a item I have no clue how to import it into the (Vanilla_Resource_Pack) I don't see a nice option like mobs when I click blocks nothing happens. can anyone help me import my 3D items into Minecraft I'm also using windows 10 edition beta. I guess this is a addon whatever that is, if no one knows that's ok I can still work on the mobs and replace what is under the mobs file mobs are still better then nothing :)

**Comment by JannisX11** [comment]
Hey,
It is not possible to change the model of items in Windows 10 Edition of Minecraft. It is only possible in Java Edition.

**Comment by Yashaku** [comment]
hello jannis thanks for your reply, is this something that's permanent or something you can fix in the future or is this on their end?

**Comment by JannisX11** [comment]
Item models is something that can't be modified right now. But I assume that Mojang will be adding those at some point. And when they do, Blockbench will be able to create those models of course.

**Comment by Yashaku** [comment]
Cool thanks! I'm happy to know its something that can be fixed I'm going to keep using this program to make mobs, this is my first mob I've ever made in 3D I made the Multicandy mod back in the day and trishtrum castle texture pack so this is a good new fun experience for me now that VR works with Minecraft. this is my first mob thought I would show you guys. thanks again for the quick reply

(Shulker) His Mouth Opens Looks Awesome! 

![02](https://user-images.githubusercontent.com/35162864/34644601-94791f42-f331-11e7-9637-76ae6b86bfc4.png)

![01](https://user-images.githubusercontent.com/35162864/34644615-c5f31258-f331-11e7-9f52-5c095a1e553a.png)
