### ISSUE TITLE
Latest update 3.9.1 massive FPS drop 

### ISSUE THREAD

**Issue by CrepiCZ** [JannisX11/blockbench#950]
Hello, i am Crepi
BB downloaded new update 3.9.1 and i can't do stuffs. from 60-90 fps i have now 1-2fps
I tried turn off shading etc but i get only 16 fps. I tried install another older version back and working good on 60 fps but i dont want outdate blockbench. please help me fix or just say if is there update around performances thank you

If u need my pc info:
Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz   2.00 GHz
6,00 GB
64 bit operation system windows 10 home latest
ATI RADEON HD 4600 SERIES

i know its bad pc setup but BB worked normal

**Comment by CrepiCZ** [comment]
okay im not alone another creators have same issue thats positive for me

**Comment by JannisX11** [comment]
Hi, for me personally, the update actually slightly improved performance.
Here are a few things you can do to help me figure out your issue:

* Open the Task Manager and check if Blockbench has a particularly high CPU or GPU usage. You can also send a screenshot of the app process list.
* Check if any other apps are open that could be graphics intensive (e. G. a game).
* Restart your computer, test Blockbench while no other windows are open.
* Do you have any plugins installed? If you have the "Ambient Occlusion" plugin installed, uninstall it.
* In the Blockbench settings, disable "Hardware Acceletation" and let me know if this improves performance.

**Comment by CrepiCZ** [comment]
I tested close everything and wha i know without ambient occlusion now running on 20 fps and web version running on 60 fps
