### ISSUE TITLE
Issue Disappearing Project. 

### ISSUE THREAD

**Issue by DragonDrew1** [JannisX11/blockbench#951]
Randomly while I am working Blockbench freeze's and the project disappears from the screen I have to save the project close that window and reopen the window to get the project to appear again but it happens very frequently.

**Comment by JannisX11** [comment]
Please provide the following information:

* A screenshot of the project disappearing
* Your Blockbench version
* Your Blockbench variant (app / desktop) and operating system (+browser)

**Comment by DragonDrew1** [comment]
![image](https://user-images.githubusercontent.com/86226013/124736677-3bf94100-dee5-11eb-9018-f21499dac755.png)
![image](https://user-images.githubusercontent.com/86226013/124736708-44ea1280-dee5-11eb-9882-ed3c7296c79c.png)
I am using version 3.9 and am using it on Windows 10 and have it downloaded as a application Thank you for your time.
