### ISSUE TITLE
[Suggestion] a sculpting tool that allows you to "chip" single cubes off the model, similar to breaking a block in Mjinecraft

### ISSUE THREAD

**Issue by frostycircle** [JannisX11/blockbench#958]
I'm an amateur so I don't know how useful this would be for professional modelers, but it could be useful for quickly/easily making fine details. The opposite could also be added, allowing you to place single cubes. Suggestions and constructive criticism are welcome.

**Comment by JannisX11** [comment]
What you are looking for is a voxel editor, for example [MagicaVoxel](https://ephtracy.github.io).
This isn't within the scope of Blockbench.
