### ISSUE TITLE
[Issue] Unlimited/Bedrock wrong UV

### ISSUE THREAD

**Issue by ZeReaperDark** [JannisX11/blockbench#96]
Hello, I'm using Blockbench Webapp, my computer is a Windows 10.

I made an entity model for Bedrock Edition so I activate the 'Entity Model Mode' setting but while this setting is activate, the UV panel doesn't let me modify the size of each face and don't even separate the faces, they keep in one square like a group. When I disactivate the setting I can edit the UV 'normally' (like I was abble few mouths ago with the setting activated).

So : I can't really edit the UV, just move it :/

**With the setting activate :**
![blockbenchuvissue](https://user-images.githubusercontent.com/31507591/34643113-fdf20f64-f31e-11e7-9d51-e87fe1916adc.PNG)

**With the setting disactivate :**
![blockbenchuvissueout](https://user-images.githubusercontent.com/31507591/34643117-04120318-f31f-11e7-921c-7a0e1f227deb.PNG)

  Thanks you for riding and I hope it could be fix soon.

ZeReaper

**Comment by JannisX11** [comment]
This is the way the Windows 10 Edition modeling system works. If you need help with it, I suggest to watch this tutorial: https://www.youtube.com/watch?v=UNaxVrYbas8&t=998s

**Comment by ZeReaperDark** [comment]
Ok, I will look at the tutorial. Thank you for your answer and for these free software and webapp :)
