### ISSUE TITLE
[Issue] Error while creating texture

### ISSUE THREAD

**Issue by luaduffy** [JannisX11/blockbench#961]
My problem is that when I want to create a texture using a template, I get this error and some parts of the model are transparent.
An error is thrown when resizing a cube using Shift, p.s.: I think so
p.s. 2: Bedrock legacy model

![Screenshot_4](https://user-images.githubusercontent.com/87409976/125570355-68fbed23-9364-4399-b3ad-a99c8e14ee2e.png)

**Comment by dragonmaster95** [comment]
@luadaffy Not a bug and the error tells you exactl what is going on.
The box-uv format (which is mandatory for the bedrock **legacy** model format) creates UVs based on the size of the cuboids. When doing so it always rounds down (so a 2x2 wide face gets a 2x2 area, a 0.5x2 gets a 0x2 area). And you cannot texture something that is 0 wide.

If your situation allows it I'd suggest switching to the new Bedrock Model format (The one that doesn't say "legacy") and switch to per-face uv in File > Project.
