### ISSUE TITLE
[Issue] I could not install plugins.

### ISSUE THREAD

**Issue by xtexChooser** [JannisX11/blockbench#962]
Desktop, Windows10 64bits

I tryed to install plugins from the file or the URL. It was sucessful. But when I restarted blockbench, the plugins are all removed.

I can not install directly in blockbench because https://github.com/JannisX11/blockbench/issues/819

**Comment by xtexChooser** [comment]
https://user-images.githubusercontent.com/46394906/125597339-38eec43c-c67e-4b0a-ab67-890d9a1543e7.mp4

**Comment by panzhenjian** [comment]
我也安装不了插件

**Comment by JannisX11** [comment]
Fixed in 3.9.3
