### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Eainai** [JannisX11/blockbench#963]
Whenever I import a texture to a Minecraft Java block model (in this case, a 128 by 16) that is larger than 16 by 16, it always shows the first 16 by 16 chunk of the texture, but not the rest. However, the block itself looks like the entire texture was stretched over it.
![Screenshot of what it looks like](https://user-images.githubusercontent.com/79539652/125693787-fd58902e-fbc4-4b7f-b7a9-00e33e90c9aa.png)
![Screenshot of console](https://user-images.githubusercontent.com/79539652/125693789-62ee27ce-9d52-467f-b9ad-df2266c93b29.png)

**Comment by dragonmaster95** [comment]
@Eainai set your project resolution to the same ratio as the texture resolution and it should render fine

**Comment by Eainai** [comment]
Thank you! It works perfectly now!
