### ISSUE TITLE
[Issue] Adding hide sidebars button to top 'toolbar' causes TypeError on next open

### ISSUE THREAD

**Issue by GMRoar** [JannisX11/blockbench#964]
Blockbench Desktop Version 3.9.2
Windows 10 Home 21H1 19043.1110

Adding the 'hide sidebars' button to the top editor tool bar causes the program to throw a TypeError on next start, due to a condition statement in actions.js at line 1596.

![image](https://user-images.githubusercontent.com/42854435/125752472-da15d9fb-cd93-4207-8b7a-c954a001e477.png)

![image](https://user-images.githubusercontent.com/42854435/125752736-9d7c0486-9eed-4f1f-9aee-f4de9437da2a.png)

**Comment by dragonmaster95** [comment]
A quick and dirty fix for anyone encountering the issue (until it gets officially fixed) is to reset the toolbars by using
`localStorage.setItem("toolbars","")` 
in the Console. After that reload Blockbench and you should be able to start Blockbench again.
