### ISSUE TITLE
[Issue] smoothed key frames only having post and not pre values in bedrock animations

### ISSUE THREAD

**Issue by RubyJam** [JannisX11/blockbench#967]
When saving an animation from a bedrock model format any smoothed key frames in my animation output the post and lerp mode information for the key frame but misses the pre line that is required for the key frame to be smooth in game

at least in my experience i haven't needed the pre and post lines to be any different and just leads to a lot of manual copying in my animations

if i remember correctly the first implementation of the smooth key frames into blockbench exported the animations out correctly with both pre and post information but since then is no longer exporting the pre for me

**Comment by JannisX11** [comment]
Smooth / Catmull rom keyframes only use the "post" value. The "pre" value is ignored by Minecraft Bedrock Edition.

**Comment by StuartDA** [comment]
Hello, this is still an Issue? 
If you put in the "Pre" values via a TextEditor they function fine and are not ignored by MC: BE.
Can this be looked into being added back in, please?

**Comment by JannisX11** [comment]
As explained above, catmull rom based curves only use "post" in the JSON structure, the "pre" value is inconsequential. If you need a discontinuous animation, use linear keyframes.
