### ISSUE TITLE
[Issue] Item darker in GUI and flickering in hand/item frame

### ISSUE THREAD

**Issue by Toma400** [JannisX11/blockbench#968]
Items exported as .json models are showing darker in Minecraft GUI, and also in some cases they are flickering while in hand/in item frame.

Tried to turn off ambient occlusion, Front Light setting in GUI and edit the code to add/remove light-related code, but the result is still changing nothing.

Uploading screenshot with Handmade Revolver darker in GUI and two Blockbench files (Handmade Revolver is only darker, Short Revolver is darker and flickering). JSON files are separately added.

![revolv_bug](https://user-images.githubusercontent.com/65849429/125906943-7e2087ef-242a-4ffa-b042-f5ea8c25fe4d.png)
[Models.zip](https://github.com/JannisX11/blockbench/files/6828575/Models.zip)
[JSON files.zip](https://github.com/JannisX11/blockbench/files/6828583/JSON.files.zip)

**Comment by Toma400** [comment]
Also found out that my weapon has weird transparency when held in main hand ;-; not sure if it's related, but I don't wanna spam with issues too much.
[Sandy_Wanderer.zip](https://github.com/JannisX11/blockbench/files/6835219/Sandy_Wanderer.zip)

![bug_1](https://user-images.githubusercontent.com/65849429/126047931-700da991-faff-470a-964a-a2fe45a4e1ca.png)
![bug_2](https://user-images.githubusercontent.com/65849429/126047935-d6871325-3d50-4baa-b5fd-0938f8a6b1e6.png)

**Comment by dragonmaster95** [comment]
> Also found out that my weapon has weird transparency when held in main hand ;-; not sure if it's related, but I don't wanna spam with issues too much.

that happens if you use the "mirror" toggles in the display settings in 1.15 or newer (because items used to render faces inside and outside, so inverting them mirrored them, but as of 1.15 it literally turns them inside-out)

**Comment by Toma400** [comment]
> > Also found out that my weapon has weird transparency when held in main hand ;-; not sure if it's related, but I don't wanna spam with issues too much.
> 
> that happens if you use the "mirror" toggles in the display settings in 1.15 or newer (because items used to render faces inside and outside, so inverting them mirrored them, but as of 1.15 it literally turns them inside-out)

Ah, I see. What's weird though, I use mirror for each model, but they are showing that only from time to time, not constantly.
And even more weirdly, previously correctly rendering models are now turned inside-out, but I can promise they were rendering correctly when I tested them (before importing that latest firearm). It's really inconsistent.
Thanks for that anyway, I'd try to mirror it without mirroring feature, if it's possible. 

Not closing this topic though, as main issue remains, I really hope for any solution ;-;

**Comment by Toma400** [comment]
Man, this - but applied to GUI view - also solved my model darkening and flickering issue O.o 
At least for the latest model, but I will test this solution on other models. If it works on some others, I will close the topic, so you will know if it was the problem for whole time.

So from now on, you can also suggest that as a solution for it, if anyone ignorant enough asks, haha ^^ thank you so much!
