### ISSUE TITLE
[issue]install botton not working

### ISSUE THREAD

**Issue by JarKue** [JannisX11/blockbench#969]
Desktop, Windows10 64bits
 I clicked on install button but nothing happened.
![3](https://user-images.githubusercontent.com/87646001/126146439-6a70ebe9-4a59-45c3-a925-29c9389b373c.png)

**Comment by JarKue** [comment]
all plugins

**Comment by JannisX11** [comment]
Did you make sure that you have a working internet connection? Also, are you located in China or the middle east?

**Comment by JarKue** [comment]
im in China

**Comment by JarKue** [comment]
Thanks.I succeeded in solving the problem!But when i restart BlockBench,it lost plugins and adjustments...

**Comment by allanromanreyes** [comment]
Having same problem in USA. Internet connection GOOD, does nothing when install area is selected.
