### ISSUE TITLE
PE Models not working

### ISSUE THREAD

**Issue by NogardYT** [JannisX11/blockbench#97]
Win Vista-Mozilla
I exported model to MCPE format, after that i made pack a tried it in MCPE, but it doesn t work. I really don't know in what is problem. I discussed about that with best Add-On makers, but anyone don t know in what is problem. Please check it !

**Comment by JannisX11** [comment]
I can't help you if you don't provide me with enough information including the resource pack.

**Comment by NogardYT** [comment]
Wolf is displayed in blockbench badly... --> bad model --> not working in MCPE
