### ISSUE TITLE
[Bug] One cube can't be slected for rotation...

### ISSUE THREAD

**Issue by windowslogic** [JannisX11/blockbench#973]
Cannot rotate a singlular cube while it's out of a group. If in group with another cube, it can only be rotated from group, causing two cubes to be rotated at once. If cube outside cube or in group with another, no options to rotate are available.

Minecraft skin.

Blockbench programme.

Windows 10 Enterprise 2016 LTSB.

**Comment by JannisX11** [comment]
The Minecraft skin format is just meant for texturing, not for modeling. You can rotate bones to slightly adjust the pose, but you are not meant to modify any cubes.
