### ISSUE TITLE
[Issue] Adding a json file deletes my progress.

### ISSUE THREAD

**Issue by woahthere** [JannisX11/blockbench#98]
I made a model (Gun) and I want to add a suppressor model that I also made with blockbench. Whenever I load the other model by doing File>Add>Model It looks like it works, but then whenver I save a lot of stuff is missing in the game.

**Comment by JannisX11** [comment]
Please check if this is still the case in Blockbench 1.11.

**Comment by JannisX11** [comment]
Adding json files has been tested in the latest version and is considered working.
