### ISSUE TITLE
[Suggestion] Merge Textures

### ISSUE THREAD

**Issue by DevCliq511** [JannisX11/blockbench#982]
Its Nice If You Put Merge Textures 

Example:

When You Select 2 Or Mire Textures And Click The Merge Texture Layers Then The Texture Will Increase Canvas And The Textures Selected Will Be Combined.

Also If You Want To Do It Plss Allow Android Blockbench To Access That Thing :)

**Comment by dragonmaster95** [comment]
@DevCliq511 There is a (Blockbench) plugin called "Texture stitcher". Install it (File > Plugins > Available > Texture Stitcher > Install), then rightclick any texture (or in your case hold click if you use a phone I guess) and chose the "stitch textures" option.

**Comment by Wackyblocks** [comment]
You can also generate a new template to merge textures. Not compatible with meshes at the moment (#1066)
