### ISSUE TITLE
The "display adjustment" function is invalid.

### ISSUE THREAD

**Issue by HGGZHYIVIQZ** [JannisX11/blockbench#986]
When I finish making the model and prepare to adjust the handheld state of the model, everything I do in the "display adjustment" interface will not be reflected in the game.(The game version used is 1.8.9)

**Comment by HGGZHYIVIQZ** [comment]
In Blockbench:
![P0(0IGBA%3L8 47GL_R_(%L](https://user-images.githubusercontent.com/88628593/128640687-04b35e0c-fce2-4cbe-9c60-49953ed1e07a.png)
In Minecraft:
![IWT))4YFJ7078}D7S10MUKP](https://user-images.githubusercontent.com/88628593/128640693-e6f0f3d8-0049-4ee3-9d96-f1d7093af461.png)

**Comment by HGGZHYIVIQZ** [comment]
If there is a problem with my operation, please point it out. Thank you very much!!!

**Comment by JannisX11** [comment]
Blockbench does not support Minecraft 1.8 display settings. 1.8 was already outdated a couple of years before the first version of Blockbench was released.
