### ISSUE TITLE
[Issue] After flipping folders that are duplicated, they get back to the original names.

### ISSUE THREAD

**Issue by Bag31140** [JannisX11/blockbench#988]
So, I was modeling my model as a Bedrock Model, and I decided to flip some cubes and folders because the model was not symmetrical. The cubes went fine, but when I flipped the folders (that were already duplicated), they got back to their original names, and I had to rename it all over.

Example: I duplicated the right arm and rotated it to be the left arm, but then after I "discovered" the flip feature, i walted just to flip it. And when I flipped it the names of the folders got back to the ones that was referring to the right arm (Like, the folders leftarmpart1, leftarmpart2, lefthand, leftfingers, etc. got automatically renamed to rightarmpart1, rightarmpart, righthand, rightfingers, etc.)

_For more details, watch the video in this link._
https://user-images.githubusercontent.com/88496932/128902160-af15e653-2d7e-4680-b0ac-39c7192b196d.mp4

**Comment by JannisX11** [comment]
The only issue I see is that this may lead to duplicate bone names. I've fixed that in a commit just now.

Other than that, it works as intended. I would recommend to use Transform > Flip from the start instead of using rotations, this makes the model more consistent and helps with animation.

**Comment by Bag31140** [comment]
> The only issue I see is that this may lead to duplicate bone names. I've fixed that in a commit just now.
> 
> Other than that, it works as intended. I would recommend to use Transform > Flip from the start instead of using rotations, this makes the model more consistent and helps with animation.

Hi there! Thanks for fixing the bug.

Yes, this was the only error I was having.
I used rotations before becuase I didn't knew that this flip feature existed (that's why I posted that suggestion to add a flip option), but still thanks for reading it and fixing the bug!
