### ISSUE TITLE
[Suggestion] Suggestion summary

### ISSUE THREAD

**Issue by ying4937** [JannisX11/blockbench#989]
I want to add a modeling vertex to blockbench modeling, which overlaps with each other

Connect the corners of one model to the corners of another model

**Comment by ying4937** [comment]
If you can, you also want to add a vertex rotation or trim movement

**Comment by ying4937** [comment]
oh Sorry, I didn't see this feature, but I still want to add vertex rotation and translation

**Comment by JannisX11** [comment]
Could you describe your suggestion in more detail?

**Comment by JannisX11** [comment]
Duplicate of #665
