### ISSUE TITLE
[Suggestion] Allow fine editing of block rotation

### ISSUE THREAD

**Issue by gitupwithit** [JannisX11/blockbench#99]
Hello, would it be possible to allow a more fine editing of block rotation? AFAIK block rotation is done via the slider and it is in 22.5 degree increments. The attached image shows an imported model where I manually edited the block's rotation (5 degrees) with a text editor. Hope this makes sense, thanks for your time!

Webapp, Ubuntu 16.04

![image](https://user-images.githubusercontent.com/32688796/35444296-17c0b55a-027c-11e8-832f-654557db1dfa.png)

**Comment by JannisX11** [comment]
Rotations of anything other than multiples of 22.5° would break blockmodels aswell as itemmodels. This is a limitation by Minecraft.

**Comment by gitupwithit** [comment]
Ohhh .. wow thanks for that. *embarassed* Explains a lot!

**Comment by lxly9** [comment]
there are mods that allow for more rotations in models and it would be amazing if there was an option to disable the rotation limit for this exact purpose!
