### ISSUE TITLE
[Issue] Particles alpha channel display error

### ISSUE THREAD

**Issue by uItimatech** [JannisX11/blockbench#992]
• Model format: Bedrock model (probably same issue with generic model) 
•Blockbench variant: Program (probably affects all) 

When using particles in an animation, the alpha channel isn't displayed properly. For instance I had particles becoming yellow instead of becoming transparent.

**Comment by JannisX11** [comment]
Could you attach some screenshots to demonstrate the issue?

**Comment by uItimatech** [comment]
Here is a recording of the problem on a particle, same thing happens with all particles I used that had transparency.

https://streamable.com/jgjso1
