### ISSUE TITLE
[Suggestion] Ability to switch through themes with a dropdown menu

### ISSUE THREAD

**Issue by uItimatech** [JannisX11/blockbench#996]
It would be really useful to be able to switch themes using a dropdown menu. The themes showing up could be the ones recently loaded, the ones in a dedicated folder or the ones saved by the user using a button. This menu could be showing at the top of the Theme tab in the preferences window.

**Comment by JannisX11** [comment]
A theme selector was added in 4.0. That should cover the requests in this issue.
